### ISSUE TITLE
Token program needs a Burn instruction

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana-program-library#11]
Sometimes users want to burn some tokens.  Let's add the token program equivalent of `1nc1nerator11111111111111111111111111111111`

**Comment by jackcmay** [comment]
@mvines I see a few options here:
- Re-use the `1nc1nerator11111111111111111111111111111111` account but only use it as a place holder in the `Transfer` instruction. The Token program doesn't actually modify that account but identifies it by key and "burns" the tokens
- Same as above using the `Transfer` instruction but use a different key (don't re-use `1nc1nerator11111111111111111111111111111111`
- Create a `Burn` instruction that burns tokens

I'm planning on doing the first, any objections?

**Comment by mvines** [comment]
Sorry for the delayed reply, I sorta feel like an explicit `Burn` instruction would be better.   Reusing `1nc1nerator11111111111111111111111111111111` feels a little too sneaky to me
