### ISSUE TITLE
Token swap: Inner instructions/program log no longer accessible through API or explorer

### ISSUE THREAD

**Issue by RichardWarfield** [solana-labs/solana-program-library#1193]
I'm not sure whether this is actually an SPL issue or not, but compare this [recent swap transaction](https://explorer.solana.com/tx/NRprnULxtu4FLZV5zGd4944DJjJ3qEUGVY9q2R8pa6s7iXPGcMWVfB7L3XjDwnmKRSXQ9v9Frn8ExorcfDFbPn7) to [this one from a day ago](https://explorer.solana.com/tx/2wK1KmP9nLEq6KSUgZTn3NruqGoNmAcxZNcL251jyyxJJjw2KhhBq4KsWpHVZGZG3K3mKCW7Yf8aQBfWcpAUWPbi):

The `swap` instruction for the more recent transaction does not have any inner instructions visible, nor a program log.  When using the API, the `innerInstructions` field is `null`.  This is a problem because as best I can tell this is the only precise way to find out the number of tokens actually received.

**Comment by CriesofCarrots** [comment]
Hi @RichardWarfield . We're missing some of that metadata on our api nodes at the moment, although we do have that data in our long-term storage. We're working on getting that backfilled as we speak.

**Comment by RichardWarfield** [comment]
Thanks.  Is this actually a token swap problem then?  I noticed that the same is was happening for Serum transactions, so I suspected it may actually be a Solana RPC problem and opened an [issue](https://github.com/solana-labs/solana/issues/15166) there; let me know if I should close this one.

**Comment by CriesofCarrots** [comment]
@RichardWarfield , whoops! No, it's definitely a general issue. I replied in the wrong place 🤕  I'll close this and update that other issue.
