### ISSUE TITLE
math: initial guess for sqrt approximation is too far off

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#1232]
#### Problem
For large numbers, starting at X / 2 as an initial guess for square root is way too far off to find the square root in a reasonable number of iterations

#### Proposed change
We can find the nearest even power of two and start from the square root of that. We could also get rid of this approximation and instead use this crate: https://crates.io/crates/integer-sqrt

tag @joncinque

**Comment by joncinque** [comment]
Makes sense to update this!  I looked through the code, and it requires `PrimInt` to be defined on the types, so we might want to consider adding a checked version that uses the num traits.  That way the `construct_uint` types will also work with it
