### ISSUE TITLE
No way track how long a the user has held a balance

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana-program-library#131]
## Problem

Token's are a great way to implement a voting system.  For the system to work we need a "hold" time component as well.

## Solution

Add a instruction that sets the current slot

* InitializeHODLSlot

Any withdrawals reset the HODLSlot to None.

A vote program can then generate a ballot from a checkpoint of the tokens balance, and the HODLSlot.  To Vote the same token must be presented with the ballot with its HODLSlot set to the expected value.

tag: @jackcmay @CriesofCarrots

**Comment by jackcmay** [comment]
@aeyakovenko Any `Transfer` will clear the source account's hold slot?

**Comment by aeyakovenko** [comment]
Deposits shouldn't clear it

**Comment by aeyakovenko** [comment]
Tag @joncinque might be useful for next gen tokens

**Comment by joncinque** [comment]
@aeyakovenko I'll add this to the list of possible new token programs.  I don't think we should add this to the SPL token standard though
