### ISSUE TITLE
Improve Associated Token Program usability.

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana-program-library#1371]
Pardon being a jotdown...

- we can't safely prepend its Instruction before TransferCheck. we always must check the existence of given associated token accounts. Fortunately, prepending doesn't incur additional fee as this instruction requires no sigs.
  -  => if the program can prove that it's worked previously for the address, silently return ok;
- it allowed nested associated tokens like this: https://explorer.solana.com/address/7RyJpfyH38Vi5PcnNp4Nmiikc1dnXKv3WFXFY5GoC3Nm I'm seeing a hard-time to think of legitimate use-case of nested associated tokens? Also, I think these tokens are effectively burnt?
  - => Disallow nested case by checking the base account's owning program_id.

context: https://github.com/solana-labs/solana-program-library/pull/1364

**Comment by jstarry** [comment]
> Also, I think these tokens are effectively burnt?

Ah, good point. There's no way to sign as an associated token. This is tough because ideally you can create associated token accounts owned by non-signer accounts because we have a pattern of creating token accounts on behalf of the owner. So due to that use-case, you could still get stuck if the owner is a PDA that hasn't been initialized yet. But maybe an extra check would be a nice safe guard for a big proportion of possible mistakes

**Comment by jstarry** [comment]
Included in usability is the ability to created associated tokens for non tokenkeg programs. After your changes in #1364 we could support arbitrary token program id's instead of hard-coding the tokenkeg id if we upgrade the associated token program.

**Comment by ryoqun** [comment]
> Included in usability is the ability to created associated tokens for non tokenkeg programs. After your changes in #1364 we could support arbitrary token program id's instead of hard-coding the tokenkeg id if we upgrade the associated token program.

Well, this might not be possible.. I think the associated token program doesn't take `tokenkeg` for inputs: https://explorer.solana.com/tx/SEk378h2Tke44haJ1Pj3rpd13REZeNDDW9CA6V2xGHXt4a2iurG9dbK6wBbomDE5YX1gTMV8mXvvBLkX9mxpckU
So, maybe are you assuming the need to deploy another different associated token program at different address?

**Comment by mvines** [comment]
👍🏼 for fixing these two issues as a part of a ATA update to support i-tokens
