### ISSUE TITLE
stake-pool: Add a configurable stake-pool lockup date to support locked stakes

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana-program-library#1392]
# Problem

No way to manage locked up stakes with stake pools

# Solution

Add support for locked up stakes to stake-pools.  Each pool can only manage stakes with the exact same lockup.  The lockup date should be configured at the stake-pool init, and cannot be changed.

**Comment by mvines** [comment]
Do stake pools require reassigning the withdraw authority of the deposited stake to the pool?   Withdraw authority of locked stake is not changeable without custodian approval

**Comment by aeyakovenko** [comment]
Ah right. :(

**Comment by joncinque** [comment]
Would we be able to create a new mode of stake pool for locked stakes?  If they're locked stakes, do we need to have a consistent withdraw authority?

**Comment by mvines** [comment]
> Would we be able to create a new mode of stake pool for locked stakes? If they're locked stakes, do we need to have a consistent withdraw authority?

Yep that's probably all doable.
