### ISSUE TITLE
stake-pool: Expand withdraw instruction to perform a merge for initialized stakes

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#1421]
#### Problem

The stake pool withdraw instruction currently performs a "split" from one of its stake accounts, which means that the recipient must be a new / initialized stake account.  This means we cannot pass in a warmed up stake account.

#### Solution

In a withdraw, check to see if the recipient stake account is initialized.  If initialized, try to merge instead of split.

**Comment by atharmohammad** [comment]
I would like to work on this issue

**Comment by joncinque** [comment]
Go for it!
