### ISSUE TITLE
Token: Allow querying of all owned tokens by pubkey

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana-program-library#1429]
#### Problem

There is no way to look up token accounts owned by an account's pubkey.  `spl-token accounts` requires an `--owner <KEYPAIR>` argument be provided (or CLI default config).

This is particularly challenging, and I expect will become a louder issue, as we are working out wallet inter-operability issues as more wallets start following our recommended practice of only exposing the system account address to the user.  For debugging, anyone should be able to look up the token accounts owned by a wallet's pubkey.

#### Proposed Solution

Accept `--owner <KEYPAIR or PUBKEY>`

**Comment by danpaul000** [comment]
cc: @t-nelson @CriesofCarrots not sure whose court this would be in.

**Comment by CriesofCarrots** [comment]
I can probably sneak this in

**Comment by CriesofCarrots** [comment]
Also, update output:
```
        USDC_MINT 40
Aux-1*  USDC_MINT  2
Aux-2*  USDC_MINT  5
        SRM_MINT  10

* Please run `spl-token gc` to clean up Aux accounts
```

`spl-token accounts -v` outputs token account addresses

**Comment by mvines** [comment]
Flipping the table around a little makes `sort` work again too:
```
USDC_MINT 40
USDC_MINT  2 (Aux-1)
USDC_MINT  5 (Aux-2)
SRM_MINT  10

* Please run `spl-token gc` to clean up Aux accounts
```
