### ISSUE TITLE
Associated Token Account: Expose get_associated_token_address function on CLI or RPC

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana-program-library#1430]
#### Problem

There is no way to quickly determine the associated token address for a given account and mint for debugging.  As wallets move to obscure the token address from users as per our inter-operability guidelines, we still need to be able to easily dive in to the token accounts.

#### Proposed solution

Provide a CLI interface or RPC call that accepts a pubkey and mint address and returns the associated token account address.

**Comment by mvines** [comment]
It'd be cool if `spl-token accounts` added an annotation when the token account is the ATA too.  For example here are my testnet tokens:
```
$ spl-token accounts
Account                                      Token                                        Balance
-------------------------------------------------------------------------------------------------
4J3eGAbKCP1QpBUWRPLjnJmXCK6jtyeChkS9SUqCif3k 3PbZyeRXJXAkWnXZ8xv5yjuBMHV8DUKoCWwkBfM2nEhV 50
9Ar54YwieToSEaV6t7izLm64XqJMsX4vgnTSXtRXLJ9k 7JYpqds3HBqGCExJVQEfmmdxGXaU2m6tkeUQdysr8nbM 100000
BNPivAkMD6EiUqRQoef3Ar38qbNXvFAj8caVmpf7kmtq 7d26CDUanpwzQ8J3bNREhPYyW9ZHS1wumDtabrTvLQcB 43
GTWCvRVdePPg6Up2KnSeFX2Kg6DudQzxQkxmSzjmTDhQ CpMah17kQEL2wqyMKt3mZBdTnZbkbfx4nqmQMFDP5vwp 1
4YYaxNYQvMDzJUAyrkUGMoFjcmSEL9CwmB3QtPNnoGm4 CpMah17kQEL2wqyMKt3mZBdTnZbkbfx4nqmQMFDP5vwp 0
```
and it's not clear what the ATA is for `CpMah17...`

**Comment by mvines** [comment]
Well I figured it out by gc-ing:
```
$ spl-token gc
Fetching token accounts
Processing token: 3PbZyeRXJXAkWnXZ8xv5yjuBMHV8DUKoCWwkBfM2nEhV
Processing token: 7JYpqds3HBqGCExJVQEfmmdxGXaU2m6tkeUQdysr8nbM
Processing token: CpMah17kQEL2wqyMKt3mZBdTnZbkbfx4nqmQMFDP5vwp
Processing token: 7d26CDUanpwzQ8J3bNREhPYyW9ZHS1wumDtabrTvLQcB
Signature: 3r6dG381PXJSwZcFRpwUb4jVUM8oXV69d8q87Dt3Tf7WhwwpsDHj6u1PKvwAve8YFYDL9vhVo93N8gbTwfTYhuDH

$ spl-token accounts
Account                                      Token                                        Balance
-------------------------------------------------------------------------------------------------
4J3eGAbKCP1QpBUWRPLjnJmXCK6jtyeChkS9SUqCif3k 3PbZyeRXJXAkWnXZ8xv5yjuBMHV8DUKoCWwkBfM2nEhV 50
9Ar54YwieToSEaV6t7izLm64XqJMsX4vgnTSXtRXLJ9k 7JYpqds3HBqGCExJVQEfmmdxGXaU2m6tkeUQdysr8nbM 100000
BNPivAkMD6EiUqRQoef3Ar38qbNXvFAj8caVmpf7kmtq 7d26CDUanpwzQ8J3bNREhPYyW9ZHS1wumDtabrTvLQcB 43
4YYaxNYQvMDzJUAyrkUGMoFjcmSEL9CwmB3QtPNnoGm4 CpMah17kQEL2wqyMKt3mZBdTnZbkbfx4nqmQMFDP5vwp 1
```
but shouldn't have to :)

**Comment by mvines** [comment]
But for the actual problem, how about 
```
$ spl-token address
```
By default it shows the same as `solana address`, encouraging you to use your system address 

But you can do a 
```
$ spl-token address -v --token <mint-address>
```
and that'll show your system address as well as the ATA address for that token

**Comment by CriesofCarrots** [comment]
`spl-token accounts` improvements merged here: https://github.com/solana-labs/solana-program-library/pull/1440

@danpaul000 , assuming address tooling (for ATAs that may not exist), does it seem like `spl-token address` as proposed ^ will suit your needs?

**Comment by danpaul000** [comment]
@CriesofCarrots as long as `spl-token address` can accept a pubkey as well, not just a CLI keypair as the owner, then yes.
