### ISSUE TITLE
spl-token-cli: Can't create additional account for token

### ISSUE THREAD

**Issue by sonrebmax** [solana-labs/solana-program-library#1477]
I tried to make new account based on https://spl.solana.com/token#example-transferring-tokens-to-an-explicit-recipient-token-account
```

$ spl-token create-account 2JVy7J2ac482nbbnYwUW9mKGbJucW7vgviuDWZRCEJVK
Creating account DXLXQQ42f3poH5MkFLrCqEmUskqFFKwU8skr1rDUSNJ5
Error: Account already exists: DXLXQQ42f3poH5MkFLrCqEmUskqFFKwU8skr1rDUSNJ5

```
I have also different look of list of accounts
```
$ spl-token accounts
Token                                         Balance  
---------------------------------------------------------------
2JVy7J2ac482nbbnYwUW9mKGbJucW7vgviuDWZRCEJVK  199999667

```

spl-token-cli 2.0.9
solana-cli 1.6.1 
RPC URL: https://devnet.solana.com

**Comment by t-nelson** [comment]
`spl-token create-account` tries to create the associated token account for the owner by default.  If you would like to create an auxiliary account, you need to pass the optional `KEYPAIR` positional parameter (`solana-keygen new --no-passphrase -so throwaway-address.json`).  This keypair is only used to reserve the new account's address and can be deleted after the account is created, `--owner` will have full control.

```
$ spl-token create-account --help
spl-token-create-account
Create a new token account

USAGE:
    spl-token create-account [FLAGS] [OPTIONS] <TOKEN_ADDRESS> [--] [KEYPAIR]

[SNIP]

ARGS:
    <TOKEN_ADDRESS>    The token that the account will hold
    <KEYPAIR>          Specify the account keypair. This may be a keypair file or the ASK keyword. [default:
                       associated token account for --owner]
```

**Comment by CriesofCarrots** [comment]
> I have also different look of list of accounts

Thanks for the heads up. We made some changes to this call recently and need to update docs

**Comment by joncinque** [comment]
Looks like this was fixed awhile ago in the docs
