### ISSUE TITLE
spl-token-cli: transfer requires knowledge of sender token account address

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana-program-library#1479]
The ATA model is designed such that users only need to know their main wallet address (system account). But in order to perform a transfer using the spl-token cli, they must determine their actual token account address: `SENDER_TOKEN_ACCOUNT_ADDRESS`

```
$ spl-token transfer -h
spl-token-transfer
Transfer tokens between accounts

USAGE:
    spl-token transfer [FLAGS] [OPTIONS] <SENDER_TOKEN_ACCOUNT_ADDRESS> <TOKEN_AMOUNT> <RECIPIENT_ADDRESS or RECIPIENT_TOKEN_ACCOUNT_ADDRESS>
    ...
ARGS:
    <SENDER_TOKEN_ACCOUNT_ADDRESS>                            The token account address of the sender
    <TOKEN_AMOUNT>                                            Amount to send, in tokens; accepts keyword ALL
    <RECIPIENT_ADDRESS or RECIPIENT_TOKEN_ACCOUNT_ADDRESS>
            If a token account address is provided, use it as the recipient. Otherwise assume the recipient address is a
            user wallet and transfer to the associated token account
 ```

For standard usage, `spl-token transfer` should probably take a mint address instead, and attempt to transfer from the owner's ATA for that mint. Transferring from a specific address could be enabled using named parameters.

**Comment by CriesofCarrots** [comment]
@mvines wdyt?

**Comment by t-nelson** [comment]
This sgtm!  Are we aware of any exchange/wallet integrations that may have wrapped CLI for SPL Token support?

**Comment by mvines** [comment]
Yep, this sounds great.   I'll place a wager that nobody as wrapped the CLI yet, and if I lose that that bet then those that did wrap the CLI probably did it wrong and should fix the integration to be ATA compliant anyway

**Comment by CriesofCarrots** [comment]
There are some other subcommands that could use sprucing up in this direction too.
Should take mint:
- burn
- close
- balance / account-info
- delegate / revoke

Mint is known, so doesn't need to be passed in:
- wrap - currently using a throwaway keypair instead of ATA
- unwrap

Should take main wallet address?
- freeze/thaw - or maybe we want to require freeze authorities to determine the explicit token account to take these actions; either way, I'll kick this one down the road a bit

**Comment by t-nelson** [comment]
>     * freeze/thaw - or maybe we want to require freeze authorities to determine the explicit token account to take these actions; either way, I'll kick this one down the road a bit

I think we may want the same explicitness for `burn` and maybe `delegate/revoke`.  Mainly to prevent footguns.  Thoughts?

**Comment by CriesofCarrots** [comment]
> I think we may want the same explicitness for `burn` and maybe `delegate/revoke`. Mainly to prevent footguns. Thoughts?

Fair point. I think I agree. I'll percolate on how that feels from an interface perspective as I start to work on the others.

**Comment by CriesofCarrots** [comment]
The specific issue described has been fixed.
For now, `burn`, `delegate/revoke`, and `freeze/thaw` still require specific token account addresses as footgun prevention. Let's open a new issue to discuss if we want to make these subcommands more "default ATA" in the guture.
