### ISSUE TITLE
stake-pool: allow the number of validators in a pool to be configurable

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana-program-library#1494]
The maximum number of validators in a stake pool is hard coded to be:
https://github.com/solana-labs/solana-program-library/blob/5df346163f4e63132af850c300a085418a2cb44d/stake-pool/program/src/state.rs#L161

But this is about as many validators currently exist on testnet, so we have basically no room to grow.

Instead the maximum could be specified at pool creation time as an optional argument to `spl-stake-pool create-pool`

**Comment by joncinque** [comment]
Finished with #1505
