### ISSUE TITLE
memo: unignore test

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana-program-library#1583]
`test_memo_compute_limits()` was ignored because the limits on bpf-tools v1.5 (solana master, solana v1.6) are significantly different than on previous bpf-tools versions (solana v1.5).

Once stable solana is on bpf-tools v1.5, unignore the test with new representative values, and update docs: https://github.com/CriesofCarrots/solana-program-library/tree/update-memo-test

**Comment by akhil484** [comment]
Hi,
I would like to take it as my first contribution. Can you please help me and explain a little more about the issue or how should I go about it?
Thanks.
