### ISSUE TITLE
Publish `@solana/spl-token` for creating transactions

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#162]
#### Problem
It's not easy to setup SPL token accounts in a test environment or in a UI that creates manages tokens because there is no published library

#### Proposed Solution
Deploy `@solana/spl-token` as is for consumption

tag @jackcmay

**Comment by jackcmay** [comment]
You are wanting a js library?

**Comment by jstarry** [comment]
Yeah exactly
