### ISSUE TITLE
js: Add option to `skipPreflight` for token and token-swap clients

### ISSUE THREAD

**Issue by michaelhly** [solana-labs/solana-program-library#1653]
`skipPreflight` is hardcoded to `false` in the token and token-swap client where a transaction is sent. I remember this use to be hardcoded to `true`. Can we make this configurable? 

https://github.com/solana-labs/solana-program-library/search?q=skipPreflight

**Comment by joncinque** [comment]
Sounds good, go for it!

**Comment by joncinque** [comment]
This has been fixed with #3094
