### ISSUE TITLE
token-lending: Javascript client for token-lending?

### ISSUE THREAD

**Issue by leonardgee** [solana-labs/solana-program-library#1654]
Is there any plan to implement a javascript client for `token-lending`?

**Comment by jordansexton** [comment]
It's a good question. I think that a TypeScript library to call the instructions and handle de/serialization would be great to have here. This could be derived from https://github.com/solana-labs/oyster/pull/75 with some small changes from its current state.

**Comment by jordansexton** [comment]
This is done: https://github.com/solana-labs/solana-program-library/tree/master/token-lending/js
