### ISSUE TITLE
Token Lending Program Needs Documentation

### ISSUE THREAD

**Issue by bonedaddy** [solana-labs/solana-program-library#1710]
The token lending program is (imo) one of the most useful programs included in the solana program library, and can be used as a primitive for building a wide variety of applications, driving adoption for Solana and increasing the number of active users. Being able to use the lending program however is fairly difficult as it involves a lot of different components, and none of these components have any real documentation. At the moment the only real option for understanding the lending program and integrating with it is having to read the source code, which there is a lot of.

At a minimum it would be useful to have documentation explaining the high level purposes of:

* Lending markets
* Lending market reserves
* Obligations

**Comment by jordansexton** [comment]
Agreed, I'll be working on this very soon.

**Comment by allanperlee** [comment]
Hás anyone worked on this issue? Im interested in contributing.

**Comment by jordansexton** [comment]
Your contribution would be very welcome! I haven't had time to work on it

**Comment by allanperlee** [comment]
Hi jordansexton, does this need tô bê assigned tô me tô work on this?

**Comment by jordansexton** [comment]
It doesn't need to be but I assigned it to you 😄

**Comment by allanperlee** [comment]
Great, thanks jordansexton!

**Comment by allanperlee** [comment]
Hi jordansexton, there is progress made on the documentation. It is located here:

https://github.com/allanperlee/dummy/blob/master/README.md

Suggestions are encouraged, thanks again.

**Comment by jordansexton** [comment]
Thank you! I'll review this today/tomorrow

**Comment by jordansexton** [comment]
Hey, it looks really good so far! If you would create a new branch and open a PR, I can more easily provide feedback and we can revise together.

**Comment by allanperlee** [comment]
Glad to hear! I tried a pull request with the `git push origin master` command, but I received an error. It asks for a personal access token. What steps can I take to correct this?

**Comment by allanperlee** [comment]
Glad to hear! I made a branch, docs, then I tried a pull request with the `git push origin master` command, but I received an error. It asks for a personal access token. What steps can I take to correct this?

**Comment by allanperlee** [comment]
Then I tried it from Git Bash and it says, `remote: Permission to solana-labs/solana-program-library.git denied to allanperlee.
fatal: unable to access 'https://github.com/solana-labs/solana-program-library.git/': The requested URL returned error: 403` after commanding `git push origin master`.

**Comment by jordansexton** [comment]
Ah, so please create a branch from your fork, and then open a pull request from that branch. This will allow maintainers of the SPL repo to make changes to that branch for the purpose of the PR.

**Comment by allanperlee** [comment]
Sorry, but which fork até you referring tô? Tô contextualize, I only cloned the Solana Program Library, then branched.

**Comment by allanperlee** [comment]
Sorry, but which fork aré you referring tô? Tô contextualize, I only cloned the Solana Program Library, then branched.

**Comment by allanperlee** [comment]
Got it, let me do that then!
