### ISSUE TITLE
running token swap project

### ISSUE THREAD

**Issue by zdbrig** [solana-labs/solana-program-library#1742]
I am working on token swap project. 
after trying:  ( under token-swap/js )
**npm install**
**npm start**
I got this problem :
_minting token B to swap
creating token swap
Transaction simulation failed: Error processing Instruction 1: custom program error: 0x2 
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8 invoke [1]
    Program log: Instruction: Init
    Program log: Error: The input account owner is not the program address
    Program SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8 consumed 16779 of 200000 compute units
    Program SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8 failed: custom program error: 0x2
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x2_

Also trying to deploy spl_token_swap.so ( After making recover ..) ends with a problem : 

**solana program deploy target/deploy/spl_token_swap.so --buffer key.json** 
_Error: Deploying program failed: Error processing Instruction 1: custom program error: 0x1_

**Comment by joncinque** [comment]
Make sure that the program is built using `cargo build-bpf` from `token-swap/program`, and then you should run `npm run start-with-test-validator` instead of `npm run start`.

**Comment by zdbrig** [comment]
Thanks @joncinque for your answer, but the problem is more complicated than that, and after hours of debugging I located the issue here
![image](https://user-images.githubusercontent.com/934740/118376199-68b46a80-b5be-11eb-80e1-7697ec906d7e.png)
and the authority is different from account owner
![image](https://user-images.githubusercontent.com/934740/118376220-8550a280-b5be-11eb-96a7-7e7c753ec457.png)

**Comment by zdbrig** [comment]
@joncinque  Thanks very much for your answer, but that's now the problem.
After long troubleshooting, I am 100% sure the problem comes from here
![image](https://user-images.githubusercontent.com/934740/118377591-0d867600-b5c6-11eb-9ddb-a6ce517712ab.png)

**Comment by zdbrig** [comment]
Oh sorry , using this prefix worked : 
SWAP_PROGRAM_OWNER_FEE_ADDRESS="HfoTxFR1Tm6kGmWgYWD6J7YHVy1UwqSULUGVLXkJqaKN" npm run start
thanks !!

![image](https://user-images.githubusercontent.com/934740/118377807-833f1180-b5c7-11eb-9fdd-f514dc4679e8.png)

**Comment by joncinque** [comment]
Ok great to hear!  I'll close this out then, let us know if you have any other questions

**Comment by zdbrig** [comment]
@joncinque  but still manual deployment is not working

**Comment by joncinque** [comment]
if you want to deploy to a local cluster using `solana program deploy` and the `SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8` address, it won't work since you need the associated private key.  Can you give more information about what isn't working?

**Comment by zdbrig** [comment]
No I need to deploy it to a new address.
