### ISSUE TITLE
Custom Token program & Solana web 3 & Explorer

### ISSUE THREAD

**Issue by zdbrig** [solana-labs/solana-program-library#1760]
Dear Solana experts,

I have a question #spl-tokens #Solana-web3 
I am using the original Spl token program : _TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA_
and solana web3 API : getTokenAccountsByOwner
![image](https://user-images.githubusercontent.com/934740/118657639-8f9fb600-b7e3-11eb-8fee-0b071d92a79a.png)
That return the list of all token accounts of any user that I know only the public key. 
This is the same api used by raydium : 
https://github.com/raydium-io/raydium-ui/blob/master/src/store/wallet.ts
**The Issue is when I use my own token program**  : 7XrDxjP8zQhE7hx45EU8fGMfqhx1CC4LCQNCFsqdVcjB
**I dont get any result**.
It's hard to know the list of accounts of a user without having a similar api. Any sugesstion ?
Note: 
On Solana Explorer, comparing my token program and and original token program, the way transactions are shown is the same. Here an example : 

Origin program ID

![image](https://user-images.githubusercontent.com/934740/118658469-5156c680-b7e4-11eb-80f7-a3510ccd950b.png)

My token program ID

![image](https://user-images.githubusercontent.com/934740/118658690-87944600-b7e4-11eb-9cc7-112072ed401e.png)

![image](https://user-images.githubusercontent.com/934740/118659388-2de04b80-b7e5-11eb-9203-e9d6d51ca8dd.png)

![image](https://user-images.githubusercontent.com/934740/118659960-a941fd00-b7e5-11eb-8575-be5521889750.png)

**Comment by CriesofCarrots** [comment]
Yes, the SPL Token and Associated Token Account program ids are hard coded and instructions are hand-parsed to produce those rpc results. 

We are looking at making the SPL Token program extensible, such that any other program that supports a standard interface can be parsed and handled automatically, but unfortunately that is some months out.

In the meantime, you could use `getProgramAccounts` with a custom `memcmp` filter for account Owner: https://docs.solana.com/developing/clients/jsonrpc-api#getprogramaccounts
This is what `getTokenAccountsByOwner` does under the hood.

**Comment by zdbrig** [comment]
@CriesofCarrots  So I think calling get program accounts with **memcmp** both **mint** public key and **owner** do the job.
Thanks very much !

**Comment by CriesofCarrots** [comment]
I'm going to close this issue, as I think your question is answered. But please reopen if needed.
