### ISSUE TITLE
Add Token v2/v3 program id to @solana/spl-token library

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#178]
#### Problem
The spl-token v1 program id is well known but not embedded inside the library. It should be exported for devs to use.

**Comment by jackcmay** [comment]
Are you referring to this: https://github.com/solana-labs/solana-program-library/blob/bd5f1f82a3e16d4630d0b64857724fe375410414/token/src/lib.rs#L17

Are you wanting it to also be expressed in the js package?

**Comment by jstarry** [comment]
Yes, that's what I'm referring to and yes I would like it in the js package

**Comment by mvines** [comment]
Update: not needed for v1, but we do need this for v2 (`Tokenkeg..`) and upcoming v3

**Comment by t-nelson** [comment]
Closed by https://github.com/solana-labs/solana-program-library/pull/694
