### ISSUE TITLE
Issue with offline multisig token transfer signing using spl-token-cli

### ISSUE THREAD

**Issue by praskoson** [solana-labs/solana-program-library#1805]
Attempting to do an offline signing of a token transaction with a multisig account using `spl-token-cli` always results in a `presigner error`.

I tried following from the solana docs (https://spl.solana.com/token#example-mint-with-multisig-authority-and-offline-signers), adjusted to make a token transfer, and also the steps from this gist: https://gist.github.com/bonedaddy/31eec8f0b57af1e630cfec2ba12d87e8. 

I will list our steps below and attach a .md file with outputs of all commands in a reply:

1. We created a 2/2 multisig account: https://explorer.solana.com/address/DajKmH7j2GFJBSrJbUGbU23LeycJ1ANcBGr3cBtLFk92?cluster=devnet
2. Created a token account for that multisig and transferred 20 tokens to it. The mint address is mx3edW3gRoM9J4sJKtuobQW3ZB1HeuZH8hQeH9HDkF3 (https://explorer.solana.com/address/HUNfGdRXv4zeGZen8wyQ4szdvC62J6k3ARsLJGAhEGZJ?cluster=devnet)
3. Created a nonce account (https://explorer.solana.com/tx/34MqovmWw8qFa4Xr8i4RqCNUM39ihwan1kqf8h9NWKKnU7b95J1UzYZtkKuBigboAyPWs2YNoRm1eJD45DQvcsNT?cluster=devnet). 
- **Pubkey** of it is: 9LpeAwKmzrQcrDMVmKtmcv3WTURyHRZkFFDZzrSgH252; 
- **nonce blockhash**: 5228y9zzh84zZBcMwenvyxHnf5zTfjnoocr3eQAdBFXA and the 
- **authority**: 2tE8aXMwGtaAwz12eCu94EXGk4ZndQX9EyyFGFCiXYxU.

4. Created a "template" transfer command: 
 ```spl-token 
--url https://api.devnet.solana.com \
transfer mx3edW3gRoM9J4sJKtuobQW3ZB1HeuZH8hQeH9HDkF3 \
10 \
Awib2aiuK4epdEUeui6uoRFn44iVeKX4FaHkoDBPGsdb \
--owner DajKmH7j2GFJBSrJbUGbU23LeycJ1ANcBGr3cBtLFk92 \
--from HUNfGdRXv4zeGZen8wyQ4szdvC62J6k3ARsLJGAhEGZJ \
--multisig-signer 2tE8aXMwGtaAwz12eCu94EXGk4ZndQX9EyyFGFCiXYxU \
--multisig-signer Gu5BVnuMBXHBTh5nJBWtrmFfLoWDhry4LQ9qANBwFaN\
--blockhash 5228y9zzh84zZBcMwenvyxHnf5zTfjnoocr3eQAdBFXA \
--fee-payer 2tE8aXMwGtaAwz12eCu94EXGk4ZndQX9EyyFGFCiXYxU \
--nonce 9LpeAwKmzrQcrDMVmKtmcv3WTURyHRZkFFDZzrSgH252 \
--nonce-authority 2tE8aXMwGtaAwz12eCu94EXGk4ZndQX9EyyFGFCiXYxU \
--sign-only \
--mint-decimals 4
```

5. Both signers sign it using this template and replacing their public key in `--multisig-signer` with our file system wallets. I also had to replace the public key under `--fee-payer` with my file system wallet. 
`2tE8aXMwGtaAwz12eCu94EXGk4ZndQX9EyyFGFCiXYxU=5qcKXwZaXBiBe7wxruTfKxMQECUesXkj5M1FuqoRL3a5FESoz97gyeMJDGr1UzcaXV4KwtePBuT9Fkpe9MdAHgkz`
`Gu5BVnuMBXHBTh5nJBWtrmFfLoWDhry4LQ9qANBwFaN=uWcVEzUcbvcVeuZd1Y6TCDkmfzBVXDD3iNHg711qSs7BmhTi8DMCoy9MMaKzAfzzfD613DKR37Jj3gwZg6e3ZJs`

6. Tried to submit the transaction:
```
spl-token \
--url https://api.devnet.solana.com \
transfer mx3edW3gRoM9J4sJKtuobQW3ZB1HeuZH8hQeH9HDkF3 \
10 \
Awib2aiuK4epdEUeui6uoRFn44iVeKX4FaHkoDBPGsdb \
--owner DajKmH7j2GFJBSrJbUGbU23LeycJ1ANcBGr3cBtLFk92 \
--from HUNfGdRXv4zeGZen8wyQ4szdvC62J6k3ARsLJGAhEGZJ \
--multisig-signer 2tE8aXMwGtaAwz12eCu94EXGk4ZndQX9EyyFGFCiXYxU \
--multisig-signer Gu5BVnuMBXHBTh5nJBWtrmFfLoWDhry4LQ9qANBwFaN \
--blockhash 5228y9zzh84zZBcMwenvyxHnf5zTfjnoocr3eQAdBFXA \
--fee-payer ~/spl_stvari/ppetar_wallet.json \
--nonce 9LpeAwKmzrQcrDMVmKtmcv3WTURyHRZkFFDZzrSgH252 \
--nonce-authority ~/spl_stvari/ppetar_wallet.json \
--signer 2tE8aXMwGtaAwz12eCu94EXGk4ZndQX9EyyFGFCiXYxU=5qcKXwZaXBiBe7wxruTfKxMQECUesXkj5M1FuqoRL3a5FESoz97gyeMJDGr1UzcaXV4KwtePBuT9Fkpe9MdAHgkz \
--signer Gu5BVnuMBXHBTh5nJBWtrmFfLoWDhry4LQ9qANBwFaN=uWcVEzUcbvcVeuZd1Y6TCDkmfzBVXDD3iNHg711qSs7BmhTi8DMCoy9MMaKzAfzzfD613DKR37Jj3gwZg6e3ZJs

Transfer 10 tokens
  Sender: HUNfGdRXv4zeGZen8wyQ4szdvC62J6k3ARsLJGAhEGZJ
  Recipient: Awib2aiuK4epdEUeui6uoRFn44iVeKX4FaHkoDBPGsdb
  Recipient associated token account: Ht7nUwAUQwGBQMKabRKMcQUjJa2tFQawp11t7Vm6hKFW
presigner error
```

Results in a presigner error.

**Comment by praskoson** [comment]
[multisig-commands-outputs.md](https://github.com/solana-labs/solana-program-library/files/6550206/multisig-commands-outputs.md)
All of the exact commands we used, including the outputs for each.

**Comment by praskoson** [comment]
Forgot to post our `solana` and `spl-token` versions: 
```
ppetar@home $ solana --version
solana-cli 1.5.20 (src:347ff770; feat:1574952541)
ppetar@home $ spl-token --version
spl-token-cli 2.0.11
```

**Comment by dahifi** [comment]
Same versions, here's my script with all of the outputs as bash vars for easy replication. You'll have to set the keypair yourself and copy the signatures manually

```

# regex for SOL wallets 
setopt BASH_REMATCH
PROGRAM_REGEX='\S{44}'

# Create test multisigs: https://spl.solana.com/token#example-mint-with-multisig-authority
# Create Wallets and save pubkeys to array $SIGNERS

# Use local hot wallet for mint and nonce authority
my_wallet=$(solana-keygen pubkey)
keypair=/path/to/id.json

# generate keystores
for i in $(seq 3); do solana-keygen new --no-passphrase -so "signer-${i}.json"; done
SIGNERS=($(for i in $(seq 3); do SIGNER="signer-${i}.json"; echo "$(solana-keygen pubkey "$SIGNER")"; done)) && echo $SIGNERS

# Create Multisig
result=$(spl-token create-multisig 2 $SIGNERS[0] $SIGNERS[1] $SIGNERS[2]) && echo $result
multisig=$([[ $result =~ $PROGRAM_REGEX ]] && echo ${BASH_REMATCH[1]}) && echo $multisig

# create token: 
result=$(spl-token create-token)
token=$([[ $result =~ $PROGRAM_REGEX ]] && echo ${BASH_REMATCH[1]}) && echo $token 

# mint token to owner wallet and send to multisig
result=$(spl-token create-account $token)
token_account=$([[ $result =~ $PROGRAM_REGEX ]] && echo ${BASH_REMATCH[1]})
echo $token_account
spl-token mint $token 100
spl-token transfer $token 50 $multisig --fund-recipient

#offline signing nonce
solana-keygen new -o nonce-keypair.json
nonce=$(solana-keygen pubkey nonce.json)
solana create-nonce-account nonce.json 1
blockhash=$(solana nonce nonce.json) && echo $blockhash

# get signatures all at once: 
spl-token transfer $token 25 $my_wallet \
   --owner $multisig \
   --multisig-signer signer-1.json \
   --multisig-signer signer-2.json \
   --blockhash $blockhash \
   --fee-payer $my_wallet \
   --nonce $nonce \
   --nonce-authority $my_wallet \
   --sign-only \
   --mint-decimals 9
```
My results below, sub yours into sig1, sig2
```
Blockhash: 83CYSQAZuVehpuoxyy5tasfPcnmpuDF2czAwjMBtPQqp
Signers (Pubkey=Signature): 4eCu3gLykavhvA7W9k5fQ9n3yHWwKxjfShbp5zGg5jfW=5Zct1LFSQkywByM92kGLLS2kSCpZUzEewk4fFqtqczFYaKwySkDsTTsrqgR3BGGVkQw917Y1EjFeVwARhtucxtNK
CtmY7kRN48awbY1XdoD46Hx68XBni8S5LjCXYFGFyCqx=63mXk23zJ1wSA2RUNUKNrhmbL4md9Lj4VsV59FvoXEhJDEMyRjH9b2Zv9GbycFco2Bj2G28T18Ba7mBg9Gz27eG9
Absent Signers (Pubkey):
 G8ngp2yyCBADo53Sk1zZyiAsKQG6MvC1SrvazUTcwVgc

sig1=4eCu3gLykavhvA7W9k5fQ9n3yHWwKxjfShbp5zGg5jfW=5Zct1LFSQkywByM92kGLLS2kSCpZUzEewk4fFqtqczFYaKwySkDsTTsrqgR3BGGVkQw917Y1EjFeVwARhtucxtNK
sig2=CtmY7kRN48awbY1XdoD46Hx68XBni8S5LjCXYFGFyCqx=63mXk23zJ1wSA2RUNUKNrhmbL4md9Lj4VsV59FvoXEhJDEMyRjH9b2Zv9GbycFco2Bj2G28T18Ba7mBg9Gz27eG9

# broadcast
spl-token transfer $token 25 $my_wallet \
   --owner $multisig \
   --multisig-signer $SIGNERS[1] \
   --multisig-signer $SIGNERS[2] \
   --blockhash $blockhash \
   --fee-payer $keypair \
   --nonce $nonce \
   --nonce-authority $keypair \
   --signer $sig1 \
   --signer $sig2
   
Transfer 25 tokens
  Sender: pKzxEgv8cvMx8Ha1awZcShgZTGzSiRW4CBK54XxMchn
  Recipient: G8ngp2yyCBADo53Sk1zZyiAsKQG6MvC1SrvazUTcwVgc
  Recipient associated token account: EQvnn9hECWMJMnbW2hSxUTDmqq9hkRfCkawDTYYhGbe3
presigner error

```

**Comment by t-nelson** [comment]
Try passing `--recipient-is-ata-owner` with the offline signature collection commands (`--sign-only` mode).  I think I'm going to flip the logic on that flag, since ATA is the primary token account addressing mechanism now

**Comment by dahifi** [comment]
Perfect, that worked!

**Comment by t-nelson** [comment]
> @t-nelson did you flip the logic on --recipient-is-ata-owner? If not, I can work on it

doesn't look like i got around to it. it's all yours!

please retain `--recipient-is-ata-owner` as a hidden flag and, if passed, warn the user that the behavior is now default, the flag is deprecated and can be removed.

new flag should be called `--no-recipient-is-ata-owner` to match convention of our other CLI tools.
