### ISSUE TITLE
@solana/spl-token package documentation

### ISSUE THREAD

**Issue by rihalto** [solana-labs/solana-program-library#1844]
It would be good to have an API documentation for the "@solana/spl-token" javascript module. Something like https://solana-labs.github.io/solana-web3.js/modules.html

**Comment by AlexLeung** [comment]
*sigh* Solana sucks at open source :/

**Comment by mvines** [comment]
All the Solana software is open source: Apache 2.0 / MIT licensed.  How do you prioritize more than 100%?

**Comment by mvines** [comment]
It's hard to see how "sigh Solana sucks at open source :/" could be considered to be constructive.

I fully agree that there needs to be major improvements to how the source code for programs **written on Solana** can be viewed through explorers. I've wanted that feature for quite a while, we've not gotten to it yet and/or perhaps a community-driven solution will emerge first. 

Your ideas are seem good, but your presentation in this case was lacking.

**Comment by emilianbold** [comment]
For anybody arriving here, the link you want is https://solana-labs.github.io/solana-program-library/token/js/ (which means this issue can be closed).

**Comment by jordansexton** [comment]
Thanks @emilianbold! I love a helpful necropost.
