### ISSUE TITLE
spl-token-cli: `no signers found` error is returned for null signer

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#1856]
#### Problem
The `owner` argument is used as the default signer for many token commands. Some of those commands require owner to be a signer but the `owner` signer may actually be a `NullSigner` which doesn't produce a valid signature. When this happens, an unhelpful `no signers found` error is returned to the user

#### Proposed Changes
Remove the `owner` global argument and add more explicit argument names to the commands that used it

**Comment by jstarry** [comment]
@t-nelson I assume we need to preserve backwards compatibility here?

**Comment by t-nelson** [comment]
> @t-nelson I assume we need to preserve backwards compatibility here?

Yeah that's why I haven't already yanked out `owner` :slightly_smiling_face: 

When is `owner` a signer, we aren't sign-only/offline and `NullSigner` valid?  `owner` was made to be allowed to be `NullSigner` because it is used in cases where it doesn't actually sign

**Comment by jstarry** [comment]
> Yeah that's why I haven't already yanked out owner 🙂

Ok, I'll add new names that alias to `owner` then if that sounds good to you

> When is owner a signer, we aren't sign-only/offline and NullSigner valid? owner was made to be allowed to be NullSigner because it is used in cases where it doesn't actually sign

I think it's intended to be the signer when minting tokens but I could be wrong. There isn't a mint authority option. I think it's also intended to be the signer for `wrap` but I could be wrong about that too.

**Comment by t-nelson** [comment]
> I think it's intended to be the signer when minting tokens but I could be wrong. There isn't a mint authority option. I think it's also intended to be the signer for `wrap` but I could be wrong about that too.

So it's a matter of not failing when the user passes a pubkey instead of a keypair when we aren't offline?

**Comment by jstarry** [comment]
> So it's a matter of not failing when the user passes a pubkey instead of a keypair when we aren't offline?

Yes, exactly. I looked through the code and didn't see any quick fix for that

**Comment by t-nelson** [comment]
> Yes, exactly. I looked through the code and didn't see any quick fix for that

Can we improve the `SignerFromPathConfig::allow_null_signer` logic when resolving `owner`?

**Comment by jstarry** [comment]
Yeah but it requires a change from clap utils I think. Only way to tell that we got a `NullSigner` back is to sign something and check for default signature

**Comment by t-nelson** [comment]
> Yeah but it requires a change from clap utils I think. Only way to tell that we got a `NullSigner` back is to sign something and check for default signature

Mmm... I was hoping we knew ahead of time whether a `NullSigner` was appropriate in the given case and let resolution fail
