### ISSUE TITLE
stake-pool Audit #5: Copy-paste code from solana-stake-program

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#1865]
#### Problem

The stake_program.rscontains 32 comments about code copied directly from the "solana-stake-program" crate.Copy-paste is not seen as a good practice as it may propagate erroneous code into other part of a project.In this case the code is enum and struct definitions used to interact with the solana-stake-program.

#### Solution

The copied code should be integrated much better and reviewed on the merit of where they are placed in the new codebase and not from where they come. In this case, as the copied code is definitions from a dependent code base, the solution would be to have common definitions that can be referenced from the new and the original code making any changes covering all usage in the project.

**Comment by allanperlee** [comment]
Hás this issue been closed already?

**Comment by mvines** [comment]
No it's still pending, see https://github.com/solana-labs/solana-program-library/blob/master/stake-pool/program/src/stake_program.rs
But this issue is now unblocked and can be resolved now that SPL is using Solana 1.7

**Comment by joncinque** [comment]
There's one last bit to be resolved before stake pools can use the SDK version, from the PR linked above :arrow_up:
