### ISSUE TITLE
token3: Recipient owner address is not included in transfer instruction

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#1891]
#### Problem
Token transfers are typically thought of as transacting between two wallet (owner) addresses rather than between the token accounts themselves. Transfers from a source token account must be signed by the owner, so the source owner is always present in the transaction account list. However, the recipient owner is not included in the transaction at all. This makes it hard for a client to fetch the participants involved in a token transfer because they must make a separate call to get the recipient token account's owner, and that account may not exist anymore or may have a different authority than at the time of transfer.

#### Proposed solution
Add a transfer checked v2 instruction which wallets can use to ensure that all transfers encode both the source and recipient owner addresses.

**Comment by ryoqun** [comment]
nice.

maybe another free-ride on the itoken (CC: @joncinque)

**Comment by joncinque** [comment]
Yep, great idea!

**Comment by lexer** [comment]
@joncinque @jstarry Let's make this happen!

**Comment by lexer** [comment]
Alternatively a recipient wallet address can be added as an extra key to the transfer instructions. Unfortunately since it's not part of the program no-one does it.
