### ISSUE TITLE
Fail to install stake-pool-cli v0.2.0 

### ISSUE THREAD

**Issue by jon-chuang** [solana-labs/solana-program-library#1905]
upon running `cargo install spl-stake-pool-cli`
```
error[E0063]: missing field `with_context` in initializer of `RpcProgramAccountsConfig`
  --> /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/spl-stake-pool-cli-0.2.0/src/client.rs:89:13
   |
89 |             RpcProgramAccountsConfig {
   |             ^^^^^^^^^^^^^^^^^^^^^^^^ missing `with_context`

error: aborting due to previous error
```
I'm wondering if its due to lack of versioning of the dependencies. (Although they appear versioned in the Cargo.toml)

**Comment by joncinque** [comment]
Thanks for noticing this.  Most likely it's picking up version 1.7 of the sdk -- I can pin the version to avoid this happening in the future
