### ISSUE TITLE
error: code 13,  PermisssionDenied 

### ISSUE THREAD

**Issue by LewisJohnson99** [solana-labs/solana-program-library#1933]
I'm trying to get started with creating tokens on Solana. but right in the beginning I receive following error when trying to install the Tools:

Error: Unable to save /Users/lewisjohnson/.config/solana/install/config.yml: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

How do I fix this??

**Comment by joncinque** [comment]
Most likely there are some permissions errors on your system, so you should make sure that `/Users/lewisjohnson/.config/solana/install/config.yml` is writable.

GitHub issues aren't the best place for technical support, however, so I invite you to come chat with us in the #developer-support channel in Discord at https://discord.gg/SdfZhPZr
