### ISSUE TITLE
solana-program: HashMap/HashSet/BTreeMap incompatibility

### ISSUE THREAD

**Issue by sham789** [solana-labs/solana-program-library#1946]
Usage of `HashMap/HashSet/BTreeMap` raises this error `Transaction simulation failed: Error processing Instruction 0: Program failed to complete`.

I see the usage of `HashMap` inside Solana programs but they fail as well, i.g:

https://github.com/solana-labs/solana-program-library/blob/79561cdca30cc8918f2a8c1802ef709a42ee1afb/token-swap/program/fuzz/src/instructions.rs#L114-L116

Is there a workaround for using `HashMap`?

**Comment by t-nelson** [comment]
`HashMap` can't be used in BPF programs due to its reliance on `rand` for state randomization.  The linked code is for a fuzzing harness, not actual on chain code.  You should use another data structure, perhaps BTreeMap, instead
