### ISSUE TITLE
BPF SDK path does not exist: /usr/bin/sdk/bpf: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by naddika** [solana-labs/solana-program-library#1982]
```
solana --version
solana-cli 1.6.14 (src:devbuild; feat:798232113)
```
But

```
cargo-build-bpf
BPF SDK path does not exist: /usr/bin/sdk/bpf: No such file or directory (os error 2)

```

How to create it? At what step? Where is it described in the documentation?

Arch Linux. Solana - built from the source, as an Arch Linux package 

```
% which cargo-build-bpf             
/usr/bin/cargo-build-bpf
```

**Comment by t-nelson** [comment]
This issue needs taken up with whoever is maintaining the Arch package.

Feel free to uninstall it and use the [tarball installation](https://docs.solana.com/cli/install-solana-cli-tools) in the meantime.  The BPF SDK should be installed properly via that method
