### ISSUE TITLE
spl-token should use 256 bits instead of 64 bits to represent an amount

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana-program-library#200]
ERC20 uses 256 bits right now, so spl-token can't map 1:1 to ERC20.  This seems like a general usability problem of spl-token.

Along the way let's make 18 decimals the (strongly recommended) default for spl-token

**Comment by mvines** [comment]
This will have ripple effects though the `getToken*` RPC methods as well.  (cc: @CriesofCarrots)

**Comment by CriesofCarrots** [comment]
Also affects `account-decoder/parse_token.rs` and `transaction-status/parse_token.rs`

**Comment by mvines** [comment]
> Along the way let's make 18 decimals the (strongly recommended) default for spl-token

Wrapped SOL should still have 9 decimals though - largely just a documentation update since a native mint account doesn't actually exist

**Comment by mvines** [comment]
Alternative path: a spl-erc20-token or spl-wrapped-erc20 program that supports the 256bit amount needed for 1:1 erc20 compatibility.   Ideally such a program reuses virtually everything from spl-token, parameterizing the amount

**Comment by mvines** [comment]
Better alternative path:  spl-token 1.1 can switch between u64 and u256 depending on the mint configuration

**Comment by mvines** [comment]
Better better alternative path: 👢.  Back to the "alternative path".   There can exist different token standard that the Eth bridge can deal with.  Native SPL-based marketplaces don't need incur the cost of Eth compatibility.

**Comment by mvines** [comment]
I think we've finally settled this.  64bits only
