### ISSUE TITLE
spl-token: `burn` reduces `supply` but the doc says it can't?

### ISSUE THREAD

**Issue by HaoCherHong** [solana-labs/solana-program-library#2033]
Not sure if I misunderstood the doc or the the doc is outdated or something.
On the [doc](https://spl.solana.com/token#burning), it says:
> There is no other way to reduce supply on chain.

However, when I use `burn` command with spl-token cli, it actually reduces the output of the `supply` command.

```
$ spl-token address --token ADKEd1KMTmJxmBX5cg9A2Fx4zpYHSdg8Lb2XzU34fygt --verbose
Wallet address: FYo6fSCpckTPUEpcTnEcBsozbgSPEUijfL87db6B7TTM
Associated token address: B2WizdnRDwX1q443eAxZBsg1yrtL7hSft4GatJx8Cmk1

$ spl-token supply ADKEd1KMTmJxmBX5cg9A2Fx4zpYHSdg8Lb2XzU34fygt
2002

$ spl-token burn B2WizdnRDwX1q443eAxZBsg1yrtL7hSft4GatJx8Cmk1 1
Burn 1 tokens
  Source: B2WizdnRDwX1q443eAxZBsg1yrtL7hSft4GatJx8Cmk1
Signature: 5dkzzFSAdj4vNBsPYwncPncvXLyLrQGseQWRMiVQm1dVWxGFuHbNv4vKeDGTftvDQyMJjif8tvBLfRzGs2ka6fz

$ spl-token supply ADKEd1KMTmJxmBX5cg9A2Fx4zpYHSdg8Lb2XzU34fygt
2001
```

I'm testing on localhost with solana-test-validator.

**Comment by CriesofCarrots** [comment]
The doc is saying that there is no way *other than* burning to reduce the supply. Burning does indeed reduce the supply, which you are seeing as a result of your commands.
I'm closing this, as the docs do describe the behavior correctly, but doc PRs welcome if you see a clearer way to say this.

**Comment by HaoCherHong** [comment]
Got it, I read it wrong. Thanks for explaining.
