### ISSUE TITLE
Example of creating non-fungible token seems wrong?

### ISSUE THREAD

**Issue by HaoCherHong** [solana-labs/solana-program-library#2040]
https://github.com/solana-labs/solana-program-library/blob/master/docs/src/token.md#example-create-a-non-fungible-token

The example gives the created token 9 decimal places
```
$ spl-token create-token --decimals 9
```
Then mint "1" token

Isn't that creates 1000000000 fungible tokens since you can transfer 0.000000001 to others?
And none of those tokens has any uniqueness since none of them has an unique id,

I suppose to create an actual non-fungible token you should create token with 0 decimal places:
```
$ spl-token create-token --decimals 0
```
then mint one and only token and disable minting.

**Comment by CriesofCarrots** [comment]
@mvines , do you mind taking a look at this vis-a-vis https://github.com/solana-labs/solana-program-library/commit/a539ef021f913a1ccc60ffdec41cd2eb2fc7f299#diff-46b42b4229cd7a39c564e780bb665a8bde4fdf722007e8473f167fe53ed4b995 ?
Perhaps the intent was to add `--decimals` to the fungible example?

**Comment by mvines** [comment]
`--decimals 0` makes more sense for sure.  I think I got my NF vs NTFs mixed up in that last doc update.

**Comment by mvines** [comment]
Assuming one doesn't want to represent fractional ownership of a thing :)

**Comment by HaoCherHong** [comment]
Created a PR (#2045) for this. Looks good to you?
