### ISSUE TITLE
SPL Token: Provide ability to send SOL to previously existing wrapped SOL account

### ISSUE THREAD

**Issue by armaniferrante** [solana-labs/solana-program-library#2077]
Currently it's not possible to send SOL to a previously existing wrapped SOL account. So to fund a wrapped SOL associated token account one must.

* Create aux account with SOL
* Send wrapped SOL to ATA
* Close aux account

This is problematic because it encourages apps to create aux token accounts that are potentially not closed. Ideally the token program would allow sending SOL directly to the ATA instead of inserting aux-related instructions before and after the send.

**Comment by mvines** [comment]
Seems like we could do this pretty easily with a new permissionless `TokenInstruction::SyncNative` that checks the current lamports held by the token account and updates `amount` to match:
https://github.com/solana-labs/solana-program-library/blob/02397e9152a8f9ee4c1596afb7d940f08294e8bd/token/program/src/state.rs#L92

Then one can send a transaction that:
* Performs a normal system transfer into the wrapped SOL account
* Runs `TokenInstruction::SyncNative` to register the credit
