### ISSUE TITLE
stake-pool doc: decrease-validator-stake help message for amount should be 'SOL' instead of 'lamports'

### ISSUE THREAD

**Issue by billythedummy** [solana-labs/solana-program-library#2158]
The help message for the `amount` argument of `decrease-validator-stake` says lamports: https://github.com/solana-labs/solana-program-library/blob/6775230b7eb8831b79564c8b92067b9d0707ee1b/stake-pool/cli/src/main.rs#L1541

when the value is actually in SOL and ran through `sol_to_lamports()` in `command_decrease_validator_stake()`: https://github.com/solana-labs/solana-program-library/blob/6775230b7eb8831b79564c8b92067b9d0707ee1b/stake-pool/cli/src/main.rs#L488

For reference, the help message for `increase-validator-stake` writes 'SOL' and is correct

**Comment by joncinque** [comment]
Great catch, thanks!
