### ISSUE TITLE
Lending program borrow rate not set on borrowing

### ISSUE THREAD

**Issue by therealssj** [solana-labs/solana-program-library#2208]
When an obligation is created the cumulative borrow rate is set to 1
https://github.com/solana-labs/solana-program-library/blob/5e320ba9768cca8ca751a4db26786ed13bb0d40f/token-lending/program/src/state/obligation.rs#L285

The way interest is accrued is
https://github.com/solana-labs/solana-program-library/blob/5e320ba9768cca8ca751a4db26786ed13bb0d40f/token-lending/program/src/state/obligation.rs#L312-L319

basically 
```
new debt = current debt * ( current cumulative borrow rate of reserve / current cumulative borrow rate stored in obligation )
current cumulative borrow rate stored in obligation = current cumulative borrow rate of reserve
```

but an obligation is initialised with the borrow rate of `1` 
doesn't that mean an obligation is paying interest as if it was opened when reserve was created ? 

to summarise, shudnt the `cumulativeBorrowRateWads` of the obligation be set somewhere here:
https://github.com/solana-labs/solana-program-library/blob/488af86a78162f55ca401c35abb6bf9c7d6b1ac8/token-lending/program/src/processor.rs#L1188-L1196

**Comment by jordansexton** [comment]
I think you're right. Here's what it was before cross-collateral was supported --

https://github.com/solana-labs/solana-program-library/blob/8d80fa90a6b3d23c6bdc95d06f4ba4750df2cca3/token-lending/program/src/processor.rs#L385-L389

This clones the current reserve cumulative borrow rate to the obligation on init.

Good catch!
