### ISSUE TITLE
Bug in token-swap js tests?

### ISSUE THREAD

**Issue by ilmoi** [solana-labs/solana-program-library#2229]
I've been studying the js tests for token-swap, and I think I found a bug in the [withdrawAllTokenTypes test](https://github.com/solana-labs/solana-program-library/blob/master/token-swap/js/cli/token-swap-test.ts#L281).

Specifically, when withdrawing both tokens from the swap, the pool tokens should be withdrawn from user's pool account, but instead they're being withdrawn from the exchange's pool account:

```js
let tokenAccountPool: PublicKey; // <-- define the exchange's pool token account up here

 const userTransferAuthority = new Account();
  console.log('Approving withdrawal from pool account');
  await tokenPool.approve(
    tokenAccountPool, // <-- incorrectly pass it into the approval function, this should have the USER's pool token account instead
    userTransferAuthority.publicKey,
    owner,
    [],
    POOL_TOKEN_AMOUNT,
  );

  console.log('Withdrawing pool tokens for A and B tokens');
  await tokenSwap.withdrawAllTokenTypes(
    userAccountA,
    userAccountB,
    tokenAccountPool, // <-- also incorrectly pass it into the token swap function, this should be the user's not the exchange's pool token account
    userTransferAuthority,
    POOL_TOKEN_AMOUNT,
    tokenA,
    tokenB,
  );

```

The reason this works in the tests is because the owner of the exchange is also the owner of the user account, and so the `tokenPool.approve()` function above doesn't throw an error. 

The result is that the user doesn't actually need to have any pool tokens and can endlessly withdraw A and B tokens from the exchange. Eg after a single withdrawal this is how the balances change:
```
BEFORE
User's A account: 0
User's B account: 0
User's pool account: 10000
Exchange's A account: 1000
Exchange's B account: 1000
Exchange's pool account: 100000

Ask for 10% of liquidity back

AFTER
User's A account: 100
User's B account: 100
User's pool account: 10000 // <-- should have gone to 0
Exchange's A account: 900
Exchange's B account: 900
Exchange's pool account: 90000 //<-- should have stayed the same
```

If the above is correct, happy to submit a PR to fix it. Just wanted to make sure I'm not missing something.

**Comment by joncinque** [comment]
The pool token account that you're referencing isn't the exchange's pool token account, but rather the pool creator's pool token account.  When you create a token swap,  you provide accounts with tokens in them, and in return you get a pool token account which can let you withdraw all of the tokens back.  The user doesn't even have a pool token account in this test, just in the deposit tests, which is why we use this account

**Comment by ilmoi** [comment]
Oh I see. Basically the "user" in this case happens to be the exchange owner, which is why we withdraw the pool tokens from them. Did I get that right?

**Comment by joncinque** [comment]
Yes exactly.

**Comment by ilmoi** [comment]
Thanks for clarifying!

**Comment by joncinque** [comment]
:smile: anytime!
