### ISSUE TITLE
Visualizations for token swap & token lending

### ISSUE THREAD

**Issue by ilmoi** [solana-labs/solana-program-library#2235]
I've been creating some diagrams for Solana's SPL programs to explain their inner workings, as I go through them.

So far I've got:
1. [Token Swap](https://github.com/ilmoi/solana-serum-program-viz/tree/master/token-swap)
2. [Token Lending](https://github.com/ilmoi/solana-serum-program-viz/tree/master/token-lending)
3. [Serum Dex](https://github.com/ilmoi/solana-serum-program-viz/tree/master/serum-dex) (not exactly SPL but relevant)

Perhaps these can be useful to the broader community / linked in docs?

@joncinque @jordansexton

**Comment by dahifi** [comment]
oh ABSOLUTELY, these should be included in the repos and readmes!

**Comment by joncinque** [comment]
Sorry for the very late response here.  We can definitely get the first two integrated in the SPL!  I'll leave jordan to comment on the lending diagrams, but the swap diagrams are certainly worthy of integration in the docs.  They're also a lovely complement to the overall diagram provided in https://github.com/solana-labs/solana-program-library/pull/2579 -- could you add a pull request with all of the diagrams, similar to that one?

Have you opened a PR with serum for the last one?
