### ISSUE TITLE
stake-pool: Validator list `find` should be replaced by a logarithmic binary search of a sorted array.

### ISSUE THREAD

**Issue by jon-chuang** [solana-labs/solana-program-library#2236]
A list walk is very expensive.

If the transaction can provide a hint, such as the index, that is derived via simulation, this would be much more efficient - just an index lookup.

At 4000 validators, this was costing 120,000 compute units, a quite shocking amount.

```rust
let maybe_validator_stake_info = validator_list.find_mut::<ValidatorStakeInfo>(
    vote_account_address.as_ref(),
    ValidatorStakeInfo::memcmp_pubkey,
);
```

Another way is to have the validator lists always be stored in sorted order.

But this requires `memcpy`. But we already have `memcpy`.

Personally, I think that as far as can be done, expensive operations should be computed on user side. This would possibly make it possible to update 10s of accounts in a single tx.

Instead of the retain instruction, I would also perform the memmove instantly, upon deleting the validator account from list.

@joncinque @billythedummy

**Comment by jon-chuang** [comment]
Where is `find` or `find_mut` used in the stake pool?

`find`:
1. Add validator. Check for duplicate (pubkey non-existence).
2. Withdraw stake. Check if any validators in list have active or transient lamports (I feel that this check should be replaced by, if 95% of stake is in reserve, you can withdraw from the reserve - a local condition). Check if preferred validator is in the list (pubkey non-existence)..
3. Deposit stake. Check if preferred validator is in list. (pubkey non-existence).

`find_mut`:
1. Remove validator. Find the validator to remove from the list.
2. Decrease stake. Find the validator to decrease from from the list.
3. Increase stake. Find the validator to increase to from the list.
4. Deposit stake. Find validator to deposit stake to.
5. Withdraw stake. Find validator to withdraw from.

Given these requirements, I believe it is much better to implement a sorted list with a memmove.

**Comment by jon-chuang** [comment]
I've implemented the sorted vec approach here:
https://github.com/igneous-labs/solana-program-library/tree/stake-pool/ordered-vec

Quite frankly, as much as it is oh-so-pleasantly more efficient, it doesn't buy us much - compute budget will increase in due time, and getting to 3950 validators is still a distant mirage.

In the first place, ordered vec doesn't solve the underlying scaling limit of `update_pool_balance`.

It does help with facilitating more transient accounts, however. 

I'll remove the changes to `update_pool_balance` for now, converting the list update into a multi-transaction walk is probably more doable.

**Comment by joncinque** [comment]
These are all great ideas! I went through most of these myself before going with the in-place deserialization model that we have now :sweat_smile:
