### ISSUE TITLE
Proptest fuzzing of `calc_lamports_withdraw_amount` fails on slightly modified master with (probably) different seeds.

### ISSUE THREAD

**Issue by jon-chuang** [solana-labs/solana-program-library#2237]
![image](https://user-images.githubusercontent.com/9093549/128664944-fb30345c-44fc-4d0c-b62b-bfa66b0f0194.png)

Proptest is probably not so good if it doesn't use a random seed to fuzz each time the test is run and that it doesn't detect this failure on master is indication it needs to be improved.

**Comment by CriesofCarrots** [comment]
Looks like the same failure I saw in CI downstream-projects: https://buildkite.com/solana-labs/solana/builds/52453#2cab453d-2075-4ad1-a0d9-bcdf0161332e
My hypothesis was that it was related to new bpf-tools release and something stale in the buildkite cache.

**Comment by joncinque** [comment]
Typically, proptest should give you a line to add to the `proptest-regressions` file to reproduce this right away.  I'm surprised that this error never showed that.  If you ever do get that seed, then we can reproduce and fix the issue.
