### ISSUE TITLE
cann't create-validator-stake

### ISSUE THREAD

**Issue by mingming-tang** [solana-labs/solana-program-library#2244]
spl-stake-pool create-validator-stake FVs4DDQfpTXJf5tEQVyYdfhQvRrpHi2RkbVaSdu4owR7 3DyJUFT1JBthyiW8R8iFUQbqfYUTyeMFjHKmiXEiCMJb
Creating stake account 9d19XjS49hvStmaX4utSWSodUABqSVrL5i36Ln2LHiRC, delegated to 3DyJUFT1JBthyiW8R8iFUQbqfYUTyeMFjHKmiXEiCMJb
RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x15 [6 log messages]

**Comment by joncinque** [comment]
If you look over at the code, error `0x15` is `WrongStaker`, meaning that the instruction was not signed by the "staker" authority for the pool

* https://github.com/solana-labs/solana-program-library/blob/7c89855f0fe473466a6fdc0a2274d40db647b517/stake-pool/program/src/error.rs#L84
* https://spl.solana.com/stake-pool#motivation for the staker definition
