### ISSUE TITLE
No way to recover tokens sent to a token address whose authority is an associated token account

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#2248]
#### Problem
When an associated token account (1) is created for an account (2) which is also an associated token account, there is no way to withdraw tokens held by the account (1) because the owner account (2) cannot sign to approve a transfer because it is a PDA for the ATA program. Tokens can only be transferred if the ATA program supports transfers itself, which it currently does not.

#### Proposed Solution
Add a "recover tokens" instruction to the ATA program which allows recovering tokens that are inaccessible

**Comment by jstarry** [comment]
To prevent this issue from occurring in the future here is a proposal to add a new instruction with fewer foot guns: https://github.com/solana-labs/solana-program-library/issues/2249

**Comment by jstarry** [comment]
Related to https://github.com/solana-labs/solana-program-library/issues/1371

**Comment by hitwill** [comment]
@chaseeb in the interim, how can we use the API to recover Kin from a 'child of a child' token account?

**Comment by hitwill** [comment]
This has affected a few of our community members as well. Keen to have a solution

**Comment by alexkruglov** [comment]
A gentle follow up on this to see if we are making progress. I am one of those affected by this

**Comment by jveer634** [comment]
Here I believe I have a similar situation. I am writing an SPL staking program for one of my projects and I need to write an emergency recover_tokens which is supposed to transfer the tokens from the staking associated token address to the authority associated token account.

If mine a similar issues? Or am I just doing things in a wrong way ?

Here is the code referrence

![image](https://user-images.githubusercontent.com/47923507/192737408-2ae2f02d-07e5-4d8c-93a3-993167d53360.png)

![image](https://user-images.githubusercontent.com/47923507/192737482-cc5b9001-4182-4f7c-a91d-d35eeac4a216.png)

![image](https://user-images.githubusercontent.com/47923507/192737550-a812d94b-777f-4f24-944f-3e443c5de6a1.png)

**Comment by jordansexton** [comment]
@jveer634 this is a closed issue. Please ask questions at https://solana.stackexchange.com/
