### ISSUE TITLE
ATA creation has some usability footguns

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#2249]
#### Problems
1) ATA (associated token account) creation can be done for non-system accounts which can lead to unrecoverable tokens (especially if an ATA is created for another ATA)
2) ATA creation is not idempotent which causes usability issues due to race conditions in RPC interactions

#### Proposed Solution
Add a new instruction for idempotent ATA creation which restricts owners to be system accounts

**Comment by ryoqun** [comment]
>     2. ATA creation is not idempotent which causes usability issues due to race conditions in RPC interactions

ref: https://github.com/solana-labs/solana-program-library/issues/1371

**Comment by jstarry** [comment]
Closed in favour of https://github.com/solana-labs/solana-program-library/issues/1371
