### ISSUE TITLE
stake-pool: instant stake activation

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#2260]
#### Problem

Any user can deposit a stake account with extra, non-staked lamports into the pool receiving pool tokens for all lamports -> pool tokens can be redeemed for a fully staked stake account.

#### Solution

A user depositing stake should only receive pool tokens equal to normal stake account rent-exemption (2.2 million lamports) + stake's delegation.  Note that we shouldn't use the provided stake account's rent exempt amount, because a user could do another version of this attack if they allocate a huge amount of data (1 MB for example), then provide that account with a small stake.  The rest of the stake is just taken by the pool, and that's fine.

**Comment by jon-chuang** [comment]
@joncinque , for consistency, I consider everything apart from the `delegation.stake`, including the rent exempt amount, as being sol deposits.

I'm not sure if this is an undesirable property.

For instance, a pool manager may want to forbid direct SOL deposits, but this mechanism would allow such deposits.

Perhaps we should stick to the choice that a user providing extra lamports beyond `delegation.stake + RENT_EXEMPT` will not be reimbursed with additional pool tokens?
