### ISSUE TITLE
stake-pool: Require signature in `SetManager`

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#2265]
#### Problem

SetManager does not require signature from new manager, while Initialize does

#### Solution

You probably want to require the signature of the new manager in SetManager as well, to make sure that the new manager is a key with a valid private key

**Comment by billythedummy** [comment]
Should we do the same for `SetStaker` as well? 

This doesn't preclude managers from being on-chain programs, right? Since `new_manager` can be a PDA of an on-chain manager program and signed via CPI using `invoke_signed`

**Comment by joncinque** [comment]
For `SetStaker`, we're safe since there's always the manager behind.  The idea of requiring a signature is to be sure that you never brick the pool.  And exactly, we can have `new_manager` as a PDA if the calling program uses `invoked_signed`
