### ISSUE TITLE
stake-pool: Consider hard-coding `spl_token::id` instead of passing in token program

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#2266]
#### Problem

There are no guarantees that a custom token program will behave exactly the same way as SPL token, so it could have sketchy logic which obviates all of the initialize checks.

#### Solution

Consider hard-coding `spl_token::id()` everywhere

**Comment by joncinque** [comment]
haha not quite, the idea is to avoid having `token_program_id` set on the stake pool, and just always use `spl_token::id()`. this is just a consideration though.  the only part that actually needs to be changed is the one references to `spl_token::id()` in the instruction code

**Comment by jon-chuang** [comment]
Hmm yeah, but then changing would require a redeployment of the program. 

What's this `spl_token_v2` though? Is my question. Isn't it an upgradeable version of the token program?

**Comment by billythedummy** [comment]
should we get rid of the `token_program_id` field on the stake pool state struct then? Though this change will not be backward compatible. 

> haha not quite, the idea is to avoid having `token_program_id` set on the stake pool, and just always use `spl_token::id()`. this is just a consideration though. the only part that actually needs to be changed is the one references to `spl_token::id()` in the instruction code

Also, sorry but I don't quite get "the only part that actually needs to be changed is the one references to `spl_token::id()` in the instruction code". What does "instruction code" refer to, the process_*instruction* functions?

**Comment by joncinque** [comment]
I literally just meant this line: https://github.com/solana-labs/solana-program-library/blob/7d748fc507162cddb158ac18c72d4484477b0357/stake-pool/program/src/instruction.rs#L780 -- it's the only line that requires `spl_token::id()`, every other part of the program (I believe) would work with any token program, not just the official SPL token program
