### ISSUE TITLE
Governance: no check for the next instruction index?

### ISSUE THREAD

**Issue by ilmoi** [solana-labs/solana-program-library#2276]
I noticed that the `process_execute_instruction` method doesn't do a check for instruction's index.

Unless I missed it, I think the only checks are:
1. That the instruction belongs to the proposal
```rust
if proposal_instruction_data.proposal != *proposal {
        return Err(GovernanceError::InvalidProposalForProposalInstruction.into());
    }
```
2. That the proposal is in an acceptable state
```rust
match self.state {
            ProposalState::Succeeded
            | ProposalState::Executing
            | ProposalState::ExecutingWithErrors => {}
            ProposalState::Draft
            | ProposalState::SigningOff
            | ProposalState::Completed
            | ProposalState::Voting
            | ProposalState::Cancelled
            | ProposalState::Defeated => {
                return Err(GovernanceError::InvalidStateCannotExecuteInstruction.into())
            }
        }
```
3. That the hold up time has passed
```rust
        if self
            .voting_completed_at
            .unwrap()
            .checked_add(proposal_instruction_data.hold_up_time as i64)
            .unwrap()
            >= current_unix_timestamp
        {
            return Err(GovernanceError::CannotExecuteInstructionWithinHoldUpTime.into());
        }
```
4. That the instruction hasn't been already executed
```rust
        if proposal_instruction_data.executed_at.is_some() {
            return Err(GovernanceError::InstructionAlreadyExecuted.into());
        }
```

Is this intentional with the idea that instructions can come in any order? Or is this a bug? Or did I miss it somewhere?

**Comment by SebastianBor** [comment]
Thank you for looking into it. In the current version the instructions are unordered. They could be spaced apart in time using the `hold_up_time` to provide soft ordering. This way the proposal owner can take care of executing them in order. 
Strong and enfrocabel ordering of instructions is planned for future versions [InstructionExecutionFlags](https://github.com/solana-labs/solana-program-library/blob/965afef2cd9f61a2b4472e0e0bd28b8b678f3913/governance/program/src/state/enums.rs#L147)
