### ISSUE TITLE
Token JS Client: Expose createTransferCheckedInstruction static method from Token class

### ISSUE THREAD

**Issue by danmt** [solana-labs/solana-program-library#2284]
# Overview

There's a static method in the Token class named `createTransferCheckedInstruction`, which is pretty convenient if you want to easily generate a TransferChecked TransactionInstruction. The mentioned method is not exposed in the [declarations file](https://github.com/danmt/solana-program-library/blob/master/token/js/module.d.ts). 

## Solution

While I'm not entirely sure how the entire build/release process goes, I fixed it locally by adding the below snippet into the [Token class declaration](https://github.com/danmt/solana-program-library/blob/master/token/js/module.d.ts#L67) in my node_modules.

```typescript
static createTransferCheckedInstruction(
      programId: PublicKey,
      source: PublicKey,
      mint: PublicKey,
      destination: PublicKey,
      owner: PublicKey,
      multiSigners: Array<Signer>,
      amount: number | u64,
      decimals: number,
    ): TransactionInstruction;
```

I would expect this to be a simple change and I can gladly put the PR together.

**Comment by mvines** [comment]
Hey, a PR for this would be great!  We normally make releases to npmjs on demand for the token package
