### ISSUE TITLE
ATA create transaction race

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana-program-library#2295]
#### Problem

Dapps that submit frequent consecutive transactions referencing the same ATA race when the account needs to be created.  This leads to subsequent transactions failing

#### Proposed Solution

Allow ATA create to succeed without effects if the account already exists in the expected state, perhaps via an explicit instruction

**Comment by Arrowana** [comment]
We suffered from this using a reward distribution back-end (for community stuff) and ended up implementing that on-chain:
https://github.com/mercurial-finance/create-ata-if-missing-program
