### ISSUE TITLE
Reorganize source tree layout based on program version

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana-program-library#230]
The current program source layout is inadequate for working on newer version of a SPL program while maintaining the existing deployed versions.  

Proposal is to refactor up the current `token/` directory into:
```
token-1.0/  <-- represents the 1.0.0 token that has already been deployed to mainnet-beta
token-dev/ <-- the 1.1.0 token that will be deployed sometime in the future.
```

When `token-dev/` is ready to be deployed, it's copied into `token-1.1/` and then `token-dev/` moves up to "1.2.0".  

The benefit of this approach is a clear representation of the on-chain source code for a given token version **while** retaining the ability to ship new patch releases for each token crate.  Of course since token 1.0.0 program is deployed, it can't be changed but the client portion of the 1.0.0 token may still need to change from time to time (such as if we ship a breaking change in the solana-sdk crate).

The same model applies to the other SPL programs.  For `token-swap` there would only be a `token-swap-dev` since 1.0.0 has not shipped yet.

**Comment by mvines** [comment]
```
memo/
token/ <-- development version of token, would be 1.1 currently
token-cli/ <-- non-program crate 
token-swap/ 
deployed/memo-1.0/  
deployed/token-1.0/
```

**Comment by mvines** [comment]
I'm thinking about this to make it more clear which version of each program, "main", is still under development, and to keep the program crates away from the non-program crates:
```
main/memo/
main/token/ <-- development version of token, would be 1.1 currently
main/token-swap/ 
deployed/memo-1.0/  
deployed/token-1.0/
token-cli/ <-- non-program crate 
```

**Comment by jackcmay** [comment]
I find that a little awkward to sequester off the programs but not the cli clients.  Also not a fan of `main`, from a deployed/not deployed, and a program terms perspective.

Maybe stick programs under `programs` like:

`programs/token`
`programs/deployed/token`

And cli under `clis` or `clients`

**Comment by mvines** [comment]
```
program/memo/
program/token/ <-- development version of token, would be 1.1 currently
program/token-swap/ 
program/deployed/memo-1.0/  
program/deployed/token-1.0/
cli/token/
```
or program**s**?

**Comment by garious** [comment]
How about?

```
memo/program/
memo/program-1.0/
memo/cli/
```

**Comment by mvines** [comment]
Yep, the current repo then ends up looking like this:
```
ci/
memo/program/
memo/program-1.0/
token-swap/program/
token/cli
token/program
token/program-1.0
```

**Comment by garious** [comment]
Looks nice to me, simple things are simple, and grouped by functionality rather than type.

**Comment by mvines** [comment]
Cargo workspaces cannot have multiple crates with the same name in them.  This layout:
```
token/program
token/program-1.0
```
implies that both program crates would be called `spl-token` (one versioned 1.1.x and the other versioned 1.0.y), and cargo says no.

Crate names like `spl-token-1-0`/`spl-token-1-1` feel clunky (`spl-token-10`/ `spl-token-11` not much better).  So I'm thinking of going with a slightly different versioning system: `spl-token` and `spl-token2`

The current "1.0" token is still `spl-token` and the crate name is also `spl-token`.  

The features we're developing for what is currently called `spl-token 1.1` would now be called `spl-token 2`.  The program crate name is `spl-token2`, and the first release of that program crate would be `spl-token2 1.0.0`.    Directory structure:

```
token/program
token/program2
```

**Comment by jackcmay** [comment]
That seems fine, would we ever increment major and minor crates versions?

**Comment by mvines** [comment]
> That seems fine, would we ever increment major and minor crates versions?

We might, if we follow semver strictly:
* `spl-token 1.1.0` is published because it adds a notable new feature to the client bindings
* `spl-token2 2.0.0` is published due to an incompatible client-side change
But in all cases, the program itself for all `spl-token` and `spl-token2` crate versions is fixed.
