### ISSUE TITLE
Cant create new token

### ISSUE THREAD

**Issue by rokelopez** [solana-labs/solana-program-library#2345]
when I try creating my SPL token it says the system cannot find the path specified. Please help

**Comment by joncinque** [comment]
This means that you haven't setup a keypair to use by default with the Solana CLI.  You can check out the docs at https://spl.solana.com/token#default-keypair for more information about how to do that.

In the future, please get in touch through Discord https://discord.gg/aS5Z8W53 in the #developer-support channel for support. GitHub is mainly used for developing.

**Comment by rokelopez** [comment]
Hey Jon, apologies. Im still getting an error. its saying that a
signature is missing for my pubkey key. Could you please help me out

**Comment by joncinque** [comment]
For sure! Please reach out at our Discord, most likely a key was improperly configured somewhere.  You can also try going through the directions outlined at https://spl.solana.com/token
