### ISSUE TITLE
Failing in convert a mnemonic to a seed for a solana wallet

### ISSUE THREAD

**Issue by DiazRock** [solana-labs/solana-program-library#2396]
I posted a related SO question [here](https://stackoverflow.com/questions/69119382/failing-in-convert-a-mnemonic-to-a-seed-for-a-solana-wallet)

I'm trying to use a wallet seed on the backend, using `nodejs`, to connect in blockchain. The Keypair module from ["@solana/web3.js"](https://github.com/solana-labs/solana-web3.js/) library has a fromSeed method, that I use with input from another method, from the [bip39](https://www.npmjs.com/package/bip39) library, that converts my mnemonic to a seed. This is my code:

```json

const mnemonic = <My-mnemonic>
console.log(bip39.validateMnemonic(mnemonic)) // true
bip39.mnemonicToSeed(mnemonic).then(buffer => Keypair.fromSeed(buffer)).catch(err => console.log(err))

```

This is my error

```bash
Error: bad seed size
    at Function.nacl.sign.keyPair.fromSeed (/home/diazrock/Carrera/Elasbit/NFT's/mint-nft-solana/node_modules/tweetnacl/nacl-fast.js:2329:11)
    at Function.fromSeed (/home/diazrock/Carrera/Elasbit/NFT's/mint-nft-solana/node_modules/@solana/web3.js/lib/index.cjs.js:5625:53)
    at bip39.mnemonicToSeed.then.buffer (repl:1:55)
```

**Comment by t-nelson** [comment]
ed25519 secret keys are generated from 32-byte seeds. `bip39.mnemonicToSeed` generates 64-byte seeds. We truncate the seed in the Rust implementation https://github.com/solana-labs/solana/blob/2de2c6ddd7981e942c634243e8558a84727d791f/sdk/src/signer/keypair.rs#L158.  Try that and verify that you're recovering the same keypair as `solana-keygen recover`
