### ISSUE TITLE
[ProgramTest] Transaction not processed when signed with a custom keypair

### ISSUE THREAD

**Issue by Konosh93** [solana-labs/solana-program-library#2443]
## Summary
I am trying to test a program using  ProgramTest but I need to sign the test transaction with a different keypair than the payer provided by the helper. Unfortunately, this seems to cause the transaction to timeout. The reason I am using another keypair is that I need the public key of the keypair to use as an owner for some token accounts used in the test. I apologize if I am misunderstanding something terribly, but I have created a simple reproduction of the issue as a PR here: https://github.com/Konosh93/rusty-sol/pull/1

### Goal
- Demonstrate how to use another `keypair` to sign transactions when running e2e tests with `ProgramTest`.

### Expected
- Start transaction processing.

### Actual
- fail to process the transaction
```
running 1 test
[2021-09-20T03:27:47.673069000Z INFO  solana_program_test] "another-payer" program loaded as native code
test test_escrow has been running for over 60 seconds
test test_escrow ... FAILED

failures:

---- test_escrow stdout ----
thread 'test_escrow' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: TimedOut, error: "Client dropped expired request." })', tests/functional.rs:56:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_escrow

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 60.33s

error: test failed, to rerun pass '--test functional'
```

**Comment by joncinque** [comment]
Hi there, apologies for the late response, but we don't typically use GitHub for tech support, and invite you to join us on Discord if you haven't already made your way there: https://discord.gg/JJkWhPjb

To quickly answer your question, you need to fund the other keypair that you're signing with, so you can just do a transfer from the payer to the other keypair.
