### ISSUE TITLE
Please Help. My tokens went to associated account.

### ISSUE THREAD

**Issue by gordylad** [solana-labs/solana-program-library#2457]
Hello I am a 60yr old crypto enthusiast. Over the weekend I made a few transactions and for some reason my tokens have gone to an associated account that I have tracked and can see them there. The strange thing is I provided liquidity to a system and I am generating rewards even though my LP tokens are in the associated account. When I harvest the rewards they go to my original wallet.

I am not able to lose funds like this and I hope developers can support me

Thanks

Gordon

**Comment by jstarry** [comment]
Hey Gordon, sorry to hear about your troubles here. When you look at the associated token account on the Solana explorer https://explorer.solana.com do you see your address as the owner? Or is the owner a different associated token account?

**Comment by gordylad** [comment]
Hi Just
Thanks for your email Im not techy so not sure but here is my account and the associated account could you check?

MY ACCOUNT       5KZEQVczYHnrVdmz2XJmsoxTUZELGPCmFCMWqhbkGfSm

OTHER ACCOUNT       AcQ7S2sprmo3VhpLvMBSFLJhSgv5tPVc1d7BXWW7poMh
    On Tuesday, 28 September 2021, 16:32:42 BST, Justin Starry ***@***.***> wrote:  
 
 


Hey Gordon, sorry to hear about your troubles here. When you look at the associated token account on the Solana explorer https://explorer.solana.com do you see your address as the owner? Or is the owner a different associated token account?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gordylad** [comment]
Hi Justin
Sorry but due to the nature of what's going on been feeling a little hazy in the head so will try to explain more.
I made transactions over the weekend both on Raydium and Orca within a few minutes of each other. On Raydium I removed liquidity and on Orca I bought Orca with Sol to add to my already added LP SOL/Orca.
Until today I was able to see my Orca/Sol pool and other Orca pools on their main web site and when I harvested rewards they went into my wallet fine.
Now the pools have dropped off and all I know is the account that I provided to you starting Ac is a mirror of what my 5K account held.
I did receive 10 SRM tokens back into my wallet today.
I hold my private seed and have the wallet password protected.
I'm pulling the little hair I have on my head account  and really hope you can help in some way.
Thanks
Gordon
    On Tuesday, 28 September 2021, 16:32:42 BST, Justin Starry ***@***.***> wrote:  
 
 


Hey Gordon, sorry to hear about your troubles here. When you look at the associated token account on the Solana explorer https://explorer.solana.com do you see your address as the owner? Or is the owner a different associated token account?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jstarry** [comment]
@gordylad can you please share which wallet you are using (phantom, sollet, etc)? And can you also review your browser history and share which domains you used for orca and raydium?

**Comment by gordylad** [comment]
Hi Justin
Wallet has always been sollet. Domains used were Orca | The DEX for people, not programs

| 
| 
|  | 
Orca | The DEX for people, not programs

Orca is the easiest, fastest, and most user-friendly cryptocurrency exchange on the Solana blockchain.
 |

 |

 |


and Home | Serum

| 
| 
|  | 
Home | Serum

TechmyBrand

Serum is a decentralized exchange (DEX) and ecosystem that brings unprecedented speed and low transaction costs ...
 |

 |

 |

 and https://raydium.io/


I have a telegram trail between me and Orca admin on telegram as they asked me to screenshot how I could see my Liquidity even though the liquidity tokens were not in my wallet but in the Ac wallet. I did this but they came back and send due to the number of transactions going through and the fact the liquidity tokens were not in my wallet they could not help. I asked again and they banned me from the telegram group!    On Tuesday, 28 September 2021, 18:57:41 BST, Justin Starry ***@***.***> wrote:  
 
 


@gordylad can you please share which wallet you are using (phantom, sollet, etc)? And can you also review your browser history and share which domains you used for orca and raydium?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jstarry** [comment]
@gordylad please visit https://github.com/solana-labs/solana-program-library/issues/2457 to give better replies. I need you to check the URL's that you visited in the past 24hr and can you please let me know if you had to recover your wallet seed phrase in the past 24hr. Thanks

**Comment by jstarry** [comment]
Also, please share the name of the telegram group and the username of the orca admin you worked with, thanks.

**Comment by gordylad** [comment]
Just to say there is still one pool on Orca that would allow me to harvest the rewards even though the LP tokens are not showing in my wallet

0.47 ORCAper day for each $10000.015749ORCAHarvestORCA/USDCTotal Liquidity$49,552,799Yearly Returns282%Dep
    On Tuesday, 28 September 2021, 18:57:41 BST, Justin Starry ***@***.***> wrote:  
 
 


@gordylad can you please share which wallet you are using (phantom, sollet, etc)? And can you also review your browser history and share which domains you used for orca and raydium?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gordylad** [comment]
Orca


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Orca

The official Telegram group for Orca, the most user-friendly DEX on Solana: https://orca.so Announcements: ht...
 |

 |

 |


@Leo40K     seems to be admin leader



    On Tuesday, 28 September 2021, 19:25:37 BST, Justin Starry ***@***.***> wrote:  
 
 


Also, please share the name of the telegram group and the username of the orca admin you worked with, thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gordylad** [comment]
Hi just to say I haven’t had to recover my wallet seed phrase per your earlier question thanks

**Comment by jstarry** [comment]
Sorry I can't help you with the information you provided. You have been scammed but I'm not sure how. Unfortunately it's very likely you'll get your funds back and there's nothing I can do to help with that. If you provide more information about how you got scammed, we can try to protect others from the same issue.

**Comment by gordylad** [comment]
ps I still do not believe a scam took place as I am very robust about any transactions

**Comment by gordylad** [comment]
and just to say the following transaction was the last one made from my account which shows a contract address not related to others https://solscan.io/tx/2up8jxoNsfYQr3qEYQttpBwDyCP2GVP5ZfgDM1chtaGehvi82TBS7d3EkSHq4qvHvK7vrpqSXxJQVvfrJk5iztfD

**Comment by t-nelson** [comment]
Please take this to Discord (https://solana.com/discord).  Github is a terrible venue for user support and we do not need noise in the developer workflow

**Comment by Clark1131** [comment]
I can't believe how terrible people have become in the world, how can a broker call me up and make me believe that I was investing into something genuine, in a couple of months I had been fleeced out of my life savings, till this day haven't even been able to get fully back on my feet. Having taken my time to do some research would like to speak with other people who have been through similar experience, together without a doubt I am sure with likeminded minds we can all get our money back. I met with a genius Freddictine consultant dot com who helped me get back on my feet again
