### ISSUE TITLE
Type Error on Beginner UI

### ISSUE THREAD

**Issue by T-Wall** [solana-labs/solana-program-library#2486]
User experienced this error when purchasing a put option on the beginner UI. 

![unknown-1](https://user-images.githubusercontent.com/91228741/136125293-2b7afc71-7231-43fb-bfdd-cf641ca8c41e.png)

**Comment by joncinque** [comment]
It looks like this is related to PsyOptions, and not this repo, so please address this issue to the PsyOptions team. It looks like the GitHub repo for frontend project is https://github.com/mithraiclabs/psyoptions-frontend
