### ISSUE TITLE
Unable to obtain / create token address for recipient

### ISSUE THREAD

**Issue by AlexLeung** [solana-labs/solana-program-library#2497]
```typescript
import { web3 } from "@project-serum/anchor";
import { Token, TOKEN_PROGRAM_ID as TPID } from "@solana/spl-token";

      var mintPublicKey = new web3.PublicKey(EXISTING_CUSTOM_TOKEN_MINT_ADDRESS);    
      var mintToken = new Token(
        connection,
        mintPublicKey,
        TPID,
        wallet.payer
      );
      
      const fromTokenAccount = await mintToken.getOrCreateAssociatedAccountInfo(
        wallet.publicKey
      );

      console.log("owner " + fromTokenAccount.owner.toBase58() + ", has token account " + fromTokenAccount.address.toBase58() + " for mint " + fromTokenAccount.mint.toBase58());

      const destPublicKey = new web3.PublicKey(RECIPIENT_ADDRESS);
      console.log("setting up account or getting for", RECIPIENT_ADDRESS);
      const toTokenAccount = await mintToken.getOrCreateAssociatedAccountInfo(
        destPublicKey
      );

      console.log("owner " + toTokenAccount.owner.toBase58() + ", has token account " + toTokenAccount.address.toBase58() + " for mint " + toTokenAccount.mint.toBase58());

      instructions.push(
        Token.createTransferInstruction(
          TPID,
          fromTokenAccount.address,
          toTokenAccount.address,
          fromWallet.publicKey,
          [],
          1
        )
      )
```

this line

```typescript
await mintToken.getOrCreateAssociatedAccountInfo(destPublicKey);
```

always returns with the error

```
Unhandled Rejection (Error): Failed to find account
```

I thought the whole point is that if it cannot find the account then it should create it for me??

**Comment by AlexLeung** [comment]
Answered here https://stackoverflow.com/questions/68236211/how-to-transfer-custom-token-by-solana-web3-js/69522224#69522224

Instead of using 

```typescript
await mintToken.getOrCreateAssociatedAccountInfo(destPublicKey);
```

use this instead

```typescript
  const associatedDestinationTokenAddr = await Token.getAssociatedTokenAddress(
    mintToken.associatedProgramId,
    mintToken.programId,
    mintPublicKey,
    destPublicKey
  );

  const receiverAccount = await connection.getAccountInfo(associatedDestinationTokenAddr);
        
  const instructions: web3.TransactionInstruction[] = [];  

  if (receiverAccount !== null && receiverAccount.owner.toBase58() !== destPublicKey.toBase58()) {
    // derived account of original owner was at one point transferred, so we transfer our account (only works with NFTs, not fungibles). I opened https://github.com/solana-labs/solana-program-library/issues/2514 to figure out fungibles
    instructions.push(
      Token.createSetAuthorityInstruction(
        TPID,
        fromTokenAccount,
        destPublicKey,
        "AccountOwner",
        fromWallet.publicKey,
        []
      )
    );
  } else {
    if (receiverAccount === null) {
      instructions.push(
        Token.createAssociatedTokenAccountInstruction(
          mintToken.associatedProgramId,
          mintToken.programId,
          mintPublicKey,
          associatedDestinationTokenAddr,
          destPublicKey,
          fromWallet.publicKey
        )
      )
    }
    instructions.push(
      Token.createTransferInstruction(
        TPID,
        fromTokenAccount,
        associatedDestinationTokenAddr,
        fromWallet.publicKey,
        [],
        1
      )
    );
  }
```

Also you can transfer the authority of

**Comment by karnie6** [comment]
hey @AlexLeung - thanks for your reply here.  FYI, I created a GH issue (https://github.com/solana-labs/solana-program-library/issues/2814 ) where I'm seeing a similar issue when trying to find/create associated account info for the seller.  I tried using your suggestion above, but seeing issues with incorrect program id.  Any ideas?

**Comment by MisterCode415** [comment]
Any update on this I get a similar issue with program id being wrong; I've been whack-a-moling life itself trying to figure out which ID we need to use here. Definitely using the program id of the token holding account but to no avail.

**Comment by karnie6** [comment]
FYI @MisterCode415 - i got this above code to work. What fixed it was listening in on the initial mint transaction to make sure it was confirmed before sending it.  Happy to send you over a code sampel if that would help!

**Comment by MisterCode415** [comment]
SNAZZY! Oh man thank you for that tip, thats amazing, I was certainly not, and was getting intermittent failure codes (real mind boggler hah). So what you brought to light makes total sense, thank you!

**Comment by karnie6** [comment]
@MisterCode415 - yeah it had def stumped me too, but once i made that change, it's basically worked for me 99+% of the time.

**Comment by MaximeLassalleHub** [comment]
@karnie6 @MisterCode415 
Can you help me on the solution?
I have the exact same issue described here when executing a Transfer transaction on a nft token minted with Metaplex.js.
How did you make sure the initial mint was confirmed before Transfer?
Thanks

**Comment by karnie6** [comment]
hey @MaximeLassalleHub - here's how I did it

`
const mintResult  = await actions.mintNFT({
    connection,
    wallet,
    uri,
    maxSupply,
  });

connection.onSignatureWithOptions(
    mintResult.txId,
    async (notification, context) => {
      if (notification.type === 'status') {

        const { result } = notification;
        if (!result.err) {
          console.log('NFT Minted with mint ID: ', mintResult.mint.toBase58());
  
         //your NFT transfer code
      }
  },
    { commitment: 'confirmed' },
  );

`

Hope this helps!
