### ISSUE TITLE
token-js: Allow a custom mint address for create-mint

### ISSUE THREAD

**Issue by tevdoradze** [solana-labs/solana-program-library#2516]
At Aurory we are going to use a custom mint address for our token (generated through the solana grind command), I think this is quite common as other projects (like star atlas etc..) are also using a vanity address.

Currently, it's not possible to directly submit a custom key pair through the cli or the JS mintToken function.

To make it possible:

- Add an optional argument to the create-token command, which should be a keypair's path + add a condition [here](https://github.com/solana-labs/solana-program-library/blob/e8b7009cc4d8cdd87232ccfc9ce93ab203ada496/token/cli/src/main.rs#L2287).
- Add an optional `mintAccountKeypair: Signer` to [the js function](https://github.com/solana-labs/solana-program-library/blob/aef1e239b37f5547c2c86390f204da41b0965adb/token/js/client/token.js#L384) + a condition for the mintAccount

**Comment by tevdoradze** [comment]
@mvines 

> > it's not possible to directly submit a custom key pair through the cli
> 
> The cli supports this actually and it's exactly the code you linked to!
> 
> > Add an optional argument to the create-token command, which should be a keypair's path + add a condition here.
> 
> The optional argument to the create-token command is the custom mint keypair

Do you think it makes sense to add an optional argument to JS [createMint](https://github.com/solana-labs/solana-program-library/blob/aef1e239b37f5547c2c86390f204da41b0965adb/token/js/client/token.js#L384) function to be able to also use a custom mint address from here?

**Comment by mvines** [comment]
Yep that seems fine to me!

**Comment by jordansexton** [comment]
Might make sense to briefly mention this is being done now in https://github.com/solana-labs/solana-program-library/pull/2539:

https://github.com/solana-labs/solana-program-library/blob/25111c64207c6f684e95990de32c787550f684ba/token/ts/src/actions/createMint.ts#L29-L39

**Comment by joncinque** [comment]
Fixed in #2539

**Comment by iMrDJAi** [comment]
@tevdoradze @joncinque Besides having a cool looking mint address, what's the point of specifying a custom keypair for the mint token? What could you do if you have access to the mint account secret key? Are there any security implications?

**Comment by joncinque** [comment]
@iMrDJAi Your question better belongs on a dedicated support forum like https://solana.stackexchange.com/ -- I (or someone else) would be happy to answer it there!
