### ISSUE TITLE
Retrieve SPL tokens from an associated token account which associated to an SPL token account

### ISSUE THREAD

**Issue by yushizhao** [solana-labs/solana-program-library#2517]
I am not sure whether I am the first one to meet this issue...
The story is, I requested a token transfer to my Solana USDC SPL token account from an exchange. Instead of directly making a token transfer, this exchange created an associated token account for the Solana USDC SPL token account, and then transfer to that associated token account.
Then, we have a nested ownership of SPL tokens: associated token account -> Solana USDC SPL token account -> system account, the real owner.
I do not have the private key of that USDC SPL token account, since it is just an token account.
When I try transfer with the key of the owner of the USDC SPL token account, it says "owner not match". Well, the owner of the associated token account is the USDC SPL token account, not that owner.
So, is there a way to retrieve the token from the associated token account?

**Comment by Moserious** [comment]
Did you resolve this matter and if so how?

**Comment by yushizhao** [comment]
@Moserious Are you also in the same situation? No. I didn't solve it. I think it need to modify the SPL token program to solve it.

**Comment by Moserious** [comment]
Yes, same situation I think. I was using FTX app and when I was transferring USDC to another exchange, the FTX prompted me to enter an USDC or SOL address. I entered a SOL address, not sure why I chose to do that, but now the USDC is "stuck" so to speak via the Associated Token Account Program. The "owner" of the USDC is reflected as my Solana account address, but I'm not sure as of yet how to send the USDC from the Token Account, but am working on it. Keep me posted, and I'll do the same.

**Comment by yushizhao** [comment]
@Moserious I think, if the situation is:

Your NATIVE sol (not wrapped sol) account -> own the ATA USDC account. 

Then you are good, you can transfer the token! Well, as long as you hold the NATIVE sol account's private key.
Or, if you mean the private key is hold by the another exchange. You can try ask them, they should be able to transfer the USDC with the private key!

Hope everything goes well!

**Comment by t-nelson** [comment]
Hi!  We don't use Github for support requests.  Please join us in #wallet-support on https://solana.com/discord instead!
