### ISSUE TITLE
cargo build-bpf failed in the token-swap

### ISSUE THREAD

**Issue by gotope** [solana-labs/solana-program-library#2518]
localhost:~/solana-program-library/token-swap/program$ cargo build-bpf 

BPF SDK: /home/enn/solana/bin/sdk/bpf

Running: rustup toolchain list -v               Running: cargo +bpf build --target bpfel-unknown-unknown --release
                             
error: command failed: 'cargo': No such file or directory (os error 2)

**Comment by gotope** [comment]
> Did you complete step 1 from https://github.com/solana-labs/solana-program-library#environment-setup?
> If so, what does `cargo --version` output?

$ cargo --version
cargo 1.55.0 (32da73ab1 2021-08-23)

$ rustup toolchain list -v
stable-aarch64-unknown-linux-gnu (default)     /home/enn/.rustup/toolchains/stable-aarch64-unknown-linux-gnu
bpf     /home/enn/projects/rustprojects/solana/bin/sdk/bpf/dependencies/bpf-tools/rust
1.52.1-aarch64-unknown-linux-gnu        /home/enn/.rustup/toolchains/1.52.1-aarch64-unknown-linux-gnu

**Comment by gotope** [comment]
maybe I know the issue, not solved yet.

my liunx is on ARM cpu, so its aarch64.
cargo build-bpf, will install solana's  modified bpf-tools,
the installed cargo and rustc is x86-arch, obviously it can not be executed.

**Comment by ducan-ne** [comment]
@gotope I facing this issue too, have you solved this?

**Comment by joncinque** [comment]
Closing this since it hasn't had any movement, the program does build properly in all CI runs
