### ISSUE TITLE
SPL is hogging CI resources

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#252]
#### Problem
A couple dependabot PR's on this repo is all it takes to get the solana CI queue backed up to 50+ tasks

#### Proposed Solution
Switch to Github actions

**Comment by mvines** [comment]
Hopefully a little better now, if not please re-open

**Comment by mvines** [comment]
Also this prevents the Travis Push build for all dependabot PRs, on top of the normal PR build: https://github.com/solana-labs/solana-program-library/commit/908ce7ccb336c7e60250a9245ec5bb4fd36d8685
