### ISSUE TITLE
the `mintTo` function doesn't take large numbers well

### ISSUE THREAD

**Issue by aster2709** [solana-labs/solana-program-library#2536]
example: 
`token.mintTo(something,something,something,1000000000000000000000)` this very large number fails.  reducing to about `1000000000` works
error message: `Assertion failed` I dug into the stack traces, and it occurs on line 1748 `token.js` file. I think this sort of number is too large javascript can handle so how should I pass it, since it doesn't take a string input!

I need to pass such big number because the token i made has 18 decimals. so the numbers are going to be big.

**Comment by CriesofCarrots** [comment]
`1000000000000000000000 > 18446744073709551615` so it won't fit in a u64 any which way

**Comment by aster2709** [comment]
> My mistake, I didn't check to see if it even fit in a u64, so you'll have to try something up to `u64::MAX`, aka `FFFFFFFFFFFFFFFF`. Also, not sure if it'll make a difference, but it should be `u64.fromBuffer(Buffer.from('FFFFFFFFFFFFFFFF', 'hex'))` and not `u64.fromBuffer(Buffer.from('FFFFFFFFFFFFFFFF'), 'hex')`

didn't work: `invalid buffer length` 
![image](https://user-images.githubusercontent.com/39130640/138382535-44cca7e5-4b0c-4be5-ad8c-a5c7b3805628.png)
