### ISSUE TITLE
[broken] this RPC method unavailable for key

### ISSUE THREAD

**Issue by cryptoboole** [solana-labs/solana-program-library#2547]
This, and other iterations of it with different wallets:

[Finding all token accounts for a wallet](https://spl.solana.com/token#finding-all-token-accounts-for-a-wallet)
```
curl http://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getProgramAccounts",
    "params": [
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
      {
        "encoding": "jsonParsed",
        "filters": [
          {
            "dataSize": 165
          },
          {
            "memcmp": {
              "offset": 32,
              "bytes": "vines1vzrYbzLMRdu58ou5XTby4qAqVRLmqo36NKPTg"
            }
          }
        ]
      }
    ]
  }
```
Results in 
`
{"jsonrpc":"2.0","error":{"code":-32010,"message":"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA excluded from account secondary indexes; this RPC method unavailable for key"},"id":1}
`

I can't find any notifications of RPC call structure changes. We can't list the tokens that are within the wallet currently.

**Comment by joncinque** [comment]
This should be fixed now, closing

**Comment by triviatroy** [comment]
I'm still getting this error on mainnet-beta

**Comment by farhan067** [comment]
Did anyone find the solution to this? I am getting this error using web3 sdk.

**Comment by Notmeor** [comment]
Still getting this error on mainnet-beta

**Comment by joncinque** [comment]
This error will appear if a program is excluded from the secondary indices.  `Tokenkeg...` has so many accounts that it is almost always excluded from `getProgramAccounts` by RPC nodes, so this is part of totally normal operation.  Locking this discussion
