### ISSUE TITLE
Memo support for js

### ISSUE THREAD

**Issue by sandeepk-e** [solana-labs/solana-program-library#2571]
I was wondering if there is support to add memo through web3 APIs.( --with-memo equivalent flag in cli ) 
I could not find anything for node. The note [here](https://github.com/solana-labs/solana-program-library/pull/25) says js utilities to come separately. Any help regarding the same would be appreciated. 

Thanks.

**Comment by jordansexton** [comment]
Is this what you're looking for?

```ts
const MEMO_PROGRAM_ID = new PublicKey('MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr');

transaction.add(
    new TransactionInstruction({
        programId: MEMO_PROGRAM_ID,
        keys: [],
        data: Buffer.from('please include this special memo', 'utf8'),
    }),
);
```

**Comment by sandeepk-e** [comment]
Yes, I forgot to update here. I found [this](https://gist.github.com/fukaoi/61a29aac0717fce4219c86165780efcd) on the same day.

Thanks for help @jordansexton .

**Comment by joncinque** [comment]
@alexandr-kazakov https://github.com/solana-labs/solana-program-library/blob/57c5fd80f60ed4d6053989e64882f9002e352910/token/js/test/e2e-2022/memoTransfer.test.ts#L119 has an example.  Also, I'm going to lock this to avoid more necro-posting -- feel free to get in touch with StackOverflow or Discord if you have a question!
