### ISSUE TITLE
Rework builds which were excluded and left behind

### ISSUE THREAD

**Issue by Lichtso** [solana-labs/solana-program-library#2572]
The following crates are excluded from the workspace so their build targets are not covered by any CI pipeline.
They seem to be unmaintained as they are unbuildable right now and the last commit was a year ago in each.

See `Cargo.toml`:
```Toml
exclude = [
  "themis/client_ristretto",
  "themis/program_ristretto",
  "token/perf-monitor",
]
```

**Comment by joncinque** [comment]
`token/perf-monitor` was fixed up in https://github.com/solana-labs/solana-program-library/pull/2586 and most likely we'll need to retire the themis parts, since they are impossible to build against the Solana 1.8.x sdk.
