### ISSUE TITLE
spl-token-swap TokenSwap::createTokenSwap irregularities between repo and npm

### ISSUE THREAD

**Issue by dahifi** [solana-labs/solana-program-library#2587]
So I have successfully run the js/cli/token-swap-test.ts via the start-with-test-validator and start using an anchor localnet. I copy the test functions to my anchor workspace and update all the imports to reference the @solana/spl-token-swap module. Running it I get 
```
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
scripts/deployPool.ts(173,9): error TS2345: Argument of type 'Numberu64' is not assignable to parameter of type 'number'.
```

I trace the reference to the npm version `createTokenSwap()` which shows the following signature in index.d.ts: 
```
static createTokenSwap(connection: Connection, payer: Account, tokenSwapAccount: Account, authority: PublicKey, tokenAccountA: PublicKey, tokenAccountB: PublicKey, poolToken: PublicKey, mintA: PublicKey, mintB: PublicKey, feeAccount: PublicKey, tokenAccountPool: PublicKey, swapProgramId: PublicKey, tokenProgramId: PublicKey, nonce: number, tradeFeeNumerator: number, tradeFeeDenominator: number, ownerTradeFeeNumerator: number, ownerTradeFeeDenominator: number, ownerWithdrawFeeNumerator: number, ownerWithdrawFeeDenominator: number, hostFeeNumerator: number, hostFeeDenominator: number, curveType: number): Promise<TokenSwap>;
```
while the same file in the monorepo's index.d.ts: 
```
createTokenSwap(connection: Connection, payer: Account, tokenSwapAccount: Account, authority: PublicKey, tokenAccountA: PublicKey, tokenAccountB: PublicKey, poolToken: PublicKey, mintA: PublicKey, mintB: PublicKey, feeAccount: PublicKey, tokenAccountPool: PublicKey, swapProgramId: PublicKey, tokenProgramId: PublicKey, tradeFeeNumerator: number, tradeFeeDenominator: number, ownerTradeFeeNumerator: number, ownerTradeFeeDenominator: number, ownerWithdrawFeeNumerator: number, ownerWithdrawFeeDenominator: number, hostFeeNumerator: number, hostFeeDenominator: number, curveType: number, curveParameters?: Numberu64): Promise<TokenSwap>;
```
diff shows that the nonce (number) is removed, and curveParameters (u64) is added. 

I've been able to swap out the npm version for my filesystem and everything runs as it should. 

Is this just a situation where the monorepo wasn't bumped and redeployed to npm?

**Comment by dahifi** [comment]
Discord user lisenmayben — Today at 5:08 PM
thanks for filing an issue to be looked at. the token program appears to be getting an update for TS - en route. not sure on an eta.

**Comment by joncinque** [comment]
That's exactly right, we just haven't uploaded the new package to npm yet.  We can get a release together soon if you need it though!

**Comment by enzoampil** [comment]
Thanks for bringing this up @dahifi . I was having issues with this exact method (`createTokenSwap`) , and only then realized it was a `nonce` parameter discrepancy that caused the issue.

**Comment by ppoliani** [comment]
would it be  possible to update the npm package with the current code?

**Comment by joncinque** [comment]
https://www.npmjs.com/package/@solana/spl-token-swap/v/0.1.3 -- enjoy! Some things were moved around, feel free to open a new issue if you run into any issues
