### ISSUE TITLE
Let the SPL token program accept signatures from the owner of the owner 

### ISSUE THREAD

**Issue by yushizhao** [solana-labs/solana-program-library#2588]
The original issue has been closed. 
https://github.com/solana-labs/solana-program-library/issues/2517
Although part of the conversation there may related to wallet support, but the original idea is not.

Recap:
associated token account <=(own) program generated account <=(own) the actural owner,

For some reasons, that ATA is created not for the actural owner, but for the owner's token account.

Is there a way to let the actural owner get the token from that ATA?

**Comment by yushizhao** [comment]
#2248 is a similar issue. #1371 is also related.

**Comment by t-nelson** [comment]
The proposal adds unnecessary complexity and is likely a security foot gun.  I'm generally opposed

**Comment by yushizhao** [comment]
@t-nelson Thank you for reopen this issue! Well, I understand. But people are losing real money for this. It is also appreciated that we do something to prevent things like this happen again in the future.

**Comment by alexbitspawn** [comment]
@t-nelson Is it possible to add a redeem authority type to the spl-token authorize fuctions, and a redeem function for token program so that the authority of the token address will have the right to redeem the spl token mistakenly sent to token address associated account(the redeem can specify recipient address or directly to authority address doesn't matter. It's not too complicated and won't have security loophole.  And this provide some level of fool protection, and people always make stupid mistake like sending token to a token address

**Comment by t-nelson** [comment]
You're asking us to risk introducing a bug that effects all tokens for those lost due to a mistake.  That seems unreasonable.  I'm sorry for you loss, but please be careful.  Fees are cheap, always send a test transaction

**Comment by yushizhao** [comment]
Hi @t-nelson , before we look into solutions whether they are risky or not, how about we simply not allow creating ATA for accounts that are aleady token accounts? For example, by checking mint address?

**Comment by yushizhao** [comment]
@alexbitspawn Hi, that is inspiring.  A redeem authority is good to have. Maybe it can close the old dead ATA and mint the same amount of tokens into a new healthy ATA owned by the actural owner.

**Comment by Arrowana** [comment]
You have to understand that if the wallet is implemented properly it should check if the owner is off curve, thus preventing such mistake, or at least properly warning that something isn't right. Phantom wallet has this feature. It seems to be something easier to fix by fundamental user protections rather than convolution downstream.

**Comment by hitwill** [comment]
I suggest merging this issue with https://github.com/solana-labs/solana-program-library/issues/2248 as it's related? (whatever the resolution is)

**Comment by hitwill** [comment]
> You have to understand that if the wallet is implemented properly it should check if the owner is off curve, thus preventing such mistake, or at least properly warning that something isn't right. Phantom wallet has this feature. It seems to be something easier to fix by fundamental user protections rather than convolution downstream on-chain.

An additional consideration is that it's not only wallets involved, but exchanges, apps, dapps, etc - although security does take precedence.

**Comment by Moserious** [comment]
I transferred USDC from one exchange to a SOL address on another exchange, and the USDC ended up in an Associated Token Account. Is it possible to transfer the USDC from the ATA using CLI tools, and if so, are there any references that may be helpful for the commands to do so? I am not very familiar with using CLI Tools, etc., but given the relatively small balance of USDC I wouldn't mind trying to transfer it, if it is even possible? Thank you!

**Comment by t-nelson** [comment]
> I transferred USDC from one exchange to a SOL address on another exchange, and the USDC ended up in an Associated Token Account. Is it possible to transfer the USDC from the ATA using CLI tools, and if so, are there any references that may be helpful for the commands to do so? I am not very familiar with using CLI Tools, etc., but given the relatively small balance of USDC I wouldn't mind trying to transfer it, if it is even possible? Thank you!

Please don't threadjack.  This is a support request, completely unrelated to the original topic.  We don't use github for support requests.  Please join us in #wallet-support on https://solana.com/discord.  Please be careful when asking this question as you are likely to receive DMs from scammers impersonating support staff.  No support will _ever_ DM you on our discord server

**Comment by yushizhao** [comment]
Wow, thank you very much!

**Comment by t-nelson** [comment]
> hey, the good news is we're finally about to support this lost fund recovery at #2889

It's still contentious.  I'm in opposition

**Comment by yushizhao** [comment]
I believe none of us want to see fixing this improperly that leads to bigger problems. No matter how it goes, thank you very much for your time and for thoroughly discussing these issues!
