### ISSUE TITLE
[spl-token] provide more useful output when using create-token with the output option

### ISSUE THREAD

**Issue by paul-schaaf** [solana-labs/solana-program-library#2592]
currently only the signature is provided. it would be helpful if it also output the created token address and its decimals

**Comment by paul-schaaf** [comment]
if you think this is a good idea, I can implement this too. just one question, I need to add another struct that includes the Cli Signature and also the token information. Should I add this struct in the cli-output crate or the spl-token cli crate? It's a cli output but only related to tokens

**Comment by CriesofCarrots** [comment]
I'm on board to add this, since we're printing that information for Display. Thanks!
It should go in spl-token-cli. We've got some other spl-token cli-output structs here: https://github.com/solana-labs/solana-program-library/blob/master/token/cli/src/output.rs

**Comment by paul-schaaf** [comment]
@CriesofCarrots cool thanks

This actually requires a little bit of reengineering because by the time the signature is added in the `and_then` call, the token information is lost. Ofc output could print 2 json objects but it would be much nicer to just have one with all the info.

So what I can do is I can have `and_then` accept a Option<Box<dyn T>> where T implements all the serialisation stuff and also additional function like `add_signature` or just have an Option<enum> of the different things that may be useful as output in the respective calls and then match on that in the `and_then`.

Can u think of another way and do you have a preference?

**Comment by CriesofCarrots** [comment]
Oh yeah, I forgot that script is way too clever for it's own good 😂 
Maybe `and_then` accepts a struct (instead of tuple) something like this:
```
TransactionInfo {
    minimum_balance_for_rent_exemption: u64,
    instruction_batches: Vec<Instruction>,
    extra_info: T
}
```
where extra_info (but better name) takes a CliOutput struct that impls a trait with `add_signature` as you said?

**Comment by paul-schaaf** [comment]
it would be have to be `extra_info: Option<Box<dyn T>>` tho wouldnt it? create-token has different outputs then create-account so they'd be different Ts and extra_info has to capture all possible Ts. On top of that not all functions might have extra_info to return.

**Comment by paul-schaaf** [comment]
well I suppose all functions could at least return the address in the output in addition to the signature so then we could drop the Option

**Comment by CriesofCarrots** [comment]
I don't *think* dynamic dispatch would be necessary, because you could declare the specific type when calling each `command_` method that returns `CommandResult`.
CommandResult would become something like:
```
type CommandResult<T> = Result<Option<TransactionInfo<T>>, Error>;
```

But I'd have to play with it to be sure.

**Comment by paul-schaaf** [comment]
match arms need to return the same type (using () and CliMint as T for extra_info)

```
`match` arms have incompatible types
expected enum `Result<std::option::Option<TransactionInfo<output::CliMint>>, Box<dyn StdError>>`
   found enum `Result<std::option::Option<TransactionInfo<()>>, Box<dyn StdError>>`rustcE0308
main.rs(2383, 41): this is found to be of type `Result<std::option::Option<TransactionInfo<output::CliMint>>, Box<dyn StdError>>`
main.rs(2401, 13): this is found to be of type `Result<std::option::Option<TransactionInfo<output::CliMint>>, Box<dyn StdError>>`
main.rs(2382, 13): `match` arms have incompatible types
```

**Comment by CriesofCarrots** [comment]
Can you push and link your branch, pretty please?

**Comment by paul-schaaf** [comment]
done

**Comment by CriesofCarrots** [comment]
Thank you!! Dang, I concede. The fact that we populate the extra_info types in the `command_` functions means my approach won't work.
Dynamic dispatch it is. `Box<dyn T>` (Option, if you like) doesn't seem to horrible to me.

**Comment by paul-schaaf** [comment]
actually that doesnt work either cause T would require `Serialize` `trait T:Serialize {}` but `Serialize` is not object safe so cannot be used in a trait object...

so enum it is?
```
struct TransactionInfoWithOutput {
    minimum_balance_for_rent_exemption: Option<u64>,
    instructions: Vec<Vec<Instruction>>,
    command_output: Option<Output>,
}

enum Output {
    CliMint(CliMint)
}
```

other ideas:
- use erased_serde
- break this architecture up completely and stop trying to have everything be done in the .and_then and let the individual functions handle their output
- serialize earlier. the output is used only to show it on the command line so the individual functions could already serialize it. in the `and_then`, we'd use `as_object_mut` to add the signature. no dynamic dispatch needed because all match arms would include the same type (serde_json::value::Value). This would remove the option to handle outputs in different ways tho (e.g. specific VerboseDisplay impl would no longer be possible)

**Comment by CriesofCarrots** [comment]
Oh right 🤕 An enum is a fine, fast option to me, since most of the commands will be able to use the same variant.

That said, if you are up for something more involved, I like bullet #2. I've never loved having everything in the `and_then`; keeps making hoops for us to jump through. Could we put together a stand-alone helper function that includes all transaction-handling stuff from that closure and just call that from each command function?

**Comment by paul-schaaf** [comment]
yea I can do 2. I'd have time for that after the weekend if that is ok

**Comment by paul-schaaf** [comment]
it's mostly done. each command now handles it own output and the `handle_tx` function does the tx processing for all functions that had previously used the `and_then` closure

I've only added special output handling for create-token for now. I think it would be better to merge this asap to because it changes the architecture so new issues build on the new architecture and avoid merge conflicts. then add output handling for the other commands in another issue.

one thing Im not super happy with is the naming of some functions and variables rn but couldnt think of anything better so far
