### ISSUE TITLE
How to connect with browser wallet to authenticate

### ISSUE THREAD

**Issue by oggreo** [solana-labs/solana-program-library#2594]
```
  var fromWallet = web3.Keypair.generate();
  ....

  // Sign transaction, broadcast, and confirm
  var signature = await web3.sendAndConfirmTransaction(
    connection,
    transaction,
    [fromWallet],
    {commitment: 'confirmed'},
  );
```

I want to transfer a token that I own to another address programatically. 
How can I connect with the browser extension to authenticate instead of passing a keypair of pub and private key?

Thanks!

**Comment by joncinque** [comment]
In that case, your best bet is to use the solana wallet-adapter library: https://github.com/solana-labs/wallet-adapter/ 

Separately, we don't do tech support over GitHub, so please come by to the #developer-support channel on the Solana Tech Discord to get help more more quickly: https://discord.gg/HhwBBs4D

**Comment by oggreo** [comment]
Thank you for the reply! Will check the library and the discord channel
