### ISSUE TITLE
problem with offline signature for token transfer

### ISSUE THREAD

**Issue by petva** [solana-labs/solana-program-library#2597]
Faced with the problem it is necessary to transfer the token from one user to another for the fee of the receiving user. One way is to create an offline transaction by the user and call it by the receiving user. With the translation of SOL, I did everything, but with tokens it does not work in any way.

Preparation:
file user.json
`[241,225,43,156,175,192,111,231,247,139,134,189,175,90,238,176,156,195,203,117,157,175,16,33,147,25,242,243,253,56,228,211,193,95,123,80,62,95,143,190,239,31,6,185,154,48,222,2,141,160,169,68,43,168,127,136,21,187,113,159,146,13,10,16]`

file payer.json:
`[227,159,215,62,236,242,137,43,50,62,46,77,89,46,14,128,17,229,184,99,60,213,63,240,40,137,56,108,18,196,251,15,17,16,28,202,133,181,130,110,4,2,218,70,184,114,79,168,171,244,181,139,66,121,77,218,173,170,222,119,241,136,237,163]`

file conf.yml:
_json_rpc_url: "http://localhost:8899"
websocket_url: ""
keypair_path: payer.json
address_labels:
  "11111111111111111111111111111111": System Program
commitment: confirmed_

There are 2 users: user and payer. The user wants to send 1 token to payer. If there are no tokens, then you can do it in the following way:

**spl-token create-token --decimals 0  => 8R3dZ5fEGVraDqGSRJmMGj63NqQNoDVUJkM2eiwfuQjg
spl-token create-account 8R3dZ5fEGVraDqGSRJmMGj63NqQNoDVUJkM2eiwfuQjg
spl-token mint 8R3dZ5fEGVraDqGSRJmMGj63NqQNoDVUJkM2eiwfuQjg 1000**

The following commands are needed just for convenience:

**BLOCKHASH=$(solana block | grep "Recent Blockhash" |  awk '{print $3}')
PAYER=$(solana-keygen pubkey payer.json)
USER=$(solana-keygen pubkey user.json)
USERTOKEN=$(spl-token accounts -v --fee-payer payer.json --owner $USER | grep $TOKEN | awk '{print $2}')**
_USERTOKEN - user`s token account_

This is how I make the signature of the user USER:

SIGNER=$(spl-token transfer $TOKEN $AMOUNT $PAYER \
  --blockhash $BLOCKHASH \
    --sign-only \
    --from $USERTOKEN \
    --owner user.json \
    --fee-payer $PAYER \
    --allow-unfunded-recipient --mint-decimals 0 | grep "=" | grep -v Pubkey )

And so I want to perform a transaction for PAYER:

spl-token transfer $TOKEN $AMOUNT $PAYER \
    --blockhash $BLOCKHASH \
    --from $USERTOKEN \
    --signer $SIGNER \
    --config conf.yml

What gives an error: #ERROR: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x4 [5 log messages]

**Comment by t-nelson** [comment]
Hi!  We don't use Github for support requests.  Please join us in #wallet-support on https://solana.com/discord
