### ISSUE TITLE
(node:8946) UnhandledPromiseRejectionWarning: Error: failed to get token accounts owned by account 3wyBGP9XptSN24oSFHwn6aiFEXGuN3NvU3FgQ3vMCrm5: Invalid param: could not find mint

### ISSUE THREAD

**Issue by Poonamsingh080** [solana-labs/solana-program-library#2619]
import SolanaWeb3 from '@solana/web3.js';
import Sereum from '@project-serum/serum';
 //import { Market } from '@project-serum/serum';
 //import  TOKEN_PROGRAM_ID  from '@solana/spl-token';
 //const SPL_ASSOCIATED_TOKEN_ACCOUNT = new SolanaWeb3.PublicKey(
  //ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
//);
  
//import * as splToken from '@solana/spl-token';
let connection = new SolanaWeb3.Connection('https://api.devnet.solana.com');
let marketAddress = new SolanaWeb3.PublicKey('8gw8Vwb836BkroF9JJ95bQyg1TDcUAjscDxgMT9RUjc1');
let programId = new SolanaWeb3.PublicKey("4cPMvw9p9SgW6gLr7JBqhtUt9yggVDgAX7o9kDvCVjY9");

(async ()=>{
  let market = await Sereum.Market.load(connection, marketAddress, {},programId);
  console.log(market)
 // Placing orders

  let owner = new SolanaWeb3.Account([7,145,7,244,72,183,88,15,160,50,109,29,85,80,121,80,
    15,177,213,205,57,59,119,229,103,249,122,166,210,146,242,161,
    43,204,65,206,236,86,242,19,183,228,114,167,7,251,237,205,230,0,76,
    249,108,255,181,50,187,146,30,50,26,111,173,248]);
    console.log(owner)
   let payer = new SolanaWeb3.PublicKey('D5XoVj7uZSNSLuQ2aK7WQ4TCmXQZQdFTKm36bNM6kX3'); // spl-token account
   market.placeOrder(connection, {
     owner,
     payer,
     side: 'buy', // 'buy' or 'sell'
     price: 123.45,
     size: 17.0,
     orderType: 'limit', // 'limit', 'ioc', 'postOnly'
   });

  })();

// const Market = new Sereum.Market();
// console.log(Market)

// import  Serum  from '@project-serum/serum';
// console.log(Serum.MARKET)
// import pkg1 from '@project-serum/serum';
// console.log(new pkg1.Market())
// const { Market } = pkg;
// console.log(pkg.Market)

// console.log(market)
 //Fetching orderbooks
  //let bids = market;
  //let asks = market;
 //L2 orderbook data
 
 
  // let getL2 = {};
  // console.log(bids)
//   for (let [price, size] of bids.getL2(20)) {
//   console.log(price, size);
//  }
// Full orderbook data
//for (let order of asks) {
  //console.log(
    //order.orderId,
    //order.price,
    //order.size,
    //order.side, // 'buy' or 'sell'
  //);
//}
 

// Retrieving open orders by owner
// console.log(owner.publicKey)
// console.log('owner.publicKey')
// let myOrders = market.loadOrdersForOwner(connection, owner.publicKey);

// Cancelling orders
// for (let order of myOrders) {
//   market.cancelOrder(connection, owner, order);
// }

// // Retrieving fills
// for (let fill of market.loadFills(connection)) {
//   console.log(fill.orderId, fill.price, fill.size, fill.side);
// }

// Settle funds
// for (let openOrders of market.findOpenOrdersAccountsForOwner(
//   connection,
//   owner.publicKey,
// )) {
//   if (openOrders.baseTokenFree > 0 || openOrders.quoteTokenFree > 0) {
//     // spl-token accounts to which to send the proceeds from trades
//     let baseTokenAccount = new PublicKey('...');
//     let quoteTokenAccount = new PublicKey('...');

//     market.settleFunds(
//       connection,
//       owner,
//       openOrders,
//       baseTokenAccount,
//       quoteTokenAccount,
//     );
//   }
// }

kindly suggest ,
what is the  issue

**Comment by t-nelson** [comment]
Hi! We don't use Github for support. Please join us in #developer-support on https://solana.com/discord!
