### ISSUE TITLE
error: could not compile `libsecp256k1`

### ISSUE THREAD

**Issue by pierorolando1** [solana-labs/solana-program-library#2631]
![image](https://user-images.githubusercontent.com/72224217/145699904-1fe1cee6-598d-44c9-a9f3-feef980b9121.png)

##### I get this error when I run `cargo install spl-token-cli`, help

**Comment by joncinque** [comment]
Hi there! We don't use GitHub for support, so you can instead join our discord and check out the #developer-support channel https://discord.gg/9xkMfbfu

There isn't much information in your screenshot, but issues like this often are due to an old version of Rust.  Try upgrading to the latest stable, 1.57 currently, and try again.

**Comment by grglzrv** [comment]
I have the same issue
![image](https://user-images.githubusercontent.com/19932357/145915317-1f70758f-3dc1-4dff-a2d7-e82bfe82a3b7.png)
Installed Solana tools 9.0 and rust 1.57

@pierorolando1 could you please share how you solve this issue, thnaks.

**Comment by pierorolando1** [comment]
@grglzrv I was trying to do that in a Digital Ocean Cluster, I don't know why but it was not working, later, I try to do the same thing in my linux personal computer (Arch Linux), and works, I recommend u to tried the same thing in a virtual box or in docker container

**Comment by grglzrv** [comment]
I used AWS ec2 VM ubuntu version 21.04 free tier, @joncinque could you please check out this issue, the problem is not resolved yet. Thanks.

**Comment by irishdan** [comment]
Same for me. also on digitalocean Ubuntu 20

**Comment by joncinque** [comment]
Looks to be a RAM issue, based on an issue in their repo: https://github.com/paritytech/libsecp256k1/issues/94

I tried this again on a blank Docker container running Ubuntu 20.04 and was able to compile everything, which leads me to believe this issue.

**Comment by grglzrv** [comment]
@joncinque I don't think that is the actual issue, you may use VM by Linode with 1Gb RAM with Ubuntu 21.10 and you gonna see that everything will be compiled correctly,  Your test with docker container, the image uses your kernel, etc., you may test it with real VM with Ubuntu 20.04 and Ubuntu 21.10 with 1GB RAM then you gonna see that the compilation will pass.

**Comment by joncinque** [comment]
@grglzrv Sorry, I'm still not able to reproduce this anywhere.  I just tried on a raspberry pi and it worked there too (albeit after a long wait).  Either way, until there's something concrete, let's take this discussion to discord, where it will be much easier to respond

**Comment by grglzrv** [comment]
@joncinque I have tried on raspberry pi 4gb with docker image - ubuntu:21.10 but i got failed to install solana tools,  i was not able to installed it on rasp pi, could you please share your steps how you install it.

**Comment by grglzrv** [comment]
```bash
pi@raspberrypi:~ $
pi@raspberrypi:~ $ docker run -d -it --name sol-token -h sol-token ubuntu:21.10
224fe270295b287d6dd36d352892ac01ead1ba81cd6fc2f41bfc27bf4c721df7
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@raspberrypi:~ $
pi@raspberrypi:~ $ docker exec -it sol-token bash
root@sol-token:/#
root@sol-token:/# apt update
Get:1 http://ports.ubuntu.com/ubuntu-ports impish InRelease [270 kB]
.....
.....
....
root@sol-token:/# apt install curl -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  ca-certificates libbrotli1 libcurl4 libldap-2.5-0 libldap-common libnghttp2-14 libpsl5 librtmp1 libsasl2-2 libsasl2-modules
  libsasl2-modules-db libssh-4 openssl publicsuffix
Suggested packages:
  libsasl2-modules-gssapi-mit | libsasl2-modules-gssapi-heimdal libsasl2-modules-ldap libsasl2-modules-otp libsasl2-modules-sql
The following NEW packages will be installed:
  ca-certificates curl libbrotli1 libcurl4 libldap-2.5-0 libldap-common libnghttp2-14 libpsl5 librtmp1 libsasl2-2 libsasl2-modules
  libsasl2-modules-db libssh-4 openssl publicsuffix
0 upgraded, 15 newly installed, 0 to remove and 1 not upgraded.
Need to get 2214 kB of archives.

....
....
.....
root@sol-token:/# sh -c "$(curl -sSfL https://release.solana.com/v1.9.0/install)"
downloading v1.9.0 installer
sh: 156: /tmp/tmp.G9QiqTakVD/solana-install-init: Exec format error
root@sol-token:/#

```

**Comment by joncinque** [comment]
You don't need the Solana tools to install the CLI, just Rust. So my steps were:
```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
$ source $HOME/.cargo/env
$ cargo instal spl-token-cli
```
This was a machine with `curl`, `pkg-config`, and `libudev-dev`.

Separately, if you're on a Raspberry Pi, you'll have to compile the CLI yourself from https://github.com/solana-labs/solana/tree/master/cli, since we don't provide the tools for arm yet.  That's where that most recent failure is from.

**Comment by grglzrv** [comment]
I gonna try to compile Solana tools on rasp pi 4 now.

I just installed everything with success but by the binary files.

```sh
wget https://github.com/solana-labs/solana/releases/download/v1.9.0/solana-release-x86_64-unknown-linux-gnu.tar.bz2
tar -xvf solana-release-x86_64-unknown-linux-gnu.tar.bz2

echo 'export PATH="/root/solana-release/bin:$PATH"' >> .profile

exit 

# login again

~# solana --version
solana-cli 1.9.0 (src:7782d34b; feat:378846963)
~# spl-token --version
spl-token-cli 2.0.15

```

But when i set this
`solana config set --url http://api.devnet.solana.com`

I got 0 SOL

If I set:
`solana config set --url  https://api.mainnet-beta.solana.com`
I got my SOL

What's the diff between those 2 URLs?

**Comment by joncinque** [comment]
I'm going to lock this issue now since it's getting off-topic, please come to Discord and chat
