### ISSUE TITLE
Custom Token Program

### ISSUE THREAD

**Issue by vandai2995** [solana-labs/solana-program-library#2639]
Dear Solana Experts,

I have a question about the custom Token Program. 

- When I create the token using the built-in SPL Token Program (TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA), everything is well. 
- When I use my own Token Program (2hsFyTmBgXhLTX2qTvgCxCQusXboS7XsGRBAzW5gpUkT) to create a new token, **the result is just an account, not exactly a mint account.** 

Like the figure below: 
Use the built-in Token Program
<img width="1185" alt="Screen Shot 2021-12-15 at 16 11 01" src="https://user-images.githubusercontent.com/21040020/146157255-1321146d-0693-451f-be47-bcbbbb5a3a68.png">
=> Result: 
<img width="1196" alt="Screen Shot 2021-12-15 at 16 14 06" src="https://user-images.githubusercontent.com/21040020/146157770-73565f27-91ef-45f4-9543-e4328f86fccb.png">

================

Use my own Token Program 
<img width="1146" alt="Screen Shot 2021-12-15 at 16 10 47" src="https://user-images.githubusercontent.com/21040020/146157394-4514a490-f9ca-436e-b119-174f999781d1.png">
=> Result: 
<img width="1161" alt="Screen Shot 2021-12-15 at 16 14 15" src="https://user-images.githubusercontent.com/21040020/146157819-9dee9d9f-dd1c-488f-be6f-aff575784027.png">

The code is the same, just different from the on-chain Program. 
Could you please help explain these issues, or give any idea? 
Many thanks!

**Comment by joncinque** [comment]
Hi there, GitHub isn't ideal for support, so please join us on Discord https://discord.gg/2AXHj5dJ

To answer your question quickly, the ecosystem doesn't currently support multiple token programs, just the one at `Tokenkeg...`.  We started a proposal to support multiple token programs at https://github.com/solana-labs/solana/pull/15927, but the work has been sidelined by other priorities.  You can read through the PR to see what it would take to support a new token program.  Essentially, you'll need buy-in from wallets and dapps to start accepting your token program too.

**Comment by AmartejS** [comment]
Is there any update on this issue. Even we are facing the same. Thanks in advance.

**Comment by joncinque** [comment]
@AmartejS The issue mentioned earlier is your best bet.  Note that this is technically possible, but you'll have to convince ecosystem partners / wallets to integrate with your token program.
