### ISSUE TITLE
 spl-token create-token  No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Rafinix** [solana-labs/solana-program-library#2644]
When I execute eh spl-token create-token code it gives me the error 2 
I do not know what I the problem, because I have created two tokens already without a problem, but now it would not let me. 
I tried to do it  over and over again,but does not work,
Here is what I do:
cd desktop
mkdir moon
solana-keygen new --outfile moon/my-keypair.json  (I have my pubkey at this point )
solana airdrop 1 <RECIPIENT_ACCOUNT_ADDRESS> --url https://api.devnet.solana.com (I got the 1 sol)
solana config get
solana config set --url https://api.devnet.solana.com
solana config set --keypair ${HOME}/new-keypair.json
spl-token create-token ( and then I get the No such file or directory (os error 2) ) 

Also I changed the code: /new-keypair.json by /my-keypair.json and it let me create the token 
but after I tried to change it to the main net ( solana config set --url https://api.mainnet-beta.solana.com ) 
and use the:  spl-token create-token 
do not let me and gave me the same error 2

**Comment by fanbyprinciple** [comment]
The error is because it is not able to find the `new-keypair.json` file which you have replaced. 

To rectify change the `solana config set --keypair ${HOME}/new-keypair.json` to `solana config set --keypair ${HOME}/my-keypair.json` and then try to run `spl-token create-token`

**Comment by jordansexton** [comment]
@fanbyprinciple thanks for answering.

@Rafinix questions like this usually get answered more quickly in the Solana Discord's #developer-support channel.

**Comment by GalKozmelj** [comment]
I SOLVED PROBLEM WITH REWRITING ALL URLS IN COMMAND AND CHANGING '\' WITH '/' SYMBOL
