### ISSUE TITLE
Spl-token importing (Question)

### ISSUE THREAD

**Issue by aprecode** [solana-labs/solana-program-library#2663]
I'm trying to import spl-token library in html like

`<script type="module" src="https://cdn.jsdelivr.net/npm/@solana/spl-token@0.1.8/lib/index.cjs.min.js"></script>`

However, browser throws an error about missing command 'require' and I'm unable to import require.js as well.

Is there any way to import these libraries without using npm?

**Comment by jordansexton** [comment]
The type of bundle you would need to do this is a UMD bundle. CJS is exported with `module.exports` and uses `require`. However, there are also some libraries and Node.js APIs like Buffer that this relies on too, so you would need to bundle and polyfill these. In general, you're going to be better off using NPM and a bundler for your frontend code than relying on scripts.
