### ISSUE TITLE
[stake-pool/js] Is there a published NPM package for @solana/spl-stake-pool?

### ISSUE THREAD

**Issue by ndollar** [solana-labs/solana-program-library#2675]
cc @joncinque and @AlexanderRay 

I just independently wrote parts of what you just wrote in https://github.com/solana-labs/solana-program-library/blob/master/stake-pool/js/src/instructions.ts and I'd rather use yours instead! 😄 

But it doesn't look like `@solana/spl-stake-pool` is published. Are there plans to publish or am I missing something? 

```bash
$ npm install --save @solana/spl-stake-pool
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@solana%2fspl-stake-pool - Not found
npm ERR! 404 
npm ERR! 404  '@solana/spl-stake-pool@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```

**Comment by joncinque** [comment]
Good point! I got the package ready for release, will let you know when it's finally published, which should be done in the next couple of days.

**Comment by joncinque** [comment]
Enjoy! https://www.npmjs.com/package/@solana/spl-stake-pool

**Comment by ndollar** [comment]
Thanks @joncinque!

**Comment by Marcjazz** [comment]
Hello, I'm actually having issues with the @solana/spl-stake-pool: Cannot use import statements outside a module
I've tried to fix this by adding "type": "module" to the spl-stake-pool package.json but it doesn't work for me because I'm using nestjs as a backend framework that transpile my ts code to js file with require statement causing new errors.
Need help or is there an alternative package?

**Comment by joncinque** [comment]
@Marcjazz Hi there, we don't use GitHub for support, so please join us in Discord https://solana.com/discord in the #developer-support channel if you have questions about setting up your project,
