### ISSUE TITLE
[RFC] Proposal for a commit-reveal scheme to generate entropy

### ISSUE THREAD

**Issue by jordansexton** [solana-labs/solana-program-library#2691]
## The easy part

Each party possesses some secret value -- say, a number they picked -- encrypts it, and commits to it.

After some time, all the values are revealed (more on this later), and sorted in some deterministic way.

Something like `hash(hash(v0) + hash(v1) + ... + hash(vN))` is calculated. This hash is used as a source of entropy for something (could be to pick a winner among the parties).

If there is at least one party whose value is truly secret (hasn't been revealed prior to other parties), then no party can predict what the outcome will be.

Put another way, all other parties except for me can be colluding, but if I enter this lottery, I know it's fair.

## The hard part

My understanding of commit-reveal schemes is that they can have weaknesses if some parties don't reveal.

In this context --

1. committing starts
2. committing ends (subsequent commits will be ignored)
3. revealing starts
4. revealing ends (subsequent reveals will be ignored)
5. final value is determined / winner is decided

During 3, any party can effectively see who is currently the winner and choose not to reveal. Reveals that would change the winner can also be censored.

## The way forward

If instead you had a way for anyone to post a proof of what all the values are, the only way to censor would be to censor that proof.

Some possible solutions considered:

1. VDF - each party runs some delay function that someone else must run to decrypt the value. Aside from being wasteful, the bigger problem is symmetry: the UX sucks because a party has to spend just as much time to commit as others have to spend to reveal.
2. Weak encryption - each party encrypts with a weak key. They can reveal or it can be brute forced. This is nice because it's asymmetrical, taking less time to commit than reveal. But it doesn't work well if someone can brute force in parallel anyway, and it's also wasteful.
3. zk-something Timelock encryption - I found some papers (e.g. https://link.springer.com/article/10.1007/s10623-018-0461-x) describing some of the properties that I think are desirable... and immediately got in over my head. https://crypto.stackexchange.com/a/81827 has some closer-to-English description. Downsides are moon math, lack of a ready implementation, and an economic model of witness encryption using Bitcoin blocks.
4. RSA Timelock encryption - Zaki Manian from Cosmos sent me this: https://gitlab.com/tezos/tezos/-/merge_requests/2940 It's still PoW but has the desirable qualities of 1 (non-parallelizability) and 2 (asymmetry). It comes with an implementation that could perhaps be ported to Rust.

Committers could be incentivized to reveal to reduce the work, and provers could be incentivized to solve and post proofs.

This could perhaps be implemented in a general way to provide value to protocols requiring some source of (eventual) random outcomes.

**Comment by jordansexton** [comment]
Thanks to @jstarry and @samkim-crypto for discussing this so far!

**Comment by jordansexton** [comment]
1996 paper that **4** is based on: https://people.csail.mit.edu/rivest/pubs/RSW96.pdf

Tezos' OCaml implementation will take some time for me to make sense of, but here are some others that might help.

Python implementation: https://asecuritysite.com/encryption/pow2

Java: http://people.csail.mit.edu/rivest/lcs35-puzzle-description.txt

JavaScript: https://github.com/glamperd/vdf

A possible weakness of the scheme is that the original committer's reveal of the value could be frontrun by incentivized solver who claims to have found the solution. It may be a requirement that solvers post some kind of proof of having performed the sequential calculations required.

**Comment by jordansexton** [comment]
Several newer papers analyze the protocol, it's utility, and propose some modern improvements.

https://www.gwern.net/docs/cs/2015-kuppusamy.pdf

https://ethz.ch/content/dam/ethz/special-interest/infk/inst-infsec/system-security-group-dam/research/secure_verification/Puzzles.pdf

https://eprint.iacr.org/2011/665.pdf

A puzzle using the protocol was created in 1999, and was eventually solved after 3 years of computation in 2019: https://www.mersenneforum.org/showthread.php?t=24385

**Comment by jordansexton** [comment]
From @samkim-crypto:

---

I thought a bit about this and also did some searching myself over the weekend. The keyword to search for here is “randomness beacon”. Many people seem to have thought about this problem as well and many of the solutions fall under the category that you listed.

I did find a pretty clever protocol though that uses VDF. It requires computing a VDF, so it is computationally wasteful to some extent, but I do not see any other downside with it.

Posting stage (say duration T): each party `i` samples random bytes `v_i` and post it on chain (we don’t even need commit-reveal here; just post directly)

Final random value is determined to be `VDF( H(v0 + v1 + … + vN) )`.

Assuming that any party requires at least T time to compute the VDF, no party can predict the output within the posting window. Hence, a party must choose to either participate or not without knowing the final value.

Here, I used a VDF but any “slow” (delay) function can be used (like iterative hashing). VDF has the advantage that one party can compute the VDF output and distribute it to the other parties with a proof that it is correct. If just a delay function is used, then each party has to compute the final value on its own. But each party still needs to compute just one instance of the VDF. In the previous VDF solution that we were considering, each user had to compute the VDF on all the other users’ inputs.

I found this solution in this paper https://eprint.iacr.org/2018/601.pdf. You just have to read page 4.

**Comment by askibin** [comment]
In the VDF case (#1 above), do you actually have to spend time to commit? You can supply input variables but not care about the solution that will be later computed, as long as you can validate it for the given inputs. But validating VDF appears to be a tricky part in practice, at least the interactive variant. Time-lock puzzles, on the other hand, look great all around. They work similarly to VDFs, but kind of backward, the committer starts with selecting random p and q primes and uses a shortcut to compute the result, while solvers have to perform all squarings. So it is super easy to validate the solution for the committer, with no need to interact with the solver. For other parties (who didn't solve but want to verify), the committer could encrypt his public key with the solution and provide along with inputs.

**Comment by jordansexton** [comment]
> do you actually have to spend time to commit?

Yeah, you don't. You could just use something like the block/slot hash. It can be biased by the leader, but as long as the can't run the VDF faster than the block time, they will effectively need to "commit" to a hash (or be skipped) before they can know the outcome.

> But validating VDF appears to be a tricky part in practice, at least the interactive variant.

The VDF can be made to noninteractive (the challenge can just be the hash as above). The problem I ran into is that validating the proof on chain is probably computationally infeasible on Solana right now.

The proof and verification both [start with the same step](https://github.com/poanetwork/vdf/blob/719925d8a33c1d482a95d608a09dcdc199e97cdc/vdf/src/proof_wesolowski.rs#L294-L295), which is to [generate a pseudorandom large prime](https://github.com/poanetwork/vdf/blob/719925d8a33c1d482a95d608a09dcdc199e97cdc/vdf/src/create_discriminant.rs#L65).

This library uses GMP, libc, and rand, which are not available for the BPF target / runtime. I modified a big integer crate to use a cheap PNRG for heuristically [guessing a prime](https://github.com/jordansexton/num-bigint/blob/91005fda1c8b92bd6743ff080078b6894ceda37a/src/prime.rs#L183).

Unfortunately even after some optimization, a few iterations of this are absurdly expensive (~2.5 million compute units). Worse, the [rest of the prime test](https://github.com/jordansexton/num-bigint/blob/91005fda1c8b92bd6743ff080078b6894ceda37a/src/prime.rs#L55) runs out of stack memory when dealing with even 256 bit integers. Something like 2048 bit numbers would be used in practice.

I'm far from an expert on the runtime but I think this is a dead end unless syscalls provide something like GMP that can efficiently perform calculations over large numbers.

>  Time-lock puzzles, on the other hand, look great all around.

I can't say I learned enough about them to know whether this is viable given the above.

**Comment by jordansexton** [comment]
If you're interested in testing this out, here's a [small program](https://github.com/jordansexton/entropy/blob/a46d0f52bcad099df70b462df7f957bfd6325f9c/programs/entropy/src/lib.rs#L66-L79) and [test](https://github.com/jordansexton/entropy/blob/master/programs/entropy/tests/compute_units_test.rs) that demonstrates the excessive compute usage, and [here's a bit of code](https://github.com/jordansexton/entropy/blob/a46d0f52bcad099df70b462df7f957bfd6325f9c/programs/entropy/src/lib.rs#L125-L148) which I first ran to run the proof before I realized all the libraries wouldn't work in the runtime. I'm not sure where to go from here.

**Comment by askibin** [comment]
agree, VDF verification looks too heavy, interactive or not. But if the challenge committer knows the outcome (i.e. ran the VDF off-chain before committing), he can use it to encrypt some data with symmetric-key algo and supply it with the challenge (should be brut-force resistant since the solution is long). Then anyone can quickly verify the solution by using it to decrypt and compare. It will require the committer to pre-run VDF, which is not ideal. This is why I like the time-puzzles you proposed. To set up a puzzle, you have to compute an outcome upfront but more efficiently (still some log(t) crunching is required) and can encrypt per above.
