### ISSUE TITLE
token-swap: Wrap SwapCurve's calculator field into Arc instead of Box 

### ISSUE THREAD

**Issue by gitmalong** [solana-labs/solana-program-library#2718]
Hi!

It's about the **Token-Swap Program**.

Please wrap the `calculator` field of `SwapCurve` into `Arc` instead of `Box`.

Current field: `pub calculator: Box<dyn CurveCalculator>,` 
Proposed replacement: `pub calculator: Arc<dyn CurveCalculator>,`

Reasoning:
Wrapped within a box we are not able to wrap `SwapState` into `Arc` to use it as shared reference in a multi threaded environment. Workarounds such as implementing an own `SwapCurve` with `pub calculator: Arc<dyn CurveCalculator>,` struct are ugly as they break the tightly coupled code that relies on the original `SwapCurve` (pack, unpack etc.).

We may have to differ between these two use cases:
a) Program that runs on the blockchain (Not sure about the impact)
b) Usage as client side lib  that enables us to calculate swaps etc. the same way as the on-chain program (Cannot not see any drawbacks)

Would that break anything and besides of that make sense to you?

Code Reference: https://github.com/solana-labs/solana-program-library/blob/master/token-swap/program/src/curve/base.rs#L64

**Comment by t-nelson** [comment]
PRs welcome :wink:

**Comment by Anurag5086** [comment]
I have added a PR, could you review it? :)

**Comment by joncinque** [comment]
Closed through #2860
