### ISSUE TITLE
Sending SPL Token to a previously closed ATA results in that account becoming the owner of another new ATA

### ISSUE THREAD

**Issue by michaelh-laine** [solana-labs/solana-program-library#2730]
Accounts: 
- O1 (Owner 1)
- T1 (Associated Token Account 1)
- T2 (Associated Token Account 2)

1. When a user (O1) transfers their entire token balance from T1 to a third party and closes their account T1, T1 no longer exists on the blockchain.
2. The third party sees an incoming SPL Token transfer from T1. They want to refund this transfer and send the funds back to T1.
3. As T1 no longer exists on the blockchain the token program assumes T1 is to be the owner and creates a new ATA: T2
4. T2 is now owned by T1, leaving O1 with no access to the funds held in T2

Real world example (shared with me, not mine):
- O1: BohU2UHteXVfdgVPcoEZLsPKwuWhaScbwg9rFvJfTL66
- T1: 95uSCi29rNa5i4BqzpMviJaqyiv4Q8yFRqTH3AYVUeRp
- T2: 43b9hEmPQXDmEXvERV4hyxBvKZK3Mo7u5M67Nu8k3keN

Real Scenario: O1 transferred wSOL to Binance from T1. Binance doesn't support wSOL and refunded this to the originating ATA (T1). Runtime assumes T1 to be the owner and created T2 to hold the wSOL. O1 now has no access to these funds.

**Solution?**
To solve this the runtime needs to know whether the recipient account is a previous ATA and who the owner was, this is not feasible in the current constraints. I don't have another practical solution but thought I'd post this here for comment from others. Perhaps a --confirm or --force flag when sending to an unfunded account to confirm the action?

**Comment by milos2211** [comment]
I had same problem, also when i realized that, supply on mint account stay unchanged. So token just vanish.

**Comment by joncinque** [comment]
Closing in favor of any other issues about this: https://github.com/solana-labs/solana-program-library/issues/1371 https://github.com/solana-labs/solana-program-library/issues/2202 https://github.com/solana-labs/solana-program-library/issues/2248 https://github.com/solana-labs/solana-program-library/issues/2294 -- check out the PR to address this issue #2889

**Comment by STAFFADMINISTRATOR** [comment]
> Accounts:
> 
> * O1 (Owner 1)
> * T1 (Associated Token Account 1)
> * T2 (Associated Token Account 2)
> 
> 1. When a user (O1) transfers their entire token balance from T1 to a third party and closes their account T1, T1 no longer exists on the blockchain.
> 2. The third party sees an incoming SPL Token transfer from T1. They want to refund this transfer and send the funds back to T1.
> 3. As T1 no longer exists on the blockchain the token program assumes T1 is to be the owner and creates a new ATA: T2
> 4. T2 is now owned by T1, leaving O1 with no access to the funds held in T2
> 
> Real world example (shared with me, not mine):
> 
> * O1: BohU2UHteXVfdgVPcoEZLsPKwuWhaScbwg9rFvJfTL66
> * T1: 95uSCi29rNa5i4BqzpMviJaqyiv4Q8yFRqTH3AYVUeRp
> * T2: 43b9hEmPQXDmEXvERV4hyxBvKZK3Mo7u5M67Nu8k3keN
> 
> Real Scenario: O1 transferred wSOL to Binance from T1. Binance doesn't support wSOL and refunded this to the originating ATA (T1). Runtime assumes T1 to be the owner and created T2 to hold the wSOL. O1 now has no access to these funds.
> 
> **Solution?** To solve this the runtime needs to know whether the recipient account is a previous ATA and who the owner was, this is not feasible in the current constraints. I don't have another practical solution but thought I'd post this here for comment from others. Perhaps a --confirm or --force flag when sending to an unfunded account to confirm the action?
