### ISSUE TITLE
Can't unwrap SOL tokens without closing WSOL account

### ISSUE THREAD

**Issue by askibin** [solana-labs/solana-program-library#2748]
It is a common approach among different protocols to create WSOL accounts on the fly, send SOL to WSOL (to wrap it automatically), and close them at the end to convert WSOL back to SOL. If it were also possible to transfer WSOL to SOL account with automatic unwrapping, it would come with some benefits:
- no need to re-create and close accounts every time, probably saving on some blockchain resources
- easier to reason about the conversion process, it will work both ways similarly, easier for new devs
- WSOL account can be permanent, protocols will unwrap only the amount they work with

**Comment by Arrowana** [comment]
A comment on this, i think wrapping isn't too bad right now, this is the flow i use in frontends:
- check if wSOL ATA exists, create it if not
- transfer SOL to ATA
- call sync native

Drawbacks:
- A bit annoying for clients if they need to consider pre-existing wSOL balance, but i think they should not, wSOL should not be something user have to deal with.
- 3 ixs, but still remains quite light

The unwrapping is trivial, with a single call to close_account. However, it might make sense to be able to unwrap without closing.

To make things easier possibly sync native could have a wrapper to do the transfer + sync in one ix.

Extra points:
- I still see a lot of UIs that are not even aware about sync native and are still doing abominations like the use of auxiliary wSOL which consume a lot of transaction space.

**Comment by yenicelik** [comment]
can you point me to one example of unwrapping sol (i.e. close-account?). I have a similar workflow to wrap sol, but a bit confused as to how to unwrap

**Comment by t-nelson** [comment]
hi. we don't use github for support. please join  us in #developer-support on https://solana.com/discord instead
