### ISSUE TITLE
[Question] How to create SPL Token with a specific prefix?

### ISSUE THREAD

**Issue by kazunetakeda25** [solana-labs/solana-program-library#2749]
How to create SPL Token with a specific prefix?
For instance, Star Atlas.
Star Atlas's SPL Token: `ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx`
It has `ATLAS` prefix.
If someone knows, please let me know.
Thanks.

**Comment by t-nelson** [comment]
Hi! We don't use github for support requests.  Please join us in #developer-support on https://solana.com/discord instead
