### ISSUE TITLE
Social Recovery Wallet and global variable

### ISSUE THREAD

**Issue by 1Upper** [solana-labs/solana-program-library#2756]
Hey, I am trying to build a social recovery wallet for Solana, so that users can reset the owner of the wallet when private key is lost. To achieve this goal, I need store the owner’s public address as a global variable and update it dynamically as guardians invoke the "recovery" method of smart contract. However, I found that the global variable on Solana is stored at account scheme and it is only mutable by the account owner. I am stuck now because it seems no way to update the owner's address (global variable) by guardians (owner's private key is lost).  How should I solve this puzzle? (Is the social recovery wallet not doable on Solana?)

Thanks in advance!

**Comment by jordansexton** [comment]
This isn't the right place for specific product development questions. Try Discord!
