### ISSUE TITLE
'Finding all token accounts for a specific mint API' always returns 429 in mainnet-beta

### ISSUE THREAD

**Issue by sungyoun0216** [solana-labs/solana-program-library#2784]
It works normally in testnet, but when used in mainnet-beta, the following response is always returned.
Why?
[Response example]
`
{
    "jsonrpc": "2.0",
    "error": {
        "code": 429,
        "message": "Too many requests for a specific RPC call, contact your app developer or support@rpcpool.com."
    },
    "id": 1
}
`

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support questions like this, and you should instead use Discord, which I believe you already were anyway.

You were answered in Discord, but for posterity, here are the published rate limits for the different public RPC providers: https://docs.solana.com/cluster/rpc-endpoints#mainnet-beta
