### ISSUE TITLE
Separate Cargo.lock per program

### ISSUE THREAD

**Issue by garious** [solana-labs/solana-program-library#28]
#### Problem

The separate Cargo.lock per program will mean we can't share lib dependencies. For example, if the Token program wants to include a Memo, it should add `spl-memo` as a dependency, but if it does that while there's a Cargo.lock file, all those dependencies will need to match perfectly.

#### Proposed solution

Add a top-level Cargo.toml and Cargo.lock, delete the nested ones

**Comment by jackcmay** [comment]
@garious I'm unable to recreate the problem presented and don't understand why it would be an issue.  Can you give more information about how to recreate the issue you are describing?

**Comment by jackcmay** [comment]
Unable to recreate
