### ISSUE TITLE
Intermittent Failure to confirm transaction when minting token

### ISSUE THREAD

**Issue by tateexon** [solana-labs/solana-program-library#2812]
Following the example here:
https://github.com/solana-labs/solana-program-library/blob/master/token/js/examples/create_mint_and_transfer_tokens.js

Steps to reproduce
1. I am spinning up a docker image to run the solana-test-validator using docker image solanalabs/solana:1.9.5
2. Setting up a test that is just running the example you provide in the link above.
3. See if the mint token test passes.
4. This happens as test automation in a ci pipeline and thus runs steps 1-3 a lot. I need the minting of the token to happen before other tests can run that need the token.

Expected: sendAndConfirmTransaction will consistently pass.
Actual: sendAndConfirmTransaction will fail intermittently in the [createMint call](https://github.com/solana-labs/solana-program-library/blob/master/token/js/examples/create_mint_and_transfer_tokens.js#L24)

Notes:
1. If I add a wrap around the failure and attempt to confirm the transaction, it will fail to confirm the transaction no matter how many times I loop the check. So once it fails to confirm once, it will never be able to confirm, almost as though it has cached the result in node. Also of note if I try to do any call that needs sendAndConfirmTransaction to be called it will fail to confirm those transactions as well, it is like a permanently bad state once you get in it and the only solutions is to kill the process and try again.
2. If I manually check with the cli while the loop is running from Note 1 I can see the transaction is confirmed.
3. This is not confined to just this token minting transaction, it can happen to any function that uses sendAndConfirmTransaction from solana/web3.js but the token minting seems to see the issue far more often.
4. Occurs on 1.8.x docker images as well.
5. Behavior also reproduces on testnet, devnet and mainnet.
6. I rewrote my test using the [golang solana library](https://github.com/gagliardetto/solana-go) and do not see this intermittency so the issue is confined to the js library itself and not an issue with the docker image or other external factors.

**Comment by joncinque** [comment]
I wonder if this has to do with the keypair being generated in JS or some other bug... do you have the signature for a failing transaction that we can check on the explorer?  Ie something like https://explorer.solana.com/tx/5tkj2PvWt6gRj7XtWGvrdttqjh7aXtUUSHV1a7h3TSt7exU4kqha9vqCr4qG9d7rjQ8a3Rf25NhAUs67xCKU4ixk
