### ISSUE TITLE
Intermittent Failure to create associated account when transferring NFT

### ISSUE THREAD

**Issue by karnie6** [solana-labs/solana-program-library#2814]
When attempting to transfer a NFT (token with supply of 1), my code intermittently fails whenever it has to create an associated account for the sender (which is weird since I thought this would already be created as the sender possesses the NFT).

My code was virtually identical to the OP's of https://github.com/solana-labs/solana-program-library/issues/2497 - but after reading @AlexLeung 's feedback, I modified my code to the following:

`const associatedSenderTokenAddr = await Token.getAssociatedTokenAddress(mintToken.associatedProgramId, mintToken.programId, mintPublicKey, fromWallet.publicKey); `

 `const senderAccount = await (connection.getAccountInfo(associatedSenderTokenAddr));`
  
 `if (senderAccount == null) {`
 
`       
 transaction.add(
          Token.createAssociatedTokenAccountInstruction(
            mintToken.associatedProgramId,
            mintToken.programId,
            mintPublicKey,
            associatedSenderTokenAddr,
            fromWallet.publicKey,
            fromWallet.publicKey))
}
`

However, whenever this case occurs, I see the following which indicates I'm not using the right programID.

Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]
    Program log: Transfer 2039280 lamports to the associated token account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Allocate space for the associated token account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Assign the associated token account to the SPL Token program
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Initialize the associated token account
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: InitializeAccount
    Program log: Error: IncorrectProgramId

Any ideas?

**Comment by jacobcreech** [comment]
We do not use github issues for support. Please join us at solana.com/discord in the #developer-support channel
