### ISSUE TITLE
Please Help. 

### ISSUE THREAD

**Issue by Serg112344567gfrfr** [solana-labs/solana-program-library#2834]
I just started a wallet, replenished it a little and started waiting for tokens on this account, after a day passed and I didn’t see them on my account, I started looking and it turned out everything had already been transferred somewhere and even a trifle of 0.05 cents many times until now translate. What to do?

I have one account and there were no others in the Sol system, here is the number 7zcUntKZcdrdhZS9tpcXNwnVGGyt1mttvSa398otu1Mw

**Comment by jordansexton** [comment]
Sorry, this Github isn't for wallet support.
