### ISSUE TITLE
Ability to provide keypair to spl-token command

### ISSUE THREAD

**Issue by unimintco** [solana-labs/solana-program-library#2862]
I'm performing a call of this CLI function

`spl-token balance --token--`

So it requires a `keypair.json` file to be present at this location `~ .config/solana/id.json` (for Mac)

Without this file CLI throws an error `error: No such file or directory (os error 2)`

Is there a way to specify a path to keypair or even better specify the whole file content (encoded or not) as a CLI param?

BTW this issue is not limited to just this command, most of spl-token cli commands I've tried has this issue.

So far if I want to check balances of several wallets I have to replace the keypair file to that location which slows down the process, making it dependent on the filesystem and IO.

I may be, of course, misreading documentation.
Thank you for help.

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for technical support, so we encourage you to join us at Discord https://discord.gg/solana or ask a question on StackOverflow, which it looks like you already did: https://stackoverflow.com/questions/70956002/ability-to-provide-keypair-to-solana-spl-token-command
