### ISSUE TITLE
429 Too Many requests for no reason

### ISSUE THREAD

**Issue by 5elfle5** [solana-labs/solana-program-library#2866]
I'm on devnet, using @solana/spl-token for creating a wallet and trasfering some tokens to it
I get these errors:
Server responded with 429 Too Many Requests.  Retrying after 500ms delay...
Server responded with 429 Too Many Requests.  Retrying after 1000ms delay...
Server responded with 429 Too Many Requests.  Retrying after 2000ms delay...
Server responded with 429 Too Many Requests.  Retrying after 4000ms delay...

I tried setting delay times as big as 9 seconds between every async method I use from spl-token library.
Please help

**Comment by ritvij14** [comment]
Hi @5elfle5, I am facing the same issue, in the Token swap program, can you please share how you solved it?

**Comment by t-nelson** [comment]
This has everything to do with your client SW calling the RPC node too frequently and nothing to do with the target program
