### ISSUE TITLE
Ability to specify --fee-payer as a bs58 encoded string instead of the file path

### ISSUE THREAD

**Issue by unimintco** [solana-labs/solana-program-library#2877]
This is a feature request, one that I will be happy to work on if it is decided as something appropriate.

The use case is simple enough, I'm writing a simple cli wrapper on top of this binary and now I have to decode key pair into a Buffer and persist it to file storage to provide as a path, and later on clean them up not to leave such sensitive information.

This would simplify my flow and rely on IO and varying disk speeds as much.
I don't think it poses any security risk since I already own the keypair, but correct me if I'm wrong.

In any case, thank you for such an amazing tool and service you're building.

**Comment by t-nelson** [comment]
I'm not sure I'm comfortable encouraging this pattern.  It's bad enough that we still have unencrypted filesystem keypairs.  Passing them around as easily copypasta'd text seems like asking for trouble.

Why are you wrapping the CLI instead of just calling APIs directly?

**Comment by unimintco** [comment]
It was a natural progression for the current tasks I have in mind, but I understand it's a hack and do have a plan to moving the implementation to JS web3 library. I'm yet not sure if you can authorise transactions with a string parameter - still need to research it, if yes, then there's probably no need for this feature on the CLI level.

My current use case is that I want to manage the wallets on behalf of the users before they choose to export the wallet (memo or private key). I store them as encrypted strings in a DB. After export I remove them from the DB.

As for the point you're making in my current hacky cli implementation I just temporarily persist the keypair to disk and clean it up after use. Most likely moving to an SDK would be a sounder option?

**Comment by t-nelson** [comment]
> Most likely moving to an SDK would be a sounder option?

Definitely.  Though I can't in good faith recommend custodying keys for users under any circumstances

If you only need to pass one external key to the CLI, you can use `-k -` and pipe the keypair as a JSON integer array, size 64 (same as keypair file contents)

**Comment by joncinque** [comment]
In that case, closing!
