### ISSUE TITLE
Support specifying a recipient account to `token.transfer_checked`

### ISSUE THREAD

**Issue by vpontis** [solana-labs/solana-program-library#2886]
Right now the token transfer instruction does not include the actual wallet recipient, it only includes the token account. This causes issues when fetching the activity for a given wallet — you won't receive see token transactions if the ATA (associated token account) already exists and didn't require creation.

**Comment by vpontis** [comment]
@joncinque @CriesofCarrots @mvines would love to get your feedback on this :)

**Comment by vpontis** [comment]
Also I would love to chat about this in the #spl channel on Discord but I don't seem to have access to that.

**Comment by vpontis** [comment]
Another way of doing this would be to create a Memo instruction and pass accounts there. But we can't do that since Memo requires all accounts to be signers — is there another version of memo that doesn't require signers?

**Comment by CriesofCarrots** [comment]
Thanks, @vpontis . This is something that is on our radar: https://github.com/solana-labs/solana-program-library/issues/1891
I'm closing this as a duplicate, but feel free to add to that issue, if we've missed anything about your use-case.

> Also I would love to chat about this in the #spl channel on Discord but I don't seem to have access to that.

That channel is limited to just Contributor roles at the moment. Maybe we need a Developers channel for SPL discussions, similar to #core-technology
