### ISSUE TITLE
Reserve some instruction codes

### ISSUE THREAD

**Issue by vporton** [solana-labs/solana-program-library#2895]
Please add reserved instruction codes like:

"Codes `>=200` can be used to extend functionality of tokens and won't be used by us, token specification developers."

**Comment by joncinque** [comment]
We won't add in a blanket area for reserved codes, but keep in mind that we won't get all the way to the end, so feel free to use 255 as the first byte for any instruction codes that you want to use. That can be an unofficial "reserved" area.
