### ISSUE TITLE
Option to make Non-Transferable Tokens (NTT)

### ISSUE THREAD

**Issue by joxoby** [solana-labs/solana-program-library#2909]
Non-transferability of tokens can be useful when the token represents achievements, certifications, events, etc. that the owner is related to. If the token can be sold/bought, it becomes meaningless.

The current token program doesn't seem to provide this type of functionality.

I wonder what you all think about adding a "non-transferable" flag to the token initializer function.

Related issue on Ethereum: https://github.com/ethereum/EIPs/issues/1238
Related blog post: https://vitalik.ca/general/2022/01/26/soulbound.html

**Comment by mvines** [comment]
This sounds like a great way to spam a user's wallet with advertisements/scams that they can't get rid of.  This is already happening regularly but at least the victims can currently dispose of the token.

**Comment by jordansexton** [comment]
I actually think this has utility to create [soulbound](https://vitalik.ca/general/2022/01/26/soulbound.html) tokens which have some interesting uses (decentralized identity comes to mind).

Could you make it so the token can be burned but not transfered? This would help with the spam issue.

**Comment by joxoby** [comment]
> This sounds like a great way to spam a user's wallet with advertisements/scams that they can't get rid of. This is already happening regularly but at least the victims can currently dispose of the token.

Valid concern. But in this case, the non-transferable tokens could still be burnt.

**Comment by mvines** [comment]
Wallets need to support burning tokens first.

**Comment by joxoby** [comment]
Draft PR: https://github.com/solana-labs/solana-program-library/pull/2912

**Comment by jpbogle** [comment]
FYI @joxoby we have been exploring a similar thing using a program we call the "token_manager" https://github.com/cardinal-labs/cardinal-token-manager

If you are the mint creator, can you not just utilize freeze authority to freeze everytime you mint someone a token? Also I feel like non-transferability could be modeled more flexibly with a `transfer_authority: COption<Pubkey>`, we have done this in our program by requiring a transfer_authority to create a "transfer_receipt" that someone can use to transfer the token to the approved party. Would be a cool feature in token-program and also solve non-transferability / soul tokens by just setting transfer_authority to None

**Comment by joncinque** [comment]
Added with #3178

**Comment by fullstackdev0410** [comment]
Hello
Can I solve the non-transferability without any contract?

**Comment by fullstackdev0410** [comment]
I was gonna develop the passport mint website and I used metaplex.
Now I need to do non-transferability of nft.
Do I have to develop the smart contract?

**Comment by joncinque** [comment]
This is off-topic, but to quickly answer -- the feature is available on token-2022, but has not been released to mainnet yet.  Also, Metaplex is not using token-2022 at the moment.  If you need this soon, then you will have to develop your own on-chain program.
