### ISSUE TITLE
Data decoding base64 (need structure)

### ISSUE THREAD

**Issue by mage-ua** [solana-labs/solana-program-library#2939]
Hello, guys!

Please help me.

Where can I take data structure of base64 ecoded messages of **programSubscribe** messages type for decoding?

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "programSubscribe",
  "params": [
    "someAddress",
    {
      "encoding": "base64",
      "commitment": "processed"
    }
  ]
}
```
Receive something like this. Need to decode data[0]

```
{
  "jsonrpc": "2.0",
  "method": "programNotification",
  "params": {
    "result": {
      "context": {
        "slot": 12345
      },
      "value": {
        "pubkey": "XXXXX",
        "account": {
          "lamports": 12345,
          "data": [
            "JEUwEoDhfYeue++EI97IyWHo9TiUneNoZsZALtCc7aKcAbsyPJZyUOLRWUfcuU7Dura0bVse8AR6o8VaHWQQwhGrR5oMCk7UAHQ7pAsAAAA=",
            "base64"
          ],
          "owner": "XXX",
          "executable": false,
          "rentEpoch": 12345
        }
      }
    },
    "subscription": 12345
  }
}
```

What fields u64, publicKey should be?

**Comment by FrankC01** [comment]
First you need to decode the data field into buffer (assume you are in TS/JS) so...
`const data = Buffer.from(data, "base64");`

You then need to deserialize, in which case you need to know how the program serializes the account so you can reverse it.

Pubkey is a array of size 32 bytes (u8)

**Comment by jordansexton** [comment]
Please direct support questions to Discord, there's a #developer-support channel.
