### ISSUE TITLE
Unable to Import Token from @solana/spl-token

### ISSUE THREAD

**Issue by fw-aaron** [solana-labs/solana-program-library#2953]
I'm getting the following error

```
import {TOKEN_PROGRAM_ID, Token, AccountLayout} from '@solana/spl-token';
                          ^^^^^
SyntaxError: The requested module '@solana/spl-token' does not provide an export named 'Token'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:193:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

Node.js v17.5.0
```

Lots of examples I see suggest that I should be able to import `Token` from this package (https://github.com/search?p=5&q=createinitaccountinstruction&type=Code). I see the newest package on npm is 0.2.0, and that is what I'm using. I also tried 0.1.8 to the same effect. When I remove `Token` from that import list, it works fine...until execution gets to `Token.createInitAccountInstruction(TOKEN_PROGRAM_ID, ...` in my program of course.

My `package.json` is pretty straightforward; I'm using the newest versions of these libraries:

```
{
    "name": "server",
    "version": "1.0.0",
    "description": "backend",
    "main": "/app/src/server.js",
    "type": "module",
    "scripts" : {
        "start": "node src/server.js"
    },
    "dependencies": {
        "@solana/web3.js" : "1.35.1",
        "@solana/spl-token" : "0.2.0"
    },
    "devDependencies": {
    }
}
```

**Comment by jacobcreech** [comment]
The new `@solana/spl-token` library at version `0.2.0` does not have the `Token` class. Instead the actions are split up and exported separately.

If you want to use the old version, make sure you install it with
```
npm install @solana/spl-token@0.1.8
```
Otherwise you can find documentation on how to use `0.2.0` on the [SPL docs](https://spl.solana.com/token) or [solanacookbook](https://solanacookbook.com/references/token.html).

Generally we do not do support in Github issues. If you want further support, please post the question on [stackoverflow](https//stackoverflow.com) with the `solana` tag or visit us in #developer-support on [discord](https://solana.com/discord)

**Comment by fw-aaron** [comment]
> The new `@solana/spl-token` library at version `0.2.0` does not have the `Token` class. Instead the actions are split up and exported separately.

I see. Looking at the cookbook and the git repository, it was pretty easy to adapt the example I was working on to the newer `0.2.0`, and my code is working now!

> If you want further support, please ... visit us in #developer-support on discord

Thank you for the invitation! Unfortunately you banned me there a couple weeks ago. As a reminder, my offense was being disrespectful to other users seeking help. Someone said something like "Is anyone here" and I mouthed off with what I thought was a pat response: something like "I am here and will be your personal assistant". I'm used to IRC (https://sol.gfxile.net/dontask.html) where my response would fit right in. I now see the difference between Solana and IRC as professional vs. amateur; respectful vs. crass, civilization vs. the wild west, etc. I'm sorry for being disrespectful. I am very impressed at the quality of support that the Solana discord provides and would like you to reconsider the ban on lmat#1258.

**Comment by Benhawkins18** [comment]
> The new `@solana/spl-token` library at version `0.2.0` does not have the `Token` class. Instead the actions are split up and exported separately.
> 
> If you want to use the old version, make sure you install it with
> 
> ```
> npm install @solana/spl-token@0.1.8
> ```
> 
> Otherwise you can find documentation on how to use `0.2.0` on the [SPL docs](https://spl.solana.com/token) or [solanacookbook](https://solanacookbook.com/references/token.html).
> 
> Generally we do not do support in Github issues. If you want further support, please post the question on [stackoverflow](https//stackoverflow.com) with the `solana` tag or visit us in #developer-support on [discord](https://solana.com/discord)

This helped me after some digging. Thanks Jacob
