### ISSUE TITLE
token-swap: Add PMM curve from Dodo

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#2955]
#### Problem

token-swap can support multiple different curves, including the classic constant product curve and the curve.fi stable swap curve.  But there are other interesting curves that capture certain market dynamics!  The PMM Curve popularized by Dodo on Ethereum is one example that could be added: https://dodoex.github.io/docs/docs/pmm

#### Solution

Add support for this new curve!  The biggest difference with it is the addition of the "regression targets" in the state and the `k` which sets the curve behavior. which needs to be set at creation.

In the end, it means supporting these equations in the curve calculator implementation: https://dodoex.github.io/docs/docs/math

More background at https://github.com/solana-labs/solana-program-library/blob/master/token-swap/proposals/ProactiveMarketMaking.md

**Comment by LuckyPigeon** [comment]
This seems interesting, can give this a shot?
