### ISSUE TITLE
token-js: Support `Reallocate` instruction

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#2956]
#### Problem

`token-2022` includes a new instruction to reallocate the space in an Account, but it isn't supported in the JS bindings.  The relevant instruction definition can be found at https://github.com/solana-labs/solana-program-library/blob/0268d76d306d86a9fb03a17d5ede18144bfad684/token/program-2022/src/instruction.rs#L529-L550

#### Solution

Following the model in #2951 , add support for this new instruction, including some tests.

**Comment by joncinque** [comment]
@tian000 certainly! It doesn't look like anyone's taken a crack at it yet

**Comment by tyirenkyi** [comment]
It looks like @tian000 isn't available anymore. Can I take a crack at it @joncinque?

**Comment by joncinque** [comment]
@tyirenkyi by all means, go for it!

**Comment by joncinque** [comment]
A few things to note:

* reallocate is only supported on the `token-2022` program, and not the base token program, so you'll need to test against that using `yarn test:e2e-2022`.  Make sure that the program is built using `cargo build-bpf` from `token/program-2022` since it isn't included with the test validator by default.
* an `ExtensionType` is actually defined as a `u16`, so you'll need two little-endian bytes for each extension type.  You can see how it's packed in Rust at https://github.com/solana-labs/solana-program-library/blob/dd8f4d138fe5c51067737124cf8feb47daf75254/token/program-2022/src/instruction.rs#L834

From there, you should be really close!

**Comment by tyirenkyi** [comment]
Hello @joncinque, I tried to follow your guidance and came up with this:
```
export const reallocateInstructionData = struct<ReallocateInstructionData>([
  u8('instruction'),
  seq(u16(), offset(u8('instruction'), -1), 'extensionTypes'),
]);
```
But I get this error every time I run the tests:
```
 RangeError [ERR_INVALID_OPT_VALUE]: The value "-1" is invalid for option "size"
      at Function.alloc (buffer.js:370:3)
      at createReallocateInstruction (file:///Users/applejeewce/solana-development/solana-program-library/token/js/src/instructions/reallocate.ts:54:23)
      at Context.<anonymous> (file:///Users/applejeewce/solana-development/solana-program-library/token/js/test/e2e-2022/reallocate.test.ts:65:7)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

It's caused by this line:
`const data = Buffer.alloc(reallocateInstructionData.span);`

I believe adding the Offset layout is causing this. The documentation recommends using `getSpan` instead of `span`, but I'll need a Buffer instance to do that. I tried to guess the right number of bytes but I never got it right, also I'm pretty sure that's not advisable.

Could you help me out again?

**Comment by joncinque** [comment]
You're on the right track -- the instruction data for reallocate is unfortunately different from everywhere else, since it's a variable-length array of `u16`s.  So in your case, you won't be able to call `reallocateInstructionData.span`, since the struct doesn't have a set size.  Instead, you need to allocate the correct size for the instruction data based on the extension types passed in. That would be something like:

```
    const data = Buffer.alloc(1 + 2 * extensionTypes.length);
    reallocateInstructionData.encode(
        {
            instruction: TokenInstruction.Reallocate,
            extensionTypes: // do your mapping of ExtensionType array to u16 array
        },
        data
    );
```

**Comment by tyirenkyi** [comment]
Hello @joncinque, I've been trying to figure out what you meant by this line
`do your mapping of ExtensionType array to u16 array`

Initially I thought you meant create a Uint16Array out of the ExtensionType array but it didn't work because of type mismatch.
This is the ReallocateInstructionData interface: 
```
export interface ReallocateInstructionData {
  instruction: TokenInstruction.Reallocate;
  extensionTypes: ExtensionType[];
}
```

And so then I change the interface to this:
```
export interface ReallocateInstructionData {
  instruction: TokenInstruction.Reallocate;
  extensionTypes: Uint16Array;
}
```
but that meant that the `struct` definition had to change, and so I abandoned that approach. I've been tripping over myself trying to figure out what you meant. Could you help me out again?

**Comment by joncinque** [comment]
When you call `reallocateInstructionData.encode` with the array of `ExtensionType`, you need to make sure that each `ExtensionType` gets encoded as a `u16`.  Here's the code that does it in Rust: https://github.com/solana-labs/solana-program-library/blob/5611ad8bd595d9e3666f8b115cd28f8116038645/token/program-2022/src/instruction.rs#L839

You''ll have to figure out how to do this conversion in JS.  For example, here's the code for reading the `u16`: https://github.com/solana-labs/solana-program-library/blob/5611ad8bd595d9e3666f8b115cd28f8116038645/token/js/src/extensions/extensionType.ts#L96

**Comment by joncinque** [comment]
@tyirenkyi are you still working on this? I'd like to get it integrated soon.  Would you mind putting up a draft PR with your changes?  If you're busy with other things, then I can take over and finish

**Comment by zrthxn** [comment]
Is this something that still needs to be worked on?

**Comment by joncinque** [comment]
@zrthxn It certainly is!
