### ISSUE TITLE
 token-js: Support `TransferFee` extension

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#2959]
#### Problem

`token-2022` includes new extension instructions to use transfer fees, but it isn't supported in the JS bindings.  The relevant top-level instruction definition can be found here: https://github.com/solana-labs/solana-program-library/blob/0268d76d306d86a9fb03a17d5ede18144bfad684/token/program-2022/src/instruction.rs#L514-L518

and the sub-instructions here: https://github.com/solana-labs/solana-program-library/blob/0268d76d306d86a9fb03a17d5ede18144bfad684/token/program-2022/src/extension/transfer_fee/instruction.rs#L15-L134

#### Solution

Following the model in #2951 , add support for these new instructions, state, and extension type, including some end-to-end tests.

**Comment by kris524** [comment]
Hello, could I pick this issue?

**Comment by joncinque** [comment]
@kris524 this one is being addressed with #3102 -- thanks for the enthusiasm though!  Please feel free to reach out about any others that interest you in this domain
