### ISSUE TITLE
createMintToInstruction is throwing error 

### ISSUE THREAD

**Issue by shubhamnixet** [solana-labs/solana-program-library#2965]
I'm getting error when i'm creating 9 digit token for amount of `1000000000`

Here is the code sample
<img width="512" alt="Screenshot 2022-02-28 at 12 39 49 AM" src="https://user-images.githubusercontent.com/83249737/155896206-a9f96f9d-42a0-4929-8dcc-e9eb0e886bf5.png">

And here is the error.:
<img width="583" alt="Screenshot 2022-02-28 at 12 40 53 AM" src="https://user-images.githubusercontent.com/83249737/155896255-2ae3ba4d-7651-4331-8ff8-93612beb1c60.png">

**Comment by t-nelson** [comment]
hi. we don't use github for support requests. please join us in #developer-support on https://solana.com/discord
