### ISSUE TITLE
Pool with stable token

### ISSUE THREAD

**Issue by Poonamsingh080** [solana-labs/solana-program-library#2979]
how to create pool with spl token and USDC
for example:
USDC on testnet = CpMah17kQEL2wqyMKt3mZBdTnZbkbfx4nqmQMFDP5vwp
SPL token on solana testnet = 2uWhmBh48rRhDdrM2mMq6BhiHh1yX16DAw6RtZJTfdHg

kindly suggest me

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support, so please join us at #developer-support on Discord https://discord.gg/solana!

To give a you a few pointers, you can read through the docs at https://spl.solana.com/token-swap#creating-a-new-token-swap-pool and take a look at how to create a pool in this end-to-end test https://github.com/solana-labs/solana-program-library/blob/00767dbd28fea3e0faff22ab7c803ea64ba12766/token-swap/js/cli/token-swap-test.ts#L89
