### ISSUE TITLE
Publish API javascript docs for spl-token

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana-program-library#298]
The API documentation for https://www.npmjs.com/package/@solana/spl-token lives only in the code right now.  ESDoc has been working out ok for solana-web3.js, so we could continue to use that solution or look around for an alternative

**Comment by roccomuso** [comment]
Are there any js example around or documentation on how to use the js lib with tokens?

**Comment by joncinque** [comment]
This is done with TypeDoc: https://solana-labs.github.io/solana-program-library/token/js/
