### ISSUE TITLE
support for semi-fungible tokens 

### ISSUE THREAD

**Issue by Alaarhi** [solana-labs/solana-program-library#2991]
Hey Guys,
this is more of a question than an issue. 
I've looking into how to mint a collection of semi-fungible tokens using spl-token.
I started with creating a semi-fungible token but I couldn't find any cmd to update it's metadata (like adding an image or a description). 
How can do that ? is there any exteranl tool that could facilitate the task ?

Appreciate your help!

**Comment by askibin** [comment]
Metaplex is the standard for holding/working with NFT metadata. You can read their docs for complete details: https://docs.metaplex.com/candy-machine-v2/getting-started
or look up more concise step by step guides

**Comment by Alaarhi** [comment]
Thanks for the link. I did check the metaplex documentations on working with NFTs. 
My question is more to the Semi-fungible tokens, SFTs. 
I saw that I can submit a PR in this github for changing the name/logo of the token : https://github.com/solana-labs/token-list
but i couldn't find any guide on how to associate it with an image or change it into an image (asset kind of like the NFT). 
I'm implementing my own collection of gift cards for my business and I need a tool like the SFT where I can generate a big amount of tokens with same values except for the address. 
I hope it makes sense and I appreciate your help.

**Comment by askibin** [comment]
you can't do it with token-list. You have to use Metaplex (or come up with your own standard, but wallets won't display your tokens as NFTs in such case). Metaplex does support semi- and fungible tokens. From here https://docs.metaplex.com/token-metadata/specification
```
A token_standard field is added to the Metadata struct representing what type of token each NFT is.
    NonFungible,   // This is a master edition
    FungibleAsset, // A token with metadata that can also have attributes, sometimes called Semi Fungible
    Fungible,      // A token with simple metadata
    NonFungibleEdition, // This is a limited edition
```
We don't use github for support, if you have further questions you can join Metaplex discord: https://discord.gg/gNz5jTvT
