### ISSUE TITLE
[spl-token]: Seemingly contradictory code

### ISSUE THREAD

**Issue by ElasticBottle** [solana-labs/solana-program-library#2993]
https://github.com/solana-labs/solana-program-library/blob/48fbb5b7c49ea35848442bba470b89331dea2b2b/token/js/src/actions/getOrCreateAssociatedTokenAccount.ts#L91

Note here that we are asserting whether or not the account info owner is equivalent to the owner itself.

However, if we when fetching the account info here https://github.com/solana-labs/solana-program-library/blob/48fbb5b7c49ea35848442bba470b89331dea2b2b/token/js/src/state/account.ts#L94, we see that we are asserting that the owner is the `program_id` (most of the time)

As far as I'm aware, the `owner` and `program_id` are two different thing, so how does this function not throw an error at all?

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support, and invite you to join us at #developer-support on Discord https://discord.gg/solana

To quickly answer your question, this is correct behavior, but a result of the overloading of the word "account" on Solana, which can refer to a base Account on-chain, or also a holding of SPL tokens.  You can see the difference that `account` in your first example is an `Account` from the @solana/spl-token package, whereas `info` is an `AccountInfo` from the @solana/web3.js package.

In the first, `owner` means the wallet that can sign for the tokens, but in the second `owner` means the program that can modify the data. More info at https://docs.solana.com/developing/programming-model/accounts#ownership-and-assignment-to-programs
