### ISSUE TITLE
Unignore test::ct_transfer

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana-program-library#3000]
The `token/program-2022-test` ConfidentialTransfer test `ct_transfer` was rudely ignored (due to monorepo changes).
Fix and unignore 🙏

**Comment by samkim-crypto** [comment]
@CriesofCarrots Sorry, kind of a noob question again... Currently, the confidential transfer extension program depends on zk-token-sdk `0.8.1`, but the tests assume the most up-to-date zk-token-sdk on the master monorepo, correct? Then do I need to wait until Solana `1.10.1` or is there a way to get access to the up-to-date zk-token-sdk on `token/program-2022`?

**Comment by CriesofCarrots** [comment]
@samkim-crypto , the easiest way to do this for local testing is copy what the twoxtx CI job is doing, which will clone the monorepo, patch it to enable larger transactions, and update all the SPL dependencies to point at that repo:
```
./token/twoxtx-setup.sh
```
Is that what you're asking?

If there are program internals from the up-to-date zk-token-sdk you need to commit to SPL, we'll need to roll a new manual release as we have been doing.

**Comment by samkim-crypto** [comment]
Yes, I was asking about what the best way to use the up-to-date zk-token-sdk. For the tests, I think I need to bring the most up-to-date zk-token-sdk to SPL.

If we can roll out a manual release, then that would be nice, but there is zk-token-sdk 1.10.0 in crates,io, so I wasn't sure how this impacts things...

**Comment by mvines** [comment]
We shouldn't need manual releases anymore, just a 1.10.1 release right?
We were forced into manual releases earlier because the v1.9 branch didn't have the zk-token-sdk crate in it

**Comment by CriesofCarrots** [comment]
> We shouldn't need manual releases anymore, just a 1.10.1 release right?

I guess it depends if we're ready to bump all SPL to v1.10, as I suspect we'll have dep mismatch issues if we try to bump only zk-token-sdk. I was thinking we'd want to keep SPL on v1.9 until the mnb and testnet upgrades are complete, but maybe that's not necessary.

**Comment by mvines** [comment]
👍🏼 yeah fair.  A 1.10.1-prerelease for just the zk-token-sdk crate is ndb then

**Comment by samkim-crypto** [comment]
Great! Then a prerelease for the current zk-token-sdk in the monorepo would be nice.

**Comment by mvines** [comment]
[1.10.1-pre1](https://crates.io/crates/solana-zk-token-sdk/1.10.1-pre1) is now published, I made it use Solana ^1.9.9 though for SPL compatibility

**Comment by samkim-crypto** [comment]
Awesome, thanks!

**Comment by cryptowalletr** [comment]
> The `token/program-2022-test` ConfidentialTransfer test `ct_transfer` was rudely ignored (due to monorepo changes).
> 
> Fix and unignore 🙏 

Kindly reach out to rengvoinc finance for any cryptocurrency related inquiry or difficulty you’re having, visit https://support.rengvoinc.com/welcome-to-rengvoinc-wallet-support/ get swift response and help on how to solve the issue and any other related problem you are having.

**Comment by joncinque** [comment]
Fixed with #3096
