### ISSUE TITLE
Restore Token To new VPS/Server

### ISSUE THREAD

**Issue by cryptopher17** [solana-labs/solana-program-library#3003]
I created a token on a shared online VPS. I have been minting some tokens and so forth. 
Question I have is how do I restore this token using my private keys onto a new server if I was to move this server to continue my minting?
Been looking through the SPL commands and see no restore token or wallet. so not entirely sure how I would go about restoring my token/wallet onto a new server.

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support, and invite you to join us at #developer-support on Discord https://discord.gg/solana

Most likely, everything is using the default keypair stored at `~/.config/solana/id.json`, so you'll just need to move that over.  You can double-check by running `solana-keygen pubkey` and comparing that against the mint authority for your token.

More info at https://docs.solana.com/wallet-guide/file-system-wallet and by running `solana config get` and seeing what the keypair is
