### ISSUE TITLE
cargo build farm-client fails on Mac m1 

### ISSUE THREAD

**Issue by Kubikasz** [solana-labs/solana-program-library#3006]
On `cargo build` compiling fails with : 
```bash 
 Compiling vipers v1.6.1
   Compiling solana-transaction-status v1.10.0
error: cannot find attribute `error` in this scope
....
error: could not compile `vipers` due to 12 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Hardware: 
* Mac m1 16gb ram 
* Macox Monterey version 12.1

I can build and run `Solana-cli` and `local test validator` 
I can build the token program also.

**Comment by askibin** [comment]
it should be working now after the latest updates, let me know if there are still any issues
