### ISSUE TITLE
Tax spl token

### ISSUE THREAD

**Issue by saman-pasha** [solana-labs/solana-program-library#3028]
thanks to spl-token that makes token creation easy, i need to write some tokens with tax enabled and some custom instructions, if i clone spl-token and change it for myself, how can i add my generated tokens in my custom spl-token to public marketplaces?

**Comment by joncinque** [comment]
Hi there, you have two main options:

1. create your own token program with the new features that you need and deploy it to a new program id.  this will require buy-in from wallets and marketplaces to use your new program, and could take a lot of time to get done.
2. add your functionality as an "extension" in the token-2022 program, similar to to the transfer fee extension.  A few bits of information about this:
  * the main source is at: https://github.com/solana-labs/solana-program-library/tree/master/token/program-2022/src/extension/transfer_fee
  * entrypoint in the processor at https://github.com/solana-labs/solana-program-library/blob/8322b8bb40e96067540e79fd20823a6d7b174920/token/program-2022/src/processor.rs#L1223
  * code calculating / using the fee during transfer: https://github.com/solana-labs/solana-program-library/blob/8322b8bb40e96067540e79fd20823a6d7b174920/token/program-2022/src/processor.rs#L286

Either way, this is more meant for the #developer-support channel in our Discord: https://solana.com/discord, so please join us there!
