### ISSUE TITLE
Tokens can be initialized with invalid mint accounts

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#303]
#### Problem
`InitializeAccount` doesn't check if `mint_info` is valid (exists, initialized, and owned by token program) and so tokens can be created with invalid mints. These token accounts are useless because without a valid mint, they can never hold a token balance.

#### Suggested Changes
- For developer experience, we should fail fast on token creation to avoid later confusion when token accounts are attempted to be minted to.
- Consider forcing mint accounts rent exempt so that token accounts are always valid

**Comment by jstarry** [comment]
Here is an example on-chain where this happened on testnet
InitializeAccount: https://explorer.solana.com/tx/5Ep4euatukeYjqFSwaPfrNT8FTfkgeYkp5boCEBPNygb9kACU11Nn7Kpzrjru3VxyFWSqMyv5jYfim6Wp9VVYceT?cluster=testnet
Invalid mint account: https://explorer.solana.com/address/3ZE2ei22iLgivkeLZkmNVcTx3zPfkN7ALLx5MdeEJ2ss?cluster=testnet

**Comment by jstarry** [comment]
@jackcmay @CriesofCarrots @mvines thoughts?

**Comment by mvines** [comment]
> These token accounts are useless because without a valid mint, they can never hold a token balance.

The account can still be closed though.  I feel like the client-side libraries could mostly mitigate this.   I'm not opposed to adding a mint validity check in InitializeAccount.

> Consider forcing mint accounts rent exempt so that token accounts are always valid

This should be client side IMO.   I don't feel like we need to enforce that in the program.

**Comment by mvines** [comment]
@CriesofCarrots - anything left to do here?

**Comment by CriesofCarrots** [comment]
Yes, still need the check for valid mint on InitializeAccount
