### ISSUE TITLE
Unable to use createInitializeAccountInstruction in a create-react-app

### ISSUE THREAD

**Issue by sandeepmukh** [solana-labs/solana-program-library#3030]
Hi! I'm trying to use the `@solana/spl-token` javascript library in an SPA (specifically a create-react-app). However, I can't seem to call the function `createInitializeAccountInstruction` in my App.js, but I can when I create a script and run it with node. 

The exact error message I'm getting in the console is:
```
Uncaught (in promise) ReferenceError: Buffer is not defined
    at createInitializeAccountInstruction (bundle.js:90111:16)
```

To reproduce this issue:

run create react app and add a button with this function as it's onClick:
```
const f = async () => {
  createInitializeAccountInstruction(Keypair.generate().publicKey, Keypair.generate().publicKey, Keypair.generate().publicKey)
}
```

Note that the addresses don't matter, even when I was using valid addresses in my initial SPA, this error still occurred. 

Then just click the button and the error will then show up in the console. 

I know that buffer is a node class, but I thought you could get around that by using `npm install --save buffer`, but this didn't work. Thanks for any help/insight!

I'm also attaching my full example App.js in case there was something I missed:
[App.txt](https://github.com/solana-labs/solana-program-library/files/8354134/App.txt)

Edit:
I'm using version 0.2.0.

**Comment by jordansexton** [comment]
This is a typical error when using Create React App / Webpack without polyfills (they aren't enabled by default in CRA5/Webpack 5). It's not specific to the SPL Token client library. Check out these links for an example of how to configure your project:

https://github.com/solana-labs/wallet-adapter/blob/e15287221b90f8d7bee60726d251a5b4c76d243a/packages/starter/create-react-app-starter/package.json#L24-L32

https://github.com/solana-labs/wallet-adapter/blob/master/packages/starter/create-react-app-starter/config-overrides.js

**Comment by elv-sandeep** [comment]
Thanks for your response Jordan! I tried cloning the create-react-app-start repo that you linked, and doing the same thing I detailed in my original post, but the issue persists. Is there any other reason this might be happening or a place where I could get a working example?

**Comment by sandeepmukh** [comment]
Thanks for your response Jordan! I tried cloning the create-react-app-start repo that you linked, and doing the same thing I detailed in my original post, but the issue persists. Is there any other reason this might be happening or a place where I could get a working example?

**Comment by gaurav-12** [comment]
Hey @sandeepmukh 
I was facing the same problem. This answer helped me: https://stackoverflow.com/a/71205013/8312512

**Comment by sandeepmukh** [comment]
@gaurav-12 That fixed the issue thank you so much!
