### ISSUE TITLE
token-swap: re-enable CI tests

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana-program-library#305]
Once https://github.com/solana-labs/solana/pull/11745 lands and ships in a Solana 1.3 release, restore the token-swap tests:
https://github.com/solana-labs/solana-program-library/blob/b619da32aea7b2898d1fe2faf4cdc7dba99df164/ci/script.sh#L59-L60
and
https://github.com/solana-labs/solana-program-library/blob/b619da32aea7b2898d1fe2faf4cdc7dba99df164/ci/script.sh#L96-L102

**Comment by joncinque** [comment]
@mvines what's the typical release schedule for the Solana crates?  Looking back, it seems like it's every 2-5 days, but I was wondering if there's a particular threshold before the next release usually
