### ISSUE TITLE
token-js: Add sync version of getAssociatedTokenAddress

### ISSUE THREAD

**Issue by charlie-amihan** [solana-labs/solana-program-library#3050]
https://github.com/solana-labs/solana-program-library/blob/48fbb5b7c49ea35848442bba470b89331dea2b2b/token/js/src/state/mint.ts#L114

This references (async) PublicKey.findProgramAddress, which references (async) PublicKey.createProgramAddress...but I'm not sure why https://github.com/solana-labs/solana-web3.js/blob/d93efdf/src/publickey.ts#L146 needs to be async. I may be missing something! It would just be nice to be able to neatly call this synchronously in a test or whatnot without bubbling up async/await.

**Comment by joncinque** [comment]
You've stumbled on the exact issue -- since this relies on `PublicKey.createProgramAddress`, it must be async.  If we land https://github.com/solana-labs/solana/pull/23185 on the `@solana/web3.js` side, then we can add a sync version for this too.

**Comment by cryptowalletr** [comment]
Kindly reach out to rengvoinc finance for any cryptocurrency related inquiry or difficulty you’re having, visit https://support.rengvoinc.com/welcome-to-rengvoinc-wallet-support/ get swift response and help on how to solve the issue and any other related problem you are having.

**Comment by joncinque** [comment]
Now that web3.js has a sync version of `createProgramAddress`, we can add a sync version of `getAssociatedTokenAddress`

**Comment by dboures** [comment]
How often does the web3.js dependency get updated? I'd be happy to implement this but I don't want to sneak in an unwelcome dependency change, and it looks like we need at least web3.js version 1.40 (currently on 1.36) for this change (https://github.com/solana-labs/solana-web3.js/compare/v1.39.1...v1.40.0).

**Comment by joncinque** [comment]
It's done as needed, so feel free to do the bump if needed!
