### ISSUE TITLE
Pubkey::new_unique() uses mutable global state, causing error

### ISSUE THREAD

**Issue by Lazar955** [solana-labs/solana-program-library#3055]
https://github.com/solana-labs/solana-program-library/blob/b2fad8a0781bddd90c8e9b768184f55306265cef/governance/program/src/instruction.rs#L697

When using `create_governance` when trying to run the program I get: ELF error: Found writable section (.data._ZN14solana_program6pubkey6Pubkey10new_unique1I17ha2b7fb560b29dc4bE) in ELF, read-write data not supported.

`Pubkey::new_unique()` shouldn't be used, and I suggest that `governed_account` is not optional.

**Comment by joncinque** [comment]
That's a great suggestion. I remember making the same comment at the time, but there was a good reason for making the parameter mandatory, which I can't remember.  @SebastianBor what's the rationale again?

**Comment by SebastianBor** [comment]
> That's a great suggestion. I remember making the same comment at the time, but there was a good reason for making the parameter mandatory, which I can't remember. @SebastianBor what's the rationale again?

The account is optional because it doesn't have to exist and can only be used as a unique identifier for the PDA seeds. However if we can't generate the pubkey on-chain then yes, we should make it mandatory

**Comment by t-nelson** [comment]
`Pubkey::new_unique()` should _never_ be used in an application.  It is only for tests and it's "uniqueness" is based strictly on how many times it has been called

**Comment by cryptowalletr** [comment]
Kindly reach out to rengvoinc finance for any cryptocurrency related inquiry or difficulty you’re having, visit https://support.rengvoinc.com/welcome-to-rengvoinc-wallet-support/ get swift response and help on how to solve the issue and any other related problem you are having.
