### ISSUE TITLE
Module '"@solana/spl-token"' has no exported member 'createAssociatedTokenAccountInstruction'

### ISSUE THREAD

**Issue by anoushk1234** [solana-labs/solana-program-library#3057]
![image](https://user-images.githubusercontent.com/32778608/161419245-fc256763-6c61-4789-98d9-5f694cce3243.png)

version: "@solana/spl-token": "0.1.8"

**Comment by jordansexton** [comment]
> version: "@solana/spl-token": "0.1.8"

You need to be using version ^0.2.0 to import these functions.

**Comment by ronanyeah** [comment]
I'm also getting this and I am using 0.2.0. TS was telling me to import `Token.createAssociatedTokenAccountInstruction`, which was incorrect.
![Screenshot from 2022-04-04 22-00-01](https://user-images.githubusercontent.com/9598261/161675470-7bf54e11-b3da-4e3b-890f-bcba5b70e5a5.png)

**Comment by jordansexton** [comment]
There is no exported `Token` class (because there isn't any Token class, or any other class) so this error makes sense. You can just import the functional interfaces and types you need now. I think you figured it out, but just answering for posterity.

**Comment by ronanyeah** [comment]
The problem still exists for me, and for several people on the Solana Discord by the looks of things. (search for "no exported member") 

TypeScript thinks `Token` still exists, I don't know why.

**Comment by jordansexton** [comment]
Can you provide a link to a repo? I'm happy to take a look. It's difficult to know how to debug an issue from just an error string with no code or dependencies.

**Comment by ronanyeah** [comment]
I just put together a minimal example with webpack + typescript and it is working correctly so it must be some sort of package conflict.

**Comment by anoushk1234** [comment]
@ronanyeah yea i re installed the package after removing nod modules and it fixed the issue moreover even though it was showing those errors it was actually getting exported

**Comment by ronanyeah** [comment]
After adding various Solana packages one-by-one I narrowed it down to `@metaplex-foundation/mpl-token-metadata` triggering the problem. Upgrading `@metaplex-foundation/mpl-token-metadata` from `1.2.5` to `2.1.0` seems to have fixed it.

Thank you both for your input.

**Comment by eliagoris** [comment]
> After adding various Solana packages one-by-one I narrowed it down to `@metaplex-foundation/mpl-token-metadata` triggering the problem. Upgrading `@metaplex-foundation/mpl-token-metadata` from `1.2.5` to `2.1.0` seems to have fixed it.
> 
> Thank you both for your input.

Can you post the full solution, please? I have the same problem but I couldn't fix it so far

**Comment by eliagoris** [comment]
Update:

Changed `@solana/spl-token` to version `^0.1.8` and it works now.
