### ISSUE TITLE
QUESTION: how to use the swap on devnet and then mainnet

### ISSUE THREAD

**Issue by beamsies** [solana-labs/solana-program-library#3058]
Hello, 

Solana SPL newb here. 

I've downloaded this repo and was successful in running the token-swap > token-swap-test locally.

What I'm confused about is how do I take this to production in my dapp? I know it is deployed to the mainnet, but what about pools? Do I need to find official pool addresses somehow to use this for real? Or do I need to make my own pool.

Sorry if this is a silly question, I'm still learning about the swap activity + liquidity pools in general.

Thanks!

**Comment by jordansexton** [comment]
We don't use Github for dev support questions.  Please ask in the #developer-support channel on the Solana Discord.
