### ISSUE TITLE
how can i get the transaction confirming time with web3?

### ISSUE THREAD

**Issue by cryptoSyndrome001** [solana-labs/solana-program-library#3060]
I'm gonna get the time of transaction processed after confirming transaction by user with web3.
I used the below code:

await new Promise((resolve, reject) => {
solConnection.onAccountChange(userAddress, (data: AccountInfo<Buffer> | null) => {
if (!data) reject();
console.log('success')
resolve(true);
});
})
But it works the first time after page loaded (in react)
how can i get it all the time without page reload?

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support, and invite you to join us on Discord https://solana.com/discord in the #developer-support channel
