### ISSUE TITLE
how can i track wallet transactions realtime?

### ISSUE THREAD

**Issue by cryptoSyndrome001** [solana-labs/solana-program-library#3061]
I have to track several wallet transactions realtime.
I used connection.onLogs function with solana mainnet datahub rpc.
But it could not capture all of the transactions, in a short word i cant catch some transactions sometime.
is it due to datahub rpc problem or the other?
How can i solve this?

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support, and invite you to join us on Discord https://solana.com/discord in the #developer-support channel
