### ISSUE TITLE
token: non-fungible and semi-fungible proposal

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana-program-library#309]
spl-token currently only supports fungible tokens.  With some minor tweaks it can also support non-fungible and semi-fungible tokens.

Proposed changes:
1. Each Token Account has an additional field: `item: u64`
3. `Transfer` instruction now only permits the transfer between (a) source and destination token accounts with the same `item`, or (b) a destination token account with an `amount` of 0, which point the destination `item` is overwritten by the source token account's `item`
4. `Approve`/`Revoke`/`SetOwner`/`CloseAccount` are `item` agnostic
5. `MintTo` is expanded to include an `item` field.   The destination account to mint into must either (a) have the same `item` field or (b) an `amount` of 0, which point the destination `item` is overwritten by the `MintTo`'s `item` field

Note: this description assumes https://github.com/solana-labs/solana-program-library/issues/308 has been implemented.

### Fungible Minting
Use existing workflow, always `MintTo` with an `item` of `0` (by convention all fungible tokens should not mint tokens with an item other than `0`)

### Non-Fungible Minting
1. `InitializeMint { decimals: 0, .. }` <-- init the collection (no fractional items)
1. `MintTo { amount: 1, item: 0 }` <-- create the first item
1. `MintTo { amount: 1, item: 1 }` <-- create the second item
1. `MintTo { amount: 1, item: 2 }` <-- create the third item
1. `SetAuthority(AuthorityType::MintTokens, None)` <-- no more items may be minted

A separate `MintTo` instruction for each item feels heavy handed, but I don't see a better way.  The associated `SystemInstruction::CreateAccount` and `InitializeAccount` instructions are not shown but are also required before each `MintTo`

To send one NFT to another party:
1. `SetOwner` the token account to them
2. `Transfer` into their token account. Destination account which must be initialized with an `amount` of 0

### Semi-Fungible Minting
1. `InitializeMint { decimals: 0, .. }` <-- init the collection (no fractional items)
1. `MintTo { amount: 10, item: 0 }` <-- create 10 of the first item
1. `MintTo { amount: 1, item: 1 }` <-- create 1 of the second item
1. `MintTo { amount: 100, item: 2 }` <-- create 100 of the third item
1. `SetAuthority(AuthorityType::MintTokens, None)` <-- no more items may be minted

To send Semi-Fungible Tokens to another party:
1. `SetOwner` the token account to them, which will transfer the full amount of your item.
2. `Transfer` one or more of your items into their token account.  Destination account which must be initialized with an `amount` of 0, or already hold one or more items of the same `item`.

**Comment by mvines** [comment]
I continue to hate `decimals` a lot...

**Comment by mvines** [comment]
Problem: `Transfer` and `MintTo`'s ability to overwrite the destination token account item value could be use to attack empty wallets.   Token accounts probably need to indicate they're willing to accept any item, possibly as an argument into `InitializeAccount`

**Comment by mvines** [comment]
Another path:
1. SFTs are really just FTs.   The benefit of the proposal above is that SFTs of the same "collection" can share a Mint.  Maybe that's not a big deal, especially if the Mint receives a URL/address to additional metadata.  
1. NFTs are a different program: `spl-item` or `spl-unique-item` perhaps.  Very similar setup as `spl-token` but with some complexity removed.   In this scenario NFTs of the same "collection" can still share a Mint.  (I strongly dislike the approach of NFTs being represented as a spl-token with just one account, seems wasteful and too difficult for clients to find all the NFTs of the same collection)

This pushes more complexity onto the client than the above proposal.

**Comment by CriesofCarrots** [comment]
>     I strongly dislike the approach of NFTs being represented as a spl-token with just one account

I don't quite follow what the alternative is. An account that can hold multiple NFTs from a collection?

>     too difficult for clients to find all the NFTs of the same collection

Isn't this the same as finding the total supply of a Mint?

**Comment by mvines** [comment]
> I don't quite follow what the alternative is. An account that can hold multiple NFTs from a collection?

Say there's an `spl-item` program with a `Mint` and `Account` like `spl-token` has.  The `Account` here doesn't hold an amount.   It probably only as a `SetOwner`-like instruction as well, to transfer ownership of that NFT to another user.

> Isn't this the same as finding the total supply of a fungible Mint?

That's a little different to me.  Without a common `Mint` to try all the NFTs together in a collection, it's hard to be able to find all the hockey cards or my little ponies.   You can't tell what's a card and what's a horse.

**Comment by mvines** [comment]
Nope, not going to pursue this approach.   The `item` brings baggage to the world of non-fungible tokens.  We can do better
