### ISSUE TITLE
getAssociatedTokenAddress given erratic token accounts

### ISSUE THREAD

**Issue by beargrilo** [solana-labs/solana-program-library#3143]
Hi, have some weird case.

Same wallet, nfts in the wallet.

For some NFT,  getAssociatedTokenAddress given the mint address and the owner address it gives the correct Token Account.
For other NFT, it's simply returns a different Token Account which according to Solscan, it's an Account

Working, getAssociatedTokenAddress get the correct SPLTokenAccount.

```json
{
    "owner": "5rwkfMePcndKecfZTkHeAeeJNPVhRLy2kH2TMdsQHTyD",
    "nft": "4215FzwnXfU5TfubscbXuedFcYbW74dCPKWkBJ26pHSx",
    "spl-token-account-expected": "D4XqdE2jvvEnF1fEKVr7pniLDBsKK2hEzxNfd6EnjNnm",
    "spl-token-account -result": "D4XqdE2jvvEnF1fEKVr7pniLDBsKK2hEzxNfd6EnjNnm"
}
```

Not Working:

```json
{
    "owner": "5rwkfMePcndKecfZTkHeAeeJNPVhRLy2kH2TMdsQHTyD",
    "nft": "AKGKLwuxns6jx5Bd967HiVVDMF7BedpkLuFpPDpERVqo",
    "spl-token-account-expected": "DA5emk1jJWhndSPx4FqNdYukZjsfsjQVPXwwa1owam2",
    "spl-token-account -result": "HdbcyzxRmYre9k9tjGqFT57Eff6FfVXp4KFAbCEjSbWi"
}
```

This is the command i'm using in JS: 

```js
mintSplAccountAddress = await splToken.getAssociatedTokenAddress(mintAddress, ownerAddress)
```

Can someone help me on this?!

**Comment by CriesofCarrots** [comment]
We don't use github for technical support.
However, briefly, it looks like some nft drops haven't used proper Associated Token Accounts. That token is in an auxiliary account:
```
$ spl-token accounts AKGKLwuxns6jx5Bd967HiVVDMF7BedpkLuFpPDpERVqo -v --owner 5rwkfMePcndKecfZTkHeAeeJNPVhRLy2kH2TMdsQHTyD -um
Account                                       Balance
-------------------------------------------------------------
DA5emk1jJWhndSPx4FqNdYukZjsfsjQVPXwwa1owam2   1  (Aux-1*)

* Please run `spl-token gc` to clean up Aux accounts
```

For Candy Machine support, see Metaplex: https://discord.com/invite/metaplex

**Comment by beargrilo** [comment]
Ty very much, @CriesofCarrots
