### ISSUE TITLE
Strange peerDependencies

### ISSUE THREAD

**Issue by Jack-Works** [solana-labs/solana-program-library#3146]
Our package manager reported that "@solana/spl-name-service" depends on peer "@angular/common" and "@angular/core". Is that necessary?

```
└─┬ @solana/spl-name-service
  └─┬ crypto-ts
    ├── ✕ missing peer @angular/common@">= 5.0.0"
    └── ✕ missing peer @angular/core@">= 5.0.0"
Peer dependencies that should be installed:
  @angular/common@">= 5.0.0"                  @angular/core@">= 5.0.0"
```

**Comment by Jack-Works** [comment]
And also for `@bonfida/spl-name-service` depends on `webpack-dev-server`. I believe it's definitely wrong.

```
├─┬ @bonfida/name-offers
│ └─┬ @bonfida/spl-name-service
│   ├─┬ webpack-dev-server
│   │ ├── ✕ missing peer webpack@"^4.0.0 || ^5.0.0"
│   │ └─┬ webpack-dev-middleware
│   │   └── ✕ missing peer webpack@"^4.0.0 || ^5.0.0"
```

**Comment by joncinque** [comment]
Nice catch! It looks like some extra packages snuck into the 0.1.3 release, which isn't even reflected in our repo: https://www.npmjs.com/package/@solana/spl-name-service/v/0.1.3

I've put in a PR to update our dependencies, and I'll publish a new version once its merges.

**Comment by joncinque** [comment]
Enjoy! https://www.npmjs.com/package/@solana/spl-name-service
