### ISSUE TITLE
token: Reconsider unsafe usage for instruction pack/unpack

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana-program-library#315]
The use of unsafe typecasting in instruction pack/unpack significantly reduces the instruction count over alternatives but is also scary to look at and is more likely it contain bugs (or have bugs accidentally introduced).  Further this is not a general pattern we want to see in all Solana contracts.

Consider alternatives that either make the unsafe go away entire, or pushes the unsafe into macros or generic libraries where the possibility of human error is reduced.

**Comment by mvines** [comment]
https://crates.io/crates/byteorder has been used by some

**Comment by mvines** [comment]
Also @jackcmay raised the point that since the instruction data is now coming in aligned in the new BPF loader that using byteorder may just be as quick as unsafe casts/copies

**Comment by jackcmay** [comment]
Byte order will not be as quick and most likely significantly slower due to copies both into and back out to account data vs cast and use in place

**Comment by mvines** [comment]
Fixed by https://github.com/solana-labs/solana-program-library/pull/349
