### ISSUE TITLE
math: Improve compute unit usage of `PreciseNumber`

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#3162]
#### Problem

`PreciseNumber` is meant to be an easy way to mimic float-style operations on a fixed-point number, but it can be cumbersome to use or very heavy on compute unit usage.  `token-swap` can barely do a couple of calculations before maxing out, which limits composability.

#### Solution

First, add some compute unit stats for different operations using `PreciseNumber` to gauge the problem. Next, change up the internal implementation to make it more efficient.  A few ideas:

* experiment with different sizes for the internal type.  It's currently a `u256` defined using https://docs.rs/uint/0.9.3/uint/, but perhaps a smaller type would do the trick, or a different underlying library would be better
* algorithms can be improved. For example, the sqrt algorithm may be wasteful
* ergonomics of the library may make it less efficient.  For example, a lot of new constants need to be created and passed by reference.  Is that the best option? Or should these APIs consume `self` and return a new value?

**Comment by rawfalafel** [comment]
We built a 256-bit math library here that's around 5x more efficient in CUs: https://github.com/orca-so/whirlpools/blob/15ccea3fec06d19012e7b7f7a47422f7e6defdbf/programs/whirlpool/src/math/u256_math.rs

Maybe this can be used as the base for a better `PreciseNumber` class :)

**Comment by joncinque** [comment]
@zrthxn I wouldn't recommend taking this on at the same time as #3165, but if you feel up to it, have at it!
