### ISSUE TITLE
math: Add fixed point approximation for natural log

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#3163]
#### Problem

Natural logs are not possible to calculate in fixed-point terms.

#### Solution

Add an approximation for `ln` using a Taylor approximation (probably only possible with `PreciseNumber` around 1), or using linear interpolation.

**Comment by zrthxn** [comment]
I'd like to work on this

**Comment by joncinque** [comment]
Great, feel free to submit a draft pull request if you want to discuss anything
