### ISSUE TITLE
token-swap: Add Oracle or CLOB curve

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#3165]
#### Problem

On-chain CLOBs like Serum are great and showcase the power of Solana.  Oracles are also really useful.  People also like to trade with AMMs.

#### Solution

Add a hybrid token-swap curve that uses a CLOB or Oracle as a price guide when trading.  More detailed information at https://github.com/solana-labs/solana-program-library/blob/master/token-swap/proposals/DynamicMarketMaking.md

**Comment by Geoge1** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14164218/

**Comment by zrthxn** [comment]
I'd like to work on this

**Comment by joncinque** [comment]
@zrthxn Go for it -- keep in mind that it's a pretty tricky one!
