### ISSUE TITLE
Close Account doesn't check if account is frozen

### ISSUE THREAD

**Issue by metamania01** [solana-labs/solana-program-library#3190]
The close account processor in token program doesn't care whether the account is frozen or not before closing it, this can result in behavior where a frozen account is closed and subsequently reinitialized as a thawed account.

**Comment by Help-desk10** [comment]
Kindly open this live chat to talk to the customer service directly on your crypto issue  https://direct.lc.chat/14157678/

**Comment by CriesofCarrots** [comment]
Yes, that's correct. We currently understand the freezing mechanism as a lock on everything currently in the account, not necessarily preventing the address from ever being used again.

Also, token-2022 will introduce a functionality where mints can require all new token accounts be initialized as frozen, allowing the mint freeze authority to curate an allow list by unfreezing accounts. If a user creates an account on such a mint, it'd be nice if they could close and reclaim the lamports, if it won't ever be approved/thawed.
