### ISSUE TITLE
spl-token-swap crate not updated

### ISSUE THREAD

**Issue by gitmalong** [solana-labs/solana-program-library#3201]
The spl-token-swap (https://github.com/solana-labs/solana-program-library/commits/master/token-swap/program) program receives constant updates but I can't see that the crate is being updated (https://crates.io/crates/spl-token-swap/versions). That is an issue cause it causes dependency problems for people using the crate as library.

**Comment by Geoge1** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14164218/
