### ISSUE TITLE
perhaps two different versions

### ISSUE THREAD

**Issue by ysfm** [solana-labs/solana-program-library#3204]
Hello. I have a ledger s+. This devices pids not set on solana-remote-wallet. I change solana core codes and now I can use my wallet with solana cli. But I have a problem with spl-token.

> error[E0308]: mismatched types
>     --> token/cli/src/main.rs:3020:68
>      |
> 3020 |             let address = pubkey_of_signer(arg_matches, "address", &mut wallet_manager)
>      |                                                                    ^^^^^^^^^^^^^^^^^^^ expected struct `solana_remote_wallet::remote_wallet::RemoteWalletManager`, found struct `RemoteWalletManager`
>      |
>      = note: expected mutable reference `&mut std::option::Option<Arc<solana_remote_wallet::remote_wallet::RemoteWalletManager>>`
>                 found mutable reference `&mut std::option::Option<Arc<RemoteWalletManager>>`
>      = note: perhaps two different versions of crate `solana_remote_wallet` are being used?
> 

when I change solana-remote-wallet path on cargo.toml I taken same error messages about different versions.
How can compile spl-token with custom remote wallet.

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support, and instead invite you to join us in #developer-support on Discord at https://discord.gg/solana, or to ask a question on StackOverflow with the "solana" tag.

To quickly answer this, if you want to use a local version of the Solana crates, you can use the `patch.crates-io.sh` script in this repo with the root of your Solana directory, ie:

```
./patch.crates-io.sh path/to/my/solana/repo
```
