### ISSUE TITLE
Clearer documentation on environment setup and common issues

### ISSUE THREAD

**Issue by zrthxn** [solana-labs/solana-program-library#3219]
This is a request to add clearer build instructions and pre-requisites for setting up the development environment for this library. Also, if feasible, provide fixes or help links to common issues one might run into.

**Comment by joncinque** [comment]
Looks like we could update (or remove) the Solana version specified in https://github.com/solana-labs/solana-program-library#development and that'll cover the build instructions and pre-requisites. Is there any language there that could be clearer?

Otherwise, do you have any examples for "common issues one might run into"?

**Comment by zrthxn** [comment]
I think removing the version would be okay, or maybe mentioning 1.10.x instead of 1.6.1. The current stable version (1.9.x) did not work for me and 1.10.x did. 

Also mentioning that a `rustup update` might be required if you've already got it installed. Cargo 1.60 was causing issues and 1.61 didn't.

Common issues one might run into
- [Error while loading shared libraries. (libssl.so.1.1)](https://github.com/project-serum/anchor/issues/1831)
- `Failed to open: ../../deploy/spl_associated_token_account.so`, which I think is caused by out-of-date Rust
- `Failed to open: ../../deploy/spl_token.so`, same reason as above
- CPU/memory at 100%, limit parallel jobs to 1

I can write all this in the readme and you can confirm.

**Comment by joncinque** [comment]
> Failed to open: ../../deploy/spl_associated_token_account.so, which I think is caused by out-of-date Rust

This is because the required program has not been built.  So in this case, you'd need to do `cargo build-bpf` in `associated-token-account/program`.

> I can write all this in the readme and you can confirm.

Please do! At this point, a PR will be most productive.
