### ISSUE TITLE
Add new function get_or_create_associated_token_account for spl-associated-token-account

### ISSUE THREAD

**Issue by aspnxdd** [solana-labs/solana-program-library#3220]
Hello all,

I think would be great to add a function to `get_or_create_associated_token_account` like in the [TS library](https://github.com/solana-labs/solana-program-library/blob/48fbb5b7/token/js/src/actions/getOrCreateAssociatedTokenAccount.ts#L35). Although it is probably required to add to the crate the dependency `solana-client` to be able to use the method `get_account` [[Link]](https://docs.rs/solana-client/latest/solana_client/rpc_client/struct.RpcClient.html#method.get_account).

**Comment by joncinque** [comment]
This is a great idea -- it would rather belong in the `spl-token-client` crate, which is the Rust-equivalent of the TS library.  Specifically, we could make a spinoff of `create_associated_token_account` which just checks the account first.

Here's the code for reference: https://github.com/solana-labs/solana-program-library/blob/38944088c0b6847922a2d59f68fae13c1a92b2a2/token/client/src/token.rs#L354

**Comment by atharmohammad** [comment]
I would like to work on this issue
