### ISSUE TITLE
Spl-token importing

### ISSUE THREAD

**Issue by AntoineMarcel** [solana-labs/solana-program-library#3228]
Hey ! For javascript browser we can import @solana/web3.js thanks to 
<script src="https://unpkg.com/@solana/web3.js@latest/lib/index.iife.js"></script>
but what is the equivalent for @solana/spl-token ? 
I don't use Node for my website and need to keep include javascript like that.

Thanks

**Comment by joncinque** [comment]
There is no browser-compatible import available for spl-token, and we don't have any plans to provide one right now.  You'll need to configure your own build to package everything together.

If you need to do this, however, you can copy something very similar to the rollup configuration for the stake-pool JS package: https://github.com/solana-labs/solana-program-library/blob/master/stake-pool/js/rollup.config.js and then run the build like in https://github.com/solana-labs/solana-program-library/blob/6b5e7cbbeb0fa9fe6448115d6c5fc83a75fc473c/stake-pool/js/package.json#L6
