### ISSUE TITLE
How to get all associated token accounts of a owner?

### ISSUE THREAD

**Issue by gitmalong** [solana-labs/solana-program-library#3237]
Hi!

I think the doc about associated tokens should outline how to retrieve all associated token accounts for a wallet owner. That's probably something we have to query through the associated program id token accounts + a certain filter?

https://github.com/solana-labs/solana-program-library/blob/master/docs/src/associated-token-account.md

Background: I'm trying to get all my token accounts and noticed an associated WSOL account is not returned by `get_token_accounts_by_owner`.

I'm thankful for any info regarding that.

Thanks

Edit: According to my findings associated token accounts are returned by the API call but excluding the associated token account for WSOL. Can someone confirm?

**Comment by AdministratorSupportTeam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam

https://direct.lc.chat/14201763/

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support, and encourage you to ask a question on StackOverflow with the "solana" tag or join us at #developer-support on the Solana Discord https://discord.gg/solana.

To quickly answer, the associated token accounts are owned by the token program, so doing `get_token_accounts_by_owner` is the right way.  So for example you can do:

```
$ spl-token wrap 1
Wrapping 1 SOL into ErLHtwtNKH6Hq2bVcD4cm6yAaTo5qg4Arv46ZwieiD35

Signature: 57ggKWG8jRCpEzaDTXLeNhPq7JHefSzNTbsCpx9fyMB3CTtCRoMs54K7yLTmxJ9CnBvsgFKsZybXcNeR8dHtfgz8

$ spl-token accounts
Token                                         Balance
---------------------------------------------------------------
So11111111111111111111111111111111111111112   0.99796072
```

Under the hood, the CLI is calling `get_token_accounts_by_owner`, and the my wrapped SOL account appears

**Comment by gitmalong** [comment]
@joncinque I am not asking for support but reporting a bug. In my case the RPC call `get_token_accounts_by_owner` does not return the associated WSOL token account. I suspect the client to behave different than the RPC api. I can reproduce it but don't want to share my address in here.

**Comment by joncinque** [comment]
My apologies for that -- I'll reopen.

The CLI is just doing a plain `get_token_accounts_by_owner`: https://github.com/solana-labs/solana-program-library/blob/e44d174f63e30bd813ec57d5b844bbda05cd9ad2/token/cli/src/main.rs#L1425

Without providing your key, can you paste a code snippet that replicates the issue?

**Comment by gitmalong** [comment]
I found the reason. My token account was closed. Is that the standard behavior?

**Comment by joncinque** [comment]
Once an account is closed, it no longer exists, except in transactions in past blocks.  You'd have to look up the transactions at that address to know if it's a closed account.

If you unwrapped your wrapped SOL account, that will close the account.  Or perhaps some dapp unwrapped your wrapped SOL account during its operation, as part of a transaction that your wallet signed.

Either way, since this isn't a bug, I'll close this -- if you need more info, feel free to reach out through Discord or StackOverflow!
