### ISSUE TITLE
token-js: getAssociatedTokenAddress() returning wrong address

### ISSUE THREAD

**Issue by Jumperlow** [solana-labs/solana-program-library#3246]
Hi all,

I'm trying to get token-js library in NodeJS to work but I'm having a little trouble.
For some reason the getAssociatedTokenAddress() function returns the wrong token address. 
The strange thing is; it only does this on a small subset (1-2%) of the tokens I've tried.

This is the error message I'm getting when executing the follow code.
Code:
```
const {
    Connection,
    PublicKey
} = require("@solana/web3.js");
const {
    Token,
    TOKEN_PROGRAM_ID,
    ASSOCIATED_TOKEN_PROGRAM_ID,
} = require('@solana/spl-token');

(async () => {
    const connection = new Connection(
        "https://api.mainnet-beta.solana.com",
        "confirmed"
    );
    
    const associatedAddress = await Token.getAssociatedTokenAddress(
        ASSOCIATED_TOKEN_PROGRAM_ID,
        TOKEN_PROGRAM_ID,
        new PublicKey("token"),
        new PublicKey("wallet")
    );
    console.log(`token account: ${associatedAddress}`)
  
    const getbalance = await connection.getTokenAccountBalance(
        associatedAddress
    );
    const quantity = getbalance.value.amount;

    console.log(`quantity: ${quantity}`)
})();

```

Error:
```
token account: 61wo8JaAN31CRy3zhyRiaXEUEPD5vgwyuGKkeRV6oiqt
/mnt/d/token-burning/node_modules/@solana/web3.js/lib/index.cjs.js:5713
      throw new Error('failed to get token account balance: ' + res.error.message);
            ^

Error: failed to get token account balance: Invalid param: could not find account
    at Connection.getTokenAccountBalance (/mnt/d/token-burning/node_modules/@solana/web3.js/lib/index.cjs.js:5713:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /mnt/d/token-burning/test.js:25:24
```

I've checked this with multiple tokens and some tokens return the right address and some don't.
Does anyone have any idea how I can tackle this problem?

**Comment by valentynkvasov** [comment]
Check it out https://yihau.github.io/solana-web3-demo/tour/create-token-account.html

I assume, you missed console.log(`token account: ${associatedAddress.toBase58()}`) instead of console.log(`token account: ${associatedAddress}`)

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support, and encourage you to ask a question on StackOverflow with the "solana" tag, or join us on Discord at #developer-support https://discord.gg/solana

Really quickly, the error says that there's no account at that address -- you're trying to get the balance on an account that hasn't been created, so that will give you `Invalid param: could not find account`.  The actual address derivation should still be correct.
