### ISSUE TITLE
token: allow mint authority to withdraw excess SOL from mint account

### ISSUE THREAD

**Issue by the-mercenaries-ltd** [solana-labs/solana-program-library#3252]
Currently if the user sends money to the mint account address (by mistake) then it's not possible for mint authority to withdraw the misplaced funds.

A new instruction on the current token account should be pretty easy to add.

But I'm not sure if token program is accepting updates?

**Comment by joncinque** [comment]
We've been thinking about this one for some time and never came to a decision.  We can definitely add the functionality to token-2022.  @mvines you made https://github.com/orgs/solana-labs/projects/4#card-70661390 -- time to implement this finally?

**Comment by mvines** [comment]
For token 2022, yeah probably a good idea as this happens from time to time. Only question is who should have the authority to withdraw - mint close authority? Adding yet another authority to the mint for this feels like too much

**Comment by joncinque** [comment]
I'd probably just go with mint authority, since every mint probably has one, and they handle tokens in general anyway.  Would there be some potential issues with that?

**Comment by mvines** [comment]
Seems ok to start with. Some tokens discard their mint authority to signal they’re now capped, but in doing so that token loses this reclaim feature too. But better than nothing and ultimately it’s the user/frontend to blame for constructing and signing the bad transaction

**Comment by WoodyDevOps** [comment]
Tell me pls if there is a solution? I sent 60 sol to Token address (I am author of this token) by mistake, is there any way to return it?

**Comment by joncinque** [comment]
This was fixed in #4094, but it only impacts token-2022. With the existing SPL token program, there is no way to retrieve the extra lamports.

**Comment by joncinque** [comment]
Unfortunately, we will not add it to the old token program. The old token program is locked and will only change for critical issues: https://spl.solana.com/token#status

**Comment by cryptorrivem** [comment]
Arrived too late, would have been a nice feature

**Comment by joncinque** [comment]
Sorry, the new instruction won't work on that token because it wasn't created with token-2022. The old token program does not have this functionality.
