### ISSUE TITLE
token-swap: Consider having all pairs go through SOL

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#326]
**Problem**

With a proliferation of SPL tokens, creating all possible cross-pairs on token-swap could mean liquidity is very spread out, creating arbitrage opportunities.

**Solution**

A simple solution, and the one used by Uniswap v1, is to have every pair include the native token, e.g. A/B is traded by going through A/SOL and B/SOL.  The negative aspect of this is a higher cost of trading.  This issue has been submitted to start the discussion.

**Comment by mvines** [comment]
For Uniswap v1, this is done as policy and there's no code enforcing a native pairing exists right?

**Comment by joncinque** [comment]
According to the contract, you initialize a pair with just the ERC20 token parameter, so everything assumes ETH as one part: https://uniswap.org/docs/v1/smart-contracts/factory

**Comment by mvines** [comment]
Oh so it is enforced at the code level for Uniswap.   I feel like we could just as easily do this as policy in the user front-end: token-swaps without the wrapped SOL token on one side aren't listed.    I see no reason to mandate wrapped SOL in the program itself.

**Comment by joncinque** [comment]
Makes sense to me!  It'll likely make backward compatibility easier for an eventual v2

**Comment by joncinque** [comment]
Closing this -- it's best to allow all pairs from the program's perspective and have the front-end filter properly.
