### ISSUE TITLE
token-js: Support `UiAmountToAmount` and `AmountToUiAmount` instructions

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#3264]
#### Problem

As part of token-2022, we added new instructions to convert both ways between amount and ui amount, but there's no support for them in JS.  For reference:

* https://github.com/solana-labs/solana-program-library/blob/056948bbd1d40c240bcdecb78cee3afeb9903ede/token/program-2022/src/instruction.rs#L477-L490
* https://github.com/solana-labs/solana-program-library/blob/056948bbd1d40c240bcdecb78cee3afeb9903ede/token/program-2022/src/instruction.rs#L491-L502

#### Solution

Add implementations for these instructions with corresponding actions.

**Comment by atharmohammad** [comment]
I would like to work on this.

**Comment by joncinque** [comment]
@atharmohammad Go for it!

**Comment by atharmohammad** [comment]
@joncinque  I have some doubts -- we need to add implementation of these instructions in js , something like here (https://github.com/solana-labs/solana-program-library/blob/master/token/js/src/instructions/approve.ts) and actions for these instructions something like here (https://github.com/solana-labs/solana-program-library/blob/master/token/js/src/actions/approve.ts), if i am on right path, i am confused how i would get the converted amount after making transaction , i am not able to find proper docs for ```sol_get_return_data``` or something.

**Comment by joncinque** [comment]
Ah yes, thanks for reaching out, this will be a more interesting issue! You'll need to:

in web3.js:
* add the return data to the `SimulatedTransactionResponse` type in web3.js, similar to `RpcTransactionReturnData` in the `solana-client` library
* populate the field during `Connection.simulateTransaction`

in spl-token:
* have the "action" implementation for each instruction simulate the transaction, and pull out the return data from the `SimulatedTransactionResponse` as a number or string, as appropriate

Be sure to add tests for each library!
