### ISSUE TITLE
Remove import syntax from @solana/spl-memo javascript lib

### ISSUE THREAD

**Issue by alexandr-kazakov** [solana-labs/solana-program-library#3286]
This lib https://www.npmjs.com/package/@solana/spl-memo doesn't work with **require** NodeJS method, because it use the **import** syntax. I suggest make it via commonjs style, as now working in @solana/web3.js and @solana/spl-token libs.

**Comment by jordansexton** [comment]
Yeah, this is a good callout, we should ship ESM and CJS builds.

**Comment by jordansexton** [comment]
@alexandr-kazakov would you consider opening a PR to change the package.json / tsconfig setup to match the SPL token lib?

**Comment by alexandr-kazakov** [comment]
I looked other JS libs here and I saw what two versions being created: commonjs and es modules. Example: https://github.com/solana-labs/solana-program-library/blob/57c5fd80f60ed4d6053989e64882f9002e352910/token/js/package.json#L21-L24
Probably in the JS memo lib we need to use the same approach. I will try to do it later, if no one does it before.

**Comment by jordansexton** [comment]
Yeah, exactly. We use the TypeScript compiler with different configs to build them. It should work to copy paste the same setup from Token to Memo.
