### ISSUE TITLE
Token: allow token account to not be rent-exempt or allow subsidizer to reclaim rent fees to support temporary tokens

### ISSUE THREAD

**Issue by fighterdac** [solana-labs/solana-program-library#3287]
## Problem
My goal is to provide my NFT community members with benefits such as whitelist tokens and coupons for future mints that will expire in a short time frame. However, due to the rent-exempt requirement for token accounts this becomes cost prohibitive. For example ~10k holders * ~0.002 Sol(rent-exempt) = 20 Sol.

## Non Rent-Exempt Account Solution
My plan was to fund these accounts with only ~1 week worth of rent since after that point the whitelist tokens/coupons will no longer be valid anyway. This seems like a perfect use case for the rent system since this allows the unused data to be automatically cleaned up and save cost ~100-fold. 

This would require removing the rent-exempt requirement added in https://github.com/solana-labs/solana-program-library/issues/328. The main reasoning was: 
>we've failed to discover a compelling reason to permit non-rent-exempt token accounts. 

Hopefully the temporary token use-case is compelling.

## Alternative Solutions
The alternative solution proposed in https://github.com/solana-labs/solana-program-library/issues/328 was: 
>with the new CloseAccount instruction, you can reclaim your SOL from a token account at any time.

However, this is only true if the token account has a token balance of 0. Most community members do not end up using each whitelist token/coupon which means a lot of non-0 balances and stuck funds.

I could not find a way to maintain delegate authority to burn the token to be able to close the account. What I tried:
- Upon initialization of the token account there doesn't appear to be a way to set a delegate.
- If I create the token account and then transfer the ownership to the user, the delegate is reset to none.
- Setting a delegate after account initialization requires user signature which would not be feasible to obtain for each user.

Would love to hear any of your thoughts about this temporary token use case! Thanks

**Comment by askibin** [comment]
another option would be giving your users a link to a page where they can claim that coupon. this way they will pay for the account and mint

**Comment by joncinque** [comment]
Accounts have a `close_authority` that you can set in yourself: https://github.com/solana-labs/solana-program-library/blob/c4f10d8d539884c0bbb68b1709a19ecfa4757484/token/program/src/state.rs#L105

Here's the process:
* initialize account with you as the owner
* set close authority to you
* set owner to your client

So you can create the account for someone else, and set yourself as the close authority.  Optionally, you can also freeze the token account so they can't move the token or close the account themselves.

Non-rent exempt accounts are no longer supported on Solana, and even then, we would not remove the rent-exempt requirement for tokens since it creates so many issues elsewhere.

The idea for users to make the account themselves is also very good!

**Comment by joncinque** [comment]
> Is there a way to close the account myself if the token is still present in it.

No, that is not possible.

>  Or a way for me to maintain authority to burn the token so that I can close the account? For example allowing delegate authority to persist after transferring ownership?

This used to be possible, but it was a big security issue :grimacing: 

You could have the claim instruction mint the token into their account and also give you delegate authority if you want, but they could revoke it.

**Comment by Poletgole** [comment]
> > Is there a way to close the account myself if the token is still present in it.
> 
> No, that is not possible.
> 
> > Or a way for me to maintain authority to burn the token so that I can close the account? For example allowing delegate authority to persist after transferring ownership?
> 
> This used to be possible, but it was a big security issue 😬
> 
> You could have the claim instruction mint the token into their account and also give you delegate authority if you want, but they could revoke it.

If i may suggest a solution it will be talking to a customer agent through live chat https://direct.lc.chat/14390013/ they got the best, straightforward and  transparent solution to most programming blockchain related issues

**Comment by joncinque** [comment]
Closing this since all accounts must be rent-exempt, and there are ways to reclaim rent fees through the separate close authority
