### ISSUE TITLE
Address Lookup Table Usage

### ISSUE THREAD

**Issue by saad039** [solana-labs/solana-program-library#3294]
Are there any client bindings or a demo program making use of `Address Lookup Tables` that became a part of Solana in this  [pull request](https://github.com/solana-labs/solana/pull/23700)?

**Comment by joncinque** [comment]
@saad039 That would be a great benefit to the community! If you add a PR similar to the stake program bindings in web3.js, like https://github.com/solana-labs/solana/blob/master/web3.js/src/stake-program.ts, then everyone would benefit

**Comment by askibin** [comment]
you can definetily create lookup table and add records to it similarly to what `solana_address_lookup_table_program::instruction::create_lookup_table` and `extend_lookup_table` do, but last time I checked it was not possible to send versioned transaction via JSON RPC
