### ISSUE TITLE
No C introspection library for Token instructions

### ISSUE THREAD

**Issue by garious** [solana-labs/solana-program-library#33]
#### Problem

People creating currencies with Token will want Ledger Wallet support. To get there, the Ledger Wallet app will need to parse Token instructions. It's easiest in C, though Rust is technically possible. Here's how we parse System, Stake, etc:

https://github.com/solana-labs/ledger-app-solana/tree/master/libsol

#### Proposed Solution

Add an equivalent to `libsol` for Token instructions.

cc: @jackcmay @t-nelson

**Comment by jackcmay** [comment]
@t-nelson the C bindings for Token are in (#48), how would you like these to be communicated/linked with Ledger Wallet app?

**Comment by jackcmay** [comment]
@t-nelson Ping

**Comment by t-nelson** [comment]
> @t-nelson Ping

@jackcmay Whoops!  Sorry, I missed your initial comment.

How do we plan on releasing the C bindings?

One thing I notice missing is some sort of versioning symbol.  Is that something cbindgen can generate for us?

**Comment by jackcmay** [comment]
@t-nelson Version added in https://github.com/solana-labs/solana-program-library/commit/f08326006b00b655ff51287b41c498e529f2851e

How would you like these binding to be shared with the ledger wallet?

**Comment by t-nelson** [comment]
@jackcmay are we planning to publish the bindings separately from the crate?  If not and we don't have any other consumers, I'd just as soon take a copy from the crate.  Welcome to suggestions though!

**Comment by jackcmay** [comment]
Copy from the crate is probably fine since they are versioned.  Might also be a good idea to put in the program id of the token program that corresponds to this program

**Comment by t-nelson** [comment]
> Copy from the crate is probably fine since they are versioned.
WFM! :+1: 

> Might also be a good idea to put in the program id of the token program that corresponds to this program

:100:

Can cbindgen output the byte string as a preprocessor macro?  So far, I've been handling the program IDs like [this](https://github.com/solana-labs/ledger-app-solana/blob/09fd327e1d7d433221404734ffd8188aa992d4ca/libsol/common_byte_strings.h#L36-L44) to facilitate test writing

**Comment by jackcmay** [comment]
@t-nelson I don't have high hopes that we can do that given my past efforts
