### ISSUE TITLE
Not able to update token image , name and SYMBOL (basically any information)

### ISSUE THREAD

**Issue by danilogiles** [solana-labs/solana-program-library#3302]
I tried to merge the json but I`m getting the following message.
This repository has been archived by the owner. It is now read-only.

Neither strata or token creator, none of them worked as well, can somebody provide me a solution or a simple guide on how to do that?

thanks,

**Comment by jordansexton** [comment]
I think you're in the wrong repo! This isn't a Strata repo, and the token list isn't managed here either.
