### ISSUE TITLE
Ship first token2 crate and upgrade the monorepo with it

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana-program-library#331]
Replace the token1 usage in master/v1.3/v1.2 with token2.   We don't need to retain backwards compatibility with token1

**Comment by CriesofCarrots** [comment]
Steps remaining:
- [ ] Upgrade monorepo
- [ ] Tag SPL release
- [ ] Deploy program to clusters

**Comment by CriesofCarrots** [comment]
Still needs deployment to devnet and testnet, when they are up

**Comment by mvines** [comment]
oops 👍

**Comment by mvines** [comment]
devnet is up now, for now...

**Comment by CriesofCarrots** [comment]
Devnet is deployed! https://explorer.solana.com/address/TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA?cluster=devnet

**Comment by CriesofCarrots** [comment]
Testnet is deployed: https://explorer.solana.com/address/TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA?cluster=testnet
