### ISSUE TITLE
token-program-2022 incorrect program id

### ISSUE THREAD

**Issue by acheroncrypto** [solana-labs/solana-program-library#3317]
Native mint's program id change in #2893 causes `wrap` command cli to fail with `InstructionError::IncorrectProgramId`.

[Problematic line 1](https://github.com/solana-labs/solana-program-library/blob/3afe1e652b8d4c497e78bed37f437d3a30430610/token/cli/src/main.rs#L1112)
[Problematic line 2](https://github.com/solana-labs/solana-program-library/blob/master/token/cli/src/main.rs#L1119)
[Problematic line 3](https://github.com/solana-labs/solana-program-library/blob/master/token/cli/src/main.rs#L1141)

Either reverting the program id change in [native_mint.rs](https://github.com/solana-labs/solana-program-library/blob/master/token/program-2022/src/native_mint.rs) or changing these lines with the old pubkey `So11111111111111111111111111111111111111112` fixes the current issue until the new token program is deployed.

**Comment by mvines** [comment]
The token cli just needs to be modified to be aware of token 2022's native mint id

**Comment by acheroncrypto** [comment]
I'm implementing token cli for wasm and I was using token 2022's native mint but I've just realized token cli is still using old token program's native mint https://github.com/solana-labs/solana-program-library/blob/master/token/cli/src/main.rs#L49
