### ISSUE TITLE
Upgrade @solana/spl-token npm package to support token2

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana-program-library#332]
Retaining backwards compatibility with token1 is not a requirement.

**Comment by mvines** [comment]
Opps, we're not quite done here.   The js tests don't pass in CI:

STR: apply the below patch and run `ci/script.sh`:
```diff
diff --git a/ci/script.sh b/ci/script.sh
index 082cfad..475c092 100755
--- a/ci/script.sh
+++ b/ci/script.sh
@@ -69,12 +69,12 @@ js_token() {
   tsc module.d.ts || exit $?
 
   # TODO: Uncomment when resolving https://github.com/solana-labs/solana-program-library/issues/332
-  # npm run cluster:localnet || exit $?
-  # npm run localnet:down
-  # npm run localnet:update || exit $?
-  # npm run localnet:up || exit $?
-  # time npm run start || exit $?
-  # npm run localnet:down
+  npm run cluster:localnet || exit $?
+  npm run localnet:down
+  npm run localnet:update || exit $?
+  npm run localnet:up || exit $?
+  time npm run start || exit $?
+  npm run localnet:down
 }
 _ js_token
```

**Comment by jstarry** [comment]
@mvines looks like the issue is that spl-token program isn't working properly with solana-sdk v1.3.6. The tests pass fine before the latest commit.

Here are the logs when testing the spl-token with v1.3.6
```
[2020-08-30T03:21:15.385060500Z INFO  solana_runtime::message_processor] BPF program 6GoJEUmgFmGJfNvjiLNkFKLLkrrkfNEdp7nrWYG99qPB failed: out of bounds memory load (insn #22638), addr 0x400002860/8 
                                                        regions: 
    0x300000000-0x300007fff 
    0x200000000-0x200000fff 
    0x200002000-0x200002fff 
    0x200004000-0x200004fff 
    0x200006000-0x200006fff 
    0x200008000-0x200008fff 
    0x20000a000-0x20000afff 
    0x20000c000-0x20000cfff 
    0x20000e000-0x20000efff 
    0x200010000-0x200010fff 
    0x200012000-0x200012fff 
    0x200014000-0x200014fff 
    0x200016000-0x200016fff 
    0x200018000-0x200018fff 
    0x20001a000-0x20001afff 
    0x20001c000-0x20001cfff 
    0x20001e000-0x20001efff 
    0x200020000-0x200020fff 
    0x200022000-0x200022fff 
    0x200024000-0x200024fff 
    0x200026000-0x200026fff 
    0x400000000-0x40000018d 
    0x100036bc0-0x1000386b4 
    0x1000386b8-0x100038753 
    0x100038828-0x10003955f 
    0x1000000e8-0x100036baf
```

Also, I think we will need to setup CI so that JS bindings are tested against the currently deployed token program on mainnet to ensure that we don't accidentally make it incompatible

**Comment by jstarry** [comment]
I'm imagining a `v2` branch that locks spl-token at v2.0.3 and then any JS changes from master can be backported there. Then, we can bump token-js in master up a minor or major version to prevent breaking semver for any new releases for token3 support. Not sure about how this would affect memo and token-swap though

**Comment by mvines** [comment]
localnet will come with the deployed program now, via https://github.com/solana-labs/solana/blob/master/fetch-spl.sh#L40
We could run the js tests against both the deployed program and the locally built version to entire the latest solana-sdk crates haven't introduced a regression.

**Comment by jstarry** [comment]
That sounds good, we will still probably need to branch at some point when we start work on token3 but I guess that's a future problem?

**Comment by mvines** [comment]
I don't think we need a branch, we'd manage that like we did with `token/program/` and `token/program2/`,  before we collapsed them.   `token/program/` might still change to adapt to future sdk changes or client-side bug fixes but no program changes, and `token/program2/` is the the next version of the program.   The rest of token/, cli and js, can then support both programs
