### ISSUE TITLE
[spl-token] There is no bundled build of the typescript package for 0.2.0

### ISSUE THREAD

**Issue by fschr** [solana-labs/solana-program-library#3323]
In previous releases of @solana/spl-token, and in releases of @solana/web3.js, a fully bundled script that you can use with `<script>` tags is part of the release. Such a file is missing from @solana/spl-token version 0.2.0.

**Comment by jordansexton** [comment]
We don't use a build tool for the library, only compiling it from TypeScript to JS. Building for the browser, including any polyfills, is left up to consumers of the library.
