### ISSUE TITLE
stake-pool-py: Support add / update metadata for pool token

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#3370]
#### Problem

#3335 added new instructions to the stake pool, to add and update token metadata, but this is not supported in python.

#### Solution

Add support for these instructions in the python bindings.

**Comment by gnapoli23** [comment]
Hello, i would like to take this :) Can you give me some guidance? Thanks :)

**Comment by joncinque** [comment]
Hi there, I would love to!! The whole idea is to add instruction creators , actions, and tests for these two new instructions for creating and updating token metadata.

For example, here's the instruction for depositing sol into the stake pool in python: https://github.com/solana-labs/solana-program-library/blob/6ab15b340e74735b7cd47d75a80f531152ce0a0e/stake-pool/py/stake_pool/instructions.py#L736-L761

Compared with its Rust implementation https://github.com/solana-labs/solana-program-library/blob/6ab15b340e74735b7cd47d75a80f531152ce0a0e/stake-pool/program/src/instruction.rs#L1396-L1428

So now you need to create the python version of https://github.com/solana-labs/solana-program-library/blob/6ab15b340e74735b7cd47d75a80f531152ce0a0e/stake-pool/program/src/instruction.rs#L1703-L1736

and

https://github.com/solana-labs/solana-program-library/blob/6ab15b340e74735b7cd47d75a80f531152ce0a0e/stake-pool/program/src/instruction.rs#L1671-L1699

Along with some tests to create and update the metadata. You can find the deposit sol python tests at https://github.com/solana-labs/solana-program-library/blob/master/stake-pool/py/tests/test_deposit_withdraw_sol.py

**Comment by gnapoli23** [comment]
@joncinque Thank you for the explanation, i'll take a look at sources and ping you if i need further assistance. Thanks!

**Comment by gnapoli23** [comment]
Hey @joncinque i started to work on it as you can see, should i open a draft PR and start discussing about the implementation? Let me know 👍🏻

**Comment by joncinque** [comment]
@gnapoli23 yes please! The sooner there's some code, the sooner you can get some feedback :smile:

**Comment by gnapoli23** [comment]
@joncinque Linked #3978 draft PR to this. Could you start to give it a look? Thanks.
