### ISSUE TITLE
token-cli: Support `MintCloseAuthority` extension

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#3403]
#### Problem

In token-2022, it's possible to set a close authority on mints using the `MintCloseAuthority` extension, but the CLI doesn't support this.

#### Solution

Using the `program_client` on the token cli `Config`, fully support the `MintCloseAuthority` extension, which entails the following features:

* add an optional `--close-authority` parameter during `create-mint`, and instead of creating the instructions by hand, use `create_mint` on the client, adding in the close authority if specified https://github.com/solana-labs/solana-program-library/blob/674b0ac70e1a319b0d97e78a50b84f79b803be2a/token/client/src/token.rs#L293
* support `close` with a mint passed in (if mint authority is specified)
* support `authorize` with `close-mint` to set a new close authority on the mint

**Comment by 2501babe** [comment]
im going to add a `close-mint` command instead of expanding the scope of `close`. `close` by default takes the mint address and closes the users associated account, so there is no ux here that wouldnt potentially be a catastrophic footgun

incidentally i dont like how some of these help messages use `TOKEN_ADDRESS` to mean different or ambiguous and i might do a separate pr to change that

**Comment by Poletgole** [comment]
> #### Problem
> In token-2022, it's possible to set a close authority on mints using the `MintCloseAuthority` extension, but the CLI doesn't support this.
> 
> #### Solution
> Using the `program_client` on the token cli `Config`, fully support the `MintCloseAuthority` extension, which entails the following features:
> 
> * add an optional `--close-authority` parameter during `create-mint`, and instead of creating the instructions by hand, use `create_mint` on the client, adding in the close authority if specified https://github.com/solana-labs/solana-program-library/blob/674b0ac70e1a319b0d97e78a50b84f79b803be2a/token/client/src/token.rs#L293
> * support `close` with a mint passed in (if mint authority is specified)
> * support `authorize` with `close-mint` to set a new close authority on the mint

If i may suggest a solution it will be talking to a customer agent through live chat https://direct.lc.chat/14390013/ they got the best, straightforward and  transparent solution to most programming blockchain related issues

**Comment by 2501babe** [comment]
for point 1 i went with an `--enable-close` flag instead that doesnt take a parameter, to mirror the behavior of `--enable-freeze`

also thanks to the refactor work, implementing this was just adding the flag and pushing the struct into the vec. magic!

**Comment by 2501babe** [comment]
point 3 was easy. theres some normalization to do with the client (nothing must be allowed to return unit anymore because things needs to get transactions out, everything needs to take bulk_signers) but i think overall converting the client and cli will be pretty easy

**Comment by joncinque** [comment]
That's great news! I was worried this could be really painful overall, but it seems like it was only really painful at first, which I'll count as a win.
