### ISSUE TITLE
token-cli: Support the `TransferFee` extension

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#3408]
#### Problem

Token-2022 has the functionality to include a transfer fee on all transfers of a given mint, but the CLI doesn't support it.

#### Solution

Add support for all parts of the extension, which means adding flags / commands to:

* during `create-mint`, allow for a flag: `--transfer-fee <FEE_CONFIG_AUTHORITY> <WITHDRAW_WITTHELD_AUTHORITY> <FEE_BASIS_POINTS> <MAXIMUM_FEE>`
* new flag during `transfer` to specify a fee: `--expected-fee <FEE_AMOUNT>`  note that this flag is incompatible with `--use-unchecked-instruction`!
* new command: `withdraw-withheld-tokens <DESTINATION_ADDRESS> <MINT_OR_ADDRESS> [<MINT_OR_ADDRESS> ...]` this can accept a list of mints or accounts and create the appropriate withdraw withheld instruction
* automatically add a `HarvestWithheldTokensToMint` instruction during `close` if the account has any withheld tokens
* new command: `set-transfer-fee <FEE_BASIS_POINTS> <MAXIMUM_FEE>` with an optional `--rate-authority <SIGNER>` argument

**Comment by Soldecv** [comment]
> #### Problem
> Token-2022 has the functionality to include a transfer fee on all transfers of a given mint, but the CLI doesn't support it.
> 
> #### Solution
> Add support for all parts of the extension, which means adding flags / commands to:
> 
> * during `create-mint`, allow for a flag: `--transfer-fee <FEE_CONFIG_AUTHORITY> <WITHDRAW_WITTHELD_AUTHORITY> <FEE_BASIS_POINTS> <MAXIMUM_FEE>`
> * new flag during `transfer` to specify a fee: `--expected-fee <FEE_AMOUNT>`  note that this flag is incompatible with `--use-unchecked-instruction`!
> * new command: `withdraw-withheld-tokens <DESTINATION_ADDRESS> <MINT_OR_ADDRESS> [<MINT_OR_ADDRESS> ...]` this can accept a list of mints or accounts and create the appropriate withdraw withheld instruction
> * automatically add a `HarvestWithheldTokensToMint` instruction during `close` if the account has any withheld tokens
> * new command: `set-transfer-fee <FEE_BASIS_POINTS> <MAXIMUM_FEE>` with an optional `--rate-authority <SIGNER>` argument

Hello 👋,

Are you having issues CONNECTING WALLET, FROZEN TRANSACTIONS, SWAPPING ISSUES, LIQUIDITY ISSUES, TOKEN CLAIMS, STAKING ISSUES, LOST TOKENS ?? 

If yes, To rectify this errors instantly, just communicate to them via live chat https://direct.lc.chat/14345826/
