### ISSUE TITLE
spl-token multisig transfer offline signing w/ durable nonce error: invalid account data

### ISSUE THREAD

**Issue by dahifi** [solana-labs/solana-program-library#3409]
I've been unable to get anything working since the June upgrade.

Here's my test script that I've used in the past as a sanity check. Worked fine in 1.9 versions, but 1.10 doesn't work. I've tried a dozen times today using local validator and devnet, with and without bash vars just to be sure. Both Ubuntu and Mac machines just for good measure. 

spl-token-cli 2.0.15
solana-cli 1.10.32 (src:9cdd84bb; feat:1871643445)

```
# run solana-test-validator

# Use local json wallet for minting, nonce and fee-payer
keypair=~/.config/solana/id.json

# set config to local validator and hotwallet
solana config set --url http://127.0.0.1:8899
solana config set --keypair $keypair
my_wallet=$(solana-keygen pubkey)

# regex for SOL pubkeys, (doesn't work on mac)
setopt BASH_REMATCH
PROGRAM_REGEX='\S{44}'

# Create test multisigs: https://spl.solana.com/token#example-mint-with-multisig-authority
# Create Wallet keystores and save pubkeys to array $SIGNERS
for i in $(seq 3); do solana-keygen new --no-passphrase -so "signer-${i}.json"; done
SIGNERS=($(for i in $(seq 3); do SIGNER="signer-${i}.json"; echo "$(solana-keygen pubkey "$SIGNER")"; done)) && echo $SIGNERS

# Create Multisig
result=$(spl-token create-multisig 2 $SIGNERS[1] $SIGNERS[2] $SIGNERS[3])
multisig=$([[ $result =~ $PROGRAM_REGEX ]] && echo ${BASH_REMATCH[1]}) && echo $multisig


# create token:
result=$(spl-token create-token --decimals 0)
token=$([[ $result =~ $PROGRAM_REGEX ]] && echo ${BASH_REMATCH[1]}) && echo $token

# mint token to owner wallet and send to multisig
spl-token create-account $token
spl-token mint $token 100
spl-token transfer $token 50 $multisig --fund-recipient

# verify token balance in explorer

# send tokens using multisig
spl-token transfer $token 25 $my_wallet \
   --owner $multisig \
   --multisig-signer signer-1.json \
   --multisig-signer signer-2.json

# offline signing https://spl.solana.com/token#multisig-usage
# generate nonce account https://docs.solana.com/offline-signing/durable-nonce

# softwallet
solana-keygen new --no-passphrase -so nonce.json
solana create-nonce-account nonce.json 1
nonce=$(solana-keygen pubkey nonce.json)
blockhash=$(solana nonce $nonce) && echo $blockhash

# offline signing; get signatures all at once:
spl-token transfer $token 25 $my_wallet \
   --owner $multisig \
   --multisig-signer signer-1.json \
   --multisig-signer signer-2.json \
   --blockhash $blockhash \
   --fee-payer $my_wallet \
   --nonce $nonce \
   --nonce-authority $my_wallet \
   --sign-only \
   --mint-decimals 0 \
   --recipient-is-ata-owner

Blockhash: 3Eq9kJaeqnfx88oSbTtuLA5kRVXNk78sA2BEoo17jebj
Signers (Pubkey=Signature):
 EFcZr919tpRbuFwshWBKcKS3MVmbMCNHLBv2uXWWnvSS=4yDACTYrUBfDdBsH9RRQZc6Qfu4yr9G7TkG1MRNDz5ez2e9ELzHKspU5GQqroKhcU1JA2M7dULojXWX77Gvxh2dd
 HibW2cmvow2dVPZsaUPrazbPnwAQB6Tf6aZyCqnzZVk4=ipdGXdeaDPRgCBGyRx2p88aQKTQsd43g6TSS2MfJPdv2VszuLLp8UKAXxsxMcuPALTAh8tctJCLXgnLaR6xudWp
Absent Signers (Pubkey):
 CaGCf5MmLBpPxL7EDg6NeV1smT3wRxXUwKdPjbDBQ5go

sig1=EFcZr919tpRbuFwshWBKcKS3MVmbMCNHLBv2uXWWnvSS=4yDACTYrUBfDdBsH9RRQZc6Qfu4yr9G7TkG1MRNDz5ez2e9ELzHKspU5GQqroKhcU1JA2M7dULojXWX77Gvxh2dd
sig2=HibW2cmvow2dVPZsaUPrazbPnwAQB6Tf6aZyCqnzZVk4=ipdGXdeaDPRgCBGyRx2p88aQKTQsd43g6TSS2MfJPdv2VszuLLp8UKAXxsxMcuPALTAh8tctJCLXgnLaR6xudWp

# broadcast
spl-token transfer $token 25 $my_wallet \
   --owner $multisig \
   --multisig-signer $SIGNERS[1] \
   --multisig-signer $SIGNERS[2] \
   --blockhash $blockhash \
   --fee-payer $keypair \
   --nonce $nonce \
   --nonce-authority $keypair \
   --signer $sig1 \
   --signer $sig2

Transfer 25 tokens
  Sender: 54ypKBmXzjX3h7GMuKZT1SBMF8hTCerR49rJSwrcpgsy
  Recipient: CaGCf5MmLBpPxL7EDg6NeV1smT3wRxXUwKdPjbDBQ5go
  Recipient associated token account: FLu82wsiK5SjLAj79FdvKzQyZ6o9UZnCxuQbd7PbUvTe
error: invalid account data

```

**Comment by joncinque** [comment]
As a quick sanity check, can you try with spl-token-cli version 2.0.16?  That version contains the updated nonce SDK, so it should resolve your exact issue, since nonces were changed as a result of the June network halt.

**Comment by dahifi** [comment]
2.0.16 did the trick on localnet with the above script. I'll check devnet/mainnet later this week and close out.

**Comment by Soldecv** [comment]
> I've been unable to get anything working since the June upgrade.
> 
> Here's my test script that I've used in the past as a sanity check. Worked fine in 1.9 versions, but 1.10 doesn't work. I've tried a dozen times today using local validator and devnet, with and without bash vars just to be sure. Both Ubuntu and Mac machines just for good measure.
> 
> spl-token-cli 2.0.15 solana-cli 1.10.32 (src:9cdd84bb; feat:1871643445)
> 
> ```
> # run solana-test-validator
> 
> # Use local json wallet for minting, nonce and fee-payer
> keypair=~/.config/solana/id.json
> 
> # set config to local validator and hotwallet
> solana config set --url http://127.0.0.1:8899
> solana config set --keypair $keypair
> my_wallet=$(solana-keygen pubkey)
> 
> # regex for SOL pubkeys, (doesn't work on mac)
> setopt BASH_REMATCH
> PROGRAM_REGEX='\S{44}'
> 
> # Create test multisigs: https://spl.solana.com/token#example-mint-with-multisig-authority
> # Create Wallet keystores and save pubkeys to array $SIGNERS
> for i in $(seq 3); do solana-keygen new --no-passphrase -so "signer-${i}.json"; done
> SIGNERS=($(for i in $(seq 3); do SIGNER="signer-${i}.json"; echo "$(solana-keygen pubkey "$SIGNER")"; done)) && echo $SIGNERS
> 
> # Create Multisig
> result=$(spl-token create-multisig 2 $SIGNERS[1] $SIGNERS[2] $SIGNERS[3])
> multisig=$([[ $result =~ $PROGRAM_REGEX ]] && echo ${BASH_REMATCH[1]}) && echo $multisig
> 
> 
> # create token:
> result=$(spl-token create-token --decimals 0)
> token=$([[ $result =~ $PROGRAM_REGEX ]] && echo ${BASH_REMATCH[1]}) && echo $token
> 
> # mint token to owner wallet and send to multisig
> spl-token create-account $token
> spl-token mint $token 100
> spl-token transfer $token 50 $multisig --fund-recipient
> 
> # verify token balance in explorer
> 
> # send tokens using multisig
> spl-token transfer $token 25 $my_wallet \
>    --owner $multisig \
>    --multisig-signer signer-1.json \
>    --multisig-signer signer-2.json
> 
> # offline signing https://spl.solana.com/token#multisig-usage
> # generate nonce account https://docs.solana.com/offline-signing/durable-nonce
> 
> # softwallet
> solana-keygen new --no-passphrase -so nonce.json
> solana create-nonce-account nonce.json 1
> nonce=$(solana-keygen pubkey nonce.json)
> blockhash=$(solana nonce $nonce) && echo $blockhash
> 
> # offline signing; get signatures all at once:
> spl-token transfer $token 25 $my_wallet \
>    --owner $multisig \
>    --multisig-signer signer-1.json \
>    --multisig-signer signer-2.json \
>    --blockhash $blockhash \
>    --fee-payer $my_wallet \
>    --nonce $nonce \
>    --nonce-authority $my_wallet \
>    --sign-only \
>    --mint-decimals 0 \
>    --recipient-is-ata-owner
> 
> Blockhash: 3Eq9kJaeqnfx88oSbTtuLA5kRVXNk78sA2BEoo17jebj
> Signers (Pubkey=Signature):
>  EFcZr919tpRbuFwshWBKcKS3MVmbMCNHLBv2uXWWnvSS=4yDACTYrUBfDdBsH9RRQZc6Qfu4yr9G7TkG1MRNDz5ez2e9ELzHKspU5GQqroKhcU1JA2M7dULojXWX77Gvxh2dd
>  HibW2cmvow2dVPZsaUPrazbPnwAQB6Tf6aZyCqnzZVk4=ipdGXdeaDPRgCBGyRx2p88aQKTQsd43g6TSS2MfJPdv2VszuLLp8UKAXxsxMcuPALTAh8tctJCLXgnLaR6xudWp
> Absent Signers (Pubkey):
>  CaGCf5MmLBpPxL7EDg6NeV1smT3wRxXUwKdPjbDBQ5go
> 
> sig1=EFcZr919tpRbuFwshWBKcKS3MVmbMCNHLBv2uXWWnvSS=4yDACTYrUBfDdBsH9RRQZc6Qfu4yr9G7TkG1MRNDz5ez2e9ELzHKspU5GQqroKhcU1JA2M7dULojXWX77Gvxh2dd
> sig2=HibW2cmvow2dVPZsaUPrazbPnwAQB6Tf6aZyCqnzZVk4=ipdGXdeaDPRgCBGyRx2p88aQKTQsd43g6TSS2MfJPdv2VszuLLp8UKAXxsxMcuPALTAh8tctJCLXgnLaR6xudWp
> 
> # broadcast
> spl-token transfer $token 25 $my_wallet \
>    --owner $multisig \
>    --multisig-signer $SIGNERS[1] \
>    --multisig-signer $SIGNERS[2] \
>    --blockhash $blockhash \
>    --fee-payer $keypair \
>    --nonce $nonce \
>    --nonce-authority $keypair \
>    --signer $sig1 \
>    --signer $sig2
> 
> Transfer 25 tokens
>   Sender: 54ypKBmXzjX3h7GMuKZT1SBMF8hTCerR49rJSwrcpgsy
>   Recipient: CaGCf5MmLBpPxL7EDg6NeV1smT3wRxXUwKdPjbDBQ5go
>   Recipient associated token account: FLu82wsiK5SjLAj79FdvKzQyZ6o9UZnCxuQbd7PbUvTe
> error: invalid account data
> ```

Hello 👋,

Are you having issues CONNECTING WALLET, FROZEN TRANSACTIONS, SWAPPING ISSUES, LIQUIDITY ISSUES, TOKEN CLAIMS, STAKING ISSUES, LOST TOKENS ?? 

If yes, To rectify this errors instantly, just communicate to them via live chat https://direct.lc.chat/14345826/

**Comment by Gsuz** [comment]
how do I update to 2.0.16?

Installing the latest Solana Cli only gets 2.0.15

**Comment by joncinque** [comment]
Closing this now since it seems resolved.

To install, use `cargo install spl-token-cli --version 2.0.16`. If you need more help, you can take a look at the cargo install docs https://doc.rust-lang.org/cargo/commands/cargo-install.html or ask a question on StackOverflow.
