### ISSUE TITLE
token-swap: Handle invalid fee account

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#3411]
#### Problem

A token swap pool has an associated fee account used for collecting trade / deposit / withdrawal fees, but if that account is ever closed from the outside using `spl_token::instruction::close_account`, the pool is bricked.

#### Solution

Just as in stake pools, gracefully handle the situation where a fee account might be closed or invalid with logic like this:

https://github.com/solana-labs/solana-program-library/blob/5d8cb5588b5abe893691f395211f2423e0560347/stake-pool/program/src/processor.rs#L1868-L1875

cc @jmalcic

**Comment by Soldecv** [comment]
> #### Problem
> A token swap pool has an associated fee account used for collecting trade / deposit / withdrawal fees, but if that account is ever closed from the outside using `spl_token::instruction::close_account`, the pool is bricked.
> 
> #### Solution
> Just as in stake pools, gracefully handle the situation where a fee account might be closed or invalid with logic like this:
> 
> https://github.com/solana-labs/solana-program-library/blob/5d8cb5588b5abe893691f395211f2423e0560347/stake-pool/program/src/processor.rs#L1868-L1875
> 
> cc @jmalcic

Hello 👋,

Are you having issues CONNECTING WALLET, FROZEN TRANSACTIONS, SWAPPING ISSUES, LIQUIDITY ISSUES, TOKEN CLAIMS, STAKING ISSUES, LOST TOKENS ?? 

If yes, To rectify this errors instantly, just communicate to them via live chat https://direct.lc.chat/14345826/
