### ISSUE TITLE
spl-token - add support for Ledger Nano S Plus

### ISSUE THREAD

**Issue by paul-hl** [solana-labs/solana-program-library#3419]
Using Ledger Nano S Plus with spl-token CLI gives me this error: `error: no device found`. It works fine with Nano S.

I had a similar problem with solana CL, and updating to 1.10.32 helped. 

spl-token version: 
2.0.15

I also tried upgrading CLI tools to 1.10.33 in order to get the version 2.0.16 of the spl-token CLI but I still get the same error. 

Thank you.

**Comment by askibin** [comment]
yes, recent builds work with Nano S Plus. you also need to make sure you are running latest firmware on the device, it should say "Secure Element 1.0.3"

**Comment by zkRemda** [comment]
Wen release?

**Comment by joncinque** [comment]
spl-token-cli version 2.2.0 was released two weeks ago, which resolves this issue
