### ISSUE TITLE
Memo TS lib exports CJS only, needs to export CJS and ESM

### ISSUE THREAD

**Issue by grimAgent** [solana-labs/solana-program-library#3454]
I'm trying to use the `@solana/spl-token` package on a NextJS application and when I try to run this:

```
import { TOKEN_PROGRAM_ID } from '@solana/spl-token'
const tokenAccounts = await connection.getParsedTokenAccountsByOwner(publicKey, { programId: TOKEN_PROGRAM_ID });
```

I get this error:
```
./node_modules/@solana/spl-token/lib/esm/extensions/extensionType.mjs:5:0
Module not found: Can't resolve './memoTransfer.mjs'

Import trace for requested module:
./node_modules/@solana/spl-token/lib/esm/extensions/index.mjs
./node_modules/@solana/spl-token/lib/esm/index.mjs
./pages/index.tsx
```

But if instead run this:

```
      const tokenAccounts = await connection.getParsedTokenAccountsByOwner(publicKey, { programId: new PublicKey('TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA') });
```

Everything works as expected.

Of course I'm using this second way for the time being, so it's not a gating issue, but thought I'd bring it up as it might be breaking something somewhere else?

**Comment by jordansexton** [comment]
It looks like the `@solana/spl-token` package was published 2 days ago: https://www.npmjs.com/package/@solana/spl-token/v/0.3.0

A change from v0.2.0 I can see is that it now includes a dependency on `@solana/spl-memo`: https://www.npmjs.com/package/@solana/spl-memo

The Memo TS lib is only built with tsc: https://github.com/solana-labs/solana-program-library/blob/cccce80e65bbd4d1cdf94cfaac0de3fbf26e11c9/memo/ts/package.json#L14

It's being exported as CJS: https://github.com/solana-labs/solana-program-library/blob/cccce80e65bbd4d1cdf94cfaac0de3fbf26e11c9/memo/ts/package.json#L9

But these compiler options look wrong, they build for ESM: https://github.com/solana-labs/solana-program-library/blob/cccce80e65bbd4d1cdf94cfaac0de3fbf26e11c9/memo/ts/tsconfig.json#L3-L4

Probably what needs to happen is that the TS + package config for the Memo TS lib needs to change to look like the Token TS lib.

**Comment by jordansexton** [comment]
As a workaround, set your version to `"@solana/spl-token": "^0.2.0"`.

**Comment by grimAgent** [comment]
> As a workaround, set your version to `"@solana/spl-token": "^0.2.0"`.

I was literally coming to add this as an FYI. You are fast. Thanks!

**Comment by eroist** [comment]
I'm getting same issue now.
Do I need to use ^0.2.0 version?

**Comment by joncinque** [comment]
Sorry about that, I'll get these fixed up to be consistent
