### ISSUE TITLE
spl-token js: Unpack methods are no exposed to clients

### ISSUE THREAD

**Issue by Arrowana** [solana-labs/solana-program-library#3472]
### Problem
`@solana/spl-token` does not export unpack functions

They are essential since clients might do all sort of account batching and need to be able to mix fetches of various account types.

A basic example is a wallet, it would do a `connection.getTokenAccountByOwner` then deserialize them all.

Then on update later on it might batch fetch token accounts and stake accounts, well everything is possible

### Solution

export `unpackAccount` and `unpackMint`

Fix
#3471

**Comment by jordansexton** [comment]
This is published in `@solana/spl-token@0.3.1` now.
Please note that the arg order has changed to `unpackX(address, info, programId?)`
I also exposed an `unpackMultisig` function for parity.
