### ISSUE TITLE
[token-2022] Restrict deposit source and withdraw destination in confidential extension to base accounts

### ISSUE THREAD

**Issue by samkim-crypto** [solana-labs/solana-program-library#3519]
In the confidential extension, it is currently possible to deposit and withdraw from the confidential extension from different source and destination accounts other than the base account for the extension. Deposit and withdraw can basically act as an alternate way to transfer tokens from accounts.

This is fine when the mint is only extended for confidential transfers, but it causes problems when the mint is extended for other extensions. For instance, using deposit for transfers could be used to bypass transfer fees.

We can add custom logic for some of the extensions for the deposit and withdraw, but I think the best way forward is to simply require that deposits/withdraws to/from confidential extensions are always directed to/from the base account. 

Wdyt @mvines ? I just want to double check that I am not missing anything about the usefulness of deposit/withdraw from different accounts.

cc @joncinque @CriesofCarrots @2501babe

**Comment by mvines** [comment]
Yes I'm ok with restricting to the base account. Not really a big loss of functionality to add this restriction and it is nice to disarm this footgun for future extensions

**Comment by joncinque** [comment]
Fixed with #3540
