### ISSUE TITLE
token-client: memo signers arent quite right

### ISSUE THREAD

**Issue by 2501babe** [solana-labs/solana-program-library#3538]
before me, memos in the client looked like this:
```
        if let Some(memo) = w_memo.take() {
            instructions.push(spl_memo::build_memo(memo.as_bytes(), &[]));
        }
```

but memos in the cli looked like this:
```
    if let Some(text) = memo {
        instructions.push(spl_memo::build_memo(text.as_bytes(), &[&config.fee_payer]));
    }
```

my understanding is the point of the memos are for the owner of a token account to attest to their ownership to some third party consumer. eg, i might transfer to an exchange omnibus wallet, and have a memo that lists an internal account number they should assign the funds to. including the signer on the memo instruction provides them an easy way to access the right pubkey without having to parse it out of arbitrary token instructions (i guess?? this is me guessing)

unfortunately neither of these code samples are right because we want to use `default_signer` rather than `fee_payer` and i just converted `Token` to use `fee_payer` for `payer` because it was trying to pay with `default_signer`. whew!

there are three possible cases:
* client end-users who provide a memo always want to sign it with their default signer. they never want to use a different signer, multiple signers or leave it unsigned. fix: add `default_signer` pubkey to `Token`
* client end-users who provide a memo may have all kind of ways they want to sign it. fix: pass pubkey vec through `with_memo`
* client end-users who provide a memo never want to sign it. anyone who consumes the memo just cares about the value. fix: construct memo with empty array

presently, everything in the cli i *think* wants to sign the memo with `default_signer` and that preexisting use of `fee_payer` is a simple oversight. but, again, i have no idea what the memo is actually trying to accomplish and am just guessing at its purpose

note that this all refers to *which accounts are marked as signers on the memo instruction*. which accounts actually sign the transaction is unchanged and irrelevant

cc @joncinque

**Comment by joncinque** [comment]
@CriesofCarrots what do you think about this? Which signers should be marked in the memo instruction during token operations? 

I worry about using `default_signer`, since someone may want to specify all of the inputs to a CLI command, completely apart from their defaults, and yet a default still gets picked up.  This is probably why it's `fee_payer` in the code currently.

What about having the `authority` on the instruction sign the memo?  So for a transfer, that would be the owner / delegate.  For a mint, that would be the mint authority. For a freeze, the freeze authority, etc etc.  This just may complicate things quite a bit unfortunately.

**Comment by 2501babe** [comment]
`default_signer` is specified by the `--owner` paramenter, and `fee_payer` defaults to `default_signer` but can be specified by the `--fee-payer` parameter. thats actually how i accidentally discovered the issue with `Token` using `default_signer` as its `payer`: a test that used both `--owner` and `--fee-payer` and the owner just happened to have zero sol

**Comment by joncinque** [comment]
> default_signer is specified by the --owner paramenter, 

I should read the code before commenting.  `default_signer` makes sense to me, since that also covers the "authority" in almost every case.

**Comment by CriesofCarrots** [comment]
While we wrote the signed-memo program for one specific use-case, I think there are a probably a bunch of different use-cases for memo signers, and I'm not sure we know what those might be for token-client users.
I'm actually inclined toward greater flexibility, ie. fix/bullet 2 in the issue description, passing an array of pubkeys. It could also be nice to preserve the ability to pass no signer, which minimizes the size of the instruction/transaction.
Perhaps we could offer different memo apis to (a) include no signers; (b) include default signer; (c) include custom list of signers (the last of which will presumably require some extra signing plumbing)...?

**Comment by 2501babe** [comment]
cool in that case ill make the existing `with_memo` in the client take the pubkeys too, and have the cli always pass in `default_signer`
