### ISSUE TITLE
token-swap: unable to build program

### ISSUE THREAD

**Issue by DuwYAnne** [solana-labs/solana-program-library#3554]
Using `cargo build-spf` doesn't work with my rust version (1.60.0) and using `cargo build-bpf` instead gives an error
```
error: failed to select a version for the requirement `librocksdb-sys = "^0.8.0"`
candidate versions found which didn't match: 6.20.3, 6.17.3, 6.11.4, ...
```
Is there a way to build the program to deploy on a local cluster? (to test certain token-swap functions)

**Comment by 2501babe** [comment]
master has upgraded to solana 1.11, if your cli tools are on 1.10, upgrading should fix this. (librocksdb has been causing great pain for many of us)

**Comment by DuwYAnne** [comment]
Yeah this worked, thanks!

**Comment by damingerdai** [comment]
i also met this issue,

this is my rust and cli version

```bash
rustc -V

rustc 1.65.0 (897e37553 2022-11-02)

solana --version

solana-cli 1.13.5 (src:959b760c; feat:1365939126)

```

**Comment by joncinque** [comment]
Upgrade to 1.14, since 1.13 is the same as 1.10. In the future, please create a new issue describing the problem you're seeing rather than necro-posting
