### ISSUE TITLE
account-compression (program): on-chain v0 release

### ISSUE THREAD

**Issue by ngundotra** [solana-labs/solana-program-library#3616]
- [x] Version account headers
- [x] Version changelog output as well
- [x] New vanity keys corresponding to spl-naming conventions
- [x] Close out preexisting programs
  - `GRoLLzvxpxxu2PGNJMMeZPyMxjAUH9pKqxGXV9DGiceU` (account-compression) 
  -  `WRAPYChf58WFCnyjXKJHtrPgzKXgHp6MD9aVDqJBbGh` (noop)

- [x] Add a `closeTree` instruction

**Comment by ngundotra** [comment]
For future v1 release:
- rewrite in raw Solana + Shank (for autogenerated anchor compatibility)
- add batchAppend instruction
- add initWithRoot instruction

**Comment by ngundotra** [comment]
Versioned account header in #3619

**Comment by ngundotra** [comment]
Versioning changelog output in #3632

**Comment by ngundotra** [comment]
Waiting to close out this v0 release until I can deploy an example program on mainnet-beta for account-compression.

Blocked on #3615

**Comment by ngundotra** [comment]
Deployed on devnet and mainnet-beta

**Comment by trankhacvy** [comment]
Hey @ngundotra why we don't deploy the `account-compression` program on testnet?
I'm trying to integrate account-compression with helius but can't run my program on testnet.

**Comment by ngundotra** [comment]
@trankhacvy it's on testnet now! thanks for flagging this, forgot to come back around and push there
