### ISSUE TITLE
Need for method to add SPL fungible token metadata

### ISSUE THREAD

**Issue by Bhaney44** [solana-labs/solana-program-library#3621]
**Overview**

I've been working on finding a method for adding metadata to a new fungible token for a few days now. However, it appears there is a need for this as one does not currently exist. I've documented some troubles in this [Issue](https://github.com/metaplex-foundation/metaplex/issues/2248).

**Core Problem**

With the change from [Solana-Labs Token List](https://github.com/solana-labs/token-list) to the  [MetaPlexToken MetaData Program](https://docs.metaplex.com/programs/token-metadata/overview), there is now no method for adding MetaData to a new asset on Solana. There is documentation for the [MetaPlex JS-SDK](https://github.com/metaplex-foundation/js), however it focuses only on the `nfts()` method and provides no information on adding metadata to a fungible token.

The MetaPlex metadata [instructions](https://docs.metaplex.com/programs/token-metadata/instructions) explain the metadata file, but they provide no explanation of how to actually add the metadata to a new SPL token. Thus, there is a need for a method to add metadata to new SPL tokens. This is important because without a method for adding metadata to assets, new SPL tokens cannot be launched on the Solana blockchain. 

**Solution Needed**
An ideal solution would be a directory, guide, or resource providing a step-by-step guide on how to add metadata to an SPL fungible token. Thanks in advance - I sincerely appreciate any suggestions or advice!

**Comment by jordansexton** [comment]
Adding metadata to a token isn't handled by the SPL Token program, but by the Token Metadata program which isn't part of SPL. It's here: https://github.com/metaplex-foundation/metaplex-program-library/tree/master/token-metadata/program

The source of the docs for Metaplex is here: https://github.com/metaplex-foundation/docs

I'm going to close this as out of scope for SPL.

**Comment by Bhaney44** [comment]
> Adding metadata to a token isn't handled by the SPL Token program, but by the Token Metadata program which isn't part of SPL. It's here: https://github.com/metaplex-foundation/metaplex-program-library/tree/master/token-metadata/program
> 
> The source of the docs for Metaplex is here: https://github.com/metaplex-foundation/docs
> 
> I'm going to close this as out of scope for SPL.

Hi @jordansexton thanks for the reply - I appreciate your time. The problem is the links you sent don't provide a method for adding metadata to an existing SPL token. I understand the authority for handling token metadata was moved from solana to metaplex, but in the process no method was transferred for adding fungible token metadata. I'll continue to seek help from metaplex, thanks anyway.
