### ISSUE TITLE
token-js: unable to create multiple token accounts for a PDA

### ISSUE THREAD

**Issue by 0xBrahma** [solana-labs/solana-program-library#3622]
This is some code to create a token account:

```typescript
import * as token from "@solana/spl-token";

// truncated setup

await token.createAccount(
  provider.connection,
  provider.wallet.payer,
  mint,
  owner
)
```

When `owner` is a PDA, this code will fail with `TokenOwnerOffCurveError`. A workaround is to call getOrCreateAssociatedTokenAccount with `allowOwnerOffCurve` set to true, but this prevents one from making creating multiple token accounts for a single PDA.

Why does this happen? Is there a fundamental reason why owners of token accounts cannot be PDAs? This seems unlikely, given that PDAs can control associated token accounts. Or maybe this is some kind of validation check performed by the `@solana/spl-token` library? This seems more likely, but a [GitHub search through the repo](https://github.com/solana-labs/solana-program-library/search?q=TokenOwnerOffCurveError) only turns up one reference of this error being thrown, inside the seemingly-unrelated `getAssociatedTokenAddress` function.

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support, and encourage you to ask a question on the Solana Stack Exchange https://solana.stackexchange.com/.

Historically, the `allowOwnerOffCurve` flag was added to protect people from creating token accounts that they didn't want to create -- mainly to avoid people creating ATAs owned by ATAs, the dreaded "nested account" problem.

If you want to create the associated token account for a PDA, you can do exactly what you specified with `getOrCreateAssociatedTokenAccount`, and for additional accounts, you can use `createAccount` with a `Keypair`, ie:

```
const newAccount = Keypair.generate();
await token.createAccount(
  provider.connection,
  provider.wallet.payer,
  mint,
  owner
  newAccount,
)
```
