### ISSUE TITLE
Can't compile.

### ISSUE THREAD

**Issue by padrone1225** [solana-labs/solana-program-library#3624]
'toBigIntLE' is not exported by node_modules/bigint-buffer/dist/browser.js, imported by node_modules/@solana/buffer-layout-utils/lib/esm/bigint.mjs

**Comment by joncinque** [comment]
Can you add some information to your issue? What package are you trying to use? If it's a buffer-layout issue, you're better off taking it upstream to that repo https://github.com/solana-labs/buffer-layout-utils

**Comment by syed-dce** [comment]
@padrone1225  Use this:

`import { toBigIntBE, toBigIntLE, toBufferBE, toBufferLE } from 'bigint-buffer';`

**Comment by joncinque** [comment]
Closing since there hasn't been any movement
