### ISSUE TITLE
token-client: remove `decimals` arg from all functions

### ISSUE THREAD

**Issue by 2501babe** [solana-labs/solana-program-library#3648]
i was thinking about this when refactoring `transfer`, it makes sense to me that `Token` should carry `decimals: Option<u8>` because it is, in fact, a property of the token. functions that require `decimals` can return a new `TokenError` variant if its not there

(ping jon next week, this requires editing a *lot* of calls in tests, so i dont want to do it on spec)

**Comment by joncinque** [comment]
This makes lots of sense to me! We kept it around as a parameter during the transition to checked functions, and we really have no need for the unchecked variants at this point. And with your idea, it can still be used if it's `None`. Big :+1: from me
