### ISSUE TITLE
[spl-token][token-2022] createInitializeNonTransferableMintInstruction return error 0xc

### ISSUE THREAD

**Issue by jimmdd** [solana-labs/solana-program-library#3664]
While I am trying to create a non transferable mint using the `@solana/spl-token` js [example](https://github.com/solana-labs/solana-program-library/blob/master/token/js/examples/nonTransferable.ts) to call `createInitializeNonTransferableMintInstruction`, on devnet, it returns error as below: 

<img width="1087" alt="Screen Shot 2022-10-04 at 10 58 40 AM" src="https://user-images.githubusercontent.com/11653910/193892019-617366cb-b551-4a6f-8d5f-808c90235201.png">

I also tried to run this on mainnet but still the same error. I wonder if there's a mismatch between the deployed instructions and the client?

**Comment by GageBachik** [comment]
+1 was running a dev stream on token2022 and ran into this same issue. 
Any instruction past createNativeMint(31) just return invalid instruction error.
aka both non transferable token and interest-bearing token

**Comment by joncinque** [comment]
Sorry about that, the deployed version was quite old, so I deployed version 0.4.3 to all networks.  Enjoy all the extensions now!
