### ISSUE TITLE
[spl-token] createAssociatedTokenAccount() results in NotEnoughKeys on v0.3.5

### ISSUE THREAD

**Issue by castle055** [solana-labs/solana-program-library#3678]
The recent changes discussed on issue #3590 break the instruction returned by `createAssociatedTokenAccount()` in the typescript SDK. It results in a `NotEnoughAccountKeys` error from the program.

The problem is that the `rent` sysvar is not provided in the accounts context while the program does require it. Looking at the issue, this seems to be intentional so I can't be sure if it has a purpose or not. However, it currently breaks the SDK so either a revert may be needed or a update to the program is.

The only workaround I found so far was either downgrading or manually appending the sysvar public key to the instruction before sending it.

Since the SDK's unit tests don't send any transactions this error is not caught. In the future, it may be a good idea to implement integration tests that test the SDK on a local validator with the program.

**Comment by joncinque** [comment]
Are you seeing this issue on a local validator running an old version? The associated-token-account program was updated a few months ago so it doesn't require the rent sysvar.  Here's a successful transaction creating an associated token account on devnet, note the lack of rent sysvar: https://explorer.solana.com/tx/5aCjJ3E2v6u8rppaXSaB39sNARyNBatBQbFhkjSvb32FgA7FqzcU3GEud5E5E2ymcxacUS3jZwTvLnWgvwjUR82W?cluster=devnet

I can't remember which version has the change, but I think anything starting with 1.10 will have it. If not, 1.11 certainly has it.  Can you try updating and see if it works?

Also, you can find all of the end-to-end JS tests at https://github.com/solana-labs/solana-program-library/tree/master/token/js/test/e2e and https://github.com/solana-labs/solana-program-library/tree/master/token/js/test/e2e-2022 which runs against a local validator.  If you think there's some coverage missing, please file an issue, or better yet, a PR!

**Comment by joncinque** [comment]
Closing since there hasn't been a response
