### ISSUE TITLE
How to parse spl-token transaction details?

### ISSUE THREAD

**Issue by arunsybex** [solana-labs/solana-program-library#3679]
https://solscan.io/tx/5mf6S58isV9d6TWcimviUwiiqJ3pcY1EoSXGkzLUvdEjDiJwenXmjnPUPSnLEMpoUPmZA2dEjrZ6jBZfrKs2sHf8?cluster=devnet

I need to get 

from: 
to: 
token_address:
amount of tokens transferred:

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for developer support! Please ask your question on the Solana Stack Exchange https://solana.stackexchange.com/
