### ISSUE TITLE
[token-2022] Unexpected function behavior (TOB-STK-5)

### ISSUE THREAD

**Issue by samkim-crypto** [solana-labs/solana-program-library#3699]
#### Description
The `decode_instruction_data` function receives a byte slice representing the instruction data. However, unintuitively to the functions name, and not commented in the code, it depends on the first byte of the slice to contain the instruction type for an extension instruction.

https://github.com/solana-labs/solana-program-library/blob/50abadd819df2e406567d6eca31c213264c1c7cd/token/program-2022/src/instruction.rs#L1761-L1768

#### Recommendations
Short term, change the function to only operate on instruction data, and remove the instruction type from the passed data prior to the call. This ensures that the function name is in line with the functions operation.

**Comment by samkim-crypto** [comment]
This seems to be a pretty minor issue and I'd be okay closing this. @joncinque wdyt?

**Comment by joncinque** [comment]
It's not a bad point, since the `input` actually corresponds to the full input, and not just the slice corresponding to the data portion of the instruction. We only did it this way for slightly cleaner code. We just need to get rid of the `1` and pass in `input[1..]` to the function
