### ISSUE TITLE
[token-2022] The UpdateMint instruction can lead to inoperable mint (TOB-STK-8)

### ISSUE THREAD

**Issue by samkim-crypto** [solana-labs/solana-program-library#3702]
#### Description
Issuing an `update_mint` instruction with the new authority set to `Pubkey::default` and the `auto_approve_new_accounts` property set to false would make it impossible to approve `Accounts` for the mint, because the `ApproveAccount` instruction requires the authority to sign.

https://github.com/solana-labs/solana-program-library/blob/50abadd819df2e406567d6eca31c213264c1c7cd/token/program-2022/src/extension/confidential_transfer/processor.rs#L64-L89

#### Recommendations
Short term, add a check to make sure the `auto_approve_new_accounts` property is not false. This ensures that contract users do not accidentally disable the authorization of accounts for a mint.

**Comment by samkim-crypto** [comment]
I'd be okay with closing this issue since this is not a unique issue for `auto_approve_new_accounts`. If any of the authority pubkeys are non-functional, then it should be expected that the functionality of the authority is lost.

**Comment by joncinque** [comment]
I agree on this.  Since the authority pubkey is non-optional, then it's their problem if they mess it up. Feel free to close this
