### ISSUE TITLE
[token-js]: add native support for querying token account balances

### ISSUE THREAD

**Issue by metaproph3t** [solana-labs/solana-program-library#3722]
Today, if you want to query for an SPL token balance, you have two options:

Option 1 - 
```typescript
let balance = (await spl-token.getAccount(connection, tokenAccount)).amount
```
Option 2 - 
```typescript
let balance = (await connection.getTokenAccountBalance(tokenAccount)).value.amount
```

Both feel a bit cumbersome for what may be a common task. What do you think about supporting the following? 

```typescript
let balance = await spl-token.getTokenAccountBalance(tokenAccount)
```

**Comment by joncinque** [comment]
To be honest, I don't see the value in adding the function, considering `getTokenAccountBalance` does exactly what you want.  A function like:

```js
async function getTokenAccountBalance(connection, tokenAccount) {
    return (await connection.getTokenAccountBalance(tokenAccount)).value.amount;
}
```

would just confuse me more than anything. But maybe someone else disagrees with me!

**Comment by metaproph3t** [comment]
Fair enough
