### ISSUE TITLE
createMint: 0xc Invalid Instruction

### ISSUE THREAD

**Issue by austinmilt** [solana-labs/solana-program-library#3737]
I see issue #3664 looks similar, but I am getting the same error in a different method. Can you confirm that there's something I can do about this?

https://solana.stackexchange.com/questions/3968/solana-token-program-0xc-invalid-instruction

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for developer support questions -- your question on the Solana Stack Exchange was the correct avenue.
