### ISSUE TITLE
token3: ensure the wrapped SOL mint is owned by the token program

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana-program-library#374]
The native mint for token 2:
https://github.com/solana-labs/solana-program-library/blob/92457f774cd3064c9cec55a0596dae6a83f20cb8/token/program/src/native_mint.rs#L7
has a bug in that it's an account that is not owned by the token program, and doesn't have account data that looks like every other mint account.

This requires special case handling within the token program itself and any user of SPL Token that wants to support wrapped SOL.  

Instead we should make wrapped SOL mint look like any other mint account to avoid special casing (which is exactly the reason why wrapped SOL exists).

The supply for the native mint would represent the current amount of Wrapped SOL (instead of the total native SOL supply)
https://github.com/solana-labs/solana-program-library/blob/92457f774cd3064c9cec55a0596dae6a83f20cb8/token/program/src/state.rs#L23

**Comment by mvines** [comment]
This will require RELEASE.md updates to describe how to create the native mint whenever a new version of SPL Token is deployed

**Comment by mvines** [comment]
This is probably now obsolete since we made this so via a bank.rs change

**Comment by t-nelson** [comment]
It kinda sucks that this requires core support though :confused: 

The alternatives kinda suck also.  I've been thinking on it

**Comment by mvines** [comment]
I'm sold on keeping the special case for SPL Token.  It's weird and we wouldn't do it if we could rewind back six months, but it works and is in prod
