### ISSUE TITLE
token-2022: cpiguard docs/js/cli

### ISSUE THREAD

**Issue by 2501babe** [solana-labs/solana-program-library#3771]
now that the cpi guard extension is merged, we need to:
* ~support enable/disable from the cli~ (done)
* ~and js client~
* ~add the extension to `spl-token display` (along with permanent delegate)~
* document the extension in `docs/src/token-2022/extensions.mdx`

**Comment by 2501babe** [comment]
i landed the necessary account decoder changes in monorepo, so `spl-token display` is now as simple as an extra print line, once we have a new 1.14 release to base on

**Comment by staccDOTsol** [comment]
hannah why r u here
