### ISSUE TITLE
token-2022: removing freeze authority prevents disabling default-frozen accounts

### ISSUE THREAD

**Issue by 2501babe** [solana-labs/solana-program-library#3789]
```
hana@laptop:debug$ ./spl-token create-token -p TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb --enable-freeze --default-frozen-accounts
Creating token DW2sasZeLTB8DYBRGCV55PkmGqZWada2ZommPCi3vNg6 under program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb

Address:  DW2sasZeLTB8DYBRGCV55PkmGqZWada2ZommPCi3vNg6
Decimals:  9

Signature: 3gC8dExDKdV66ViosnPjYR974DYzGeaFd4WnNRYkqB7LMpmLTbBTSAwdSTaWd4Hg2k17KQjU1xDaF6NmJwWcJ5Lr

hana@laptop:debug$ ./spl-token authorize DW2sasZeLTB8DYBRGCV55PkmGqZWada2ZommPCi3vNg6 freeze --disable
Updating DW2sasZeLTB8DYBRGCV55PkmGqZWada2ZommPCi3vNg6
  Current freeze authority: 69Dthojcy5wKzyzesKn6JgvdSpN9JmZzD3EKT8CUCyx6
  New freeze authority: disabled

Signature: 47SNA3wJXMj2icq77tBc7k5mtrEZu5mZK8nTonTYL8ZWgeMLXys33aKXmGKoFteGU3CFPbxCsgm2Ewq2n56SQV2S

hana@laptop:debug$ ./spl-token update-default-account-state DW2sasZeLTB8DYBRGCV55PkmGqZWada2ZommPCi3vNg6 initialized
Error: "Mint DW2sasZeLTB8DYBRGCV55PkmGqZWada2ZommPCi3vNg6 has no freeze authority."
hana@laptop:debug$ ./spl-token create-account DW2sasZeLTB8DYBRGCV55PkmGqZWada2ZommPCi3vNg6
Creating account Gm3ar4HRTDrCq3EpzP3mtXXJmNVZHxMk3cDYDe17YLi6

Signature: 2J6wTNRJsJUg4xeBcQS8a25n9Xjnkwsya6TBDDiPAqekCzSTReyw5GcLbjQdQsaAAKayYaWMTcDdeZVYGmpebhDm

hana@laptop:debug$ ./spl-token display Gm3ar4HRTDrCq3EpzP3mtXXJmNVZHxMk3cDYDe17YLi6

SPL Token Account
  Address: Gm3ar4HRTDrCq3EpzP3mtXXJmNVZHxMk3cDYDe17YLi6
  Program: TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb
  Balance: 0
  Decimals: 9
  Mint: DW2sasZeLTB8DYBRGCV55PkmGqZWada2ZommPCi3vNg6
  Owner: 69Dthojcy5wKzyzesKn6JgvdSpN9JmZzD3EKT8CUCyx6
  State: Frozen
  Delegation: (not set)
  Close authority: (not set)
Extensions:
  Immutable owner
```

noticed this while reading the extension code when reviewing #3785. note this is a problem with the _program_, not with the cli. from `process_update_default_account_state`:
```
    let freeze_authority =
        Option::<Pubkey>::from(mint.base.freeze_authority).ok_or(TokenError::NoAuthorityExists)?;
    Processor::validate_owner(
        program_id,
        &freeze_authority,
        freeze_authority_info,
        freeze_authority_info_data_len,
        account_info_iter.as_slice(),
    )?;

    let extension = mint.get_extension_mut::<DefaultAccountState>()?;
    extension.state = state.into();
    Ok(())
```

plausible solutions:
* allow setting default state to `AccountState::Initialized` in absence of a freeze authority
* prevent revoking freeze authority if default state is `AccountState::Frozen`
* automatically reset default state to `AccountState::Initialized` when revoking freeze authority

2 seems best to me, altho 1 is also not unreasonable. 3 is too "surprising" for something that cant be undone

it could be argued that this is working as intended in the sense that removing freeze authority "freezes" the state of the default account extension, but i would argue this is a confusion of terms. whats actually happening is every new account is frozen, despite the mint lacking a freeze authority, which should be impossible. also it basically breaks the mint: because they cant be unfrozen, in effect no new accounts can ever be created

**Comment by 2501babe** [comment]
cc @joncinque

**Comment by joncinque** [comment]
Number 2 seems like the best option to me.

Who can authorize in the case of number 1? It might be weird -- if I create a token with default state frozen, create the set of accounts that I want, and unfreeze them, and I never want anyone else to ever create a token for my mint, I can revoke the freeze authority. If it's possible to change the default state, then it's impossible to implement that idea.  Unless we just tell people "don't revoke the freeze authority" but that seems more confusing that anything.

**Comment by CriesofCarrots** [comment]
Imho, this is currently working as intended.

> if I create a token with default state frozen, create the set of accounts that I want, and unfreeze them, and I never want anyone else to ever create a token for my mint, I can revoke the freeze authority.

Right, this use-case is actually a motivator for the current code, and there isn't an alternative way to do this with any of the solutions proposed that I can see. Is there an actual problem?

**Comment by 2501babe** [comment]
sorry, i guess it just struck me as "wrong" that accounts would still be frozen without an authority to freeze them. if this is meant to do that then i guess we can just close

**Comment by CriesofCarrots** [comment]
My leaning is to leave as-is. Presumably users should always be very careful about revoking mint authority (or any authority, since it can't be undone).
What do you think @joncinque ?

**Comment by joncinque** [comment]
Agreed, my vote is to leave it as is
