### ISSUE TITLE
Token Upgrade cli not working as stated in docs

### ISSUE THREAD

**Issue by Psionyc** [solana-labs/solana-program-library#3807]
**In the Solana docs (https://spl.solana.com/token-upgrade) it's stated that the spl-token-upgrade-cli be installed via cargo**

![image](https://user-images.githubusercontent.com/102559775/200946246-17d6b905-6234-4a99-a0d3-549ed40706fb.png)

### Meanwhile the spl-token-upgrade-cli only prints "Hello World" when used...

![Screenshot 2022-11-09 223508](https://user-images.githubusercontent.com/102559775/200946812-1f8c8332-0599-46f4-9a59-4bd1cb57d55f.png)

### After visiting docs.rs as stated in the docs... I found out that the main.rs file only contains  3 lines of code

![image](https://user-images.githubusercontent.com/102559775/200947329-f74d672d-84c4-43c2-8d63-d7a4de0206a0.png)

### However, the code sure is available on GitHub

![image](https://user-images.githubusercontent.com/102559775/200947618-11106182-d3d6-4ae0-829b-b37ba33ee910.png)

**Comment by joncinque** [comment]
This is correct unfortunately. We're still waiting on dependent crates to publish a real version of the CLI. What you've downloaded is just a placeholder because people frontrun our crates if we don't publish immediately. I'll leave this open and resolve it when we do publish finally.

**Comment by 2501babe** [comment]
spl-token-upgrade-cli 0.1.0 is now out
