### ISSUE TITLE
token-js: Add PermanentDelegate support

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#3814]
#### Problem

 #3725 is adding the PermanentDelegate extension and support in token-client, but we need it in JS.

#### Solution

Add the support!

**Comment by atharmohammad** [comment]
I would like to work on this issue.

**Comment by joncinque** [comment]
Please do! We can separate CLI and JS into separate issues if you prefer

**Comment by atharmohammad** [comment]
> Please do! We can separate CLI and JS into separate issues if you prefer

That would be great ! I wanted to confirm that ```permanentDelegate``` can also be used to transfer tokens from one account to another because it's working for ```burn``` instruction but when i am using it for ``` transfer``` instruction it's failing with some custom error. 
```transfer(connection,payer,account,destination,permanentDelegate,1,undefined,undefined,TEST_PROGRAM_ID);```
