### ISSUE TITLE
Use of global public functions in instruction.rs

### ISSUE THREAD

**Issue by eulerbeat** [solana-labs/solana-program-library#3815]
https://github.com/solana-labs/solana-program-library/blob/d50f2745f8aa0c0e5a537664e5bc71484fb6c76e/token/program/src/instruction.rs#L770

Just wanna confirm, are these functions(this and till the test) for CPI calls?

**Comment by CriesofCarrots** [comment]
Yes, one use of the Instruction builders is to prepare instructions for CPI calls. They can also be used for preparing top-level Transaction instructions. Hopefully I've understood your question correctly.

In future, please ask questions like this on the Solana Stack Exchange: https://solana.stackexchange.com/questions/ask You'll be able to provide clarifications and get better support
Our github issues are for software bugs and problems affecting code-development itself. Cheers!
