### ISSUE TITLE
token-cli: Add PermanentDelegate support

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#3840]
#### Problem

https://github.com/solana-labs/solana-program-library/pull/3725 added the PermanentDelegate extension and support in token-client, but we need it in the CLI.

#### Solution

Add it!

**Comment by atharmohammad** [comment]
I would like to work on it , just to be sure these are the changes i am thinking for adding it's support in cli , please add if there are some other changes needed  : 
1). adding a ```enable-permanent-delegate``` flag to make ```mint-authority``` also ```permanent-delegate``` in create-token
2). return ```permanent-delegate``` in ```Authorize``` for previous authority
3). tests

**Comment by joncinque** [comment]
Yep, that's all perfect!
