### ISSUE TITLE
Unable to build the token program

### ISSUE THREAD

**Issue by rohit-msl** [solana-labs/solana-program-library#3865]
Upon Running the below command 
npm run test:build-programs
I am facing the issue "cargo_build_sbf] Failed to install sbf-tools: A required privilege is not held by the client. (os error 1314) "

**Comment by rohit-msl** [comment]
After runing vs code as administrator I am having different issue now

![Screenshot 2022-12-02 132338](https://user-images.githubusercontent.com/117927299/205280570-35340fb7-4116-48d2-9947-6d036c4840ad.png)

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for developer support, and encourage you to ask a question the Solana Stack Exchange https://solana.stackexchange.com/.

Quickly, you just need to install the Solana CLI https://docs.solana.com/cli/install-solana-cli-tools
