### ISSUE TITLE
token-js: tlv parser does not handle extra space in the buffer well

### ISSUE THREAD

**Issue by 2501babe** [solana-labs/solana-program-library#3912]
allocate a token account with six extra bytes and try to find a post hoc initializable boolean data extension, which takes up five bytes in the repr. parser will attempt to read a u16 past the end of the buffer
 
```
HANA BEGIN
     cpi guard type/len: 11/1, memo transfer type/len: 8/1
     buffer: <Buffer 00 00 00 00 00>

HANA idx: 0, tlv len: 5
     entry type: 0 ==? 11
     entry len: 0
     type idx: 4
  -> newly computed: 4

HANA idx: 4, tlv len: 5

     RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4
      at new NodeError (node:internal/errors:371:5)
      at boundsError (node:internal/buffer:86:9)
      at Buffer.readUInt16LE (node:internal/buffer:243:5)
      at getExtensionData (file:///home/hana/work/solana/solana-program-library/token/js/src/extensions/extensionType.ts:127:35)
      at Context.<anonymous> (file:///home/hana/work/solana/solana-program-library/token/js/test/e2e-2022/tlv.test.ts:115:24)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

fixing this one thing isnt hard but instead of just whacking my mole im writing proptests for the parser

edit: actually i wrote that very confidently but its weird to me that i tell it to alloc six more and i see five here. im not sure how it finds the start or end of the tlv buffer to begin with, writing this will solve all my questions tho

**Comment by 2501babe** [comment]
its because it puts an `02` byte to mark the start of tlv so the remaining five of six bytes are available for data. interestingly initialize fails if you only give it account length plus one

**Comment by 2501babe** [comment]
ah its the lte in `if rest_input.len() <= tlv_start_index` in `fn type_and_tlv_indices`. doesnt really matter

**Comment by 2501babe** [comment]
ok i think ive wandered into a tarpit here, instead of this dumb combinatorial extension test case generator thing, im just gonna test the actual bug (extra bytes breaking the parser) and delete the rest of the shit i wrote for it. the proper place for me to do the more complicated tests is in rust, where it matters

**Comment by joncinque** [comment]
> im just gonna test the actual bug (extra bytes breaking the parser)

That seems like the best approach. We did address some similar-ish issues on the Rust side too if that helps in https://github.com/solana-labs/solana-program-library/pull/3762 and https://github.com/solana-labs/solana-program-library/pull/3761
