### ISSUE TITLE
TokenSwap createInitSwapInstruction

### ISSUE THREAD

**Issue by LELUK911** [solana-labs/solana-program-library#3930]
Hi, I try, create one account or my swap, but "createInitSwapInstruction" at first field dont accept a PublicKey, and if i try getAccount, this is null.

I follow the tutorial on soldev, but i dont understand  because  of this error, and i think that i wrong something in sendTransaction command.. this is extract from my code

Swap code instruction

![problem](https://user-images.githubusercontent.com/86750582/208398394-760fd29a-facf-413c-a976-4ddc3e091fd8.jpeg)

front-End swap

![codeSign](https://user-images.githubusercontent.com/86750582/208398864-b318947d-9456-4fd3-aa07-ec8b131123f1.jpeg)

Get Account function

![getAccouunt](https://user-images.githubusercontent.com/86750582/208399157-f0e9fbbe-8f26-423f-95f4-3c460999d8ec.jpeg)

Create Account

![CreateAccount](https://user-images.githubusercontent.com/86750582/208399243-76111735-eb97-45cd-aba1-407d90ecc409.jpeg)

**Comment by joncinque** [comment]
Hi there, we don't provide developer support over GitHub, and recommend that you either ask the question directly to soldev or the Solana Stack Exchange https://solana.stackexchange.com/
