### ISSUE TITLE
Is solana docs are outdated?

### ISSUE THREAD

**Issue by daniyal-tayyab** [solana-labs/solana-program-library#3963]
Hello, I am trying to generate fungible token. I am  following the official docs, but getting a lot of error and warnings like:
confirmTransaction is deprecated
OR
SolanaJSONRPCError: airdrop to failed: Internal error 
OR
Error: signature must be base58 encoded: undefined.
I want to ask is the solana documention is outdated?

My code:
```
import {
  clusterApiUrl,
  Connection,
  Keypair,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";

import { createMint } from "@solana/spl-token";

const payer = Keypair.generate();
const mintAuthority = Keypair.generate();
const freezeAuthority = Keypair.generate();

const connection = new Connection(clusterApiUrl("devnet"), "confirmed");

try {
  const airDropSignature = await connection.requestAirdrop(
    payer.publicKey,
    LAMPORTS_PER_SOL
  );

  const latestBlockHash = await connection.getLatestBlockhash();
  console.log(latestBlockHash);

  await connection.confirmTransaction({
    blockhash: latestBlockHash.blockhash,
    lastValidBlockHeight: latestBlockHash.lastValidBlockHeight,
    airDropSignature,
  });

  console.log("transaction confirmed");

  const mint = await createMint(
    connection,
    payer,
    mintAuthority.publicKey,
    freezeAuthority.publicKey,
    9 // We are using 9 to match the CLI decimal default exactly
  );
  console.log(mint.toBase58());
} catch (err) {
  console.log(err);
}

```

**Comment by daniyal-tayyab** [comment]
I have tried all the possible solutions that i can find on internet, but nothing worked for me

**Comment by aa21** [comment]
Yes we are also having A LOT of errors trying to set up 
web3 
+ SPL Token 
+ Metaplex Token Metadata 
+ Auction House

The documentations look clear but all the code keep throwing errors. Example tutorials on the web or on github are also causing multiple errors. 

There are so many GitHub accounts and paths .. I'm not sure why? 
Nothing has clear versioning. 
There is no documentation on conflicting versions (if any). 

So far Solana Rust compilation and JS development has been extremely painful for us. 
Our client is upset, my developer's morale is low, I'm burning late night oil and still stuck in this tar pit.

**Comment by daniyal-tayyab** [comment]
@aa21  Yes I can understand your pain. I am also suffering alot.

**Comment by aa21** [comment]
To help others I will document any documents that help me here:

SPL Token - official introduction and examples:
https://spl.solana.com/token

SPL Token - methods, properties:
https://solana-labs.github.io/solana-program-library/token/js/modules.html

Sol Web3 Examples - Unofficial @yihau :
https://yihau.github.io/solana-web3-demo/

**Comment by aa21** [comment]
> Hello, I am trying to generate fungible token.. .  I want to ask is the solana documention is outdated?

Hi @daniyal-tayyab .. I realised yesterday that there are two main versions of SPL-Token 

 `"@solana/spl-token": "^0.1.x"`
 and 
`"@solana/spl-token": "^0.2.x"`

0.2.x is the latest version and code that worked on `0.1.x` will NOT work on `0.2.x` .. e.g. `0.1.8`. 

I faced a lot of headache without knowing this, because all the code I found online was throwing errors. 
I advice you to check your `package.json`.

*This important information is hidden away deep inside this github here:*
https://github.com/solana-labs/solana-program-library/tree/master/token/js

Maybe Solana developers believe that pain is the best teacher? 🤷‍♂️

**Comment by daniyal-tayyab** [comment]
@aa21 Thanks man you saved my day.

**Comment by aa21** [comment]
@daniyal-tayyab you're welcome :)

Another thing I realised today was that `React 18` breaks away from `React 17`. 

Looks like the year 2022 had a lot of breaking changes in multiple libraries. 
The lesson I learnt was to start paying more attention to **_`package.json` module versions_**.
