### ISSUE TITLE
Recreate SPL Transfer from a `CompiledInstruction`

### ISSUE THREAD

**Issue by saadahmsiddiqui** [solana-labs/solana-program-library#3975]
Hi, i wanted to ask if i can decode an existing SPL token transfer from transaction hash only. 

`const transaction = await client.getTransaction(transactionHash!);`

Returns a `TransactionReponse` from `@solana/web3.js` which contains `CompiledInstructions`. Id be really interested to know if it's possible to recreate a `TransferInstruction` from existing on chain data

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for developer support, and encourage you to ask your question on the Solana Stack Exchange https://solana.stackexchange.com/ or some other support forum.
