### ISSUE TITLE
token-swap: Incorporate more invariants / curves, e.g. curve.fi

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#398]
**Problem**

The curve defined by Uniswap: `x * y = k` is useful for many applications, but can be difficult to work with in the stablecoin space, where slippage needs to be minimal.  For example, if trading USDC for DAI, which are both USD stablecoins, you can have 4% slippage because of harsh curve movements.

**Solution**

Allow for different curves to be set for the token swap.  For example, curve.fi uses a special kind of "varying leverage" curve.  More can be found at their whitepaper: https://www.curve.fi/stableswap-paper.pdf  -- they suggest an invariant of the form:
```
A * n ^ n * sum(x_i) + D = A * D * n ^ n + (D ^ (n + 1)) / (n ^ n * product(x_i))
```
where n is the number of currencies in the pool, D is the sum of all coins, x_i is an individual coin amount, and A is some constant.  This provides for dynamic leverage while calculating the invariant -- it essentially flattens the function when balances are close to equal, and then creates huge prices movements at the tails.

Their "optimal" recommendation is A = 85, fee = 0.06%, providing 312% APR for liquidity providers.

**Comment by joncinque** [comment]
Curve variants have been added, but the stable curve implementation is not totally there, so I'll leave this issue open

**Comment by rawfalafel** [comment]
@joncinque which parts are in complete?

**Comment by joncinque** [comment]
@rawfalafel the withdrawal / deposit calculation doesn't line up perfectly with stable swap, so it could be possible to leak value out in a fee-less environment using combinations of deposit on one side and swap.  That's why the stable curve does not have the same proptests as the other curves

**Comment by joncinque** [comment]
Closing this in favor of more specific issues, since the stable curve has been included for awhile
