### ISSUE TITLE
ci: Remove uses of `Pubkey::new`

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#4006]
#### Problem

The monorepo has deprecated `Pubkey::new` in https://github.com/solana-labs/solana/pull/29805, and SPL still uses `Pubkey::new` in a few places.

#### Solution

Once 1.14.14 exists, remove all uses of `Pubkey::new` in favor of `Pubkey::try_from` and undo the workaround from #4007

**Comment by nahnicholas** [comment]
Ty

**Comment by joncinque** [comment]
This was done as part of  #4592
