### ISSUE TITLE
error Unable to resolve module crypto from/node_modules/@solana/spl-name-service/dist/utils.js: crypto could not be found within the project or in these directories:

### ISSUE THREAD

**Issue by sparshmartires** [solana-labs/solana-program-library#4028]
Showing All Messages
error Unable to resolve module crypto from/node_modules/@solana/spl-name-service/dist/utils.js: crypto could not be found within the project or in these directories:

**Comment by SpiceTank1** [comment]
Hello guys , I'm a designer looking for work for my agency - get in touch if you have work for us !
@fredrikparker ( LinkedIn , Telegram ) freddy@aadu.agency
