### ISSUE TITLE
Skipping freeze authority because this mint has none

### ISSUE THREAD

**Issue by TheOrcs** [solana-labs/solana-program-library#4050]
We ran into a problem that our tokens do not have freeze authority.

Can this problem be solved somehow?

```
   > Program log: Setting freeze authority
   > Program log: Skipping freeze authority because this mint has none
   > Program Metaplex Token Metadata consumed 26188 of 78361 compute units
```
![image](https://user-images.githubusercontent.com/96340327/218224765-8a7d9c5c-b5db-4ec8-a3eb-a744937a3d69.png)

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for developer support, and encourage you to ask your question on the Solana Stack Exchange https://solana.stackexchange.com/ or any other developer support forum / discord.
