### ISSUE TITLE
Numerical error in `amount_to_ui_amount`

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana-program-library#432]
Minor numerical error when casting from u64 to f64. Passing u64::MAX into the function, the result differs slightly since the resulting f64 value cannot completely represent the u64 value.

**Comment by mvines** [comment]
This only affects the presentation of a token balance of u64::MAX to the user in the token CLI, so this seems pretty minor

**Comment by jackcmay** [comment]
Yup, I'm fine with closing this issue as acceptable
