### ISSUE TITLE
token-js: Support transfer hook interface

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#4337]
#### Problem

The transfer-hook used by token-2022 complicates transfers since you may need to fetch additional accounts before creating a transfer instruction, and the JS library doesn't provide that functionality.

#### Solution

Add JS support for the transfer hook extension

**Comment by jerryarmstrong** [comment]
:vulcan_salute:

**Comment by wjthieme** [comment]
Is this currently being worked as this would be a lifesaver?

**Comment by buffalojoec** [comment]
We had a hand up from @jerryarmstrong on it!
