### ISSUE TITLE
createInitializeMintInstruction : ReferenceError: Can't find variable: Buffer

### ISSUE THREAD

**Issue by qertis** [solana-labs/solana-program-library#4494]
I am currently using the @solana/spl-token library in my project and encountered an error while attempting to use the createInitializeMintInstruction function. The error message states: "ReferenceError: Can't find variable: Buffer".

![image](https://github.com/solana-labs/solana-program-library/assets/3893228/3b872e48-218c-46ea-9164-a5b39b4ecfa9)

**Additional Information:**

<details>

```
"vue": "3.3.4"
"@solana/spl-token": "~0.3.8"
"@solana/web3.js": "~1.77.3"
```

```vue
<template>
  <span>EXAMPLE</span>
</template>

<script lang="ts" setup>
import { createInitializeMintInstruction } from '@solana/spl-token'
import { PublicKey } from '@solana/web3.js'

(async () => {
  try {
    // Initialize that account as a Mint
    createInitializeMintInstruction(
      new PublicKey('5tpiMLGAmsp6aWRoRSrM43WBjtbVtCFxjcbZTVxv6k7Q'),
      9,
      new PublicKey('5tpiMLGAmsp6aWRoRSrM43WBjtbVtCFxjcbZTVxv6k7Q'),
      new PublicKey('5tpiMLGAmsp6aWRoRSrM43WBjtbVtCFxjcbZTVxv6k7Q'),
    );
  } catch (e) {
    debugger
  }
})();
</script>
```

</details>

**Comment by wjthieme** [comment]
There is no direct support for Buffer in browser-based JavaScript. You will need to use a polyfill

**Comment by joncinque** [comment]
:point_up: is correct, closing
