### ISSUE TITLE
token-js: Expose `calculateFee` for mints with transfer fees

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#4513]
#### Problem

The rust side provides a nifty way to calculate a transfer fee using `calculate_fee` https://github.com/solana-labs/solana-program-library/blob/108e91e441e6633f046168536be571068e90169b/token/program-2022/src/extension/transfer_fee/mod.rs#L50, but wallets or JS clients can't use this.

#### Solution

Add an implementation for `calculateFee` in token-js.

**Comment by dhruvdabhi101** [comment]
I would like to try this issue

**Comment by joncinque** [comment]
Yep that's pretty much it. And it would also be good to add a helper like https://github.com/solana-labs/solana-program-library/blob/108e91e441e6633f046168536be571068e90169b/token/program-2022/src/extension/transfer_fee/mod.rs#L133 on `TransferFeeConfig`

**Comment by dhruvdabhi101** [comment]
I will try solve this issue then, if there is something i don't understand then please help me, since I'm beginner in Rust.

**Comment by pcellix** [comment]
@dhruvdabhi101 have you worked on it?
I would like to join as contributor as well :D

**Comment by joncinque** [comment]
Yep that's correct, https://github.com/solana-labs/solana-program-library/pull/4594 resolved it. Closing the issue
