### ISSUE TITLE
token-cli: Support transfer hook fully

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#4548]
#### Problem

The transfer-hook used by token-2022 complicates transfers since you may need to fetch additional accounts before creating a transfer instruction, and those accounts may be provided for offline signing.

On top of that, the regular create + update functionality needs to be provided too.

#### Solution

Add CLI support for the transfer hook extension

**Comment by buffalojoec** [comment]
Hey Jon! Is this still needed?

Sounds like:
- Wiring up the token client's permissioned transfer and create/update transfer hook extension/program ID to a CLI command
- Allowing retrieval of these accounts for offline signing

About the gist of it?

**Comment by joncinque** [comment]
Yes! I actually have a branch that does a bit of this, but then I wasn't sure of the best way to specify an account for offline signing in the command line... since we also need to know if the account is writable / signer, how do we do that? Like, should it be:

```
--transfer-hook-account <PUBKEY>:0:0
```

or

```
--transfer-hook-account <PUBKEY>:readonlysigner
```

Anyway, I put up #4916 so we can discuss there
