### ISSUE TITLE
token-cli: Support metadata pointer extension

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#4551]
#### Problem

With https://github.com/solana-labs/solana-program-library/pull/4549, token-2022 can also store a pointer to a metadata account, but this isn't exposed in the CLI except for setting authorities.

#### Solution

Add the functionality

**Comment by jim4067** [comment]
let me try this

**Comment by jim4067** [comment]
I would love to have a look at this.

Here is what I was thinking,

Add a subcommand to the `create-account` command called `metadata_address` that accepts the metadata pointer as an argument. 

Something like this `spl-token create-account <TOKEN_MINT>  --metadata_address <METADATA_ADDRESS>`

**Comment by joncinque** [comment]
Sounds good overall! Just to clarify, the extension exists on the mint, so you would have to add it to `create-token`, and to keep consistency with every other command, let's keep it kebab-case, and call it `metadata-address`

**Comment by jim4067** [comment]
thanks for the heads up 👍🏾 

How do I deal with the test failures?

**Comment by joncinque** [comment]
you probably need to build the required programs: token-2022, token, and associated-token-account, since they're loaded at https://github.com/solana-labs/solana-program-library/blob/016ba2487dc536ea62c6edf14201aff7f930877e/token/cli/src/main.rs#L4521-L4540

**Comment by jim4067** [comment]
I've tried building those programs but the tests seem to fail. 

For context, I am in the cli crate, and I am using `cargo test` 

Is there pre-requisites that I need set-up for my dev-env(I have the solana config set to devnet)?
