### ISSUE TITLE
single-pool: Consider relaxing the vote account discriminator check

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#4593]
#### Problem

The single-validator stake pool program uses the withdraw authority on the vote account to validate updates to the token metadata.

This works fine currently, but the vote state is getting an update in 1.16: https://github.com/solana-labs/solana/blob/f62d2318863f6385bcbee0691edc87ff643a4108/sdk/program/src/vote/state/vote_state_versions.rs#L7, which causes the deserialization to fail.

This was discovered while upgrading to 1.16 in #4592, and fixed there by also checking for the number "2" at https://github.com/solana-labs/solana-program-library/blob/3bb3b907dfd82207f71a740259f9fc39be1d85d1/stake-pool/single-pool/src/processor.rs#L227

This could be an issue going forward if any new vote state versions are added, causing the single pool program to fail.

#### Solution

Maybe we can relax the check and pass for any number greater than 0. I'm not convinced this is the best way, which is why I created an issue.

cc @2501babe

**Comment by 2501babe** [comment]
im in favor of adding 2 rather than removing the check, the point is to ensure a new version with a different layout at worst fails rather than exhibits undefined behavior. ultimately we need to upstream a way to get this field before we can freeze...
