### ISSUE TITLE
spl-token-cli: Inflexible keypair specification

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana-program-library#468]
#### Problem

`spl-token-cli` takes the keypair defined in the user-global solana CLI config file and uses it for all signing roles

#### Proposed solution

Support specifying all signing roles individually, like the `solana` CLI

**Comment by joncinque** [comment]
Closing this, since we can specify a fee-payer with the `--fee-payer` arg, the owner with the `--owner` arg, and authorities with the `--*-authority` arg, and the multisig signers too.
