### ISSUE TITLE
token-cli: Support updating metadata pointer extension

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#4701]
#### Problem

#4636 added support to initialize the metadata pointer extension in a new mint, but it still isn't possible to update the metadata pointer address.

#### Solution

Add a new top-level command, called `UpdateMetadataPointerAddress`, which calls `update_metadata_pointer_address`: https://github.com/solana-labs/solana-program-library/blob/fccc0919513d7939ff624d3a80db2b1b883ca8b3/token/client/src/token.rs#L1576

Currently, the most similar instruction is `update_default_account_state` https://github.com/solana-labs/solana-program-library/blob/fccc0919513d7939ff624d3a80db2b1b883ca8b3/token/cli/src/main.rs#L2305

**Comment by Rhythm-08** [comment]
Hello @joncinque , I am interested in this issue
Can you assign this issue to me.

**Comment by joncinque** [comment]
@Rhythm-08 Go for it! I typically only assign issues to team members, but if you send a PR for this, I'll gladly take a look!

**Comment by dhruvdabhi101** [comment]
If this issue is open to fix then I can give it a try. React to this comment if it's available.

**Comment by buffalojoec** [comment]
> If this issue is open to fix then I can give it a try. React to this comment if it's available.

Might just want to check with @Rhythm-08 , possibly collab ?!

**Comment by Rhythm-08** [comment]
> > If this issue is open to fix then I can give it a try. React to this comment if it's available.
> 
> Might just want to check with @Rhythm-08 , possibly collab ?!

Sure
