### ISSUE TITLE
stake-pool: Support metadata-pointer and token-metadata extensions

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#4717]
#### Problem

Stake pools enumerate the supported token-2022 extensions, but token-metadata and metadata-pointer are not included, which means that new stake pools can't take advantage of the new token-metadata standards.

#### Solution

Very simply, add `ExtensionType::MetadataPointer` and `ExtensionType::TokenMetadata` to `is_extension_supported_for_mint`. https://github.com/solana-labs/solana-program-library/blob/dd0f0ed70e6bf3c0ab83d764a3811d597234e725/stake-pool/program/src/state.rs#L494-L511

This is blocked until token-2022 has the `TokenMetadata` extension, which is expected to land in about a week.

**Comment by danpaul000** [comment]
@joncinque is this fixed by https://github.com/solana-labs/solana-program-library/pull/4770

**Comment by joncinque** [comment]
Ah yes, thanks!
