### ISSUE TITLE
discriminator / program-error: Constant recompilation in token-2022

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#4769]
#### Problem

Anytime there's a tiny change made in token-2022, a bunch of crates get recompiled. What's strange is that if you run `cargo test` once, make a whitespace change, then re-run `cargo test`, you'll see:

```
   Compiling spl-discriminator-syn v0.1.0 (/home/jon/src/solana/solana-program-library/libraries/discriminator/syn)
   Compiling spl-token-2022 v0.7.0 (/home/jon/src/solana/solana-program-library/token/program-2022)
```

And if you immediately run `cargo test` again without making any changes, you'll see:

```
   Compiling spl-discriminator-derive v0.1.0 (/home/jon/src/solana/solana-program-library/libraries/discriminator/derive)
   Compiling spl-discriminator v0.1.0 (/home/jon/src/solana/solana-program-library/libraries/discriminator)
   Compiling spl-type-length-value v0.2.0 (/home/jon/src/solana/solana-program-library/libraries/type-length-value)
   Compiling spl-tlv-account-resolution v0.2.0 (/home/jon/src/solana/solana-program-library/libraries/tlv-account-resolution)
   Compiling spl-token-metadata-interface v0.1.0 (/home/jon/src/solana/solana-program-library/token-metadata/interface)
   Compiling spl-transfer-hook-interface v0.1.0 (/home/jon/src/solana/solana-program-library/token/transfer-hook-interface)
   Compiling spl-token-2022 v0.7.0 (/home/jon/src/solana/solana-program-library/token/program-2022)
```

#### Solution

There was a partial solution attempted at #4766, but it still didn't resolve the issue.

Most likely, there's something getting recompiled due to a changing crate feature, but it's not clear where.

cc @buffalojoec

**Comment by buffalojoec** [comment]
Hey Jon, I'm having a hard time reproducing this issue on `master`. Any ideas on how else I might be able to trigger?

I've tried:
- `cargo clean` before each of the following
- Making a whitespace change in the `program2022` crate as described above
- Making a whitespace change in the `tests` dir of `program2022` as described above
- Making a code change in the `program2022` crate as described above
- Making a code change in the `tests` dir of `program2022` as described above
- All of the above with `cargo test`, `cargo test-sbf`, `cargo test --features serde-traits`, and `cargo test --features default`
- Upgraded from Solana CLI 1.16.1 to 1.16.4 and did the whole run-through again

I can confirm with `--verbose` that for me, it's only recompiling `spl-program-2022` each run.

Lmk

**Comment by joncinque** [comment]
Thanks for reporting that it worked on your side, looks like you're right. I tried this on an Ubuntu box and it works correctly as expected. Maybe this is one of those "arch linux broke something and I'm going to have to fix it". Sorry for the bother!
