### ISSUE TITLE
Missing multisign check

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana-program-library#477]
Problem: 
The validate_owner function does not verify that the signers are unique thus making it allowed for the same signer to sign an instruction multiple time, what this means is that the whole purpose of multi-signing is rendered moot

Proposed solution:
Only count a single signer once within the function, handle repeated cases by either ignoring them or returning an error code

**Comment by mvines** [comment]
In addition to fixing for v3, we should add a notice to the v2 docs that multisig doesn't work
