### ISSUE TITLE
Close Tree and get rent back

### ISSUE THREAD

**Issue by zsyborg** [solana-labs/solana-program-library#4789]
I have tried createCloseEmptyTreeIx and other similar functions i found while digging in the programs. I want to close the tree and get rent back. All it says that an unexpected "." is causing an error, i tried every thing possible

const redIx = await createCloseEmptyTreeIx(
  merkleTree: merkleTree.PublicKey,
  authority: merkleTree.PublicKey,
  recipient: keypair.PublicKey
): TransactionInstruction {
  return createCloseEmptyTreeInstruction({
    merkleTree,
    authority,
    recipient,
  });

**Comment by Ozodimgba** [comment]
I’m chasing this

**Comment by spirobel** [comment]
according to this :  https://solana.stackexchange.com/questions/7198/is-there-a-way-i-can-closee-all-the-tree-accounts-i-created-on-devnet it is not possible
