### ISSUE TITLE
Add constant splToken.MEMO_PROGRAM_ID

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-program-library#4895]
Currently the standard `memo` program `MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr` doesn't have a constant built in to splToken, so [docs on sending memos ask users to specify the constant manually](https://solanacookbook.com/references/basic-transactions.html#how-to-add-a-memo-to-a-transaction). 

This is consistent with other program address constants, like `splToken.TOKEN_PROGRAM_ID`.

```
splToken.MEMO_PROGRAM_ID = 'MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr'
```

We want to encourage the use of memos as it as memos human readability for transactions, and support for them is gaining among wallets.

**Comment by buffalojoec** [comment]
Seems reasonable to me! Thanks for pointing this out

**Comment by joncinque** [comment]
How about using it through the `@solana/spl-memo` package: https://github.com/solana-labs/solana-program-library/blob/5a6a34a9a69635b4307a650d5be44186719db49f/memo/js/src/index.ts#L4 ?
