### ISSUE TITLE
Introduce Library for Pod Types & Utils

### ISSUE THREAD

**Issue by buffalojoec** [solana-labs/solana-program-library#4915]
## Problem

`bytemuck` and `Pod` types are repeated across SPL.

### Description

SPL crates have been making more persistent use of `bytemuck` and it's associated `Pod` trait to perform byte-wise operations on account state and other buffers.

As this demand for `bytemuck` and Pod-compatible types grows, we've seen some code be duplicated across SPL crates.

Some examples can be seen in:
- [`spl-type-length-value`](https://github.com/solana-labs/solana-program-library/blob/master/libraries/type-length-value/src/pod.rs)
- [`spl-token-metadata-interface`](https://github.com/solana-labs/solana-program-library/blob/master/token-metadata/interface/src/state.rs#L22)
- [`spl-token-2022`](https://github.com/solana-labs/solana-program-library/blob/master/token/program-2022/src/pod.rs)

## Solution

Create a library for all `bytemuck` and `Pod` types and utils to be shared across these crates, and also publicly available to others.

**Comment by qiweiii** [comment]
I would like to try this!

**Comment by serbangv** [comment]
Started working on this.

**Comment by buffalojoec** [comment]
> Started working on this.

Thank you mate!
