### ISSUE TITLE
solana_token_audit#5: Example config file

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana-program-library#495]
Description
Since the CLI supports an optional config file, having an example config file somewhere in the
repo would be helpful.

Proof of Issue
Lack of config file in the repository

Severity and Impact Summary
Nothing, as it more of an informational and pedagogic comment for the future developers.

Recommendation:
Include an example config file in the repository.

**Comment by mvines** [comment]
I feel like this could just be a documentation change, "spl-token reuses the main `solana` command-line configuration file"

**Comment by jackcmay** [comment]
Think this is sufficient?
https://github.com/solana-labs/solana-program-library/blob/master/docs/src/token.md#configuration

I was thinking we could link to the main Solana CLI docs where it talks about config files but I couldn't find anything specific to the config file, just this: https://docs.solana.com/cli/conventions

**Comment by jackcmay** [comment]
@mvines 👀

**Comment by mvines** [comment]
> Think this is sufficient?
https://github.com/solana-labs/solana-program-library/blob/master/docs/src/token.md#configuration

Yep, that does the trick IMO
