### ISSUE TITLE
solana_token_audit#6: Naming convention of using 2 in method names

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana-program-library#496]
Description
The naming convention of having the instructions be called X and X2 (Approve, Approve2,
Transfer, Transfer2 etc.) does not explain anything about the difference between the
instructions and makes the system needlessly confusing.

Proof of Issue
Filename: token/program/src/instruction.rs

Severity and Impact Summary
This is more a problem in that if two or more declarations have unclear, or similar names there
may be a confusion if the right method is used or not.

Recommendation
Change the naming convention to better represent the difference between the instructions,
e.g. “approve” vs “approve_decimals”

**Comment by jackcmay** [comment]
@mvines, I guess we could call these `_checked`, _checked_decimals`, or something.  How lazy are you feeling? ;-)

**Comment by mvines** [comment]
I don't mind something like `_checked`: `Transfer` and `TransferChecked`
