### ISSUE TITLE
solana_token_audit#10: Inconsistent error check order

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana-program-library#500]
Description
Method process_transfer checks for the MintMismatch case before the AccountFrozen one,
most other functions checks for AccountFrozen first.

Proof of Issue
Method process_transfer
Filename: token/program/src/processor.rs
Beginning Line Number: 171

Severity and Impact Summary
The inconsistency in checking for a frozen account could lead to undefined results if something
will interfere with the execution. Keeping a consistent structure on the way that the checks are
made make the implementation more predictable in its behavior.

Recommendation
Change the order so that AccountFreeze is checked before MintMismatch

**Comment by jackcmay** [comment]
@CriesofCarrots Did you get a chance to review and fix this?

**Comment by CriesofCarrots** [comment]
On it right now

**Comment by CriesofCarrots** [comment]
The specific example of process_transfer is fixed, however.
