### ISSUE TITLE
[Token-2022] Transfer hook interface error reporting

### ISSUE THREAD

**Issue by febo** [solana-labs/solana-program-library#5042]
## Issue

There is currently an issue on how errors originating from the `transfer-hook-interface` are reported on the logs/client. Since the interface has its own `TransferHookError` error enum with overlapping codes (indices) with `TokenError` error enum, errors originating from the `transfer-hook-interface` get "translated" to a `TokenError` with the same code.

For example, if the extra accounts metas account is missing:
```rust
let validation_pubkey = get_extra_account_metas_address(mint_info.key, program_id);
let validation_info = additional_accounts
    .iter()
    .find(|&x| *x.key == validation_pubkey)
    .ok_or(TransferHookError::IncorrectAccount)?;
```

The error gets translated as `Lamport balance below rent-exempt threshold`, since both `TransferHookError::IncorrectAccount` and `TokenError::NotRentExempt` have an error code (index) of `0`.

A similar situation will happen if one of the accounts required for the transfer-hook program on-chain is missing: 
```rust
let account_info = account_infos
    .iter()
    .find(|&x| *x.key == account_meta.pubkey)
    .ok_or(AccountResolutionError::IncorrectAccount)?
    .clone();
cpi_account_infos.push(account_info);
```

`AccountResolutionError::IncorrectAccount` has an error code (index) of `0`.

Below is a sample output:
![image](https://github.com/solana-labs/solana-program-library/assets/729235/37d75d21-c590-4afc-8454-48bddfb60e20)

## Potential Solution

Errors originated from `transfer-hook-interface` and `tlv-account-resolution` could be mapped to individual `TokenError`s specific to the situation where they are generated – e.g., similar to how there seems to be errors for the `CpiGuard` and `ConfidentialTransfer`.

**Comment by joncinque** [comment]
Thanks for reporting this! I like your solution too, makes sense to me

**Comment by buffalojoec** [comment]
@febo Thanks for pointing this out, I'm happy to dive into this.

Seems like what's being proposed and agreed upon by @joncinque is just adding a slew of errors prefixed with `AccountResolution` or `TransferHook`, but wouldn't it make more sense to have some kind of hundred-place discriminator value as the error code?

In other words you'd have something like:

```rust
const ACCOUNT_RESOLUTION_ERROR_DISCRIM: u32 = 200
const TRANSFER_HOOK_ERROR_DISCRIM: u32 = 300

pub enum TokenError {
   ...
   AccountResolution(e: AccountResolutionError),
   TransferHook(e: TransferHookError),
   ...
}
```

and then you'd just modify this function:

https://github.com/solana-labs/solana-program-library/blob/1ef113180cc85cf8db2d2f1742878132f8143f6e/token/program/src/error.rs#L82C1-L86C2

to look something like this:

```rust
impl From<TokenError> for ProgramError {
    fn from(e: TokenError) -> Self {
        match e {
           TokenError::AccountResolutionError(err) => {
               ProgramError::Custom(
                   ACCOUNT_RESOLUTION_ERROR_DISCRIM + u32::from(err)
               )
           },
           TokenError::TransferHookError(err) => {
               ProgramError::Custom(
                   TRANSFER_HOOK_ERROR_DISCRIM + u32::from(err)
               )
           },
           _ => ProgramError::Custom(e as u32)
    }
}
```

**Comment by febo** [comment]
> In other words you'd have something like:
> 
> ```rust
> const ACCOUNT_RESOLUTION_ERROR_DISCRIM: u32 = 200
> const TRANSFER_HOOK_ERROR_DISCRIM: u32 = 300
> 
> pub enum TokenError {
>    ...
>    AccountResolution(e: AccountResolutionError),
>    TransferHook(e: TransferHookError),
>    ...
> }
> ```

I like this approach. The only observation is that I think it would not work with the `FromPrimitive` derive. My impression is that `FromPrimitive` derive only works with unitary enums – although we could always have the `FromPrimitive` trait "manually" implemented. The trait is useful for client code to convert the error code back to the error enum variant.

A bit unrelated question, but since we are talking about the `TokenError`, is there a reason for the `impl PrintProgramError` to not be something like:
```rust
impl PrintProgramError for TokenError {
    fn print<E>(&self)
    where
        E: 'static
            + std::error::Error
            + DecodeError<E>
            + PrintProgramError
            + num_traits::FromPrimitive,
    {
        msg!("Error: {}", self.to_string());
    }
}
```
Since `TokenError` derives `thiserror::Error`, the `Display` implementation is present for each variant using the `#[error("...")]` message.

**Comment by buffalojoec** [comment]
> The only observation is that I think it would not work with the `FromPrimitive` derive

Right I would just hand-crank that trait.



> A bit unrelated question, but since we are talking about the `TokenError`, is there a reason for the `impl PrintProgramError` to not be something like:

Ahh this is another good point. This ties into the whole idea of making our errors better overall, especially in `solana-program`.

In that spirit, it appears we can flex `thiserror` a lot more than we have been as well, leveraging input types for dynamic errors, etc.:

https://github.com/dtolnay/thiserror/blob/0495eaa802c73454ed6969fa1a3520db635bb901/src/lib.rs#L26-L28

**Comment by joncinque** [comment]
> A bit unrelated question, but since we are talking about the TokenError, is there a reason for the impl PrintProgramError to not be something like:

haha this goes way back, but doing the dynamic string formatting uses up a lot of compute units, so we hard-coded all the error strings.
