### ISSUE TITLE
token v3: Native mint supply should increase/decrease as users wrap/close accounts

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana-program-library#506]
The native mint in token2 currently reports 0 supply, regardless of actual wrapped accounts in circulation.
Update InitializeAccount and CloseAccount processing code to update native mint supply appropriately.

**Comment by CriesofCarrots** [comment]
This adjustment requires passing the native-mint account into `CloseAccount` instructions. Punting until v3.

**Comment by t-nelson** [comment]
@CriesofCarrots

This seems to be covered by #374, mind if we close this one?

**Comment by CriesofCarrots** [comment]
> @CriesofCarrots
> 
> This seems to be covered by #374, mind if we close this one?

Sure, I've no strong opinion, if you think the other issue details this need sufficiently.

**Comment by mvines** [comment]
Passing the mint into `CloseAccount` is not really viable anymore with Token2 and since we've basically implicitly that there'll never be a Token3 in the foreseeable future I don't think we need to track this limitation
