### ISSUE TITLE
Unable to Withdraw  from a Closed Validator

### ISSUE THREAD

**Issue by hjozwiak** [solana-labs/solana-program-library#5162]
Hello,

I am encountering an error when I am trying to withdraw staked SOL from a validator that has stopped operating. Is there a way  to free this SOL up, or is this not something supported yet by the stake pool program? I will attach the  logs from the dry run, if there is s  way to get more logs please let me know and I can attach them here.
[dryrun.txt](https://github.com/solana-labs/solana-program-library/files/12464834/dryrun.txt)

**Comment by joncinque** [comment]
Hi there, your pool's stake account delegated to that validator must have gotten destaked after the validator went delinquent for some time.

The current deployed program doesn't work with this, but the upcoming version handles this exact situation by optionally deactivating the decreased stake account https://github.com/solana-labs/solana-program-library/blob/8ae351d45de84ed5dc55edf3fd60b4551a802a46/stake-pool/program/src/processor.rs#L1459-L1468

**Comment by hjozwiak** [comment]
Is there an ETA for the upcoming version being deployed to mainnet?

**Comment by joncinque** [comment]
The foundation is working on establishing the multisig which will handle the program going forward. I can't tell you for sure, but I'm hoping it'll happen within a month

**Comment by joncinque** [comment]
The new version with the fix was deployed to mainnet last month, closing this issue
