### ISSUE TITLE
Replace broken package `mkdirp-promise`

### ISSUE THREAD

**Issue by rawfalafel** [solana-labs/solana-program-library#521]
* https://github.com/solana-labs/solana-program-library/blob/13de66817d7ff6c9885ac9cab01c2eeaf364f379/token-swap/js/client/util/store.js#L9
* https://github.com/solana-labs/solana-program-library/blob/13de66817d7ff6c9885ac9cab01c2eeaf364f379/token/js/client/util/store.js#L9

`mkdirp-promise` is broken and should be replaced with `mkdirp`

**Comment by mvines** [comment]
@rawfalafel - in what way is `mkdirp-promise` broken?

**Comment by rawfalafel** [comment]
Hi, sorry! My GitHub notifications were broken and I forgot about this until now.

`mkdirp-promise.mkdirp` never resolves. There's an issue here: https://github.com/ahmadnassri/mkdirp-promise/issues/89

Here's my console output:
```
master* $ npm run start                                                                                                     [16:20:07]

> @solana/spl-token-swap@0.0.1 start /home/rawfalafel/code/solana-program-library/token-swap/js
> babel-node --ignore node_modules cli/main.js

Run test: loadPrograms
Connection to cluster established: http://localhost:8899 { 'solana-core': '1.3.9 e45f1df5' }
Loading program: ../../target/bpfel-unknown-unknown/release/spl_token.so
Loading program: ../../target/bpfel-unknown-unknown/release/spl_token_swap.so
```
