### ISSUE TITLE
SPL-Name service program has not been updated to the latest version on-chain

### ISSUE THREAD

**Issue by ellttBen** [solana-labs/solana-program-library#5211]
Hi there,

Are there any plans to deploy the latest version of the spl_name_service program on-chain? The currently deployed version (Jan 27, 2022 at 16:25:20 UTC) is missing the critical account resizing feature. This has forced us to over-allocate most domain name accounts, which is costly to both users and the network.

Thanks for your help

**Comment by buffalojoec** [comment]
Hey there, I'm not sure if it's been planned but I'm assuming you're talking about mainnet-beta?

Let me see if we can do anything about that.
