### ISSUE TITLE
Create SPL Token Metadata JS Library

### ISSUE THREAD

**Issue by buffalojoec** [solana-labs/solana-program-library#5228]
With the addition of token metadata to Token2022 and the SPL Token Metadata interface itself to the SPL library, we need to support this cool feature & interface in JavaScript!

The goal here is to lay down a JavaScript library for SPL Token Metadata and then import it into `@solana/spl-token` for Token2022 metadata support.

This issue is for the Token Metadata library `@solana/spl-token-metadata`.

#### Problem
We have no JavaScript support for SPL Token Metadata.

#### Solution
Create a JavaScript library for the SPL Token Metadata Interface!
Dubbed `@solana/spl-token-metadata`

**Comment by mistersimon** [comment]
Hey @buffalojoec, would love to pick this up. 

Trying to wrap my head around the boundary between the functionality in @solana/spl-token vs @solana/spl-token-metadata - any pointers/thoughts?

Is the @solana/spl-token-metadata purely meant to be an interface, and then the functionality implemented in @solana/spl-token?

**Comment by buffalojoec** [comment]
> Is the @solana/spl-token-metadata purely meant to be an interface, and then the functionality implemented in @solana/spl-token?

Yeah, that's it! Think about it like this: other people should be able to use `@solana/spl-token-metadata` to interact with their own on-chain program, if it implements the interface, without needing to use `@solana/spl-token` (conceptually speaking).

**Comment by mistersimon** [comment]
Hey @buffalojoec thanks for the pointers - much appreciated. 

Let me work on this, probably take me a few days to get up to speed - hope to share something early next week. 

I always felt doing an interface in javascript a bit clunky, I think  @solana/spl-token-metadata could either be:
1. Pure typescript interface
2. Javascript class with no implementation - users will need to extend the class with functionality to get it to work. 

Would opt for option 1, unless you got any opinions - doesn't force people using the library to implement a class and haven't been able to find any precedence in the code base

**Comment by buffalojoec** [comment]
> Hey @buffalojoec thanks for the pointers - much appreciated.
> 
> Let me work on this, probably take me a few days to get up to speed - hope to share something early next week.
> 
> I always felt doing an interface in javascript a bit clunky, I think @solana/spl-token-metadata could either be:
> 
> 1. Pure typescript interface
> 2. Javascript class with no implementation - users will need to extend the class with functionality to get it to work.
> 
> Would opt for option 1, unless you got any opinions - doesn't force people using the library to implement a class and haven't been able to find any precedence in the code base

I would tend to lean toward option 1, but see what makes sense as you lay it down!

**Comment by mistersimon** [comment]
Hey @buffalojoec, 

Done a initial implementation - let me know if i'm on the right track. Theres a lot of boilerplate, but the key file is "token-metadata/js/src/instruction.ts"

If everything looks okay, as a next step would start working on the `@solana/spl-token` code. Perhaps as we work on that some changes are needed to this code.

https://github.com/solana-labs/solana-program-library/pull/5292

**Comment by buffalojoec** [comment]
> If everything looks okay, as a next step would start working on the `@solana/spl-token` code. Perhaps as we work on that some changes are needed to this code.

I just reviewed and left some feedback. I think let's get the interface library nailed down before moving to `spl-token`. Realistically, we should be able to have a fully completed and polished `spl-token-metadata` library before `spl-token` needs to be touched.
