### ISSUE TITLE
Add Token Metadata Support to `@solana/spl-token`

### ISSUE THREAD

**Issue by buffalojoec** [solana-labs/solana-program-library#5229]
With the addition of token metadata to Token2022 and the SPL Token Metadata interface itself to the SPL library, we need to support this cool feature & interface in JavaScript!

The goal here is to lay down a JavaScript library for SPL Token Metadata and then import it into @solana/spl-token for Token2022 metadata support.

This issue is importing and implementing `@solana/spl-token-metadata`.

Depends on #5228.

Problem
We have no JavaScript support for SPL Token Metadata when working with Token2022 in the `@solana/spl-token` JS library.

Solution
Import and implement `@solana/spl-token-metadata` to provide `@solana/spl-token` with support for Token2022's token metadata.

Depends on #5228.

**Comment by jedusor1** [comment]
This would be super useful indeed. Any news on the progress with this one?

**Comment by buffalojoec** [comment]
> This would be super useful indeed. Any news on the progress with this one?

#5292

**Comment by mistersimon** [comment]
Hey @buffalojoec, can check if i'm understanding what needs to be done correctly:

1. Import `createInstruction` functions from `@solana/spl-token-metadata` and re-export

1. Create `actions` that makes the call to the blockchain for each of the instructions, similar to:
https://github.com/solana-labs/solana-program-library/blob/master/token/js/src/actions/burn.ts

2. Create a function `getTokenMetadata` which calls gets the token instruction, similar to:
https://github.com/solana-labs/solana-program-library/blob/master/token/js/src/state/mint.ts#L75

**Comment by buffalojoec** [comment]
> Hey @buffalojoec, can check if i'm understanding what needs to be done correctly:
> 
> 1. Import `createInstruction` functions from `@solana/spl-token-metadata` and re-export
> 2. Create `actions` that makes the call to the blockchain for each of the instructions, similar to:
>    https://github.com/solana-labs/solana-program-library/blob/master/token/js/src/actions/burn.ts
> 3. Create a function `getTokenMetadata` which calls gets the token instruction, similar to:
>    https://github.com/solana-labs/solana-program-library/blob/master/token/js/src/state/mint.ts#L75

1 & 2 yes, you're correct. For 3, it's actually going to look a bit different.

Since the metadata in Token2022 is a `Mint` extension, we'll want to follow the existing pattern for fetching a mint (using the function you linked), and then unpacking the extension data for `TokenMetadata`. Like this:

https://github.com/solana-labs/solana-program-library/blob/367dff42aa0dc04058a8bb576c41faf436fce9eb/token/js/src/extensions/transferFee/state.ts#L92-L99

**Comment by mistersimon** [comment]
Okay, thanks for the guidance. Will put something together and we can take
it from there!

**Comment by buffalojoec** [comment]
Completed with #5667 !
