### ISSUE TITLE
README in @solana/spl-account-compression has 'docs here' link that 404s 

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-program-library#5244]
See https://www.npmjs.com/package/@solana/spl-account-compression

'docs here' points to https://solana-labs.github.io/solana-program-library/account-compression/sdk/docs/ which is a 404.

https://github.com/solana-labs/solana-program-library/blob/282c716910b88e28495d5fb20143848bc01f79d5/account-compression/sdk/README.md?plain=1#L3

Also we should avoid 'here' links, they're bad for SEO, people scanning the page, training ML answers etc. It's better to use something like 

> see the [Solana account compression docs](https://example.com).

**Comment by mikemaccana** [comment]
https://solana-labs.github.io/solana-program-library/account-compression/sdk/ also seems to work.

**Comment by joncinque** [comment]
> It looks like the compression docs have been (maybe) accidentally deployed to https://solana-labs.github.io/solana-program-library/index.html.

That was my mistake, sorry! https://solana-labs.github.io/solana-program-library/account-compression/sdk is the correct link. And please feel free to just do a pull request directly when you notice something like this! Looks like Joe took care of it though
