### ISSUE TITLE
[spl-account-compression] Support more tree heights between 5 and 14

### ISSUE THREAD

**Issue by richardwu** [solana-labs/solana-program-library#5286]
The tree depths supported currently have a gap between height 5 and 14.

For shallow canopy trees, this is not a big issue since the difference in space + rent is quite small.

However, for full canopy trees (height = canopy depth), the difference between a height 5 and depth 14 is 7.4 SOL:

<img width="519" alt="image" src="https://github.com/solana-labs/solana-program-library/assets/10563314/e6628c7a-1fff-4f76-a9a5-847f85a94120">
<img width="524" alt="image" src="https://github.com/solana-labs/solana-program-library/assets/10563314/92b4bc54-762f-4e8d-999f-1aac478420bf">

A use case where tree heights between 5 to 14 is desired is in Bubblegum https://github.com/metaplex-foundation/mpl-bubblegum. Since some state is tied to the tree itself (eg a flag that lets someone decompress a cNFT into a legacy NFT), one might want to create an isolated tree for a given collection.

**Comment by ngundotra** [comment]
Hey @richardwu what heights & buffer sizes do you want to see supported?

**Comment by richardwu** [comment]
Possible to do h = 6, 7, 8, 9, 10, 11, 12, 13, where maybe buffer size:

h <= 8, b = 16
h <= 13, b = 32
