### ISSUE TITLE
spl-token (getAccount || unpackAccount) issue: Do not know how to serialize a BigInt.

### ISSUE THREAD

**Issue by FraNoceti** [solana-labs/solana-program-library#5365]
Hi I'm trying to get Aoounts info but the deserializer is giving this issues, tried also switching between node versions. Any clue? 

Error I'm getting:
```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at serializeJavascriptValueToJSONString
```

**Comment by buffalojoec** [comment]
Hey there, typically we'd love to see developer support questions asked on <https://solana.stackexchange.com/>.

If you still have issues please post on there!

At first glance, it looks like you're trying to `JSON.stringify()` on an object whose fields contain one or more `bigint`s.

You have to define custom "stringifying" for `bigint` with `JSON.stringify()`, as it's not natively supported.
<https://github.com/GoogleChromeLabs/jsbi/issues/30>

**Comment by iMrDJAi** [comment]
@FraNoceti
```js
const JSONReplacer = (_, val) => typeof val === 'bigint' ? `${val}` : val
console.log(JSON.stringify(accountInfo, JSONReplacer, 2))
```
