### ISSUE TITLE
[spl-token-2022]: Allow serialisation/deserialisation for token-2022 extensions

### ISSUE THREAD

**Issue by nikhil-helius** [solana-labs/solana-program-library#5431]
Hey guys,  I am planning to add support for `token-2022` indexing. In order to do this, I would like to have all the extensions support serialising/de-serialising. Is it ok if I create a PR to support this via the `serde-trait` feature-flag? Is there any reason not to do this?

**Comment by buffalojoec** [comment]
Sounds good! Thanks!

**Comment by nikhil-helius** [comment]
Is there a way to get this in having `solana-1.16` dependency? I see that the latest code requires `1.17`?

**Comment by buffalojoec** [comment]
Where do you see that requirement?
https://github.com/solana-labs/solana-program-library/blob/d97f735de7d435ef2207f20b6efd8631cefac345/token/program-2022/Cargo.toml#L26

**Comment by nikhil-helius** [comment]
When I specify the path locally 

```
spl-token-2022 =  { path = "../../../solana/solana-program-library/token/program-2022" }
```
I see this error 

```

all possible versions conflict with previously selected packages.

  previously selected package `solana-program v1.17.0`
    ... which satisfies dependency `solana-program = "=1.17.0"` of package `solana-sdk v1.17.0`
    ... which satisfies dependency `solana-sdk = "=1.17.0"` of package `solana-zk-token-sdk v1.17.0`
    ... which satisfies dependency `solana-zk-token-sdk = "^1.16.13"` of package `spl-pod v0.1.0 (/Users/nikhil/helius/solana/solana-program-library/libraries/pod)`
    ... which satisfies path dependency `spl-pod` of package `spl-tlv-account-resolution v0.4.0 (/Users/nikhil/helius/solana/solana-program-library/libraries/tlv-account-resolution)`
    ... which satisfies path dependency `spl-tlv-account-resolution` of package `spl-transfer-hook-interface v0.3.0 (/Users/nikhil/helius/solana/solana-program-library/token/transfer-hook-interface)`
    ... which satisfies path dependency `spl-transfer-hook-interface` of package `spl-token-2022 v0.9.0 (/Users/nikhil/helius/solana/solana-program-library/token/program-2022)`
  ```
  
 The root of this conflict is that solana-zk-token-sdk v1.17.0 depends on solana-sdk v1.17.0, which in turn depends on solana-program v1.17.0.

**Comment by buffalojoec** [comment]
Ah nuts. We'd have to go pin _a lot_ of stuff to `<1.17.0` and we don't typically do that in SPL unless there's a major problem. Are you guys unable to use `1.17.0`?

**Comment by nikhil-helius** [comment]
Probably not. We're still in between upgrading to `1.16` and that's a heavy lift for us on our infra. Don't think we can use `1.17` now. 
I did create a [PR](https://github.com/solana-labs/solana-program-library/pull/5437). Is there a way to hotfix it to an older release so we can use it with `1.16`? Other alternate is to shadow all the extension interfaces on our codebase temporarily and use that to index the extensions till we upgrade to `1.17` but I would like to avoid this if possible.

**Comment by nikhil-helius** [comment]
Yes, we're hard-fixing to `1.16.15`. Right now, we're using `spl-token22-0.9`. Will we get a release for the PR? Any idea when we can get it in?

**Comment by nikhil-helius** [comment]
bump @buffalojoec

**Comment by buffalojoec** [comment]
Adding more `serde` support shouldn't be a breaking change, so I don't think we'll do a minor release. We'll probably just do a patch release.
