### ISSUE TITLE
[spl-token-2022-js]: Add `SetTransferFee` instruction

### ISSUE THREAD

**Issue by iMrDJAi** [solana-labs/solana-program-library#5451]
While it's possible to create a Mint with a transfer fee in TypeScript with `createInitializeTransferFeeConfigInstruction()`, there seem to be no way to update the fee later.

**Comment by buffalojoec** [comment]
Ah, thanks for calling this out, looks like we just need to add the functions to support `SetTransferFee` in a similar fashion to the others!

**Comment by sam41306061** [comment]
Hello @buffalojoec , Is this issues still open at the moment?

**Comment by buffalojoec** [comment]
> Hello @buffalojoec , Is this issue still open at the moment? 

Yes, appears so! Would you like to work on it?

**Comment by sam41306061** [comment]
@buffalojoec Yeah, I would like to take a crack at it. For context, do you have a repo or project where you are using this where I can see exactly what you outlined above?

**Comment by buffalojoec** [comment]
> @buffalojoec Yeah, I would like to take a crack at it. For context, do you have a repo or project where you are using this where I can see exactly what you outlined above?

https://github.com/solana-labs/solana-program-library/blob/5ce6eace7c128c3eb5686e02de983ee431b73ce1/token/js/src/extensions/transferFee/instructions.ts#L63-L89

We're missing a function like this for `SetTransferFee`.

**Comment by buffalojoec** [comment]
Rust side:

https://github.com/solana-labs/solana-program-library/blob/5ce6eace7c128c3eb5686e02de983ee431b73ce1/token/program-2022/src/extension/transfer_fee/instruction.rs#L397-L422

**Comment by nasjuice** [comment]
Hello, 

I added a PR for this here
https://github.com/solana-labs/solana-program-library/pull/6678
