### ISSUE TITLE
spl-token-cli: Not possible to create a token account without owner keypair

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#548]
#### Problem
The `spl-token-cli create-account` command takes an `--owner` argument which is required to be a keypair. This is overly restrictive because the owner doesn't need to be a signer for the transaction to succeed. Specifying an address is sufficient and it's convenient to create token accounts for your friends in order to transfer tokens!

#### Proposed Changes
Move away from a global "owner" argument in the CLI program and have a specific "owner" arg for the `create-account` subcommand which accepts either a public key or keypair

**Comment by CriesofCarrots** [comment]
Similarly, the owner arg in `spl-token accounts` need only be a public key
