### ISSUE TITLE
Create SPL Token Group JS Library

### ISSUE THREAD

**Issue by buffalojoec** [solana-labs/solana-program-library#5648]
With the addition of token groups to Token2022 and the SPL Token Group interface itself to the SPL library, we need to support this cool feature & interface in JavaScript!

The goal here is to lay down a JavaScript library for SPL Token Group and then import it into `@solana/spl-token` for Token2022 group support.

This issue is for the Token Group library `@solana/spl-token-group`.

Problem
We have no JavaScript support for SPL Token Group.

Solution
Create a JavaScript library for the SPL Token Group Interface!
Dubbed `@solana/spl-token-group`

---

Note: this is the exact same process/request as #5228 

It might help to explore the `@solana/spl-token-metadata` package to get an idea for how the Token Group one might look!

**Comment by buffalojoec** [comment]
cc @mistersimon if you're interested!

**Comment by mistersimon** [comment]
Yeah @buffalojoec happy to pick this up. Should be able to get something up by the end of the week. 

Looks like it should be straightforward, will follow the structure we did for `@solana/spl-token-metadata`

**Comment by buffalojoec** [comment]
> Yeah @buffalojoec happy to pick this up. Should be able to get something up by the end of the week.
> 
> Looks like it should be straightforward, will follow the structure we did for `@solana/spl-token-metadata`

No rush, mate, and yes exactly!

**Comment by mistersimon** [comment]
Just to update - wanted to finish https://github.com/solana-labs/solana-program-library/issues/5229 first before jumping on this. 

Unlikely i'll be able to get started on this until after Christmas. Happy for someone else to take over if theres a need

**Comment by qiweiii** [comment]
I could try this

**Comment by qiweiii** [comment]
@buffalojoec @mistersimon I tried to implement this in #6014, please check it out when have time, thanks!
