### ISSUE TITLE
transfer-hook: Important differences between js client and rust offchain client

### ISSUE THREAD

**Issue by mechmind** [solana-labs/solana-program-library#5686]
While digging code for clean-room implementation I found pretty serious differences between those two clients in handling of transfer hook additional account addresses. Those differences arise when computing seeds for derived program addresses from ExtraAccountMeta.
They are important enough to break compatibility.

1. JS client do not use "privilege de-escalation" for derived program accounts. Rust client uses it when address just got computed in [state.rs#L290](https://github.com/solana-labs/solana-program-library/blob/98aa8aa836e44dcdd668683fdfae7dce7348cfdf/libraries/tlv-account-resolution/src/state.rs#L290);
2. Rust client does have additional seed source type `Seed::AccountData` that JS does not support;
3. **Most importantly** JS and Rust clients build arrays of addresses differently. 
JS takes addresses from instruction, then adds hookmeta account to list and then resolves new addresses from account meta and them to array. Source: [transferHook/instructions.ts#L156](https://github.com/solana-labs/solana-program-library/blob/98aa8aa836e44dcdd668683fdfae7dce7348cfdf/token/js/src/extensions/transferHook/instructions.ts#L156)
Rust takes addresses from instruction, then resolves new addresses and then adds hookmeta account to that list. Source: [offchain.rs#L61](https://github.com/solana-labs/solana-program-library/blob/98aa8aa836e44dcdd668683fdfae7dce7348cfdf/token/transfer-hook/interface/src/offchain.rs#L61)
Although comment states that order of pushing does not matter it indeed is. Since seed resolver can use not only original instruction addresses but also newly added addresses from previous resolves and referenes them by index then incorrect version of code will take different account as seed and transaction will break.

**Comment by buffalojoec** [comment]
Thanks for these findings! I appreciate you being so thorough.

I'll investigate the differences and bring them to parity.
