### ISSUE TITLE
How to integrate Confidential transfer to DAPP.  Js confidential transfer seems not finish？

### ISSUE THREAD

**Issue by peter-jim** [solana-labs/solana-program-library#5724]
I had read source code of spl-token package , It seems not offer method to Confidential transfer,How can I use it?

**I want to integrate this feature into my wallet** ，thank you!

**Comment by buffalojoec** [comment]
Hey @peter-jim that's right this feature is not yet available in the `@solana/spl-token` JavaScript package. We're still iterating on the Rust implementation, and once that's finalized we can move to JS.

Once we're ready to go, we can throw some issues up for people who want to maybe help with that effort, such as maybe yourself! Keep an eye out, thanks.
