### ISSUE TITLE
How to run cargo test on solana-program-library/token/program-2022-test?

### ISSUE THREAD

**Issue by peter-jim** [solana-labs/solana-program-library#5789]
When I use 'cargo test' or use specific "cargo test --test confidential_transfer -- confidential_transfer_fee_config", I always get `running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s`

thank you

**Comment by buffalojoec** [comment]
Hey there, thanks for cloning SPL down and messing around! Unfortunately, the issues section isn't for development help, it's for reporting bugs or enhancements to the code within!

You need to run `cargo test-sbf` and you'll want to do it from within the crate's root of the program you wish to test.
