### ISSUE TITLE
[spl-stake-pool] not able to import types from JS package 

### ISSUE THREAD

**Issue by aaronovz1** [solana-labs/solana-program-library#5888]
Cannot import types such as `StakeAccount` in a React 18 application.

![image](https://github.com/solana-labs/solana-program-library/assets/20787054/f7b2924d-3407-4bac-9946-3e2f67748733)

The underlying library also appears to use `superstruct` which looks like overkill?

For now we just need the things that are marked for export to actually be exported and usable.

Project reproducing the issue: https://github.com/aaronovz1/stake-pool-issues

**Comment by buffalojoec** [comment]
I don't necessarily have a problem exporting these types, but it looks like they were intentionally left out of the exports:

https://github.com/solana-labs/solana-program-library/blob/177a6c94d751e49be0e299b0155823195a21e7fe/stake-pool/js/src/index.ts#L46-L48

In the meantime, you should be able to get by with a type alias like this:

```ts
type StakeAccount = Awaited<ReturnType<typeof getStakeAccount>>;
```

I also wonder if we should just include these in `@solana/web3.js` under the Stake Program submodule.

**Comment by aaronovz1** [comment]
Your suggestion partially works but we have a function which converts an `AccountInfo` into a `StakeAccount` but this can't be done as the superstruct method `create` can't take just the `StakeAccount` type for the second param.

```
export function accountInfoToStakeAccount(account: AccountInfo<Buffer | ParsedAccountData>): StakeAccount | undefined {
  return ("parsed" in account?.data && create(account.data.parsed, StakeAccount)) || undefined;
}
```

`'StakeAccount' only refers to a type, but is being used as a value here.`

A similar thing is done here https://github.com/solana-labs/solana-program-library/blob/177a6c94d751e49be0e299b0155823195a21e7fe/stake-pool/js/src/index.ts#L129 but we load a number of accounts within one gMA call, so need access to parsing the account separate to a single gAI call.

**Comment by buffalojoec** [comment]
So, this library is specific to the Stake Pool program. The type `StakeAccount` is the `jsonParsed` account data for an account owned by the Stake Program, so it doesn't belong in this library as an exported member of Stake Pool.

Technically, if it was to be exported anywhere, it would be the legacy `@solana/web3.js`, under `programs/stake`.

With that being said, there will soon be a new client library specifically for the Stake Pool program, where types for the program's account state will be available. Considering we don't currently export `jsonParsed` types for accounts at the moment, it might make sense to wait until that library is available.

> The underlying library also appears to use `superstruct` which looks like overkill?

I'm a little bit confused why you consider the use of superstruct in `@solana/spl-stake-pool` to be overkill, but you're also using it in your library?

With that being said, and considering my points above, is there another way you can do this without superstruct, or do you need this library? Maybe something like:

```ts
type StakeAccount = Awaited<ReturnType<typeof getStakeAccount>>;

export function accountInfoToStakeAccount(account: AccountInfo<Buffer | ParsedAccountData>): StakeAccount | undefined {
  return 'parsed' in account?.data ? account.data.parsed as StakeAccount : undefined;
}
```

**Comment by aaronovz1** [comment]
Sorry for late response - using your example we can get away with not using superstruct. It was just there from some old legacy code. I think this can be closed now thanks.
