### ISSUE TITLE
Clone repo, I'm able to compile the contract but on my JS code for @solana/spl-tools, not able to find module as pnpm doesn't save after running pnpm install @solana/spl-tools. I tried 3 different times, package manager is messed up

### ISSUE THREAD

**Issue by bps1980** [solana-labs/solana-program-library#5893]

**Comment by joncinque** [comment]
Sorry, `@solana/spl-tools` does not exist anywhere in this repo. Can you give more details about what you're trying to do and the error that you're seeing?

**Comment by bps1980** [comment]
Sorry I’m hallucinating, I meant spl-tokens not tools

**Comment by bps1980** [comment]
It’s @solana/spl-tokens and it’s not a js code for smart contracts. Smart Contracts are written in rust.

This is to connect to the blockchain. Here is the .js code:

const { Token, TOKEN_PROGRAM_ID } = ***@***.***/spl-token");
const { Connection, PublicKey, Keypair } = ***@***.***/web3.js");

async function main() {
    // Your existing mint, payer, and recipient details
    const mintPublicKey = new PublicKey("");
    const recipientTokenAccount = new PublicKey("");
    const payerKeypair = Keypair.generate(); // Your account that will pay for the transaction

    // Establish a connection to the cluster
    const connection = new Connection(link<https://rpc.ankr.com/solana_devnet/a62e9ca39b1ccedf47c1bd02af472a2438212b774438f46c4b8b10b3cb681d36>, "confirmed");

    // Create a new token instance
    const token = new Token(
        connection,
        mintPublicKey,
        TOKEN_PROGRAM_ID,
        payerKeypair // Use the payer's keypair for signing transactions
    );

    // Amount to mint (consider decimals)
    const amountToMint = 150000000; // Adjust based on your token's decimals

    // Minting new tokens to the recipient's token account
    await token.mintTo(
        recipientTokenAccount, // Token account of the recipient
        payerKeypair.publicKey, // Payer of the transaction
        [], // Multisig owners (if applicable)
        amountToMint // Amount to mint
    );

    console.log(`Minted ${amountToMint} tokens to ${recipientTokenAccount.toString()}`);
}

main().catch(err => {
    console.error("Error executing the script:", err);
});
