### ISSUE TITLE
return funds from scam accont

### ISSUE THREAD

**Issue by abaykanat** [solana-labs/solana-program-library#5972]
hi developers!
help me, please...
I was waiting for staking to be activated and while waiting I followed the link received through nft. After that, my staking account changed owner to another address.
This account already has many victims, but does not withdraw funds from staking. This address **does not have an owner program**. Is it possible to somehow return staking accounts with funds to their owners?
my account: 7ZxRGZcKRgARNe35fPq6rkfdTWBZQe3KdofEnBmBeZzu
my stake account: FuAqLX55WcSkSdVYtpmRWDvpC71YiezvkzcN4RYjHNd8
scammer account: 9rsYjYAzT8NtHDsdwDp2eP7pqTWHjs6CJCzmCySLtXGm
transaction to change the owner of my stake account: https://solanabeach.io/transaction/5AmutirdmMujU6hLXJezB9d3NcQsN3sgCrz1FHgHxKw3GKKye3Updyz3Dc4myuaBaZxEfmfrR7bzycj2RXJqaTK4

**Comment by buffalojoec** [comment]
Hey, really sorry to hear you got scammed!

Unfortunately this is not the place to report such an event or ask for assistance. I’m not sure who could really help with that.

Regardless, this repository is for engineering efforts only, so I'll be closing this.

**Comment by abaykanat** [comment]
hello!
I think you and developers can help by closing the loophole/vulnerability for scammers and returning the money to the deceived user. Here's how I suggest doing it:
1. prohibit changing Stake Authority Address and Withdraw Authority Address if the stake account is waiting for the start of a new epoch to be activated. this will protect many people and they will not lose their stake account, like me and many others;
2. after deactivating staking, return deactivating sol to the address that created this stake account. this will return the sol to its true owners.
Example:
my account 7ZxRGZcKRgARNe35fPq6rkfdTWBZQe3KdofEnBmBeZzu created a stake account FuAqLX55WcSkSdVYtpmRWDvpC71YiezvkzcN4RYjHNd8 (https://solscan.io/tx/51AKRzWTtZDrfg5Mf1RPLLdxcRLxHWuHQ mK5kKyAGQbssaU3Q3CM5Qo59DEcKVqySp681Lhr5oUVguraShNP6xiu). but in the next transaction the scammers changed the Stake Authority Address and Withdraw Authority Address in this account (https://solscan.io/tx/5AmutirdmMujU6hLXJezB9d3NcQsN3sgCrz1FHgHxKw3GKKye3Updyz3Dc4myuaBaZxEfmfrR7bzycj2RXJqaTK4).
It is necessary that after deactivating staking, Solana returns to my address 7ZxRGZcKRgARNe35fPq6rkfdTWBZQe3KdofEnBmBeZzu, which created the stake address FuAqLX55WcSkSdVYtpmRWDvpC71YiezvkzcN4RYjHNd8.

**Comment by abaykanat** [comment]
can I register two different tickets for these two cases?

**Comment by joncinque** [comment]
Again, we're sorry to hear that you were scammed. Unfortunately, the changes that you outline will just end up creating a worse experience for users and slightly change how attackers carry out their scams, without actually protecting users.

I'm locking this issue.
