### ISSUE TITLE
Docs: Suggested app is deprecated in Token Documentation

### ISSUE THREAD

**Issue by jmanywhere** [solana-labs/solana-program-library#6031]
Under `/token#transferring-tokens-between-wallets` it suggests using `sollet.io` however that app has been deprecated and doing a google search, malicious imitators pop up requesting sensitive data.

Would recommend removing the suggestion entirely or update to a more permanent suggestion.

![image](https://github.com/solana-labs/solana-program-library/assets/41244007/64097001-2486-4ed6-943c-36345fbda1ed)

**Comment by CriesofCarrots** [comment]
Agreed. Thanks for creating the issue.
