### ISSUE TITLE
Token JS: Use `COptionPubkeyLayout` for all `COption` fields

### ISSUE THREAD

**Issue by buffalojoec** [solana-labs/solana-program-library#6170]
After #6164, we now have a serialization layout for `COption<Pubkey>`, where a `None` value is represented by a single `0`, while `Some(Pubkey)` is represented by a `1` plus the public key bytes.

There are a handful more instructions in Token2022 that use `COption<Pubkey>`. Here are a few examples:

https://github.com/solana-labs/solana-program-library/blob/8b22d759fef30795eff99385f15ae1c4380eeb90/token/program-2022/src/instruction.rs#L474-L482

https://github.com/solana-labs/solana-program-library/blob/8b22d759fef30795eff99385f15ae1c4380eeb90/token/program-2022/src/instruction.rs#L549-L553

Update their JavaScript instruction builders to use the new layout!

**Comment by qiweiii** [comment]
would like to work on this!
