### ISSUE TITLE
token-js: Add TokenGroup support

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#6175]
#### Problem

The TokenGroup, TokenGroupMember, GroupPointer, and GroupMemberPointer extensions are all in the token-2022 program, and the two pointer extensions are live on all networks, but they aren't supported in `@solana/spl-token`.

The `TokenGroup` and `TokenGroupMember` have a JS library at https://github.com/solana-labs/solana-program-library/tree/master/token-group/js

#### Proposed Solution

Similar to #5667, add support for these extensions by incorporating `@solana/spl-token-group` into `@solana/spl-token`

**Comment by buffalojoec** [comment]
The pointers have been added! Now we just need support for the Token Group interface, similarly to Token Metadata, by making use of the existing `@solana/spl-token-group` package!

**Comment by qiweiii** [comment]
I can add that!

**Comment by ErwanTouba** [comment]
Hello there, i'm having an issue and after googling my error i landed here.
Might be of interest for you:

    "@solana/spl-token": "^0.4.2",
    "@solana/web3.js": "^1.91.1",




`✔ Vite server hmr 9 files in 19.54ms

 WARN  [Vue Router warn]: uncaught error during route navigation:


 ERROR  The requested module '@solana/spl-token-group' does not provide an export named 'TOKEN_GROUP_MEMBER_SIZE'

  TOKEN_GROUP_MEMBER_SIZE,
  ^
  
  SyntaxError: The requested module '@solana/spl-token-group' does not provide an export named 'TOKEN_GROUP_MEMBER_SIZE'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)


 WARN  [Vue Router warn]: uncaught error during route navigation:


 ERROR  The requested module '@solana/spl-token-group' does not provide an export named 'TOKEN_GROUP_MEMBER_SIZE'

  TOKEN_GROUP_MEMBER_SIZE,
  ^
  
  SyntaxError: The requested module '@solana/spl-token-group' does not provide an export named 'TOKEN_GROUP_MEMBER_SIZE'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)


 WARN  Cannot stringify arbitrary non-POJOs SyntaxError

✘ [ERROR] No matching export in "node_modules/@solana/spl-token-group/lib/esm/index.js" for import "TOKEN_GROUP_SIZE"

    node_modules/@solana/spl-token/lib/esm/extensions/tokenGroup/actions.js:2:154:
      2 │ ...n, createUpdateGroupMaxSizeInstruction, createUpdateGroupAuthorityInstruction, createInitializeMemberInstruction, TOKEN_GROUP_SIZE, TOKEN_GROUP_MEMBER_SIZE, } from '@solana/spl-token-group';
        ╵                                                                                                                      ~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@solana/spl-token-group/lib/esm/index.js" for import "TOKEN_GROUP_MEMBER_SIZE"

    node_modules/@solana/spl-token/lib/esm/extensions/tokenGroup/actions.js:2:172:
      2 │ ...n, createUpdateGroupMaxSizeInstruction, createUpdateGroupAuthorityInstruction, createInitializeMemberInstruction, TOKEN_GROUP_SIZE, TOKEN_GROUP_MEMBER_SIZE, } from '@solana/spl-token-group';
        ╵                                                                                                                                        ~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@solana/spl-token-group/lib/esm/index.js" for import "TOKEN_GROUP_SIZE"

    node_modules/@solana/spl-token/lib/esm/extensions/tokenGroup/state.js:4:9:
      4 │ export { TOKEN_GROUP_SIZE, TOKEN_GROUP_MEMBER_SIZE } from '@solana/spl-token-group';
        ╵          ~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@solana/spl-token-group/lib/esm/index.js" for import "TOKEN_GROUP_MEMBER_SIZE"

    node_modules/@solana/spl-token/lib/esm/extensions/tokenGroup/state.js:4:27:
      4 │ export { TOKEN_GROUP_SIZE, TOKEN_GROUP_MEMBER_SIZE } from '@solana/spl-token-group';
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@solana/spl-token-group/lib/esm/index.js" for import "TOKEN_GROUP_SIZE"

    node_modules/@solana/spl-token/lib/esm/extensions/tokenGroup/state.js:4:9:
      4 │ export { TOKEN_GROUP_SIZE, TOKEN_GROUP_MEMBER_SIZE } from '@solana/spl-token-group';
        ╵          ~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@solana/spl-token-group/lib/esm/index.js" for import "TOKEN_GROUP_MEMBER_SIZE"

    node_modules/@solana/spl-token/lib/esm/extensions/tokenGroup/state.js:4:27:
      4 │ export { TOKEN_GROUP_SIZE, TOKEN_GROUP_MEMBER_SIZE } from '@solana/spl-token-group';
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~


 ERROR  error while updating dependencies:                                                                                                                                                     3:50:40 PM
Error: Build failed with 6 errors:
node_modules/@solana/spl-token/lib/esm/extensions/tokenGroup/actions.js:2:154: ERROR: No matching export in "node_modules/@solana/spl-token-group/lib/esm/index.js" for import "TOKEN_GROUP_SIZE"
node_modules/@solana/spl-token/lib/esm/extensions/tokenGroup/actions.js:2:172: ERROR: No matching export in "node_modules/@solana/spl-token-group/lib/esm/index.js" for import "TOKEN_GROUP_MEMBER_SIZE"
node_modules/@solana/spl-token/lib/esm/extensions/tokenGroup/state.js:4:9: ERROR: No matching export in "node_modules/@solana/spl-token-group/lib/esm/index.js" for import "TOKEN_GROUP_SIZE"
node_modules/@solana/spl-token/lib/esm/extensions/tokenGroup/state.js:4:9: ERROR: No matching export in "node_modules/@solana/spl-token-group/lib/esm/index.js" for import "TOKEN_GROUP_SIZE"
node_modules/@solana/spl-token/lib/esm/extensions/tokenGroup/state.js:4:27: ERROR: No matching export in "node_modules/@solana/spl-token-group/lib/esm/index.js" for import "TOKEN_GROUP_MEMBER_SIZE"`

**Comment by buffalojoec** [comment]
@ErwanTouba Thanks for reporting. Solution was published.
https://github.com/solana-labs/solana-program-library/releases/tag/token-js-v0.4.3
