### ISSUE TITLE
[Token-2022] [Feature] Allow The Transfer Fee Withdraw Authority To Update Itself

### ISSUE THREAD

**Issue by GageBachik** [solana-labs/solana-program-library#6220]
**Problem**

Once the "createInitializeTransferFeeConfigInstruction" has been used there's no way for the Withdraw Withheld Fees Authority to change who can withdraw the fees. 

**Solution**
Consider allowing the Withdraw Withheld Fees Authority on the Transfer Fee Config to update itself to another account.

**Thoughts**
Token owners should be able to pass this ability to on-chain programs / services so they can manage fees in interesting ways including swaps, holder re-dispersions, and auto LP strategies among other things.

**Comment by buffalojoec** [comment]
Sorry, maybe I'm missing something but isn't that what this authority type is for?

https://github.com/solana-labs/solana-program-library/blob/651f2a01ca01ef51a5fbec6f66c4d95e40c66e5a/token/program-2022/src/processor.rs#L760-L774

**Comment by GageBachik** [comment]
> Sorry, maybe I'm missing something but isn't that what this authority type is for?
> 
> https://github.com/solana-labs/solana-program-library/blob/651f2a01ca01ef51a5fbec6f66c4d95e40c66e5a/token/program-2022/src/processor.rs#L760-L774

I am so dumb. I didn't see any instructions for it in the transfer fee extension folder and after a random stack exchange search said it wasn't possible to update the config currently. I should have done more digging first. Thank you <3
