### ISSUE TITLE
small consistency refactor needed

### ISSUE THREAD

**Issue by MohammedAlabd** [solana-labs/solana-program-library#6282]
https://github.com/solana-labs/solana-program-library/blob/6002a1d2617a9b9ab783093ef52c342b6c278cdf/token-metadata/js/src/state.ts#L42C1-L42C18

this should be 
```ts
export function  pack(meta: TokenMetadata): Uint8Array {
```

not 

```ts
export const  pack = (meta: TokenMetadata): Uint8Array => {
```

this is how it is being done in other places such as the in [instruction.ts](https://github.com/solana-labs/solana-program-library/blob/master/token-metadata/js/src/instruction.ts)

**Comment by joncinque** [comment]
It's a good point, we should probably enforce it directly in the linter

**Comment by FaybianB** [comment]
@MohammedAlabd @joncinque Hello, may I be assigned this issue?

**Comment by joncinque** [comment]
@FaybianB I won't assign the issue, but feel free to put in a PR!

**Comment by FaybianB** [comment]
@joncinque Done!

**Comment by MohammedAlabd** [comment]
there are some small stuff in other places as well

would be cool if one PR could address them all

**Comment by joncinque** [comment]
> there are some small stuff in other places as well

PRs are always welcome! It would probably be easiest to do this at the eslint level with `allowArrowFunctions` set to false https://eslint.org/docs/latest/rules/func-style#allowarrowfunctions

**Comment by FaybianB** [comment]
I can address this in the same PR.

> > there are some small stuff in other places as well
> 
> PRs are always welcome! It would probably be easiest to do this at the eslint level with `allowArrowFunctions` set to false https://eslint.org/docs/latest/rules/func-style#allowarrowfunctions
