### ISSUE TITLE
[transfer-hook] Remove deprecated functions from cli

### ISSUE THREAD

**Issue by samkim-crypto** [solana-labs/solana-program-library#6307]
#### Problem
Solana clap-v3 utils deprecated a number of functions with version 1.18. https://github.com/solana-labs/solana-program-library/pull/6278 temporarily suppresses the warnings from deprecated functions.

#### Solution
Remove the deprecated functions from the cli.

**Comment by samkim-crypto** [comment]
I apologize for this 🙏 . The PR that exposes `SignerSource` and adds `pubkey_from_source` has been backported and merged to 1.18 (https://github.com/solana-labs/solana/pull/34678). These will be available in the next 1.18 release. Thanks for pointing this out!

**Comment by tonton-sol** [comment]
Thank you! I am glad I'm not crazy 🤪

**Comment by joncinque** [comment]
Resolved with https://github.com/solana-labs/solana-program-library/pull/6525
