### ISSUE TITLE
@solana/spl-token-swap@0.4.0 causing ESM import errors

### ISSUE THREAD

**Issue by mario-arduini** [solana-labs/solana-program-library#6323]
Similar to [this](https://github.com/solana-labs/solana-program-library/issues/3562) I am using Next 14.1.0 and the token-swap js package is broken, just by installing and importing few functions/variables/etc... i get the following error

```
ReferenceError: exports is not defined

Call Stack
exports
node_modules\@solana\spl-token-swap\dist\esm\index.js (2:22)
```

i tried referincing the fixes on the previous github issue but without success, any suggestion?

thanks!

**Comment by steveluscher** [comment]
Was this with version 0.4.1 or 0.4.2? Those had broken builds and have been deprecated. Can you try with 0.4.4?
