### ISSUE TITLE
Token Upgrade program is absent on the `mainnet`

### ISSUE THREAD

**Issue by rogaldh** [solana-labs/solana-program-library#6404]
Hi. I’ve been working on an application that uses the Token Upgrade program, but it is absent on the `mainnet-beta`.
Are there plans to deploy it there?

**Comment by joncinque** [comment]
Hi there, it's not deployed at the moment, since it's meant as more of a reference implementation for others to use, and also has not been audited.  Feel free to deploy it on your own if you like though!

**Comment by rogaldh** [comment]
Got it. Thanks
