### ISSUE TITLE
token-2022: Add missing "mint" param for approveChecked function

### ISSUE THREAD

**Issue by PBillingsby** [solana-labs/solana-program-library#6474]
The `approveChecked` function in `token/js/src/actions/approveChecked.ts` is missing the mint param.

This PR adds that missing parameter #6473

**Comment by buffalojoec** [comment]
Thanks for calling this out. In the future, if it's something simple like a missing line in the documentation on a function, you don't need to create an issue if you already have a PR up.

If an issue is required (like a bug or feature), you should define the issue independent of any PR and describe the problem and a potential solution. Then, any PR that seeks to close the issue should link to it.

Seems you got the linking backwards here!

**Comment by PBillingsby** [comment]
That makes sense. Thank you @buffalojoec ! Noted for future PR's and issues.
