### ISSUE TITLE
Buffer is not defined

### ISSUE THREAD

**Issue by Ayong1001** [solana-labs/solana-program-library#6770]
![屏幕截图 2024-05-29 165740](https://github.com/solana-labs/solana-program-library/assets/88236046/64098be2-728e-49de-9188-eb8c9b0e1b25)

**Comment by Ayong1001** [comment]
![Uploading 屏幕截图 2024-05-29 165943.png…]()

**Comment by gxxcastillo** [comment]
For anyone who comes across this problem: https://solana.stackexchange.com/questions/212/uncaught-referenceerror-buffer-is-not-defined-using-phantom-wallet-solana-and
