### ISSUE TITLE
transfer-hook: Unable to use seed to generate an ExtraAccountMeta that isn't a PDA

### ISSUE THREAD

**Issue by jychab** [solana-labs/solana-program-library#6845]
**Problem**

Currently, to generate a non-PDA account (a regular account) for a transfer hook, you can only use the `ExtraAccountMeta::new_with_pubkey` method. This method requires a static public key as input, which means the public key must be predetermined and unchanging.

However, there are scenarios where we might want to generate a non-PDA account dynamically. This means creating an account whose public key is determined at runtime based on other account data in the instruction.

For example, 
`authority` that can be derived from the `source_fee_account` data cannot be created using `ExtraAccountMeta::new_with_pubkey`

```
pub struct TransferHookCtx<'info> {
    #[account(
        token::mint = mint,
        token::authority = owner,
    )]
    pub source_token: InterfaceAccount<'info, TokenAccount>,
    /// CHECK:
    pub mint: AccountInfo<'info>,
    #[account(
        token::mint = mint,
    )]
    pub destination_token: InterfaceAccount<'info, TokenAccount>,
    /// CHECK: source token account owner, can be SystemAccount or PDA owned by another program
    pub owner: UncheckedAccount<'info>,
    /// CHECK: ExtraAccountMetaList Account,
    #[account(
        seeds = [b"extra-account-metas", mint.key().as_ref()], 
        bump
    )]
    pub extra_account_meta_list: UncheckedAccount<'info>,
    pub associated_token_program: Program<'info, AssociatedToken>,
    pub token_program: Interface<'info, TokenInterface>,
    pub system_program:  Program<'info, System>,
    #[account(mut)]
    pub source_fee_account: Account<'info, FeeAccount>,
    #[account(
        mut,
        seeds = [b"pda_authority", mint.key().as_ref()], 
        bump
    )]
    /// CHECK: 
    pub pda_authority: SystemAccount<'info>,
    /// CHECK: 
    pub authority: AccountInfo<'info>,
    #[account(
        init_if_needed,
	payer = payer,
	associated_token::authority = authority,
	associated_token::mint = mint,
    )]
    pub token_account: InterfaceAccount<'info, TokenAccount>
}
```

**Comment by joncinque** [comment]
This is an excellent point, and has come up in some of our discussions. What do you think @buffalojoec ?

**Comment by buffalojoec** [comment]
Just to clarify, you're talking about an example like below, right?

Say we have an account with the following state.

```rust
struct Config {
    authority: Pubkey,
    /* ... */
}
```

You want to be able to specify an extra account meta whose key is stored in the Config account's `authority` field?

**Comment by jychab** [comment]
Yup. I'm mainly interested in using pubkeys inside an account data. Not sure if there's any use cases to do the same for instruction data/ account keys tho.

**Comment by buffalojoec** [comment]
Ok cool. It's likely that the solution to account data can just be used for the other use cases, too.

Yeah we've discussed this a bit. Originally I suggested support for something along these lines, but I think I was after something even more generic, not account/instruction data.

I think we can support this. We'll just have to add another means for validation at the account resolution level.

For example, static addresses are easy to evaluate (`==`), and for PDAs we have the `Seed` variants which provide instructions for the resolution step to validate the provided address using the seed instructions.

I think we'd just need a simple `as_ref()` check on the provided address to compare against some slice of data. We'll also need new instructions similar to `Seed` that devs can use to initialize such an extra account configuration.

Maybe something like this?

```rust
enum KeyFromData {
    AccountData {
        account_index: u8,
        start_index: u8,
        length: u8,
    },
    InstructionData {
        start_index: u8,
        length: u8,
    },
}
```

What do you think?

P.S. Now might be a good time to extend some `index` configs to use larger integers, like `usize` or `u64`, for large instruction data.
