### ISSUE TITLE
Question/Bug: Solana 1.18.17 crates don't build | Spl-pod 0.1.0 needed for older version of solana

### ISSUE THREAD

**Issue by LevBeta** [solana-labs/solana-program-library#6931]
I still use, and many people still use, older versions of Solana, like 16/17, for other projects. It looks like spl-pod 0.1.0 has stopped compiling recently.

Is there any way, or a possible fix, to resolve this problem?

Small part of the error:

```error[E0659]: `solana_program` is ambiguous
 --> /home/goncalo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-pod-0.1.0/src/error.rs:5:1
  |
5 | #[spl_program_error]
  | ^^^^^^^^^^^^^^^^^^^^ ambiguous name
  |
  = note: ambiguous because of a conflict between a name from a glob import and an outer scope during import or macro resolution
  = note: `solana_program` could refer to a crate passed with `--extern`
  = help: use `::solana_program` to refer to this crate unambiguously```

https://solana.stackexchange.com/questions/14948/unable-to-build-rust-program-with-jupiter-core-dependency-for-swapping-sol-to-us

**Comment by buffalojoec** [comment]
This was fixed in https://github.com/solana-labs/solana-program-library/pull/6590, but it looks like the version containing the fix was included in patch version 0.4.1. Unfortunately the minimum Solana version it supports is `1.18.2`.

**Comment by buffalojoec** [comment]
This error arises when you have multiple versions of `solana-program` in your lockfile. Maybe try working out how to rectify that, and the issue should resolve?

**Comment by LevBeta** [comment]
> This error arises when you have multiple versions of `solana-program`

I have the solana version locked in at 1.16.17, but even some bumps don't seem to fix, my workaround was really bumping everything to a newer solana version. As it also seems the better options, even by this quote the last issue

https://github.com/solana-labs/solana-program-library/issues/6897#issuecomment-2187137105

**Comment by LevBeta** [comment]
But still "solana-account-decoder" 1.18.17, can't compile because of spl-token-group-interface-0.1.0

**Comment by buffalojoec** [comment]
> But still "solana-account-decoder" 1.18.17, can't compile because of spl-token-group-interface-0.1.0

Yeah, we're still dealing with a few dependency tree issues around the 2.0 release. I'd suggest tracking them over on https://github.com/solana-labs/solana-program-library/issues/6897 then. I think this one is part of that broader effort.

**Comment by joncinque** [comment]
This should be resolved with https://github.com/solana-labs/solana-program-library/issues/6897 -- please open a new issue if you're still seeing problems though!
