### ISSUE TITLE
Question (Bug?): Upgrade of @solana/spl-token from 0.4.6->0.4.7 throws ERR_REQUIRE_ESM error

### ISSUE THREAD

**Issue by alexolaruhf** [solana-labs/solana-program-library#6958]
Has anyone else noticed an error such as the one below when upgrading the @solana/spl-token package from 0.4.6 to 0.4.7? 

Just downgrading the version of the package to 0.4.6 fixed the error for us.

We are using Node v18.20.3

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/src/app/node_modules/@alphaledger/solana-lib/node_modules/@solana/spl-token/lib/cjs/index.js from /usr/src/app/node_modules/@alphaledger/solana-lib/dist/client/operations/utils.js not supported.

index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.

Instead either rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /usr/src/app/node_modules/@alphaledger/solana-lib/node_modules/@solana/spl-token/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

**Comment by kewlfft** [comment]
Same here, it seems to be related to `@solana/spl-token-group` downgraded from 0.0.4 to 0.0.3 in the npm package.

**Comment by buffalojoec** [comment]
Yeah, looks like @kewlfft is correct.

The 0.0.3 release for `@solana/spl-token-group` was deprecated, citing CommonJS build errors.

<img width="505" alt="Screenshot 2024-07-02 at 11 11 24 PM" src="https://github.com/solana-labs/solana-program-library/assets/67205063/178fc03e-70b0-4861-8d28-abb0a348dd6d">

Version 0.4.6 for `@solana/spl-token` was using th correct version (0.0.4), but it looks like we missed a commit somewhere to bump versions, and the dependencies for `@solana/spl-token` fell behind.

---


I'm happy to reconcile this issue, but it would help if either of you guys could paste in some code that would help me reproduce - so I can accurately confirm a fix. Thanks!

**Comment by ordas21** [comment]
can confirm the same even when downgrading to 0.4.6 I am having this issue, but I am unsure if its related to other packages  utilize 0.4.7

**Comment by buffalojoec** [comment]
Should be all set, guys. Upgrade to 0.4.8.
