### ISSUE TITLE
Feature: Allow permanent delegate to close ata's for mint

### ISSUE THREAD

**Issue by danielkboyer** [solana-labs/solana-program-library#6978]
I am writing a program that handles transferring NFT's that are associated with a physical item (that has a wallet onboard and can sign transactions). I am able to transfer the NFT from the sellers ata to the buyers ata successfully using the permanent delegate (which is the program). The problem I am facing now is I want to close the sellers ata to get the rent back but in this scenario the seller is not a signer (and should not be as they already signed in an earlier transaction and then shipped the physical item). I think it would be beneficial to allow the permanent delegate the right to close ata accounts for the mint.

**Comment by joncinque** [comment]
The `close_authority` feature exists for this, where some other entity is allowed to close a user's account:

https://github.com/solana-labs/solana-program-library/blob/a898de170836b153fdb407744b0c8eebebca9127/token/program-2022/src/state.rs#L123-L124

This needs to be configured by the owner, however, which means that either:

* you need to get the owner to sign a transaction setting you as the close authority
* you need to create token accounts for your users, where you set yourself as the close authority and then assign ownership to them, which means that you can't use ATAs

I would encourage you to use the existing functionality.
