### ISSUE TITLE
Feature Request: Use `u64` for Token-Group Interface `max_size`

### ISSUE THREAD

**Issue by jacksondoherty** [solana-labs/solana-program-library#7061]
Although they don't exist today, there are conceivable NFT projects that could have billions of members, especially with compression. For example, a project I'm working on called [Garden](https://www.gardenbrowser.com/) will have a total possible supply of ~64B, which doesn't fit in `u32`. Unless there is a significant benefit to using `u32` that I'm not aware of, we should use the maximum type here.

**Comment by buffalojoec** [comment]
I'm not opposed to it. PRs welcome! I think the tricky bit is working with the extension state layout's alignment.

**Comment by jacksondoherty** [comment]
Will look into making a PR 👍

**Comment by jacksondoherty** [comment]
PR submitted here: #7130
