### ISSUE TITLE
token-js: `createAssociatedTokenAccountIdempotentInstruction` shouldn't require client to pass in `associatedToken`

### ISSUE THREAD

**Issue by metaproph3t** [solana-labs/solana-program-library#7178]
The handy [`createAssociatedTokenAccountIdempotentInstruction`](https://github.com/solana-labs/solana-program-library/blob/69257a6959b4abac239235092679e8044fb18d39/token/js/src/instructions/associatedTokenAccount.ts#L48C17-L65) allows you create instructions that idempotently create associated token accounts. One thing that annoys me about it is that it requires me to pass in the associated token account, like so:
```
...
.preInstructions([
        createAssociatedTokenAccountIdempotentInstruction(
          this.provider.publicKey,
          token.getAssociatedTokenAddressSync(
            tokenMint,
            pdaOwner,
            true
          ),
          pdaOwner,
          tokenMint
)]
...
```
I don't see the purpose of this given that associated token accounts can always be derived by the `getAssociatedTokenAddressSync`. Maybe this function was written before `getAssociatedTokenAddressSync` existed? In any case, it would be nice if this parameter was made optional or removed entirely.

**Comment by joncinque** [comment]
The instruction creators like this are meant to be totally customizable, just like [`createAssociatedTokenAccountInstruction`](https://github.com/solana-labs/solana-program-library/blob/69257a6959b4abac239235092679e8044fb18d39/token/js/src/instructions/associatedTokenAccount.ts#L17) -- if you want to add a helper, PRs are always welcome!

**Comment by metaproph3t** [comment]
What does customizable mean here? An associated token account pubkey is the result of applying `getAssociatedTokenAddressSync` to `mint` and `owner`, so what's the point of having both `mint`/`owner` and `associatedToken`? I'm trying to understand what use-case this unlocks

**Comment by joncinque** [comment]
"customizable" just means you can set every possible account in the instruction, even if it's incorrect. If you're particularly performance-sensitive, then this creator allows you to incur the cost of deriving the associated token account address just once rather than being forced to do it multiple times.

But either way, we can definitely add a helper!
