### ISSUE TITLE
[Bug] stake-pool: Can't create stake pool in devnet

### ISSUE THREAD

**Issue by Chazzzzzzz** [solana-labs/solana-program-library#7208]
following this page: https://spl.solana.com/stake-pool/cli

My local solana config is devnet

spl-stake-pool create-pool --epoch-fee-numerator 3 --epoch-fee-denominator 100 --max-validators 1000 --unsafe-fees
Creating reserve stake 4JrNuqR1F6N5Yp7uBS3E626gAbdsbtnxa2cbzNxLgwnY
Creating mint 7G7j3t9GFR5rQ9uMA76CingxJcWDAezSUCTMFFChnmUr
Creating associated token account 9wrW2wbfqHs4cYbWkcGdyfJXw2h4fBR3a6iKomPsXzL to receive stake pool tokens of mint 7G7j3t9GFR5rQ9uMA76CingxJcWDAezSUCTMFFChnmUr, owned by SahScoe6eHCbC4a8M6BPp27bHqFVaQiDPqYpFeDCwFb
Creating pool fee collection account 9wrW2wbfqHs4cYbWkcGdyfJXw2h4fBR3a6iKomPsXzL
Setting up required accounts for stake pool: reserve stake 4JrNuqR1F6N5Yp7uBS3E626gAbdsbtnxa2cbzNxLgwnY and mint 7G7j3t9GFR5rQ9uMA76CingxJcWDAezSUCTMFFChnmUr
Signature: 4FaKkVkumPeo7ZMYYnWa4VqBYmfrUbHphjqCSgC18AQcaaTWhPwiqp32mnfZ8LD4VksAtuPV96vLZiwSNtiUenFt
Creating stake pool 58mfDry3syYczmnF2jAkNZ1yt2EJi5Lm2wuAaQWwgh8w with validator list 43zWwHcE9asqqfb1SuLt6Se28QCXcGmZUMTSySwZnsZZ
RPC response error -32002: Transaction simulation failed: Error processing Instruction 2: custom program error: 0x3; 9 log messages:
  Program 11111111111111111111111111111111 invoke [1]
  Program 11111111111111111111111111111111 success
  Program 11111111111111111111111111111111 invoke [1]
  Program 11111111111111111111111111111111 success
  Program SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy invoke [1]
  Program log: Instruction: Initialize stake pool
  Program log: Error: The calculation failed
  Program SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy consumed 17379 of 599700 compute units
  Program SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy failed: custom program error: 0x3

**Comment by joncinque** [comment]
The devnet version of the stake pool program is out of date, and the upgrade key has been lost unfortunately. We might end up deploying to another address for devnet, but in the meantime you should use testnet.

**Comment by Chazzzzzzz** [comment]
got you.

**Comment by joncinque** [comment]
I've added some info to the docs, I hope that'll help for the future!
