### ISSUE TITLE
token v3: Add tighter restrictions on self-transfers

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#722]
#### Problem
Whenever the same account is used as the source and destination for a transfer, the instruction will succeed. This could cause issues for programs and apps that make certain assumptions on a successful transfer. They may assume that source and destination were actual SPL token accounts for example, but that's not necessarily true.

#### Proposed Changes
- Fail self-transfer if "self" is not a valid, initialized SPL token account
- Fail self-transfers if the authority for "self" did not authorize the transfer
- Fail self-transfers if `amount` is greater than the current balance

**Comment by CriesofCarrots** [comment]
Based on how I've seen self-transfers used, I think the 3rd bullet will cause a lot of issues for users. I think the user assumption is to provide an amount greater than 0. So I don't think we should implement that bullet.

**Comment by jstarry** [comment]
> Based on how I've seen self-transfers used, I think the 3rd bullet will cause a lot of issues for users. I think the user assumption is to provide an amount greater than 0. So I don't think we should implement that bullet.

I think that's fair from an end user perspective, I've adjusted it to "Fail self-transfers if `amount` is greater than current balance"
