### ISSUE TITLE
Anchor Serealize/Deseralize not impl for enum CompressionAccountType in account-compression program

### ISSUE THREAD

**Issue by mubarizkyc** [solana-labs/solana-program-library#7247]
![Screenshot from 2024-09-07 15-34-04](https://github.com/user-attachments/assets/71ad0ec3-5410-4d5a-8339-636205c93021)

**Comment by dperdic** [comment]
Any update on this? I'm facing the same issue, even on older versions.
Using anchor 0.29.0.

**Comment by ngundotra** [comment]
Working on it this week! Thanks for ping

**Comment by ngundotra** [comment]
@dperdic Thank you for putting this together. I am publishing a new version of the crate with your suggested fix!

**Comment by ngundotra** [comment]
@mubarizkyc If you are working on v0.30.1 and having issues using spl-account-compression, I've provided an example solution that rebuilds the SDK using anchor's `declare_program!()` macro here: https://github.com/ngundotra/spl-account-compression-idl-issue .

Thanks to @dperdic for setting up this example
