### ISSUE TITLE
`spl-math` Solana v2.0.x release

### ISSUE THREAD

**Issue by andrei-pump** [solana-labs/solana-program-library#7287]
A new version of [`spl-math`](https://crates.io/crates/spl-math/versions) crate should be released, so it can be used in a project using Solana v2.0.x.

The current latest version [v0.2.0](https://crates.io/crates/spl-math/0.2.0/dependencies) cannot be used with Solana v2.0.x because it depends on `solana-program ^1.16.1`.

**Comment by joncinque** [comment]
Thanks for reporting this! https://crates.io/crates/spl-math/0.3.0 has just been published, let me know if you have any other issues.
