### ISSUE TITLE
safari @solana/spl-token, getAssociatedTokenAddress error 

### ISSUE THREAD

**Issue by rixhy-cyd** [solana-labs/solana-program-library#7312]
Importing getAssociatedTokenAddress from @solana/spl-token is causing 

'Unhandled JS Exception: Invalid regular expression: invalid group specifier name

Which basically is @solana/spl-token is using some lookbehind assertion RegEx, which is supported only from IOS 16.4 the versions before those are not supporting the causing error 

Is there any workaround for this

For context: Was trying to use this library in a react native application where OS version below 16.4 causes me error

**Comment by joncinque** [comment]
Ah darn, this might be similar to https://github.com/solana-labs/solana-web3.js/pull/2785 / https://github.com/solana-labs/solana-web3.js/pull/2745.

Looking through the code in the token JS library, I can't find any instances of regexes though. Do you have a full stack trace of the error? Maybe it's being thrown from a dependency, and we need to upgrade it

**Comment by rixhy-cyd** [comment]
Hey Jon C,

Thanks for looking into this, I don't have a stack trace for it, let me try
to debug more, am using your library in a react native app where having the
import getOrCreateAssociatedTokenAccount from @solana/spl-token was causing
me the issue, where my app crashes without any data.

**Comment by TusharAgarwal-hub** [comment]
pls give me the chance to make changes and solve the issue.

**Comment by joncinque** [comment]
It's open-source software, so feel free to make a PR if you can reproduce and fix the problem!

**Comment by steveluscher** [comment]
Let us know if you find the problem, and make sure that your lockfile has the [2.0.0-rc.1](https://github.com/solana-labs/solana-web3.js/compare/v2.0.0-rc.0...v2.0.0-rc.1) versions of `@solana/*` packages in it.
