### ISSUE TITLE
@solana/spl-token library doesn't work in Vite project

### ISSUE THREAD

**Issue by gopolar09** [solana-labs/solana-program-library#7351]
When I install `"@solana/spl-token": "^0.4.8"` in vite project and run `vite build`, I see this error.

../../node_modules/@solana/spl-type-length-value/lib/esm/splDiscriminate.js (1:9): "createHash" is not exported by "__vite-browser-external", imported by "../../node_modules/@solana/spl-type-length-value/lib/esm/splDiscriminate.js".

1: import { createHash } from 'crypto';
            ^
2: export const splDiscriminate = (discriminator, length = 8) => {
3:     const digest = createHash('sha256').update(discriminator).digest();

It's because Vite doesn't support built-in node.js module like `crypto`.
https://www.npmjs.com/package/crypto

Can you update your package to include the polyfills as default?

Thanks

**Comment by steveluscher** [comment]
We shouldn't be computing discriminators at runtime anyway. #7360.
