### ISSUE TITLE
[Bug] Access violation in stack frame

### ISSUE THREAD

**Issue by sultandilaram** [solana-labs/solana-program-library#7357]
I am trying to close an empty tree (7MjVK2Y3MCd5ZJme7npcVPJkgtb6pZj2ztkWQXjeSECR) through CPI and keep get this stack frame violation issue

<img width="780" alt="image" src="https://github.com/user-attachments/assets/13fa8b01-506b-43ad-8aad-6f6122c51251">

**Comment by sultandilaram** [comment]
@ngundotra ?

**Comment by ngundotra** [comment]
@sultandilaram working on fix

**Comment by ngundotra** [comment]
Deployed new version to mainnet. See release tagged `spl-account-compression-v0.3.2` 

https://explorer.solana.com/tx/5nLt3t6b3sw2sp3Fy5ZtoRzZgoY5n481KJyq7FidPEAhZvbYQ98jvojDKNVXGs6kZUS8515bUU1GShRC3XpbEEhT/inspect will now simulate as successful.

Thank you for flagging!

**Comment by sultandilaram** [comment]
@ngundotra 
Same issues is back with replace leaf
https://solscan.io/tx/4qau5V9YJyztJMASN2P8thmrMNMqaTfh1AWeV2vHb7as69UVSCd4rYSBYsMc49YiLk34dwuGcTWUT4veBqyp8LKz

**Comment by ngundotra** [comment]
Looks like the proof that was provided was incorrect still.

But thank you for flagging this.

**Comment by sultandilaram** [comment]
Oh Sorry, although now it's because of proof before it was saying "Access violation from stack". I will ping you once the proof issue is resolved or in anyway the stack issue comes up.

**Comment by sultandilaram** [comment]
This is what I am getting when skip preflight is false @ngundotra 
<img width="1430" alt="image" src="https://github.com/user-attachments/assets/899c8e70-16cf-4de6-8549-559c07d3b123">

**Comment by ngundotra** [comment]
This still looks like an issue with your proof. Invalid root recomputed means a bad proof was created. 

Try checking the proof before using it in a transaction

**Comment by sultandilaram** [comment]
Oh I see it now thanks, it threw me off with stack frame issue didn't notice what's up there.
Thank you/
