### ISSUE TITLE
token3: Ensure that token accounts are initialized with a valid mint

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#744]
#### Problem
When token accounts are initialized, the mint account data is validated but the account owner is not guaranteed to belong to the SPL Token program. This means that it's possible to create token accounts with invalid mints. This bug doesn't look harmful since a valid mint is needed to mint tokens.

#### Proposed Change
Add check for `mint_account_info.owner` in `process_initialize_account`

**Comment by joncinque** [comment]
Explicit owner check in `process_initialize_account` was added in #2810
