### ISSUE TITLE
Cannot build any program crates using cargo build-sbf 

### ISSUE THREAD

**Issue by Nagaprasadvr** [solana-labs/solana-program-library#7467]
Im trying to build program-2022 crate with cargo build-sbf but im getting this rust deps error 
`package `solana-program v2.1.0` cannot be built because it requires rustc 1.79.0 or newer, while the currently active rustc version is 1.75.0-dev`

**Comment by buffalojoec** [comment]
Looks like you're running a version of platform-tools that's out of date for the minimum supported Rust version of Token-2022. If you're building from `master`, Token-2022 is using Solana v2.1.0, which has an MSRV of Rust v1.79. A good rule of thumb is to use the same version for your Solana CLI as the crates you're trying to build.
