### ISSUE TITLE
Update or Remove Multisig with wrong Program-Id

### ISSUE THREAD

**Issue by stelgic** [solana-labs/solana-program-library#7524]
While investigate why the multisig for mint is failing I found out the Program Id is older then token2022 program id. 
I have create new multisig and want to remove the current authorized Multisig and set the nw one.

SPL-TOKEN command: spl-token authorize mntXXXXXXXXXXXX mint 3uqBpdyitSBmQ3tmo1FhH2RKkHPiTbYQCm9fbb7jzet6
![Image](https://github.com/user-attachments/assets/65d39686-aacf-40f6-8c82-e612f0deb8e0)

**Comment by joncinque** [comment]
Thanks for your report. This behavior is by design -- the spl-token CLI defaults to `Tokenkeg...` and not token-2022.

**Comment by stelgic** [comment]
I need instruction how to set new mint authority as the multisig is not working

**Comment by joncinque** [comment]
Unless there's evidence that there's a bug in the CLI or SPL, please ask your question on the Solana Stack Exchange: https://solana.stackexchange.com/

We want to make sure to keep signal strong in the GitHub issue tracker -- to make sure that it remains the best place to track issues that affect the development of SPL programs.
