### ISSUE TITLE
CI doesn't specify rust versions

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana-program-library#764]
A clippy change in rust nightly just broke CI for everyone: https://travis-ci.com/github/solana-labs/solana-program-library/jobs/423323225

(The specific lint: https://github.com/rust-lang/rust-clippy/commit/c693de350aff4a3930e66bccf65caf79b390dca2)

**Comment by joncinque** [comment]
I think this is done now, since we use `ci/rust-version.sh` all over the place.  Is this good to close?

**Comment by CriesofCarrots** [comment]
Yep! Looks like it.
