### ISSUE TITLE
How to create and mint multisig controlled token?

### ISSUE THREAD

**Issue by khssnv** [solana-labs/solana-program-library#787]
Hello. There is not a bug report, but a question on how to use a CLI tool.

I see there is a sweet functionality [recently implemented](https://github.com/solana-labs/solana-program-library/commit/d02975bb0be44b51d2688541c6ee0d6ee606409c#diff-d587635f3541d3409d5226615ee6e533c17209eb5192e6271b4a6e651e74f0c3) for token rust CLI by @t-nelson. I'm wondering for a workflow with it.

In case I want to try it to create 2/3 multisig account controlled token, what should I do?

1. Create three keypairs
```console
solana-keygen new --no-passphrase -o ./id1.json && solana-keygen new --no-passphrase -o ./id2.json && solana-keygen new --no-passphrase -o ./id3.json
```

2. Create a multisig account
```console
spl-token create-multisig 2 $(solana-keygen pubkey ./id1.json) $(solana-keygen pubkey ./id2.json) $(solana-keygen pubkey ./id3.json)
```

3. Create a token with 1-st account
```console
spl-token create-token
```

4. Then... move token ownership to multisig account?
```console
spl-token authorize <TOKEN_ADDRESS> owner <MULTISIG_ADDRESS>
```
This one fails for me with message `RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xf`.

6. Initiate mint with offline signature by `id1.json` key?
7. Create token minting transaction composing offline signature of `id1.json` with online signature by `id2.json`?

Could you help me to clarify that, please? Let me know in case I can help you to develop docs or something for it, it is of interest to me to have that. Thank you.

**Comment by t-nelson** [comment]
It looks like you've specified the `owner` authority for a `Mint` account.  `Mint` accounts only support `mint` and `freeze` authorities.

Sorry about the unhelpful error message!  I've filed another issue to fix that up.

Thanks for reporting!
