### ISSUE TITLE
token-swap: Token error messages are printed incorrectly

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#822]
#### Problem
The token-swap program prints all `ProgramError`s returned from the processor as if they are `SwapError`s but they actually may be `TokenError`s. This means errors are only identified by custom error index and so a `TokenError::NotRentExempt` error would be printed as `SwapError::AlreadyInUse`.

#### Proposed Changes
- Create new `SwapError` variants for failed token transfers, burns, and mints
- Log invoked token instruction errors
- Map invoked token instruction errors to those variants instead of passing through

**Comment by throwbackjams** [comment]
Hey Jon / Justin - I made a [pull request](https://github.com/solana-labs/solana-program-library/pull/3338) which addresses this issue. In the PR description, you will find a summary of changes made, in case helpful. Please let me know your thoughts - I'm open to feedback!

Thanks!
