### ISSUE TITLE
example: Provide ProgramTest example with spl-token CPI

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#829]
Program developers will want to write end-to-end tests using other programs, which is not totally possible with unit tests.  `solana-program-test` is extremely useful, so we should have a small example of how to use it.  A few things to consider:

* an example of adding another program's `processor` function (e.g. spl_token)
* an example using a builtin (e.g. stake)

Also, there's an error that I ran into while doing this:
`error: the `#[global_allocator]` in solana_measure conflicts with global allocator in: spl_stake_pool`

so an extra comment or an FAQ point about that error and how to resolve it would be useful as well, e.g. adding
`#![cfg(all(target_arch = "bpf", not(feature = "no-entrypoint")))]` in entrypoint.rs to avoid defining `global_allocator` twice.

tag @jackcmay

**Comment by jackcmay** [comment]
@joncinque 
- What do you think we should do something simple like two test programs, once calls the other to keep the example super clean (rather then call token)?
- Does the current cross-program-invocation example cover the builtin example (it calls system program

**Comment by mvines** [comment]
I definitely thing this example should invoke SPL Token.  The first thing people familiar with ERC-20 ask seems to be, "so how do I customize the SPL Token implementation for my application".  To which we reply, "please don't, there's a better way".

I conveniently wrote this example earlier today, https://github.com/mvines/solana-bpf-program-template/pull/3, that perhaps can be recycled in whole or part for this issue

**Comment by jackcmay** [comment]
@mvines What was the intent of writing that example in its own repo and not as an example under SPL?

**Comment by mvines** [comment]
Nope.  Just wanted to park it somewhere for now, and seemed easiest to add it under my account for now.

**Comment by jackcmay** [comment]
Cool, I'll add it to the examples

**Comment by joncinque** [comment]
@jackcmay my bad, I put this in late yesterday and hadn't read through all of the examples you've already provided.  the `cross-program-invocation` program is perfect as it is for using builtins.  I was thinking the same thing as @mvines regarding an spl-token CPI example, since most people want to work with tokens.

**Comment by jackcmay** [comment]
@joncinque the global allocator conflict should go away now that SPL is on v1.4.8.  I remove the extra checks in this PR: https://github.com/solana-labs/solana-program-library/pull/852
