### ISSUE TITLE
Other token accounts can be mistaken for multisig accounts

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#86]
#### Problem
Accounts are determined to be multisig if their data size equals the size of a multisig account. There is no restriction on non-multisig accounts that they must not equal the size of a multisig account so other token account types could be mistaken as a multisig account if they are big enough and are set as a token account owner

Doesn't seem likely that this would happen in practice, but if it did, it could result in an owner account that has always passes the owner validation check if `m` is 0.

#### Proposed Change
* Assert that token account types are different sizes
* Require token accounts to have a specific size

**Comment by mvines** [comment]
I think we just need a unit test that asserts the sizes of the three token account types are not the same

**Comment by jstarry** [comment]
We don't enforce the data length of token accounts when they are initialized though

**Comment by mvines** [comment]
Ha, yeah we might need to add handling to reject a multisig account where N == 0 as well.  It looks like we might accept that

**Comment by jstarry** [comment]
There is a check for that: `is_valid_signer_index`

**Comment by mvines** [comment]
Oh good so then we just need this unit test then: https://github.com/solana-labs/solana-program-library/issues/86#issuecomment-654977104

**Comment by jackcmay** [comment]
Do you mean a test like this? ;-)
https://github.com/solana-labs/solana-program-library/blob/07d249b6908421ab340c13f5bba290bbcc023309/token/src/state.rs#L597

I'll add the account size assertions too as I'm looking into breaking up the 'State' enum

**Comment by mvines** [comment]
Yep!
