### ISSUE TITLE
Fix Associated Program Account Docs JS Code

### ISSUE THREAD

**Issue by paul-schaaf** [solana-labs/solana-program-library#869]
https://spl.solana.com/associated-token-account#finding-the-associated-token-account-address\

js example here is wrong because of missing `await`. will PR this once I have time and it's still open. The following code works

```
import { PublicKey } from "@solana/web3.js";
import { TOKEN_PROGRAM_ID } from "@solana/spl-token";

const SPL_ASSOCIATED_TOKEN_ACCOUNT_PROGRAM_ID = new PublicKey("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL");

async function findAssociatedTokenAddress(
    walletAddress: PublicKey,
    tokenMintAddress: PublicKey
): Promise<PublicKey> {
    return (await PublicKey.findProgramAddress(
        [
            walletAddress.toBuffer(),
            TOKEN_PROGRAM_ID.toBuffer(),
            tokenMintAddress.toBuffer(),
        ],
        SPL_ASSOCIATED_TOKEN_ACCOUNT_PROGRAM_ID
    ))[0];
}
```

**Comment by mvines** [comment]
oops, thanks.

**Comment by paul-schaaf** [comment]
ah dang forgot to mention, parameters also have param `Pubkey` when it should be `PublicKey` @mvines

**Comment by mvines** [comment]
https://github.com/solana-labs/solana-program-library/commit/1fe820c16d864d9fca99cd58a73738bbdc25a449

Guess I should really actually try to run that function...
