### ISSUE TITLE
token-cli: unexpected behavior when closing a wrapped SOL account with another wrapped SOL account as recipient

### ISSUE THREAD

**Issue by RichardWarfield** [solana-labs/solana-program-library#887]
When closing a wrapped SOL account (`spl-token close <acctA> <acctB>`) where acctB is another wrapped SOL token account, the token program will happily send unwrapped SOL to acctB, resulting in a situation where acctB has a balance of SOL that cannot easily be accessed.  I'm not entirely sure this qualifies as a bug but it seems to me that either the `close` instruction should fail when `acctA` is non-empty, or the token program should update the wrapped SOL amount to reflect the new balance.

**Comment by mvines** [comment]
A check could be added in `spl-token close` to ensure that `<acctB>` is a system account, with a `--force` option to override.   This behaviour is aligned with `solana transfer`, which will happily send SOL to any account even if it's a non-system account. 

So it's not a bug per se.  Close is in fact fully honouring your request and working as initially designed.  But it certainly could be made more user friendly.

**Comment by joncinque** [comment]
Since we have `sync-native` available, the CLI can tack on a `sync-native` instruction if the destination is a wrapped account.

**Comment by zrthxn** [comment]
@joncinque  I'll be working on this next.
