### ISSUE TITLE
lending: Support cross collateralized loans

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#993]
#### Problem
Loans can only be collateralized by a single currency and collateral cannot be pooled for multiple loans

#### Proposed Changes

Expand `Obligation` to include a list of borrow / collateral amounts
- Add authority which will be allowed to repay obligations (and remove obligation tokenization)
- For each borrow / collateral amount, track the quote currency value and the slot the value were last computed at.
- Reasonably high max of total currencies per obligation*

Obligation market value calculation
- Introduce `RefreshCollateralValue` instruction for computing the market value of obligation collateral
  - Requires reserve and dex accounts for collateral exchange rate and price discovery, respectively
- Introduce `RefreshBorrowValue` instruction for computing the market value of obligation borrow amount
  - Requires reserve and dex accounts for interest accrual and price discovery, respectively

Liquidation
- `Liquidation` instruction now requires an obligation with recently refreshed market values to determine loan health

**Comment by joncinque** [comment]
> Expand Obligation to include a list of borrow / collateral amounts

Would it be easier to have one borrow type and multiple collateral types?  Unless this is to be more like Aave, it could be clearer for people to manage.  Then you might also be able to just have a `RefreshObligation` instruction which takes care of all calculations, rather than separating the collateral and borrow side.

> Add authority which will be allowed to repay obligations (and remove obligation tokenization)

We could also create a tokenized market for the authority, as you mentioned :smile: 

Otherwise, this approach seems good to me!

**Comment by jstarry** [comment]
> Would it be easier to have one borrow type and multiple collateral types? Unless this is to be more like Aave, it could be clearer for people to manage. Then you might also be able to just have a RefreshObligation instruction which takes care of all calculations, rather than separating the collateral and borrow side.

Yeah, not opposed to combine those instructions. I think it's worth the flexibility to allow a many to many relationship for collateral to loans though to support multiple borrow currencies

> Otherwise, this approach seems good to me!

Thanks for looking it over!
