### ISSUE TITLE
lending: Support for flash loans

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-program-library#997]
#### Problem
No support for flash loans

#### Proposed Changes
Add `FlashLoan` instruction:
1. Transfer requested amount of tokens
2. Invoke serialized instruction
3. Transfer back sent tokens + fee

**Comment by marbar3778** [comment]
Could you expand on how this would work? 

Would step one be transferred to the user, then a second tx to invoke the serialized instruction then another transaction to return the funds?

**Comment by marbar3778** [comment]
ah didnt see this sysvar: https://docs.solana.com/developing/builtins/sysvars#instructions. I see how it works now. Now need to better understand that sysvar 😃

**Comment by jordansexton** [comment]
Looks like https://github.com/solana-labs/solana-program-library/pull/1444 will address this
